# XGBoosted + Prophet Hybrid Model

We saw in 1modeling_experiments.ipynb that XGBoost+Prophet performed well. The margins between Prophet and the XGBoosted Prophet models were quite slim. We do some feature engineering and hyperparameter tuning to see if we can improve performance.

## Import Packages

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import datetime

from sklearn.model_selection import TimeSeriesSplit
from sklearn.metrics import mean_squared_error, mean_absolute_percentage_error
from sklearn.linear_model import LinearRegression

from prophet import Prophet
from pandas.tseries.holiday import USFederalHolidayCalendar
from prophet.diagnostics import cross_validation, performance_metrics
from prophet.plot import plot_cross_validation_metric
from prophet.plot import add_changepoints_to_plot
import itertools

import warnings
from statsmodels.tools.sm_exceptions import ConvergenceWarning
warnings.simplefilter('ignore', ConvergenceWarning)

import xgboost as xgb
from xgboost import plot_importance

In [2]:
# this is the time series split we will work with
tscv = TimeSeriesSplit(gap=0, max_train_size=None, n_splits=26, test_size=14)


# we import the data and clean it for future use
rs = pd.read_csv('../../scr/data/cleaned_rat_sightings_data/all_cleaned_rat_sightings.csv')
rs['created_date'] = pd.to_datetime(rs['created_date']) 

rs = rs[rs['borough']=='MANHATTAN']

In [3]:
# mark cutoff dates, and also rename columns
rs = rs[rs['created_date'] < '2025-03-01']
rs = rs[rs['created_date'] >= '2020-01-01']
rs = rs.groupby([rs['created_date'].dt.date]).size().reset_index(name='count')
rs.rename(columns={'created_date': 'ds', 'count': 'y'}, inplace=True)

# fill missing dates with 0
full_dates = pd.date_range(start='2020-01-01', end='2025-02-28', freq='D').date
rs = rs.set_index('ds').reindex(full_dates, fill_value=0).rename_axis('ds').reset_index()
rs

              ds   y
0     2020-01-01   4
1     2020-01-02   7
2     2020-01-03  16
3     2020-01-04  10
4     2020-01-05   5
...          ...  ..
1881  2025-02-24  19
1882  2025-02-25  20
1883  2025-02-26  15
1884  2025-02-27  16
1885  2025-02-28  14

[1886 rows x 2 columns]

**Warning:** One should be cautious about temporal leakage. Our goal is to forecast 14 days out into the future. So, we should not use something like a lagged feature by 7 days. The reason is that when we are forecasting the 8th day out and onwards, we would be using a feature that is still outside of our scope. In other words, we should really avoid any lagged features of <14 days for our purposes.

## First Run

In [ ]:
def create_features(df):
    # create time series features based on time series index.
    df = df.copy()
    df['dayofweek'] = df.index.dayofweek
    df['quarter'] = df.index.quarter
    df['month'] = df.index.month
    df['year'] = df.index.year
    df['dayofyear'] = df.index.dayofyear
    df['dayofmonth'] = df.index.day
    df['weekofyear'] = df.index.isocalendar().week
    return df

def add_cyclic(df):
    # features to handly cyclic behavior
    target_map = df['y'].to_dict()
    df['dayofweek_sin'] = np.sin(2 * np.pi * df['dayofweek']/7)
    df['dayofweek_cos'] = np.cos(2 * np.pi * df['dayofweek']/7)
    df['month_sin'] = np.sin(2 * np.pi * df['month']/12)
    df['month_cos'] = np.cos(2 * np.pi * df['month']/12)
    return df

def add_lags(df):
    # lags
    target_map = df['y'].to_dict()
    df['lag15'] = (df.index - pd.Timedelta('15 days')).map(target_map)
    df['lag16'] = (df.index - pd.Timedelta('16 days')).map(target_map)
    return df

def add_seasonal_lags(df):
    # lags of various lengths for different levels of seasonality
    target_map = df['y'].to_dict()
    df['lag30'] = (df.index - pd.Timedelta('30 days')).map(target_map)
    df['lag60'] = (df.index - pd.Timedelta('60 days')).map(target_map)
    df['lag90'] = (df.index - pd.Timedelta('90 days')).map(target_map)
    df['lag120'] = (df.index - pd.Timedelta('120 days')).map(target_map)
    df['lag150'] = (df.index - pd.Timedelta('150 days')).map(target_map)
    df['lag180'] = (df.index - pd.Timedelta('180 days')).map(target_map)

    df['lag362'] = (df.index - pd.Timedelta('365 days')).map(target_map)
    df['lag363'] = (df.index - pd.Timedelta('365 days')).map(target_map)
    df['lag364'] = (df.index - pd.Timedelta('365 days')).map(target_map)
    df['lag365'] = (df.index - pd.Timedelta('365 days')).map(target_map)
    df['lag366'] = (df.index - pd.Timedelta('365 days')).map(target_map)
    df['lag367'] = (df.index - pd.Timedelta('365 days')).map(target_map)
    
    df['lag730'] = (df.index - pd.Timedelta('730 days')).map(target_map)
    df['lag1095'] = (df.index - pd.Timedelta('1095 days')).map(target_map)
    df['lag1460'] = (df.index - pd.Timedelta('1460 days')).map(target_map)
    df['lag1825'] = (df.index - pd.Timedelta('1825 days')).map(target_map)
    return df

def add_moving_averages(df):
    df = df.copy()
    df = df.sort_index()
    
    # Moving averages (using previous values only)
    # Must shift by 14 days because we do not want to let there be temporal leakage in our evaluations
    df['ma7'] = df['y'].shift(14).rolling(window=7).mean()
    df['ma30'] = df['y'].shift(14).rolling(window=30).mean()
    df['ma60'] = df['y'].shift(14).rolling(window=60).mean()
    df['ma90'] = df['y'].shift(14).rolling(window=90).mean()
    df['ma120'] = df['y'].shift(14).rolling(window=120).mean()
    df['ma150'] = df['y'].shift(14).rolling(window=150).mean()
    df['ma180'] = df['y'].shift(14).rolling(window=180).mean()
    df['ma365'] = df['y'].shift(14).rolling(window=365).mean()
    
    return df

In [ ]:
## Add weather data.

import requests
import pandas as pd

lat, lon = 40.7831, -73.9712
start = "2020-01-01"
end   = "2025-02-28"

url = (
    "https://archive-api.open-meteo.com/v1/archive"
    f"?latitude={lat}&longitude={lon}"
    f"&start_date={start}&end_date={end}"
    "&daily=temperature_2m_max,temperature_2m_min,temperature_2m_mean,"
    "apparent_temperature_max,apparent_temperature_min,apparent_temperature_mean,"
    "precipitation_sum,snowfall_sum"
    "&timezone=America/New_York"
)

response = requests.get(url)
data = response.json()

if 'error' in data:
    nd = pd.read_csv("weatherdata.csv")
    nd = nd.set_index('date')
    wd = nd
    
else:
    wd = pd.DataFrame(data["daily"])
    wd["date"] = pd.to_datetime(wd["time"])
    wd = wd.set_index("date")

In [ ]:
def add_weather_data(df, wd):
    df = df.copy()
    wd = wd.copy()
    
    # Ensure datetime index
    df.index = pd.to_datetime(df.index)
    wd.index = pd.to_datetime(wd.index)
    
    # Drop unnecessary columns
    if "time" in wd.columns:
        wd = wd.drop(columns=["time"])
    
    # Remove overlapping columns to avoid join errors
    overlap = wd.columns.intersection(df.columns)
    wd = wd.drop(columns=overlap)
    
    # Join on date index
    df = df.join(wd, how="left")
    
    return df

def add_more_weather_feature(df):
    target_map = df['apparent_temperature_min'].to_dict()
    df['apparent_temperature_min_lag14'] = (df.index - pd.Timedelta('14 days')).map(target_map)
    df['apparent_temperature_min_lag15'] = (df.index - pd.Timedelta('15 days')).map(target_map)
    df['apparent_temperature_min_lag16'] = (df.index - pd.Timedelta('16 days')).map(target_map)
    df['apparent_temperature_min_lag17'] = (df.index - pd.Timedelta('17 days')).map(target_map)
    df['apparent_temperature_min_lag18'] = (df.index - pd.Timedelta('18 days')).map(target_map)
    df['apparent_temperature_min_lag19'] = (df.index - pd.Timedelta('19 days')).map(target_map)
    df['apparent_temperature_min_lag20'] = (df.index - pd.Timedelta('20 days')).map(target_map)
    df['apparent_temperature_min_lag21'] = (df.index - pd.Timedelta('21 days')).map(target_map)

    df['apparent_temperature_min_lag30'] = (df.index - pd.Timedelta('30 days')).map(target_map)
    df['apparent_temperature_min_lag60'] = (df.index - pd.Timedelta('60 days')).map(target_map)
    df['apparent_temperature_min_lag90'] = (df.index - pd.Timedelta('90 days')).map(target_map)
    df['apparent_temperature_min_lag120'] = (df.index - pd.Timedelta('120 days')).map(target_map)
    df['apparent_temperature_min_lag150'] = (df.index - pd.Timedelta('150 days')).map(target_map)
    df['apparent_temperature_min_lag180'] = (df.index - pd.Timedelta('180 days')).map(target_map)
    df['apparent_temperature_min_lag210'] = (df.index - pd.Timedelta('210 days')).map(target_map)
    df['apparent_temperature_min_lag240'] = (df.index - pd.Timedelta('240 days')).map(target_map)
    df['apparent_temperature_min_lag270'] = (df.index - pd.Timedelta('270 days')).map(target_map)
    df['apparent_temperature_min_lag300'] = (df.index - pd.Timedelta('300 days')).map(target_map)
    df['apparent_temperature_min_lag330'] = (df.index - pd.Timedelta('330 days')).map(target_map)
    df['apparent_temperature_min_lag360'] = (df.index - pd.Timedelta('360 days')).map(target_map)
    df['apparent_temperature_min_lag365'] = (df.index - pd.Timedelta('365 days')).map(target_map)
    df['apparent_temperature_min_lag730'] = (df.index - pd.Timedelta('730 days')).map(target_map)

    target_map = df['temperature_2m_max'].to_dict()
    df['temperature_2m_max_lag14'] = (df.index - pd.Timedelta('14 days')).map(target_map)
    df['temperature_2m_max_lag30'] = (df.index - pd.Timedelta('30 days')).map(target_map)
    df['temperature_2m_max_lag60'] = (df.index - pd.Timedelta('60 days')).map(target_map)

    return df

In [ ]:
date_range = pd.date_range(start="2020-01-01", end="2025-02-28")

# Generate US federal holidays
calendar = USFederalHolidayCalendar()
holidays = calendar.holidays(start=date_range.min(), end=date_range.max())

federal_holidays = pd.DataFrame({
    'holiday': 'federal_us',
    'ds': pd.to_datetime(holidays),
    'lower_window': 0,
    'upper_window': 1})

holidays = federal_holidays

In [ ]:
from pandas.tseries.holiday import USFederalHolidayCalendar

def add_federal_holidays(df, custom_holidays=None):
    df = df.copy()
    
    # Ensure datetime index
    df.index = pd.to_datetime(df.index)
    
    cal = USFederalHolidayCalendar()
    holidays = cal.holidays(start=df.index.min(), end=df.index.max())
    
    if custom_holidays:
        for d in custom_holidays:
            if len(d) == 5:  # MM-DD format handling
                years = df.index.year.unique()
                for y in years:
                    holidays = holidays.append(pd.to_datetime([f"{y}-{d}"]))
            else:  # YYYY-MM-DD format handling
                holidays = holidays.append(pd.to_datetime([d]))
    
    holidays = holidays.drop_duplicates().sort_values()
    
    df["is_federal_holiday"] = df.index.isin(holidays).astype(int)
    
    return df

In [ ]:
def add_law_flag(df, law_name: str, start_date: str):
    # Adds a binary column to indicate when a new law is active.
    df = df.copy()
    df.index = pd.to_datetime(df.index)
    start_dt = pd.to_datetime(start_date)
    # Create binary column: 1 if date >= start_date, else 0
    df[law_name] = (df.index >= start_dt).astype(int)
    
    return df

In [ ]:
def add_new_lags(df, x):
    # lags
    target_map = df[x].to_dict()
    df[f'{x}lag15'] = (df.index - pd.Timedelta('15 days')).map(target_map)
    df[f'{x}lag16'] = (df.index - pd.Timedelta('16 days')).map(target_map)
    df[f'{x}lag16'] = (df.index - pd.Timedelta('15 days')).map(target_map)
    df[f'{x}lag17'] = (df.index - pd.Timedelta('16 days')).map(target_map)
    df[f'{x}lag18'] = (df.index - pd.Timedelta('15 days')).map(target_map)
    df[f'{x}lag19'] = (df.index - pd.Timedelta('16 days')).map(target_map)
    df[f'{x}lag20'] = (df.index - pd.Timedelta('15 days')).map(target_map)
    df[f'{x}lag21'] = (df.index - pd.Timedelta('16 days')).map(target_map)

    df[f'{x}lag30'] = (df.index - pd.Timedelta('15 days')).map(target_map)
    df[f'{x}lag365'] = (df.index - pd.Timedelta('16 days')).map(target_map)
    df[f'{x}lag730'] = (df.index - pd.Timedelta('15 days')).map(target_map)
    return df

In [ ]:
FEATURES = ['apparent_temperature_min_lag30',
            'apparent_temperature_min_lag60',
            'apparent_temperature_min_lag120',
            'apparent_temperature_min_lag365',
            'apparent_temperature_min_lag730',
            'dayofyear', 'temperature_2m_max_lag14', 'temperature_2m_max_lag30',
            'temperature_2m_max_lag60', 
            'is_federal_holiday', 
            'lag15', 'lag16', 'lag30', 'lag60', 'lag90', 'lag120', 'lag150', 
            'lag180', 
            'lag362', 'lag363', 'lag364', 'lag365', 'lag366', 'lag367',
            'residualslag15', 'residualslag16', 'residualslag17',
            'residualslag18', 'residualslag19', 'residualslag20', 'residualslag21',
            'residualslag30', 'residualslag365', 'residualslag730', 
            'trend', 'yhat_lower', 'yhat_upper', 
            ]

In [ ]:
params = {'objective': 'reg:squarederror',
         'eval_metric': 'rmse',
         'booster': 'gbtree',
         'base_score': 0.5, 
         'n_estimators': 200, 
        #  'min_child_weight': 6, 
         'learning_rate': 0.01,
        # 'max_depth': 6, 
        # 'subsample': 1,
        # 'colsample_bytree': 0.96,
        # 'colsample_bylevel': 0.6, 
        # 'colsample_bynode': 0.9, 
        # 'reg_alpha': 2.2, 
        # 'gamma': 100, 
        # 'reg_lambda': 0.18,
        #  'early_stopping_rounds': 100, 
        }

In [ ]:
save = rs['ds'].copy().values
rs = rs.set_index('ds')
rs.index = pd.to_datetime(rs.index)
rs['ds']=save
rs = create_features(rs)
rs = add_cyclic(rs)
rs = add_lags(rs)
rs = add_seasonal_lags(rs)
rs = add_moving_averages(rs)
rs = add_weather_data(rs,wd)
rs = add_more_weather_feature(rs)
rs = add_federal_holidays(rs, custom_holidays = ['12-31'])
rs = add_law_flag(rs, law_name='Trash_Law', start_date = '2024-03-01')
rs = add_law_flag(rs, law_name = 'New_Trash_Law', start_date = '2024-11-01')
rs = add_law_flag(rs, law_name='Rat_Mitigation_Zone', start_date = '2023-07-07')
rs = add_law_flag(rs, law_name='Rat_Czar_Appointed', start_date = '2023-04-12')
rs.columns

In [ ]:
results = []

for i, (train_index, test_index) in enumerate(tscv.split(rs)):
    # Split the dataset into training and testing sets
    train = rs.iloc[train_index]
    test = rs.iloc[test_index]
    
    # Fit Prophet on the training data
    model = Prophet(holidays=holidays)
    model.add_country_holidays(country_name='US')
    model.fit(train)
    
    # Make predictions on the training set to calculate residuals
    train_future = model.make_future_dataframe(periods=0, freq='D')  # Use periods=0 to only use the training data
    train_forecast = model.predict(train_future)
    
    # Calculate residuals (actual - predicted) on the training data
    train_residuals = train['y'].values - train_forecast['yhat'].values
    
#    train_residuals = train['y'].values - train_forecast['yhat'][:len(train)].values
    # Build a new DataFrame of residuals
    residuals_df = pd.DataFrame({'ds': train['ds'], 'y': train_residuals })

    train.loc[:, 'residuals'] = train_residuals
    add_new_lags(train, 'residuals')

    train.loc[:, 'trend'] = train_forecast['trend'].values
    train.loc[:, 'yhat_lower'] = train_forecast['yhat_lower'].values
    train.loc[:, 'yhat_upper'] = train_forecast['yhat_upper'].values
    
    X_train_residuals = train[FEATURES]
    y_train_residuals = residuals_df['y']
    
    xgb_model = xgb.XGBRegressor(**params)
    xgb_model.fit(X_train_residuals, y_train_residuals)

    test.loc[:, 'residuals'] = np.nan    
    dummy = pd.concat([X_train_residuals, test], axis=0)  # row-wise   
    add_new_lags(dummy,'residuals')

    test = dummy.iloc[test_index]

    # Forecast using Prophet on the test set
    future = model.make_future_dataframe(periods=len(test), freq='D')
    prophet_forecast = model.predict(future)

    
    # Predict residuals using XGBoost for the test set
    test.loc[:, 'trend'] = prophet_forecast[-len(test):]['trend'].values
    test.loc[:, 'yhat_lower'] = prophet_forecast[-len(test):]['yhat_lower'].values
    test.loc[:, 'yhat_upper'] = prophet_forecast[-len(test):]['yhat_upper'].values
    
    X_test = test[FEATURES]  # Features for the test set
    xgb_residual_preds = xgb_model.predict(X_test)
    
    
    
    # Combine Prophet's forecast and XGBoost's residual prediction
    y_pred = prophet_forecast['yhat'][-len(test):].values + xgb_residual_preds
    y_true = test['y'].values
    
    rmse = np.sqrt(mean_squared_error(y_true, y_pred))
    mape = mean_absolute_percentage_error(y_true, y_pred)
    
    # Store the results for this fold
    results.append({'fold': i, 'rmse': rmse, 'mape': mape})
    
    
    # # Uncomment code below if you want to have plots on feature importance. I'll leave it commented out for obvious reasons.
    # fig, (ax1, ax2, ax3, ax4, ax5) = plt.subplots(5, 1, figsize=(10, 30))
    # plot_importance(xgb_model, ax=ax1, importance_type='gain')
    # ax1.set_title('Gain-based Importance', fontsize=12)

    # plot_importance(xgb_model, ax=ax2, importance_type='weight')
    # ax2.set_title('Split-based Importance', fontsize=12)

    # plot_importance(xgb_model, ax=ax3, importance_type='cover')
    # ax3.set_title('Cover Importance', fontsize=12)

    # plot_importance(xgb_model, ax=ax4, importance_type='total_gain')
    # ax4.set_title('Total Gain Importance', fontsize=12)

    # plot_importance(xgb_model, ax=ax5, importance_type='total_cover')
    # ax5.set_title('Total Cover Importance', fontsize=12)

    plt.show()

# Convert the results into a DataFrame
prophet_xgb_results_df = pd.DataFrame(results)
mean_rmse = prophet_xgb_results_df['rmse'].mean()
mean_mape = prophet_xgb_results_df['mape'].mean()
prophet_xgb_results_df.loc['mean'] = ['mean', mean_rmse, mean_mape]

In [ ]:
train.columns

In [ ]:
prophet_xgb_results_df

# Examining Residuals Data

In [ ]:
model = Prophet(holidays=holidays)
model.add_country_holidays(country_name='US')
model.fit(rs)
rs_future = model.make_future_dataframe(periods=0, freq='D')  # Use periods=0 to only use the training data
rs_forecast = model.predict(rs_future)
    
rs_residuals = rs['y'].values - rs_forecast['yhat'][:len(rs)].values.astype(int)

In [ ]:
residuals = pd.DataFrame({'ds': rs['ds'],  # Use the 'ds' column from the original `rs` dataframe
    'y': rs_residuals  # Use the computed residuals
})
residuals['y'].describe()

In [ ]:
plt.figure(figsize=(50, 12))
plt.plot(residuals_df['ds'], residuals_df['y'], marker='o', linestyle='', color='b', label='Residuals', markersize = 10)
plt.title('Residuals vs Date')
plt.xlabel('Date', size =20)
plt.ylabel('Residuals', size =30)
plt.grid(True)
plt.xticks(rotation=45, size= 20)  # Rotate x-axis labels for better readability
plt.yticks(size=20)
plt.legend()
plt.show()

In [ ]:
import plotly.graph_objects as go
import pandas as pd

window_size = 30

residuals_df['rolling_mean'] = residuals_df['y'].rolling(window=window_size).mean()
residuals_df['rolling_variance'] = residuals_df['y'].rolling(window=window_size).var()
residuals_df['y_365_days_ago'] = residuals_df['y'].shift(365)
residuals_df['y_15_days_ago'] = residuals_df['y'].shift(15)



fig = go.Figure()

fig.add_trace(go.Scatter(
    x=residuals_df['ds'],
    y=residuals_df['y'],
    mode='markers',
    name='Residuals',
    marker=dict(size=5, color='blue') 
))

# fig.add_trace(go.Scatter(
#     x=residuals_df['ds'],
#     y=residuals_df['rolling_mean'],
#     mode='lines',
#     name=f'Rolling Mean (window={window_size})',
#     line=dict(color='red', width=3)
# ))

# fig.add_trace(go.Scatter(
#     x=residuals_df['ds'],
#     y=residuals_df['rolling_variance'],
#     mode='lines',
#     name=f'Rolling Variance (window={window_size})',
#     line=dict(color='green', width=3)
# ))

# Plot 365 days ago actuals as orange dots
fig.add_trace(go.Scatter(
    x=residuals_df['ds'],
    y=residuals_df['y_365_days_ago'],
    mode='markers',  # Change mode to 'markers' to plot dots
    name='365 Days Ago Actuals',
    marker=dict(color='orange', size=4)  # Customize the dot color and size
))

# fig.add_trace(go.Scatter(
#     x=residuals_df['ds'],
#     y=residuals_df['y_15_days_ago'],
#     mode='markers',  # Change mode to 'markers' to plot dots
#     name='15 Days Ago Actuals',
#     marker=dict(color='green', size=4)  # Customize the dot color and size
# ))


# Update layout
fig.update_layout(
    title='Residuals and 365 Days Ago Actuals vs Date',
    xaxis_title='Date',
    yaxis_title='Residuals',
    xaxis=dict(tickangle=45, tickfont=dict(size=20)),
    yaxis=dict(tickfont=dict(size=20)),
    legend=dict(font=dict(size=10),  # Further reduced legend size
                x=0.8, y=0.95,  # Legend position
                traceorder='normal',
                bgcolor='rgba(255, 255, 255, 0.7)',  # Background for legend
                bordercolor='Black', borderwidth=1),
    width=1000,  # Width of the plot
    height=600,  # Height of the plot
    margin=dict(l=100, r=100, t=100, b=100), 
    template='plotly'
)

# Show the figure
fig.show()

# window_size = 730
# residuals_df['rolling_mean'] = residuals_df['y'].rolling(window=window_size).mean()
# residuals_df['rolling_variance'] = residuals_df['y'].rolling(window=window_size).var()

# plt.figure(figsize=(60, 12))

# plt.plot(residuals_df['ds'], residuals_df['y'], marker='o', linestyle='', color='b', label='Residuals', markersize=10)
# plt.plot(residuals_df['ds'], residuals_df['rolling_mean'], color='r', label=f'Rolling Mean (window={window_size})', linewidth=3)
# plt.plot(residuals_df['ds'], residuals_df['rolling_variance'], color='g', label=f'Rolling Variance (window={window_size})', linewidth=3)

# # Add title and labels
# plt.title('Residuals, Rolling Mean, and Rolling Variance vs Date')
# plt.xlabel('Date', size=20)
# plt.ylabel('Residuals', size=30)
# plt.grid(True)
# plt.xticks(rotation=45, size=20)  # Rotate x-axis labels for better readability
# plt.yticks(size=20)

# # Show legend
# plt.legend()

# # Show plot
# plt.show()

In [ ]:
import matplotlib.pyplot as plt
import statsmodels.api as sm


sm.graphics.tsa.plot_acf(residuals_df['y'], lags=24)
sm.graphics.tsa.plot_pacf(residuals_df['y'], lags=24)
plt.show()

# Optuna Hyperparameter Tuning


In the XGBoost + Prophet hybrid model, we can tune a lot of parameters and also do a lot of feature engineering. For this reasoning, we shall use Optuna. Optuna also has the added benefit that it can record its studies in a .db so that future studies can piggyback off of old studies.

In [4]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import datetime

from sklearn.model_selection import TimeSeriesSplit
from sklearn.metrics import mean_squared_error, mean_absolute_percentage_error
from sklearn.linear_model import LinearRegression

from prophet import Prophet
from pandas.tseries.holiday import USFederalHolidayCalendar
from prophet.diagnostics import cross_validation, performance_metrics
from prophet.plot import plot_cross_validation_metric
from prophet.plot import add_changepoints_to_plot
import itertools

import warnings
from statsmodels.tools.sm_exceptions import ConvergenceWarning
warnings.simplefilter('ignore', ConvergenceWarning)

import xgboost as xgb
from xgboost import plot_importance
import optuna
from optuna.exceptions import TrialPruned

In [5]:
# we import the data and clean it for future use
rs = pd.read_csv('../../scr/data/cleaned_rat_sightings_data/all_cleaned_rat_sightings.csv')
rs['created_date'] = pd.to_datetime(rs['created_date']) 
# mark cutoff dates, and also rename columns
rs = rs[rs['created_date']<'2025-03-01']
rs = rs[rs['created_date']>='2020-01-01']
rs = rs[rs['borough']=='MANHATTAN']
rs = rs.groupby([rs['created_date'].dt.date]).size().reset_index(name='count')
rs.rename(columns={'created_date': 'ds', 'count': 'y'}, inplace=True)

The next cell block is a copy and paste of the functions from the first part of this notebook. We have this cellblock here so that we can run code in this section without having to rerun the previous sections.

In [6]:
def create_features(df):
    # create time series features based on time series index.
    df = df.copy()
    df['dayofweek'] = df.index.dayofweek
    df['quarter'] = df.index.quarter
    df['month'] = df.index.month
    df['year'] = df.index.year
    df['dayofyear'] = df.index.dayofyear
    df['dayofmonth'] = df.index.day
    df['weekofyear'] = df.index.isocalendar().week
    return df

def add_cyclic(df):
    # features to handly cyclic behavior
    target_map = df['y'].to_dict()
    df['dayofweek_sin'] = np.sin(2 * np.pi * df['dayofweek']/7)
    df['dayofweek_cos'] = np.cos(2 * np.pi * df['dayofweek']/7)
    df['month_sin'] = np.sin(2 * np.pi * df['month']/12)
    df['month_cos'] = np.cos(2 * np.pi * df['month']/12)
    return df

def add_lags(df):
    # lags
    target_map = df['y'].to_dict()
    df['lag15'] = (df.index - pd.Timedelta('15 days')).map(target_map)
    df['lag16'] = (df.index - pd.Timedelta('16 days')).map(target_map)
    return df

def add_seasonal_lags(df):
    # lags of various lengths for different levels of seasonality
    target_map = df['y'].to_dict()
    df['lag30'] = (df.index - pd.Timedelta('30 days')).map(target_map)
    df['lag60'] = (df.index - pd.Timedelta('60 days')).map(target_map)
    df['lag90'] = (df.index - pd.Timedelta('90 days')).map(target_map)
    df['lag120'] = (df.index - pd.Timedelta('120 days')).map(target_map)
    df['lag150'] = (df.index - pd.Timedelta('150 days')).map(target_map)
    df['lag180'] = (df.index - pd.Timedelta('180 days')).map(target_map)

    df['lag362'] = (df.index - pd.Timedelta('365 days')).map(target_map)
    df['lag363'] = (df.index - pd.Timedelta('365 days')).map(target_map)
    df['lag364'] = (df.index - pd.Timedelta('365 days')).map(target_map)
    df['lag365'] = (df.index - pd.Timedelta('365 days')).map(target_map)
    df['lag366'] = (df.index - pd.Timedelta('365 days')).map(target_map)
    df['lag367'] = (df.index - pd.Timedelta('365 days')).map(target_map)
    
    df['lag730'] = (df.index - pd.Timedelta('730 days')).map(target_map)
    df['lag1095'] = (df.index - pd.Timedelta('1095 days')).map(target_map)
    df['lag1460'] = (df.index - pd.Timedelta('1460 days')).map(target_map)
    df['lag1825'] = (df.index - pd.Timedelta('1825 days')).map(target_map)
    return df

def add_moving_averages(df):
    df = df.copy()
    df = df.sort_index()
    
    # Moving averages (using previous values only)
    # Must shift by 14 days because we do not want to let there be temporal leakage in our evaluations
    df['ma7'] = df['y'].shift(14).rolling(window=7).mean()
    df['ma30'] = df['y'].shift(14).rolling(window=30).mean()
    df['ma60'] = df['y'].shift(14).rolling(window=60).mean()
    df['ma90'] = df['y'].shift(14).rolling(window=90).mean()
    df['ma120'] = df['y'].shift(14).rolling(window=120).mean()
    df['ma150'] = df['y'].shift(14).rolling(window=150).mean()
    df['ma180'] = df['y'].shift(14).rolling(window=180).mean()
    df['ma365'] = df['y'].shift(14).rolling(window=365).mean()
    
    return df


## Add weather data.

import requests
import pandas as pd

lat, lon = 40.7831, -73.9712
start = "2020-01-01"
end   = "2025-02-28"

url = (
    "https://archive-api.open-meteo.com/v1/archive"
    f"?latitude={lat}&longitude={lon}"
    f"&start_date={start}&end_date={end}"
    "&daily=temperature_2m_max,temperature_2m_min,temperature_2m_mean,"
    "apparent_temperature_max,apparent_temperature_min,apparent_temperature_mean,"
    "precipitation_sum,snowfall_sum"
    "&timezone=America/New_York"
)

response = requests.get(url)
data = response.json()

if 'error' in data:
    nd = pd.read_csv("weatherdata.csv")
    nd = nd.set_index('date')
    wd = nd
    
else:
    wd = pd.DataFrame(data["daily"])
    wd["date"] = pd.to_datetime(wd["time"])
    wd = wd.set_index("date")


def add_weather_data(df, wd):
    df = df.copy()
    wd = wd.copy()
    
    # Ensure datetime index
    df.index = pd.to_datetime(df.index)
    wd.index = pd.to_datetime(wd.index)
    
    # Drop unnecessary columns
    if "time" in wd.columns:
        wd = wd.drop(columns=["time"])
    
    # Remove overlapping columns to avoid join errors
    overlap = wd.columns.intersection(df.columns)
    wd = wd.drop(columns=overlap)
    
    # Join on date index
    df = df.join(wd, how="left")
    
    return df

def add_more_weather_feature(df):
    target_map = df['apparent_temperature_min'].to_dict()
    df['apparent_temperature_min_lag14'] = (df.index - pd.Timedelta('14 days')).map(target_map)
    df['apparent_temperature_min_lag15'] = (df.index - pd.Timedelta('15 days')).map(target_map)
    df['apparent_temperature_min_lag16'] = (df.index - pd.Timedelta('16 days')).map(target_map)
    df['apparent_temperature_min_lag17'] = (df.index - pd.Timedelta('17 days')).map(target_map)
    df['apparent_temperature_min_lag18'] = (df.index - pd.Timedelta('18 days')).map(target_map)
    df['apparent_temperature_min_lag19'] = (df.index - pd.Timedelta('19 days')).map(target_map)
    df['apparent_temperature_min_lag20'] = (df.index - pd.Timedelta('20 days')).map(target_map)
    df['apparent_temperature_min_lag21'] = (df.index - pd.Timedelta('21 days')).map(target_map)

    df['apparent_temperature_min_lag30'] = (df.index - pd.Timedelta('30 days')).map(target_map)
    df['apparent_temperature_min_lag60'] = (df.index - pd.Timedelta('60 days')).map(target_map)
    df['apparent_temperature_min_lag90'] = (df.index - pd.Timedelta('90 days')).map(target_map)
    df['apparent_temperature_min_lag120'] = (df.index - pd.Timedelta('120 days')).map(target_map)
    df['apparent_temperature_min_lag150'] = (df.index - pd.Timedelta('150 days')).map(target_map)
    df['apparent_temperature_min_lag180'] = (df.index - pd.Timedelta('180 days')).map(target_map)
    df['apparent_temperature_min_lag210'] = (df.index - pd.Timedelta('210 days')).map(target_map)
    df['apparent_temperature_min_lag240'] = (df.index - pd.Timedelta('240 days')).map(target_map)
    df['apparent_temperature_min_lag270'] = (df.index - pd.Timedelta('270 days')).map(target_map)
    df['apparent_temperature_min_lag300'] = (df.index - pd.Timedelta('300 days')).map(target_map)
    df['apparent_temperature_min_lag330'] = (df.index - pd.Timedelta('330 days')).map(target_map)
    df['apparent_temperature_min_lag360'] = (df.index - pd.Timedelta('360 days')).map(target_map)
    df['apparent_temperature_min_lag365'] = (df.index - pd.Timedelta('365 days')).map(target_map)
    df['apparent_temperature_min_lag730'] = (df.index - pd.Timedelta('730 days')).map(target_map)

    target_map = df['temperature_2m_max'].to_dict()
    df['temperature_2m_max_lag14'] = (df.index - pd.Timedelta('14 days')).map(target_map)
    df['temperature_2m_max_lag30'] = (df.index - pd.Timedelta('30 days')).map(target_map)
    df['temperature_2m_max_lag60'] = (df.index - pd.Timedelta('60 days')).map(target_map)

    return df


date_range = pd.date_range(start="2020-01-01", end="2025-02-28")

# Generate US federal holidays
calendar = USFederalHolidayCalendar()
holidays = calendar.holidays(start=date_range.min(), end=date_range.max())

federal_holidays = pd.DataFrame({
    'holiday': 'federal_us',
    'ds': pd.to_datetime(holidays),
    'lower_window': 0,
    'upper_window': 1})

holidays = federal_holidays

from pandas.tseries.holiday import USFederalHolidayCalendar

def add_federal_holidays(df, custom_holidays=None):
    df = df.copy()
    
    # Ensure datetime index
    df.index = pd.to_datetime(df.index)
    
    cal = USFederalHolidayCalendar()
    holidays = cal.holidays(start=df.index.min(), end=df.index.max())
    
    if custom_holidays:
        for d in custom_holidays:
            if len(d) == 5:  # MM-DD format handling
                years = df.index.year.unique()
                for y in years:
                    holidays = holidays.append(pd.to_datetime([f"{y}-{d}"]))
            else:  # YYYY-MM-DD format handling
                holidays = holidays.append(pd.to_datetime([d]))
    
    holidays = holidays.drop_duplicates().sort_values()
    
    df["is_federal_holiday"] = df.index.isin(holidays).astype(int)
    
    return df

def add_law_flag(df, law_name: str, start_date: str):
    # Adds a binary column to indicate when a new law is active.
    df = df.copy()
    df.index = pd.to_datetime(df.index)
    start_dt = pd.to_datetime(start_date)
    # Create binary column: 1 if date >= start_date, else 0
    df[law_name] = (df.index >= start_dt).astype(int)
    
    return df

def add_new_lags(df, x):
    # lags
    target_map = df[x].to_dict()
    df[f'{x}lag15'] = (df.index - pd.Timedelta('15 days')).map(target_map)
    df[f'{x}lag16'] = (df.index - pd.Timedelta('16 days')).map(target_map)
    df[f'{x}lag17'] = (df.index - pd.Timedelta('17 days')).map(target_map)
    df[f'{x}lag18'] = (df.index - pd.Timedelta('18 days')).map(target_map)
    df[f'{x}lag19'] = (df.index - pd.Timedelta('19 days')).map(target_map)
    df[f'{x}lag20'] = (df.index - pd.Timedelta('20 days')).map(target_map)
    df[f'{x}lag21'] = (df.index - pd.Timedelta('21 days')).map(target_map)

    df[f'{x}lag30'] = (df.index - pd.Timedelta('30 days')).map(target_map)
    df[f'{x}lag365'] = (df.index - pd.Timedelta('365 days')).map(target_map)
    df[f'{x}lag730'] = (df.index - pd.Timedelta('730 days')).map(target_map)
    return df

In [7]:
ALL_FEATURES = {'dayofweek', 'quarter', 'month', 'year', 'dayofyear',
       'dayofmonth', 'weekofyear', 'dayofweek_sin', 'dayofweek_cos',
       'month_sin', 'month_cos', 'lag15', 'lag16', 'lag30', 'lag60', 'lag90',
       'lag120', 'lag150', 'lag180', 'lag362', 'lag363', 'lag364', 'lag365',
       'lag366', 'lag367', 'lag730', 'lag1095', 'lag1460', 'lag1825', 'ma7',
       'ma30', 'ma60', 'ma90', 'ma120', 'ma150', 'ma180', 'ma365',
       'temperature_2m_max', 'temperature_2m_min', 'temperature_2m_mean',
       'apparent_temperature_max', 'apparent_temperature_min',
       'apparent_temperature_mean', 'precipitation_sum', 'snowfall_sum',
       'apparent_temperature_min_lag14', 'apparent_temperature_min_lag15',
       'apparent_temperature_min_lag16', 'apparent_temperature_min_lag17',
       'apparent_temperature_min_lag18', 'apparent_temperature_min_lag19',
       'apparent_temperature_min_lag20', 'apparent_temperature_min_lag21',
       'apparent_temperature_min_lag30', 'apparent_temperature_min_lag60',
       'apparent_temperature_min_lag90', 'apparent_temperature_min_lag120',
       'apparent_temperature_min_lag150', 'apparent_temperature_min_lag180',
       'apparent_temperature_min_lag210', 'apparent_temperature_min_lag240',
       'apparent_temperature_min_lag270', 'apparent_temperature_min_lag300',
       'apparent_temperature_min_lag330', 'apparent_temperature_min_lag360',
       'apparent_temperature_min_lag365', 'apparent_temperature_min_lag730',
       'temperature_2m_max_lag14', 'temperature_2m_max_lag30',
       'temperature_2m_max_lag60', 'is_federal_holiday', 'Trash_Law',
       'New_Trash_Law', 'Rat_Mitigation_Zone', 'Rat_Czar_Appointed',
       'residuals', 'residualslag15', 'residualslag16', 'residualslag17',
       'residualslag18', 'residualslag19', 'residualslag20', 'residualslag21',
       'residualslag30', 'residualslag365', 'residualslag730', 'trend',
       'yhat_lower', 'yhat_upper'}

# ALL_FEATURES =['lag60', 'ma7', 'yhat_lower', 'temperature_2m_max_lag60', 'dayofweek', 
#                'apparent_temperature_min_lag360', 'dayofyear', 'apparent_temperature_min_lag120', 'Trash_Law', 'quarter', 'month_sin', 'ma60', 'Rat_Mitigation_Zone', 'temperature_2m_max_lag30', 'lag730', 'apparent_temperature_max', 'apparent_temperature_min', 
#                'residualslag365', 'lag366', 'lag363', 'lag364', 'apparent_temperature_min_lag180', 
#                'apparent_temperature_min_lag240', 'apparent_temperature_min_lag18', 'apparent_temperature_min_lag90', 'dayofweek_cos']

In [8]:
save = rs['ds'].copy().values
rs = rs.set_index('ds')
rs.index = pd.to_datetime(rs.index)
rs['ds']=save
rs = create_features(rs)
rs = add_cyclic(rs)
rs = add_lags(rs)
rs = add_seasonal_lags(rs)
rs = add_moving_averages(rs)
rs = add_weather_data(rs,wd)
rs = add_more_weather_feature(rs)
rs = add_federal_holidays(rs, custom_holidays = ['12-31'])
rs = add_law_flag(rs, law_name='Trash_Law', start_date = '2024-03-01')
rs = add_law_flag(rs, law_name = 'New_Trash_Law', start_date = '2024-11-01')
rs = add_law_flag(rs, law_name='Rat_Mitigation_Zone', start_date = '2023-07-07')
rs = add_law_flag(rs, law_name='Rat_Czar_Appointed', start_date = '2023-04-12')
rs

,y,ds,dayofweek,quarter,month,year,dayofyear,dayofmonth,weekofyear,dayofweek_sin,...,apparent_temperature_min_lag365,apparent_temperature_min_lag730,temperature_2m_max_lag14,temperature_2m_max_lag30,temperature_2m_max_lag60,is_federal_holiday,Trash_Law,New_Trash_Law,Rat_Mitigation_Zone,Rat_Czar_Appointed
ds,,,,,,,,,,,,,,,,,,,,,
2020-01-01,4,2020-01-01,2,1,1,2020,1,1,1,0.974928,...,NaN,NaN,NaN,NaN,NaN,1,0,0,0,0
2020-01-02,7,2020-01-02,3,1,1,2020,2,2,1,0.433884,...,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0
2020-01-03,16,2020-01-03,4,1,1,2020,3,3,1,-0.433884,...,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0
2020-01-04,10,2020-01-04,5,1,1,2020,4,4,1,-0.974928,...,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0
2020-01-05,5,2020-01-05,6,1,1,2020,5,5,1,-0.781831,...,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2025-02-24,19,2025-02-24,0,1,2,2025,55,24,9,0.000000,...,-11.1,-10.8,0.2,-2.2,-0.2,0,1,1,1,1
2025-02-25,20,2025-02-25,1,1,2,2025,56,25,9,0.781831,...,-6.9,-8.1,-0.4,4.1,2.5,0,1,1,1,1
2025-02-26,15,2025-02-26,2,1,2,2025,57,26,9,0.974928,...,-4.1,-7.1,0.6,2.0,7.5,0,1,1,1,1
2025-02-27,16,2025-02-27,3,1,2,2025,58,27,9,0.433884,...,4.9,-5.1,5.8,4.1,15.4,0,1,1,1,1
2025-02-28,14,2025-02-28,4,1,2,2025,59,28,9,-0.433884,...,-9.0,-6.7,0.3,8.9,13.0,0,1,1,1,1

In [9]:
import logging
logging.getLogger("cmdstanpy").disabled = True

In [10]:
import optuna

def objective(trial):
    print("Trial starting:", trial.number)

    # Prophet Hyperparameters
    prophet_params = {
        "changepoint_prior_scale": trial.suggest_float("changepoint_prior_scale", 0.1, 0.5, log=True),
        "seasonality_prior_scale": trial.suggest_float("seasonality_prior_scale", 0.1, 10, log=True),
        "holidays_prior_scale": trial.suggest_float("holidays_prior_scale", 0.01, 10, log=True),
    }

    # XGBoost Hyperparameters
    xgb_params = {"device": "cuda",
        "n_estimators": trial.suggest_int("n_estimators", 100, 2000),
        "max_depth": trial.suggest_int("max_depth", 3, 10),
        "learning_rate": trial.suggest_float("learning_rate", 0.001, 1, log=True),
        "subsample": trial.suggest_float("subsample", 0.2, 1.0),
        "colsample_bytree": trial.suggest_float("colsample_bytree", 0.2, 1.0),
        "gamma": trial.suggest_float("gamma", 0, 5),
        "min_child_weight": trial.suggest_int("min_child_weight", 2, 10),
        "reg_lambda": trial.suggest_float("reg_lambda", 0.1, 10, log=True),
        "reg_alpha": trial.suggest_float("reg_alpha", 0.01, 10, log=True),
        "objective": "reg:squarederror",
        "random_state": 42
    }


    # Feature Selection
    selected_features = []

    for feature in ALL_FEATURES:
        if trial.suggest_categorical(feature, [True, False]):
            selected_features.append(feature)


    # prevent Optuna from accidentally picking no features
    if len(selected_features) == 0: 
        selected_features.append("trend")


    results = []

    for i, (train_index, test_index) in enumerate(tscv.split(rs)):

        train = rs.iloc[train_index].copy()
        test = rs.iloc[test_index].copy()

        model = Prophet(**prophet_params, holidays=holidays)
        model.add_country_holidays(country_name='US')
        model.fit(train)

        train_future = model.make_future_dataframe(periods=0, freq='D')
        train_forecast = model.predict(train_future)

        train_residuals = train['y'].values - train_forecast['yhat'].values

        residuals_df = pd.DataFrame({'ds': train['ds'],'y': train_residuals})

        train['residuals'] = train_residuals

        add_new_lags(train, 'residuals')

        train['trend'] = train_forecast['trend'].values
        train['yhat_lower'] = train_forecast['yhat_lower'].values
        train['yhat_upper'] = train_forecast['yhat_upper'].values

        X_train_residuals = train[selected_features]
        y_train_residuals = residuals_df['y']

        # Train XGBoost
        xgb_model = xgb.XGBRegressor(**xgb_params)
        xgb_model.fit(X_train_residuals, y_train_residuals)

        # Prepare Test Data
        test['residuals'] = np.nan # need to add this otherwise it won't run

        dummy = pd.concat([train, test], axis=0)

        add_new_lags(dummy, 'residuals') # need to add the lags that test can actually see

        test = dummy.iloc[test_index].copy() # cut out the test set again

        # Prophet Forecast
        future = model.make_future_dataframe(periods=len(test), freq='D')
        prophet_forecast = model.predict(future)

        # add outputs of Prophet for use in the XGBoost model
        test.loc[:, 'trend'] = prophet_forecast[-len(test):]['trend'].values
        test.loc[:, 'yhat_lower'] = prophet_forecast[-len(test):]['yhat_lower'].values
        test.loc[:, 'yhat_upper'] = prophet_forecast[-len(test):]['yhat_upper'].values

        X_test = test[selected_features]

        xgb_residual_preds = xgb_model.predict(X_test)

        y_pred = np.round(prophet_forecast['yhat'][-len(test):].values + xgb_residual_preds)
        y_true = test['y'].values

        rmse = np.sqrt(mean_squared_error(y_true, y_pred))
        results.append(rmse)

        # # Report intermediate result to Optuna
        # trial.report(rmse, step=i)

        # # Check if trial should be pruned
        # if trial.should_prune():
        #     raise TrialPruned()

    return np.mean(results)

In [ ]:
splits = 26 # from among 7, 13, 26, 


# this is the time series split we will work with
tscv = TimeSeriesSplit(gap=0, max_train_size=None, n_splits=splits, test_size=14)

study = optuna.create_study(
    direction="minimize",
    study_name="hybrid_model_feature_parameter_search",
    storage=f"sqlite:///xgbprophet_model{splits}.db",
    load_if_exists=True
)
study.optimize(objective, n_trials=200, n_jobs=-1)

print("Best RMSE:", study.best_value)
print("Best params:", study.best_params)


best_features = [f for f in ALL_FEATURES if study.best_params.get(f, False)]

best_hyperparams = {k: v for k, v in study.best_params.items() if k not in ALL_FEATURES}
print("Selected Features:")
print(best_features)

print("\nBest Hyperparameters:")
print(best_hyperparams)

[I 2026-03-15 17:15:50,262] Using an existing study with name 'hybrid_model_feature_parameter_search' instead of creating a new one.

Trial starting: 302
Trial starting: 292
Trial starting: 289
Trial starting: 291
Trial starting: 294
Trial starting: 299
Trial starting: 297
Trial starting: 298
Trial starting: 293
Trial starting: 290
Trial starting: 296
Trial starting: 295
Trial starting: 287
Trial starting: 300
Trial starting: 301
Trial starting: 288

[I 2026-03-15 17:35:53,987] Trial 302 finished with value: 13.71340864823187 and parameters: {'changepoint_prior_scale': 0.4049508860436023, 'seasonality_prior_scale': 0.8126395637319624, 'holidays_prior_scale': 0.29783156885675377, 'n_estimators': 892, 'max_depth': 7, 'learning_rate': 0.0055887028678074544, 'subsample': 0.6689736500530491, 'colsample_bytree': 0.9541099048802497, 'gamma': 1.4121310519464036, 'min_child_weight': 10, 'reg_lambda': 0.13499303155895848, 'reg_alpha': 0.14608175983781668, 'month_sin': True, 'apparent_temperature_min_lag150': False, 'apparent_temperature_min_lag21': False, 'apparent_temperature_min_lag16': True, 'apparent_temperature_min_lag365': True, 'dayofweek_cos': False, 'apparent_temperature_min_lag60': True, 'residualslag19': False, 'dayofweek_sin': True, 'Rat_Czar_Appointed': False, 'apparent_temperature_min_lag730': True, 'yhat_upper': False, 'apparent_temperature_min_lag360': False, 'apparent_temperature_min_lag18': False, 'temperature_2m_mean': False, 'apparent_temperature_max': True, 'lag365': False, 'temperature_2m_max_lag60': True, 'lag1095': False, 'ma150': False, 'apparent_temperature_min_lag15': False, 'lag15': False, 'apparent_temperature_min_lag19': True, 'residualslag365': True, 'apparent_temperature_mean': True, 'yhat_lower': False, 'is_federal_holiday': False, 'apparent_temperature_min_lag180': True, 'apparent_temperature_min_lag17': False, 'apparent_temperature_min_lag330': True, 'residualslag15': True, 'ma90': False, 'Rat_Mitigation_Zone': True, 'snowfall_sum': False, 'precipitation_sum': True, 'dayofyear': True, 'month': False, 'dayofmonth': False, 'lag367': False, 'lag120': False, 'lag1825': True, 'lag60': False, 'lag362': False, 'year': False, 'Trash_Law': True, 'residualslag17': True, 'residualslag30': False, 'temperature_2m_max_lag14': False, 'apparent_temperature_min_lag30': False, 'quarter': True, 'temperature_2m_max_lag30': False, 'month_cos': False, 'New_Trash_Law': False, 'lag16': False, 'residualslag21': True, 'lag180': True, 'ma120': False, 'apparent_temperature_min_lag90': False, 'ma30': True, 'apparent_temperature_min_lag300': False, 'lag1460': True, 'apparent_temperature_min': True, 'residualslag16': True, 'temperature_2m_min': True, 'apparent_temperature_min_lag20': False, 'lag30': True, 'lag730': True, 'apparent_temperature_min_lag14': True, 'apparent_temperature_min_lag210': True, 'ma365': True, 'apparent_temperature_min_lag120': False, 'trend': False, 'ma180': True, 'apparent_temperature_min_lag270': True, 'residualslag730': True, 'residualslag18': True, 'lag363': False, 'residuals': True, 'ma60': True, 'temperature_2m_max': False, 'lag366': True, 'lag150': True, 'weekofyear': True, 'lag90': True, 'apparent_temperature_min_lag240': False, 'dayofweek': False, 'ma7': False, 'residualslag20': True, 'lag364': False}. Best is trial 246 with value: 4.333800161951233.

Trial starting: 303

[I 2026-03-15 17:36:18,009] Trial 298 finished with value: 13.748086857289024 and parameters: {'changepoint_prior_scale': 0.39713603900429384, 'seasonality_prior_scale': 0.8353949742279996, 'holidays_prior_scale': 0.31160500787086914, 'n_estimators': 894, 'max_depth': 7, 'learning_rate': 0.005295844355245781, 'subsample': 0.6930927833834213, 'colsample_bytree': 0.9485814554079968, 'gamma': 1.350038480457613, 'min_child_weight': 10, 'reg_lambda': 0.13656116105705207, 'reg_alpha': 0.15453532527475738, 'month_sin': True, 'apparent_temperature_min_lag150': False, 'apparent_temperature_min_lag21': False, 'apparent_temperature_min_lag16': True, 'apparent_temperature_min_lag365': True, 'dayofweek_cos': False, 'apparent_temperature_min_lag60': True, 'residualslag19': False, 'dayofweek_sin': True, 'Rat_Czar_Appointed': False, 'apparent_temperature_min_lag730': True, 'yhat_upper': False, 'apparent_temperature_min_lag360': False, 'apparent_temperature_min_lag18': False, 'temperature_2m_mean': False, 'apparent_temperature_max': True, 'lag365': False, 'temperature_2m_max_lag60': True, 'lag1095': False, 'ma150': False, 'apparent_temperature_min_lag15': False, 'lag15': False, 'apparent_temperature_min_lag19': True, 'residualslag365': True, 'apparent_temperature_mean': True, 'yhat_lower': False, 'is_federal_holiday': False, 'apparent_temperature_min_lag180': True, 'apparent_temperature_min_lag17': False, 'apparent_temperature_min_lag330': True, 'residualslag15': True, 'ma90': False, 'Rat_Mitigation_Zone': True, 'snowfall_sum': False, 'precipitation_sum': False, 'dayofyear': True, 'month': False, 'dayofmonth': False, 'lag367': False, 'lag120': False, 'lag1825': True, 'lag60': False, 'lag362': False, 'year': False, 'Trash_Law': True, 'residualslag17': True, 'residualslag30': False, 'temperature_2m_max_lag14': False, 'apparent_temperature_min_lag30': False, 'quarter': True, 'temperature_2m_max_lag30': False, 'month_cos': False, 'New_Trash_Law': False, 'lag16': False, 'residualslag21': True, 'lag180': True, 'ma120': True, 'apparent_temperature_min_lag90': False, 'ma30': True, 'apparent_temperature_min_lag300': False, 'lag1460': True, 'apparent_temperature_min': True, 'residualslag16': True, 'temperature_2m_min': True, 'apparent_temperature_min_lag20': False, 'lag30': True, 'lag730': True, 'apparent_temperature_min_lag14': True, 'apparent_temperature_min_lag210': True, 'ma365': True, 'apparent_temperature_min_lag120': False, 'trend': False, 'ma180': True, 'apparent_temperature_min_lag270': True, 'residualslag730': True, 'residualslag18': True, 'lag363': False, 'residuals': True, 'ma60': True, 'temperature_2m_max': False, 'lag366': True, 'lag150': True, 'weekofyear': True, 'lag90': True, 'apparent_temperature_min_lag240': False, 'dayofweek': False, 'ma7': False, 'residualslag20': True, 'lag364': False}. Best is trial 246 with value: 4.333800161951233.

Trial starting: 304

[I 2026-03-15 17:36:33,610] Trial 291 finished with value: 13.460146372398924 and parameters: {'changepoint_prior_scale': 0.40282369675986684, 'seasonality_prior_scale': 1.3351006230370128, 'holidays_prior_scale': 0.31722471222367743, 'n_estimators': 862, 'max_depth': 7, 'learning_rate': 0.003239793000096118, 'subsample': 0.6882043745907971, 'colsample_bytree': 0.9583387143636426, 'gamma': 1.3977328926662538, 'min_child_weight': 10, 'reg_lambda': 0.577046506492789, 'reg_alpha': 0.3073390530678378, 'month_sin': True, 'apparent_temperature_min_lag150': False, 'apparent_temperature_min_lag21': False, 'apparent_temperature_min_lag16': True, 'apparent_temperature_min_lag365': True, 'dayofweek_cos': False, 'apparent_temperature_min_lag60': True, 'residualslag19': False, 'dayofweek_sin': True, 'Rat_Czar_Appointed': False, 'apparent_temperature_min_lag730': True, 'yhat_upper': False, 'apparent_temperature_min_lag360': False, 'apparent_temperature_min_lag18': False, 'temperature_2m_mean': False, 'apparent_temperature_max': False, 'lag365': False, 'temperature_2m_max_lag60': True, 'lag1095': False, 'ma150': False, 'apparent_temperature_min_lag15': False, 'lag15': False, 'apparent_temperature_min_lag19': True, 'residualslag365': True, 'apparent_temperature_mean': True, 'yhat_lower': True, 'is_federal_holiday': False, 'apparent_temperature_min_lag180': True, 'apparent_temperature_min_lag17': False, 'apparent_temperature_min_lag330': True, 'residualslag15': True, 'ma90': False, 'Rat_Mitigation_Zone': True, 'snowfall_sum': False, 'precipitation_sum': True, 'dayofyear': True, 'month': False, 'dayofmonth': False, 'lag367': False, 'lag120': False, 'lag1825': True, 'lag60': False, 'lag362': False, 'year': False, 'Trash_Law': True, 'residualslag17': True, 'residualslag30': False, 'temperature_2m_max_lag14': False, 'apparent_temperature_min_lag30': False, 'quarter': True, 'temperature_2m_max_lag30': False, 'month_cos': False, 'New_Trash_Law': False, 'lag16': False, 'residualslag21': True, 'lag180': True, 'ma120': False, 'apparent_temperature_min_lag90': False, 'ma30': True, 'apparent_temperature_min_lag300': False, 'lag1460': True, 'apparent_temperature_min': False, 'residualslag16': True, 'temperature_2m_min': True, 'apparent_temperature_min_lag20': False, 'lag30': True, 'lag730': True, 'apparent_temperature_min_lag14': True, 'apparent_temperature_min_lag210': True, 'ma365': True, 'apparent_temperature_min_lag120': False, 'trend': False, 'ma180': True, 'apparent_temperature_min_lag270': True, 'residualslag730': True, 'residualslag18': True, 'lag363': False, 'residuals': True, 'ma60': True, 'temperature_2m_max': False, 'lag366': True, 'lag150': True, 'weekofyear': True, 'lag90': True, 'apparent_temperature_min_lag240': False, 'dayofweek': False, 'ma7': False, 'residualslag20': True, 'lag364': False}. Best is trial 246 with value: 4.333800161951233.

Trial starting: 305

[I 2026-03-15 17:37:06,792] Trial 288 finished with value: 13.03933074700635 and parameters: {'changepoint_prior_scale': 0.40253469921600127, 'seasonality_prior_scale': 1.3578071086506556, 'holidays_prior_scale': 0.29941622254929023, 'n_estimators': 865, 'max_depth': 7, 'learning_rate': 0.003401865533108019, 'subsample': 0.6948247569424078, 'colsample_bytree': 0.941795692123367, 'gamma': 1.3680458220675433, 'min_child_weight': 10, 'reg_lambda': 0.13681984746356565, 'reg_alpha': 0.141413198163877, 'month_sin': True, 'apparent_temperature_min_lag150': False, 'apparent_temperature_min_lag21': False, 'apparent_temperature_min_lag16': True, 'apparent_temperature_min_lag365': True, 'dayofweek_cos': False, 'apparent_temperature_min_lag60': True, 'residualslag19': False, 'dayofweek_sin': True, 'Rat_Czar_Appointed': False, 'apparent_temperature_min_lag730': True, 'yhat_upper': False, 'apparent_temperature_min_lag360': False, 'apparent_temperature_min_lag18': False, 'temperature_2m_mean': False, 'apparent_temperature_max': False, 'lag365': False, 'temperature_2m_max_lag60': True, 'lag1095': False, 'ma150': False, 'apparent_temperature_min_lag15': False, 'lag15': False, 'apparent_temperature_min_lag19': True, 'residualslag365': True, 'apparent_temperature_mean': True, 'yhat_lower': False, 'is_federal_holiday': False, 'apparent_temperature_min_lag180': True, 'apparent_temperature_min_lag17': False, 'apparent_temperature_min_lag330': True, 'residualslag15': True, 'ma90': False, 'Rat_Mitigation_Zone': True, 'snowfall_sum': False, 'precipitation_sum': True, 'dayofyear': True, 'month': False, 'dayofmonth': False, 'lag367': False, 'lag120': False, 'lag1825': True, 'lag60': False, 'lag362': False, 'year': False, 'Trash_Law': True, 'residualslag17': True, 'residualslag30': False, 'temperature_2m_max_lag14': False, 'apparent_temperature_min_lag30': False, 'quarter': True, 'temperature_2m_max_lag30': False, 'month_cos': False, 'New_Trash_Law': False, 'lag16': False, 'residualslag21': True, 'lag180': True, 'ma120': False, 'apparent_temperature_min_lag90': False, 'ma30': True, 'apparent_temperature_min_lag300': False, 'lag1460': True, 'apparent_temperature_min': False, 'residualslag16': True, 'temperature_2m_min': True, 'apparent_temperature_min_lag20': False, 'lag30': True, 'lag730': True, 'apparent_temperature_min_lag14': True, 'apparent_temperature_min_lag210': True, 'ma365': False, 'apparent_temperature_min_lag120': False, 'trend': False, 'ma180': True, 'apparent_temperature_min_lag270': True, 'residualslag730': True, 'residualslag18': True, 'lag363': False, 'residuals': True, 'ma60': True, 'temperature_2m_max': False, 'lag366': True, 'lag150': True, 'weekofyear': True, 'lag90': True, 'apparent_temperature_min_lag240': False, 'dayofweek': False, 'ma7': False, 'residualslag20': True, 'lag364': False}. Best is trial 246 with value: 4.333800161951233.

Trial starting: 306

[I 2026-03-15 17:37:25,547] Trial 300 finished with value: 13.054524047206682 and parameters: {'changepoint_prior_scale': 0.4028604393996746, 'seasonality_prior_scale': 0.8443681767136788, 'holidays_prior_scale': 0.29653042076522, 'n_estimators': 877, 'max_depth': 7, 'learning_rate': 0.003152185555241672, 'subsample': 0.6886947186282713, 'colsample_bytree': 0.9545207525439232, 'gamma': 1.4082161954915002, 'min_child_weight': 10, 'reg_lambda': 0.1366808758650323, 'reg_alpha': 0.1467963287108267, 'month_sin': True, 'apparent_temperature_min_lag150': False, 'apparent_temperature_min_lag21': False, 'apparent_temperature_min_lag16': True, 'apparent_temperature_min_lag365': True, 'dayofweek_cos': False, 'apparent_temperature_min_lag60': True, 'residualslag19': False, 'dayofweek_sin': True, 'Rat_Czar_Appointed': False, 'apparent_temperature_min_lag730': True, 'yhat_upper': False, 'apparent_temperature_min_lag360': False, 'apparent_temperature_min_lag18': False, 'temperature_2m_mean': False, 'apparent_temperature_max': True, 'lag365': False, 'temperature_2m_max_lag60': True, 'lag1095': False, 'ma150': False, 'apparent_temperature_min_lag15': False, 'lag15': False, 'apparent_temperature_min_lag19': True, 'residualslag365': True, 'apparent_temperature_mean': True, 'yhat_lower': False, 'is_federal_holiday': False, 'apparent_temperature_min_lag180': True, 'apparent_temperature_min_lag17': False, 'apparent_temperature_min_lag330': True, 'residualslag15': True, 'ma90': False, 'Rat_Mitigation_Zone': True, 'snowfall_sum': False, 'precipitation_sum': True, 'dayofyear': True, 'month': False, 'dayofmonth': False, 'lag367': False, 'lag120': False, 'lag1825': True, 'lag60': False, 'lag362': False, 'year': False, 'Trash_Law': True, 'residualslag17': True, 'residualslag30': False, 'temperature_2m_max_lag14': False, 'apparent_temperature_min_lag30': False, 'quarter': True, 'temperature_2m_max_lag30': False, 'month_cos': False, 'New_Trash_Law': False, 'lag16': False, 'residualslag21': True, 'lag180': True, 'ma120': True, 'apparent_temperature_min_lag90': False, 'ma30': True, 'apparent_temperature_min_lag300': False, 'lag1460': True, 'apparent_temperature_min': True, 'residualslag16': True, 'temperature_2m_min': True, 'apparent_temperature_min_lag20': False, 'lag30': True, 'lag730': True, 'apparent_temperature_min_lag14': True, 'apparent_temperature_min_lag210': True, 'ma365': True, 'apparent_temperature_min_lag120': False, 'trend': False, 'ma180': True, 'apparent_temperature_min_lag270': True, 'residualslag730': True, 'residualslag18': True, 'lag363': False, 'residuals': True, 'ma60': True, 'temperature_2m_max': False, 'lag366': True, 'lag150': True, 'weekofyear': True, 'lag90': True, 'apparent_temperature_min_lag240': False, 'dayofweek': False, 'ma7': False, 'residualslag20': True, 'lag364': False}. Best is trial 246 with value: 4.333800161951233.

Trial starting: 307

[I 2026-03-15 17:37:38,614] Trial 293 finished with value: 13.050606954630515 and parameters: {'changepoint_prior_scale': 0.41399061341025734, 'seasonality_prior_scale': 0.7862109519450973, 'holidays_prior_scale': 0.307236782046085, 'n_estimators': 882, 'max_depth': 7, 'learning_rate': 0.0032907517419139354, 'subsample': 0.6996773924738577, 'colsample_bytree': 0.9403684901357012, 'gamma': 1.4120360551097833, 'min_child_weight': 10, 'reg_lambda': 0.13737930273123158, 'reg_alpha': 0.1534194728719445, 'month_sin': True, 'apparent_temperature_min_lag150': False, 'apparent_temperature_min_lag21': False, 'apparent_temperature_min_lag16': True, 'apparent_temperature_min_lag365': True, 'dayofweek_cos': False, 'apparent_temperature_min_lag60': True, 'residualslag19': False, 'dayofweek_sin': True, 'Rat_Czar_Appointed': False, 'apparent_temperature_min_lag730': True, 'yhat_upper': False, 'apparent_temperature_min_lag360': False, 'apparent_temperature_min_lag18': False, 'temperature_2m_mean': False, 'apparent_temperature_max': True, 'lag365': False, 'temperature_2m_max_lag60': True, 'lag1095': False, 'ma150': False, 'apparent_temperature_min_lag15': False, 'lag15': False, 'apparent_temperature_min_lag19': True, 'residualslag365': True, 'apparent_temperature_mean': True, 'yhat_lower': False, 'is_federal_holiday': False, 'apparent_temperature_min_lag180': True, 'apparent_temperature_min_lag17': False, 'apparent_temperature_min_lag330': True, 'residualslag15': True, 'ma90': False, 'Rat_Mitigation_Zone': True, 'snowfall_sum': False, 'precipitation_sum': True, 'dayofyear': True, 'month': False, 'dayofmonth': False, 'lag367': False, 'lag120': False, 'lag1825': True, 'lag60': False, 'lag362': False, 'year': False, 'Trash_Law': True, 'residualslag17': True, 'residualslag30': False, 'temperature_2m_max_lag14': False, 'apparent_temperature_min_lag30': False, 'quarter': True, 'temperature_2m_max_lag30': False, 'month_cos': False, 'New_Trash_Law': False, 'lag16': False, 'residualslag21': True, 'lag180': True, 'ma120': False, 'apparent_temperature_min_lag90': False, 'ma30': True, 'apparent_temperature_min_lag300': False, 'lag1460': True, 'apparent_temperature_min': False, 'residualslag16': True, 'temperature_2m_min': True, 'apparent_temperature_min_lag20': False, 'lag30': True, 'lag730': True, 'apparent_temperature_min_lag14': True, 'apparent_temperature_min_lag210': True, 'ma365': False, 'apparent_temperature_min_lag120': False, 'trend': False, 'ma180': True, 'apparent_temperature_min_lag270': True, 'residualslag730': True, 'residualslag18': True, 'lag363': False, 'residuals': True, 'ma60': True, 'temperature_2m_max': False, 'lag366': True, 'lag150': True, 'weekofyear': True, 'lag90': True, 'apparent_temperature_min_lag240': False, 'dayofweek': False, 'ma7': False, 'residualslag20': True, 'lag364': False}. Best is trial 246 with value: 4.333800161951233.

Trial starting: 308

[I 2026-03-15 17:37:48,187] Trial 301 finished with value: 12.886792668961533 and parameters: {'changepoint_prior_scale': 0.4038280774303638, 'seasonality_prior_scale': 1.3337945296973994, 'holidays_prior_scale': 0.3026137494811919, 'n_estimators': 885, 'max_depth': 7, 'learning_rate': 0.0031482204294166287, 'subsample': 0.6981760787154836, 'colsample_bytree': 0.9218649699800506, 'gamma': 1.3789196059716964, 'min_child_weight': 10, 'reg_lambda': 0.13675442143242805, 'reg_alpha': 0.15445807475935636, 'month_sin': True, 'apparent_temperature_min_lag150': False, 'apparent_temperature_min_lag21': False, 'apparent_temperature_min_lag16': True, 'apparent_temperature_min_lag365': True, 'dayofweek_cos': False, 'apparent_temperature_min_lag60': True, 'residualslag19': False, 'dayofweek_sin': True, 'Rat_Czar_Appointed': False, 'apparent_temperature_min_lag730': True, 'yhat_upper': False, 'apparent_temperature_min_lag360': False, 'apparent_temperature_min_lag18': False, 'temperature_2m_mean': False, 'apparent_temperature_max': True, 'lag365': False, 'temperature_2m_max_lag60': True, 'lag1095': False, 'ma150': False, 'apparent_temperature_min_lag15': False, 'lag15': False, 'apparent_temperature_min_lag19': True, 'residualslag365': True, 'apparent_temperature_mean': True, 'yhat_lower': False, 'is_federal_holiday': False, 'apparent_temperature_min_lag180': True, 'apparent_temperature_min_lag17': False, 'apparent_temperature_min_lag330': True, 'residualslag15': True, 'ma90': False, 'Rat_Mitigation_Zone': True, 'snowfall_sum': False, 'precipitation_sum': True, 'dayofyear': True, 'month': False, 'dayofmonth': False, 'lag367': False, 'lag120': False, 'lag1825': True, 'lag60': False, 'lag362': False, 'year': False, 'Trash_Law': True, 'residualslag17': True, 'residualslag30': False, 'temperature_2m_max_lag14': False, 'apparent_temperature_min_lag30': False, 'quarter': True, 'temperature_2m_max_lag30': False, 'month_cos': False, 'New_Trash_Law': False, 'lag16': False, 'residualslag21': True, 'lag180': True, 'ma120': False, 'apparent_temperature_min_lag90': False, 'ma30': True, 'apparent_temperature_min_lag300': False, 'lag1460': True, 'apparent_temperature_min': False, 'residualslag16': True, 'temperature_2m_min': True, 'apparent_temperature_min_lag20': False, 'lag30': True, 'lag730': True, 'apparent_temperature_min_lag14': True, 'apparent_temperature_min_lag210': True, 'ma365': False, 'apparent_temperature_min_lag120': False, 'trend': False, 'ma180': True, 'apparent_temperature_min_lag270': True, 'residualslag730': True, 'residualslag18': True, 'lag363': False, 'residuals': True, 'ma60': True, 'temperature_2m_max': False, 'lag366': True, 'lag150': True, 'weekofyear': True, 'lag90': True, 'apparent_temperature_min_lag240': False, 'dayofweek': False, 'ma7': False, 'residualslag20': True, 'lag364': False}. Best is trial 246 with value: 4.333800161951233.

Trial starting: 309

[I 2026-03-15 17:37:58,279] Trial 296 finished with value: 13.299666851276157 and parameters: {'changepoint_prior_scale': 0.4006650080230327, 'seasonality_prior_scale': 1.3487477227263975, 'holidays_prior_scale': 0.2874337180588489, 'n_estimators': 905, 'max_depth': 7, 'learning_rate': 0.003328058701971685, 'subsample': 0.6962596667705175, 'colsample_bytree': 0.9485496266906274, 'gamma': 1.4088470672606945, 'min_child_weight': 10, 'reg_lambda': 0.13550138580231846, 'reg_alpha': 0.1477871750044372, 'month_sin': True, 'apparent_temperature_min_lag150': False, 'apparent_temperature_min_lag21': False, 'apparent_temperature_min_lag16': True, 'apparent_temperature_min_lag365': True, 'dayofweek_cos': False, 'apparent_temperature_min_lag60': True, 'residualslag19': False, 'dayofweek_sin': True, 'Rat_Czar_Appointed': False, 'apparent_temperature_min_lag730': True, 'yhat_upper': False, 'apparent_temperature_min_lag360': False, 'apparent_temperature_min_lag18': False, 'temperature_2m_mean': False, 'apparent_temperature_max': True, 'lag365': False, 'temperature_2m_max_lag60': True, 'lag1095': False, 'ma150': False, 'apparent_temperature_min_lag15': False, 'lag15': False, 'apparent_temperature_min_lag19': True, 'residualslag365': True, 'apparent_temperature_mean': True, 'yhat_lower': False, 'is_federal_holiday': False, 'apparent_temperature_min_lag180': True, 'apparent_temperature_min_lag17': False, 'apparent_temperature_min_lag330': True, 'residualslag15': True, 'ma90': False, 'Rat_Mitigation_Zone': True, 'snowfall_sum': False, 'precipitation_sum': True, 'dayofyear': True, 'month': False, 'dayofmonth': False, 'lag367': False, 'lag120': False, 'lag1825': True, 'lag60': False, 'lag362': False, 'year': False, 'Trash_Law': True, 'residualslag17': True, 'residualslag30': False, 'temperature_2m_max_lag14': False, 'apparent_temperature_min_lag30': False, 'quarter': True, 'temperature_2m_max_lag30': False, 'month_cos': False, 'New_Trash_Law': False, 'lag16': False, 'residualslag21': True, 'lag180': True, 'ma120': False, 'apparent_temperature_min_lag90': False, 'ma30': True, 'apparent_temperature_min_lag300': False, 'lag1460': True, 'apparent_temperature_min': False, 'residualslag16': True, 'temperature_2m_min': True, 'apparent_temperature_min_lag20': False, 'lag30': True, 'lag730': True, 'apparent_temperature_min_lag14': True, 'apparent_temperature_min_lag210': True, 'ma365': True, 'apparent_temperature_min_lag120': False, 'trend': False, 'ma180': True, 'apparent_temperature_min_lag270': True, 'residualslag730': True, 'residualslag18': True, 'lag363': False, 'residuals': True, 'ma60': True, 'temperature_2m_max': False, 'lag366': True, 'lag150': True, 'weekofyear': True, 'lag90': True, 'apparent_temperature_min_lag240': False, 'dayofweek': False, 'ma7': False, 'residualslag20': True, 'lag364': True}. Best is trial 246 with value: 4.333800161951233.

Trial starting: 310

[I 2026-03-15 17:38:16,683] Trial 287 finished with value: 13.131710450319009 and parameters: {'changepoint_prior_scale': 0.3992801207447313, 'seasonality_prior_scale': 1.3350966207316242, 'holidays_prior_scale': 0.3068243191198456, 'n_estimators': 873, 'max_depth': 7, 'learning_rate': 0.003189466451041769, 'subsample': 0.706708553051008, 'colsample_bytree': 0.9320603268494428, 'gamma': 1.3718759088663792, 'min_child_weight': 10, 'reg_lambda': 0.1384526041590997, 'reg_alpha': 0.149430058838451, 'month_sin': True, 'apparent_temperature_min_lag150': False, 'apparent_temperature_min_lag21': False, 'apparent_temperature_min_lag16': True, 'apparent_temperature_min_lag365': True, 'dayofweek_cos': False, 'apparent_temperature_min_lag60': True, 'residualslag19': False, 'dayofweek_sin': True, 'Rat_Czar_Appointed': False, 'apparent_temperature_min_lag730': True, 'yhat_upper': False, 'apparent_temperature_min_lag360': False, 'apparent_temperature_min_lag18': False, 'temperature_2m_mean': False, 'apparent_temperature_max': True, 'lag365': False, 'temperature_2m_max_lag60': True, 'lag1095': False, 'ma150': False, 'apparent_temperature_min_lag15': False, 'lag15': False, 'apparent_temperature_min_lag19': True, 'residualslag365': True, 'apparent_temperature_mean': True, 'yhat_lower': False, 'is_federal_holiday': False, 'apparent_temperature_min_lag180': True, 'apparent_temperature_min_lag17': False, 'apparent_temperature_min_lag330': True, 'residualslag15': True, 'ma90': False, 'Rat_Mitigation_Zone': True, 'snowfall_sum': False, 'precipitation_sum': True, 'dayofyear': True, 'month': False, 'dayofmonth': False, 'lag367': False, 'lag120': False, 'lag1825': True, 'lag60': False, 'lag362': False, 'year': False, 'Trash_Law': True, 'residualslag17': True, 'residualslag30': False, 'temperature_2m_max_lag14': False, 'apparent_temperature_min_lag30': False, 'quarter': True, 'temperature_2m_max_lag30': False, 'month_cos': False, 'New_Trash_Law': False, 'lag16': False, 'residualslag21': True, 'lag180': True, 'ma120': False, 'apparent_temperature_min_lag90': False, 'ma30': True, 'apparent_temperature_min_lag300': False, 'lag1460': True, 'apparent_temperature_min': False, 'residualslag16': True, 'temperature_2m_min': True, 'apparent_temperature_min_lag20': False, 'lag30': True, 'lag730': True, 'apparent_temperature_min_lag14': True, 'apparent_temperature_min_lag210': True, 'ma365': True, 'apparent_temperature_min_lag120': False, 'trend': False, 'ma180': True, 'apparent_temperature_min_lag270': True, 'residualslag730': True, 'residualslag18': True, 'lag363': False, 'residuals': True, 'ma60': True, 'temperature_2m_max': False, 'lag366': True, 'lag150': True, 'weekofyear': True, 'lag90': True, 'apparent_temperature_min_lag240': False, 'dayofweek': False, 'ma7': False, 'residualslag20': True, 'lag364': False}. Best is trial 246 with value: 4.333800161951233.

Trial starting: 311

[I 2026-03-15 17:38:27,055] Trial 295 finished with value: 4.334226429492822 and parameters: {'changepoint_prior_scale': 0.4039322030420901, 'seasonality_prior_scale': 1.3704979089587657, 'holidays_prior_scale': 0.3011123073194776, 'n_estimators': 845, 'max_depth': 7, 'learning_rate': 0.0031956838212934204, 'subsample': 0.7117847192196565, 'colsample_bytree': 0.939681089115598, 'gamma': 1.367325173947554, 'min_child_weight': 10, 'reg_lambda': 0.13673231181062528, 'reg_alpha': 0.14880857971676184, 'month_sin': True, 'apparent_temperature_min_lag150': False, 'apparent_temperature_min_lag21': False, 'apparent_temperature_min_lag16': True, 'apparent_temperature_min_lag365': True, 'dayofweek_cos': False, 'apparent_temperature_min_lag60': True, 'residualslag19': False, 'dayofweek_sin': True, 'Rat_Czar_Appointed': False, 'apparent_temperature_min_lag730': True, 'yhat_upper': False, 'apparent_temperature_min_lag360': False, 'apparent_temperature_min_lag18': False, 'temperature_2m_mean': False, 'apparent_temperature_max': True, 'lag365': False, 'temperature_2m_max_lag60': True, 'lag1095': False, 'ma150': False, 'apparent_temperature_min_lag15': False, 'lag15': False, 'apparent_temperature_min_lag19': True, 'residualslag365': True, 'apparent_temperature_mean': True, 'yhat_lower': False, 'is_federal_holiday': False, 'apparent_temperature_min_lag180': True, 'apparent_temperature_min_lag17': False, 'apparent_temperature_min_lag330': True, 'residualslag15': True, 'ma90': False, 'Rat_Mitigation_Zone': True, 'snowfall_sum': False, 'precipitation_sum': True, 'dayofyear': True, 'month': False, 'dayofmonth': False, 'lag367': False, 'lag120': False, 'lag1825': True, 'lag60': False, 'lag362': False, 'year': False, 'Trash_Law': True, 'residualslag17': True, 'residualslag30': False, 'temperature_2m_max_lag14': False, 'apparent_temperature_min_lag30': False, 'quarter': True, 'temperature_2m_max_lag30': False, 'month_cos': False, 'New_Trash_Law': False, 'lag16': False, 'residualslag21': True, 'lag180': True, 'ma120': False, 'apparent_temperature_min_lag90': False, 'ma30': True, 'apparent_temperature_min_lag300': False, 'lag1460': True, 'apparent_temperature_min': False, 'residualslag16': True, 'temperature_2m_min': True, 'apparent_temperature_min_lag20': False, 'lag30': True, 'lag730': True, 'apparent_temperature_min_lag14': True, 'apparent_temperature_min_lag210': True, 'ma365': True, 'apparent_temperature_min_lag120': False, 'trend': False, 'ma180': True, 'apparent_temperature_min_lag270': True, 'residualslag730': True, 'residualslag18': True, 'lag363': False, 'residuals': False, 'ma60': True, 'temperature_2m_max': False, 'lag366': True, 'lag150': True, 'weekofyear': True, 'lag90': True, 'apparent_temperature_min_lag240': False, 'dayofweek': False, 'ma7': False, 'residualslag20': True, 'lag364': False}. Best is trial 246 with value: 4.333800161951233.

Trial starting: 312

[I 2026-03-15 17:38:29,751] Trial 292 finished with value: 13.347730770737003 and parameters: {'changepoint_prior_scale': 0.4061862586296542, 'seasonality_prior_scale': 1.3789513766992192, 'holidays_prior_scale': 0.28336189947672386, 'n_estimators': 917, 'max_depth': 7, 'learning_rate': 0.0033994403736637333, 'subsample': 0.6977975029174076, 'colsample_bytree': 0.9435008823518037, 'gamma': 1.3340528369278315, 'min_child_weight': 10, 'reg_lambda': 0.13820773035689182, 'reg_alpha': 0.1610838862845388, 'month_sin': True, 'apparent_temperature_min_lag150': False, 'apparent_temperature_min_lag21': False, 'apparent_temperature_min_lag16': True, 'apparent_temperature_min_lag365': True, 'dayofweek_cos': False, 'apparent_temperature_min_lag60': True, 'residualslag19': False, 'dayofweek_sin': True, 'Rat_Czar_Appointed': False, 'apparent_temperature_min_lag730': True, 'yhat_upper': False, 'apparent_temperature_min_lag360': False, 'apparent_temperature_min_lag18': False, 'temperature_2m_mean': False, 'apparent_temperature_max': True, 'lag365': False, 'temperature_2m_max_lag60': True, 'lag1095': False, 'ma150': False, 'apparent_temperature_min_lag15': False, 'lag15': False, 'apparent_temperature_min_lag19': True, 'residualslag365': True, 'apparent_temperature_mean': True, 'yhat_lower': True, 'is_federal_holiday': False, 'apparent_temperature_min_lag180': True, 'apparent_temperature_min_lag17': False, 'apparent_temperature_min_lag330': True, 'residualslag15': True, 'ma90': False, 'Rat_Mitigation_Zone': True, 'snowfall_sum': False, 'precipitation_sum': False, 'dayofyear': True, 'month': False, 'dayofmonth': False, 'lag367': False, 'lag120': False, 'lag1825': True, 'lag60': False, 'lag362': False, 'year': False, 'Trash_Law': True, 'residualslag17': True, 'residualslag30': False, 'temperature_2m_max_lag14': False, 'apparent_temperature_min_lag30': False, 'quarter': True, 'temperature_2m_max_lag30': False, 'month_cos': False, 'New_Trash_Law': False, 'lag16': False, 'residualslag21': True, 'lag180': True, 'ma120': False, 'apparent_temperature_min_lag90': False, 'ma30': True, 'apparent_temperature_min_lag300': False, 'lag1460': True, 'apparent_temperature_min': True, 'residualslag16': True, 'temperature_2m_min': True, 'apparent_temperature_min_lag20': False, 'lag30': True, 'lag730': True, 'apparent_temperature_min_lag14': True, 'apparent_temperature_min_lag210': True, 'ma365': True, 'apparent_temperature_min_lag120': False, 'trend': False, 'ma180': True, 'apparent_temperature_min_lag270': True, 'residualslag730': True, 'residualslag18': True, 'lag363': False, 'residuals': True, 'ma60': True, 'temperature_2m_max': False, 'lag366': True, 'lag150': True, 'weekofyear': True, 'lag90': True, 'apparent_temperature_min_lag240': False, 'dayofweek': False, 'ma7': False, 'residualslag20': True, 'lag364': False}. Best is trial 246 with value: 4.333800161951233.

Trial starting: 313

[I 2026-03-15 17:38:44,663] Trial 289 finished with value: 13.363254043480937 and parameters: {'changepoint_prior_scale': 0.4018374050195889, 'seasonality_prior_scale': 1.356660203589177, 'holidays_prior_scale': 0.3069457183010805, 'n_estimators': 937, 'max_depth': 7, 'learning_rate': 0.003294234938456643, 'subsample': 0.7172778490907648, 'colsample_bytree': 0.9409605347361921, 'gamma': 1.3236420224465861, 'min_child_weight': 10, 'reg_lambda': 0.13600087512114836, 'reg_alpha': 0.31126487269886993, 'month_sin': True, 'apparent_temperature_min_lag150': False, 'apparent_temperature_min_lag21': False, 'apparent_temperature_min_lag16': True, 'apparent_temperature_min_lag365': True, 'dayofweek_cos': False, 'apparent_temperature_min_lag60': True, 'residualslag19': False, 'dayofweek_sin': True, 'Rat_Czar_Appointed': False, 'apparent_temperature_min_lag730': True, 'yhat_upper': False, 'apparent_temperature_min_lag360': False, 'apparent_temperature_min_lag18': False, 'temperature_2m_mean': False, 'apparent_temperature_max': False, 'lag365': False, 'temperature_2m_max_lag60': True, 'lag1095': False, 'ma150': False, 'apparent_temperature_min_lag15': False, 'lag15': False, 'apparent_temperature_min_lag19': True, 'residualslag365': True, 'apparent_temperature_mean': True, 'yhat_lower': False, 'is_federal_holiday': False, 'apparent_temperature_min_lag180': True, 'apparent_temperature_min_lag17': False, 'apparent_temperature_min_lag330': True, 'residualslag15': True, 'ma90': False, 'Rat_Mitigation_Zone': True, 'snowfall_sum': False, 'precipitation_sum': False, 'dayofyear': True, 'month': False, 'dayofmonth': False, 'lag367': False, 'lag120': False, 'lag1825': True, 'lag60': False, 'lag362': False, 'year': False, 'Trash_Law': True, 'residualslag17': True, 'residualslag30': False, 'temperature_2m_max_lag14': False, 'apparent_temperature_min_lag30': False, 'quarter': True, 'temperature_2m_max_lag30': False, 'month_cos': False, 'New_Trash_Law': False, 'lag16': False, 'residualslag21': True, 'lag180': True, 'ma120': True, 'apparent_temperature_min_lag90': False, 'ma30': True, 'apparent_temperature_min_lag300': False, 'lag1460': True, 'apparent_temperature_min': False, 'residualslag16': True, 'temperature_2m_min': True, 'apparent_temperature_min_lag20': False, 'lag30': True, 'lag730': True, 'apparent_temperature_min_lag14': True, 'apparent_temperature_min_lag210': True, 'ma365': True, 'apparent_temperature_min_lag120': False, 'trend': False, 'ma180': True, 'apparent_temperature_min_lag270': True, 'residualslag730': True, 'residualslag18': True, 'lag363': False, 'residuals': True, 'ma60': True, 'temperature_2m_max': False, 'lag366': True, 'lag150': True, 'weekofyear': True, 'lag90': True, 'apparent_temperature_min_lag240': False, 'dayofweek': False, 'ma7': False, 'residualslag20': True, 'lag364': False}. Best is trial 246 with value: 4.333800161951233.

Trial starting: 314

[I 2026-03-15 17:39:12,851] Trial 290 finished with value: 4.327594319345157 and parameters: {'changepoint_prior_scale': 0.3998114498477507, 'seasonality_prior_scale': 0.7919535339964112, 'holidays_prior_scale': 0.36724632299712584, 'n_estimators': 881, 'max_depth': 7, 'learning_rate': 0.0033092224233094653, 'subsample': 0.7025828154551923, 'colsample_bytree': 0.9312477937620559, 'gamma': 1.3592312696314628, 'min_child_weight': 10, 'reg_lambda': 0.13793150225938292, 'reg_alpha': 0.1437659390166272, 'month_sin': True, 'apparent_temperature_min_lag150': False, 'apparent_temperature_min_lag21': False, 'apparent_temperature_min_lag16': True, 'apparent_temperature_min_lag365': True, 'dayofweek_cos': False, 'apparent_temperature_min_lag60': True, 'residualslag19': False, 'dayofweek_sin': True, 'Rat_Czar_Appointed': False, 'apparent_temperature_min_lag730': True, 'yhat_upper': False, 'apparent_temperature_min_lag360': False, 'apparent_temperature_min_lag18': False, 'temperature_2m_mean': False, 'apparent_temperature_max': True, 'lag365': False, 'temperature_2m_max_lag60': True, 'lag1095': False, 'ma150': False, 'apparent_temperature_min_lag15': False, 'lag15': False, 'apparent_temperature_min_lag19': True, 'residualslag365': True, 'apparent_temperature_mean': True, 'yhat_lower': False, 'is_federal_holiday': False, 'apparent_temperature_min_lag180': True, 'apparent_temperature_min_lag17': False, 'apparent_temperature_min_lag330': True, 'residualslag15': True, 'ma90': False, 'Rat_Mitigation_Zone': True, 'snowfall_sum': False, 'precipitation_sum': True, 'dayofyear': True, 'month': False, 'dayofmonth': False, 'lag367': False, 'lag120': False, 'lag1825': True, 'lag60': False, 'lag362': False, 'year': False, 'Trash_Law': True, 'residualslag17': True, 'residualslag30': True, 'temperature_2m_max_lag14': False, 'apparent_temperature_min_lag30': False, 'quarter': True, 'temperature_2m_max_lag30': False, 'month_cos': False, 'New_Trash_Law': False, 'lag16': False, 'residualslag21': True, 'lag180': True, 'ma120': True, 'apparent_temperature_min_lag90': False, 'ma30': True, 'apparent_temperature_min_lag300': False, 'lag1460': True, 'apparent_temperature_min': False, 'residualslag16': True, 'temperature_2m_min': True, 'apparent_temperature_min_lag20': False, 'lag30': True, 'lag730': True, 'apparent_temperature_min_lag14': True, 'apparent_temperature_min_lag210': True, 'ma365': False, 'apparent_temperature_min_lag120': False, 'trend': False, 'ma180': True, 'apparent_temperature_min_lag270': True, 'residualslag730': True, 'residualslag18': True, 'lag363': False, 'residuals': False, 'ma60': True, 'temperature_2m_max': False, 'lag366': True, 'lag150': True, 'weekofyear': True, 'lag90': True, 'apparent_temperature_min_lag240': False, 'dayofweek': False, 'ma7': False, 'residualslag20': True, 'lag364': False}. Best is trial 290 with value: 4.327594319345157.

Trial starting: 315

[I 2026-03-15 17:39:29,185] Trial 297 finished with value: 4.329902591489777 and parameters: {'changepoint_prior_scale': 0.402325259465113, 'seasonality_prior_scale': 0.789200209199518, 'holidays_prior_scale': 0.3064111895879283, 'n_estimators': 881, 'max_depth': 7, 'learning_rate': 0.003293231908227232, 'subsample': 0.6893074684157405, 'colsample_bytree': 0.93512184493615, 'gamma': 1.3873824916980424, 'min_child_weight': 10, 'reg_lambda': 0.14161515248011752, 'reg_alpha': 0.15284029314238917, 'month_sin': True, 'apparent_temperature_min_lag150': False, 'apparent_temperature_min_lag21': False, 'apparent_temperature_min_lag16': True, 'apparent_temperature_min_lag365': True, 'dayofweek_cos': False, 'apparent_temperature_min_lag60': True, 'residualslag19': False, 'dayofweek_sin': True, 'Rat_Czar_Appointed': False, 'apparent_temperature_min_lag730': True, 'yhat_upper': False, 'apparent_temperature_min_lag360': False, 'apparent_temperature_min_lag18': False, 'temperature_2m_mean': False, 'apparent_temperature_max': True, 'lag365': False, 'temperature_2m_max_lag60': True, 'lag1095': False, 'ma150': False, 'apparent_temperature_min_lag15': False, 'lag15': False, 'apparent_temperature_min_lag19': True, 'residualslag365': True, 'apparent_temperature_mean': True, 'yhat_lower': False, 'is_federal_holiday': False, 'apparent_temperature_min_lag180': True, 'apparent_temperature_min_lag17': False, 'apparent_temperature_min_lag330': True, 'residualslag15': True, 'ma90': False, 'Rat_Mitigation_Zone': True, 'snowfall_sum': False, 'precipitation_sum': True, 'dayofyear': True, 'month': False, 'dayofmonth': False, 'lag367': False, 'lag120': False, 'lag1825': True, 'lag60': False, 'lag362': False, 'year': False, 'Trash_Law': True, 'residualslag17': True, 'residualslag30': False, 'temperature_2m_max_lag14': False, 'apparent_temperature_min_lag30': False, 'quarter': True, 'temperature_2m_max_lag30': False, 'month_cos': False, 'New_Trash_Law': False, 'lag16': False, 'residualslag21': True, 'lag180': True, 'ma120': True, 'apparent_temperature_min_lag90': False, 'ma30': True, 'apparent_temperature_min_lag300': False, 'lag1460': True, 'apparent_temperature_min': False, 'residualslag16': True, 'temperature_2m_min': True, 'apparent_temperature_min_lag20': False, 'lag30': True, 'lag730': True, 'apparent_temperature_min_lag14': True, 'apparent_temperature_min_lag210': True, 'ma365': False, 'apparent_temperature_min_lag120': False, 'trend': False, 'ma180': True, 'apparent_temperature_min_lag270': True, 'residualslag730': True, 'residualslag18': True, 'lag363': False, 'residuals': False, 'ma60': True, 'temperature_2m_max': False, 'lag366': True, 'lag150': True, 'weekofyear': True, 'lag90': True, 'apparent_temperature_min_lag240': False, 'dayofweek': False, 'ma7': False, 'residualslag20': True, 'lag364': False}. Best is trial 290 with value: 4.327594319345157.

Trial starting: 316

[I 2026-03-15 17:39:31,275] Trial 299 finished with value: 4.32694914587703 and parameters: {'changepoint_prior_scale': 0.40299864553653225, 'seasonality_prior_scale': 0.7773646597001904, 'holidays_prior_scale': 0.29065605898299623, 'n_estimators': 881, 'max_depth': 7, 'learning_rate': 0.0030673329748455405, 'subsample': 0.6996151137206843, 'colsample_bytree': 0.9546774253726503, 'gamma': 1.343881886323868, 'min_child_weight': 10, 'reg_lambda': 0.13747191411964463, 'reg_alpha': 0.30755334093922576, 'month_sin': True, 'apparent_temperature_min_lag150': False, 'apparent_temperature_min_lag21': False, 'apparent_temperature_min_lag16': True, 'apparent_temperature_min_lag365': True, 'dayofweek_cos': False, 'apparent_temperature_min_lag60': True, 'residualslag19': False, 'dayofweek_sin': True, 'Rat_Czar_Appointed': False, 'apparent_temperature_min_lag730': True, 'yhat_upper': False, 'apparent_temperature_min_lag360': False, 'apparent_temperature_min_lag18': False, 'temperature_2m_mean': False, 'apparent_temperature_max': True, 'lag365': False, 'temperature_2m_max_lag60': True, 'lag1095': False, 'ma150': False, 'apparent_temperature_min_lag15': False, 'lag15': False, 'apparent_temperature_min_lag19': True, 'residualslag365': True, 'apparent_temperature_mean': True, 'yhat_lower': False, 'is_federal_holiday': False, 'apparent_temperature_min_lag180': True, 'apparent_temperature_min_lag17': False, 'apparent_temperature_min_lag330': True, 'residualslag15': True, 'ma90': False, 'Rat_Mitigation_Zone': True, 'snowfall_sum': False, 'precipitation_sum': True, 'dayofyear': True, 'month': False, 'dayofmonth': False, 'lag367': False, 'lag120': False, 'lag1825': True, 'lag60': False, 'lag362': False, 'year': False, 'Trash_Law': True, 'residualslag17': True, 'residualslag30': False, 'temperature_2m_max_lag14': False, 'apparent_temperature_min_lag30': False, 'quarter': True, 'temperature_2m_max_lag30': False, 'month_cos': False, 'New_Trash_Law': False, 'lag16': False, 'residualslag21': True, 'lag180': True, 'ma120': False, 'apparent_temperature_min_lag90': False, 'ma30': True, 'apparent_temperature_min_lag300': False, 'lag1460': True, 'apparent_temperature_min': True, 'residualslag16': True, 'temperature_2m_min': True, 'apparent_temperature_min_lag20': False, 'lag30': True, 'lag730': True, 'apparent_temperature_min_lag14': True, 'apparent_temperature_min_lag210': True, 'ma365': True, 'apparent_temperature_min_lag120': False, 'trend': False, 'ma180': True, 'apparent_temperature_min_lag270': True, 'residualslag730': True, 'residualslag18': True, 'lag363': False, 'residuals': False, 'ma60': True, 'temperature_2m_max': False, 'lag366': True, 'lag150': True, 'weekofyear': True, 'lag90': True, 'apparent_temperature_min_lag240': False, 'dayofweek': False, 'ma7': False, 'residualslag20': True, 'lag364': False}. Best is trial 299 with value: 4.32694914587703.

Trial starting: 317

[I 2026-03-15 17:39:34,134] Trial 294 finished with value: 13.170365918202974 and parameters: {'changepoint_prior_scale': 0.41162151176313566, 'seasonality_prior_scale': 0.8432285895983872, 'holidays_prior_scale': 0.2889999045091559, 'n_estimators': 948, 'max_depth': 7, 'learning_rate': 0.003226537503153562, 'subsample': 0.72167020672104, 'colsample_bytree': 0.9442021243815367, 'gamma': 1.3440646858314362, 'min_child_weight': 10, 'reg_lambda': 0.13773839847033642, 'reg_alpha': 0.15394906701988154, 'month_sin': True, 'apparent_temperature_min_lag150': False, 'apparent_temperature_min_lag21': False, 'apparent_temperature_min_lag16': True, 'apparent_temperature_min_lag365': True, 'dayofweek_cos': False, 'apparent_temperature_min_lag60': True, 'residualslag19': False, 'dayofweek_sin': True, 'Rat_Czar_Appointed': False, 'apparent_temperature_min_lag730': True, 'yhat_upper': False, 'apparent_temperature_min_lag360': False, 'apparent_temperature_min_lag18': False, 'temperature_2m_mean': False, 'apparent_temperature_max': True, 'lag365': False, 'temperature_2m_max_lag60': True, 'lag1095': False, 'ma150': False, 'apparent_temperature_min_lag15': False, 'lag15': False, 'apparent_temperature_min_lag19': True, 'residualslag365': True, 'apparent_temperature_mean': True, 'yhat_lower': True, 'is_federal_holiday': False, 'apparent_temperature_min_lag180': True, 'apparent_temperature_min_lag17': False, 'apparent_temperature_min_lag330': True, 'residualslag15': True, 'ma90': False, 'Rat_Mitigation_Zone': True, 'snowfall_sum': False, 'precipitation_sum': True, 'dayofyear': True, 'month': False, 'dayofmonth': False, 'lag367': False, 'lag120': False, 'lag1825': True, 'lag60': False, 'lag362': False, 'year': False, 'Trash_Law': True, 'residualslag17': True, 'residualslag30': False, 'temperature_2m_max_lag14': False, 'apparent_temperature_min_lag30': False, 'quarter': True, 'temperature_2m_max_lag30': False, 'month_cos': False, 'New_Trash_Law': False, 'lag16': False, 'residualslag21': True, 'lag180': True, 'ma120': True, 'apparent_temperature_min_lag90': False, 'ma30': True, 'apparent_temperature_min_lag300': False, 'lag1460': True, 'apparent_temperature_min': False, 'residualslag16': True, 'temperature_2m_min': True, 'apparent_temperature_min_lag20': False, 'lag30': True, 'lag730': True, 'apparent_temperature_min_lag14': True, 'apparent_temperature_min_lag210': True, 'ma365': False, 'apparent_temperature_min_lag120': False, 'trend': False, 'ma180': True, 'apparent_temperature_min_lag270': True, 'residualslag730': True, 'residualslag18': True, 'lag363': False, 'residuals': True, 'ma60': True, 'temperature_2m_max': False, 'lag366': True, 'lag150': True, 'weekofyear': True, 'lag90': True, 'apparent_temperature_min_lag240': False, 'dayofweek': False, 'ma7': False, 'residualslag20': True, 'lag364': False}. Best is trial 299 with value: 4.32694914587703.

Trial starting: 318

[I 2026-03-15 17:56:47,106] Trial 313 finished with value: 4.375124674220996 and parameters: {'changepoint_prior_scale': 0.433064689485431, 'seasonality_prior_scale': 1.5327777896884702, 'holidays_prior_scale': 0.19178674854011232, 'n_estimators': 702, 'max_depth': 7, 'learning_rate': 0.004336786322873389, 'subsample': 0.6648702872508898, 'colsample_bytree': 0.8689159595765483, 'gamma': 0.8266961770662987, 'min_child_weight': 10, 'reg_lambda': 0.1575464933267646, 'reg_alpha': 0.18302415137822475, 'month_sin': True, 'apparent_temperature_min_lag150': False, 'apparent_temperature_min_lag21': False, 'apparent_temperature_min_lag16': True, 'apparent_temperature_min_lag365': True, 'dayofweek_cos': False, 'apparent_temperature_min_lag60': True, 'residualslag19': False, 'dayofweek_sin': True, 'Rat_Czar_Appointed': True, 'apparent_temperature_min_lag730': True, 'yhat_upper': False, 'apparent_temperature_min_lag360': False, 'apparent_temperature_min_lag18': False, 'temperature_2m_mean': False, 'apparent_temperature_max': False, 'lag365': False, 'temperature_2m_max_lag60': True, 'lag1095': False, 'ma150': False, 'apparent_temperature_min_lag15': False, 'lag15': False, 'apparent_temperature_min_lag19': True, 'residualslag365': True, 'apparent_temperature_mean': False, 'yhat_lower': True, 'is_federal_holiday': False, 'apparent_temperature_min_lag180': True, 'apparent_temperature_min_lag17': False, 'apparent_temperature_min_lag330': True, 'residualslag15': True, 'ma90': False, 'Rat_Mitigation_Zone': True, 'snowfall_sum': False, 'precipitation_sum': False, 'dayofyear': True, 'month': False, 'dayofmonth': False, 'lag367': False, 'lag120': False, 'lag1825': True, 'lag60': False, 'lag362': False, 'year': False, 'Trash_Law': True, 'residualslag17': True, 'residualslag30': False, 'temperature_2m_max_lag14': False, 'apparent_temperature_min_lag30': False, 'quarter': True, 'temperature_2m_max_lag30': False, 'month_cos': False, 'New_Trash_Law': False, 'lag16': False, 'residualslag21': False, 'lag180': True, 'ma120': True, 'apparent_temperature_min_lag90': False, 'ma30': True, 'apparent_temperature_min_lag300': False, 'lag1460': True, 'apparent_temperature_min': True, 'residualslag16': True, 'temperature_2m_min': True, 'apparent_temperature_min_lag20': False, 'lag30': True, 'lag730': True, 'apparent_temperature_min_lag14': True, 'apparent_temperature_min_lag210': True, 'ma365': False, 'apparent_temperature_min_lag120': False, 'trend': True, 'ma180': True, 'apparent_temperature_min_lag270': True, 'residualslag730': True, 'residualslag18': True, 'lag363': False, 'residuals': False, 'ma60': True, 'temperature_2m_max': False, 'lag366': True, 'lag150': True, 'weekofyear': True, 'lag90': True, 'apparent_temperature_min_lag240': False, 'dayofweek': False, 'ma7': False, 'residualslag20': True, 'lag364': False}. Best is trial 299 with value: 4.32694914587703.

Trial starting: 319

[I 2026-03-15 17:56:52,331] Trial 317 finished with value: 4.39712017967976 and parameters: {'changepoint_prior_scale': 0.43071565510092286, 'seasonality_prior_scale': 0.6054494757677142, 'holidays_prior_scale': 0.3734070081555904, 'n_estimators': 647, 'max_depth': 7, 'learning_rate': 0.002866006551017194, 'subsample': 0.7216962211083559, 'colsample_bytree': 0.9765249430380037, 'gamma': 0.8212039470704999, 'min_child_weight': 10, 'reg_lambda': 0.1597911925219058, 'reg_alpha': 0.17830746450788587, 'month_sin': True, 'apparent_temperature_min_lag150': False, 'apparent_temperature_min_lag21': False, 'apparent_temperature_min_lag16': True, 'apparent_temperature_min_lag365': True, 'dayofweek_cos': False, 'apparent_temperature_min_lag60': False, 'residualslag19': False, 'dayofweek_sin': True, 'Rat_Czar_Appointed': False, 'apparent_temperature_min_lag730': True, 'yhat_upper': False, 'apparent_temperature_min_lag360': False, 'apparent_temperature_min_lag18': False, 'temperature_2m_mean': False, 'apparent_temperature_max': True, 'lag365': False, 'temperature_2m_max_lag60': True, 'lag1095': False, 'ma150': False, 'apparent_temperature_min_lag15': False, 'lag15': False, 'apparent_temperature_min_lag19': True, 'residualslag365': True, 'apparent_temperature_mean': True, 'yhat_lower': False, 'is_federal_holiday': False, 'apparent_temperature_min_lag180': True, 'apparent_temperature_min_lag17': False, 'apparent_temperature_min_lag330': True, 'residualslag15': True, 'ma90': False, 'Rat_Mitigation_Zone': True, 'snowfall_sum': False, 'precipitation_sum': True, 'dayofyear': True, 'month': True, 'dayofmonth': False, 'lag367': False, 'lag120': False, 'lag1825': True, 'lag60': False, 'lag362': False, 'year': False, 'Trash_Law': True, 'residualslag17': True, 'residualslag30': False, 'temperature_2m_max_lag14': False, 'apparent_temperature_min_lag30': True, 'quarter': True, 'temperature_2m_max_lag30': False, 'month_cos': False, 'New_Trash_Law': True, 'lag16': False, 'residualslag21': True, 'lag180': True, 'ma120': False, 'apparent_temperature_min_lag90': False, 'ma30': True, 'apparent_temperature_min_lag300': False, 'lag1460': True, 'apparent_temperature_min': False, 'residualslag16': True, 'temperature_2m_min': True, 'apparent_temperature_min_lag20': True, 'lag30': True, 'lag730': True, 'apparent_temperature_min_lag14': True, 'apparent_temperature_min_lag210': True, 'ma365': True, 'apparent_temperature_min_lag120': False, 'trend': True, 'ma180': True, 'apparent_temperature_min_lag270': False, 'residualslag730': True, 'residualslag18': True, 'lag363': False, 'residuals': False, 'ma60': True, 'temperature_2m_max': False, 'lag366': True, 'lag150': True, 'weekofyear': True, 'lag90': True, 'apparent_temperature_min_lag240': True, 'dayofweek': False, 'ma7': True, 'residualslag20': True, 'lag364': False}. Best is trial 299 with value: 4.32694914587703.

Trial starting: 320

[I 2026-03-15 17:58:46,337] Trial 303 finished with value: 4.347639991321332 and parameters: {'changepoint_prior_scale': 0.406548640885952, 'seasonality_prior_scale': 1.4481797651730588, 'holidays_prior_scale': 0.19766806166493456, 'n_estimators': 881, 'max_depth': 7, 'learning_rate': 0.0033231575115768293, 'subsample': 0.6945631321619526, 'colsample_bytree': 0.9406243658201411, 'gamma': 0.827295193296337, 'min_child_weight': 10, 'reg_lambda': 0.1377871135704828, 'reg_alpha': 0.2977848004227865, 'month_sin': True, 'apparent_temperature_min_lag150': False, 'apparent_temperature_min_lag21': False, 'apparent_temperature_min_lag16': True, 'apparent_temperature_min_lag365': True, 'dayofweek_cos': False, 'apparent_temperature_min_lag60': True, 'residualslag19': False, 'dayofweek_sin': True, 'Rat_Czar_Appointed': False, 'apparent_temperature_min_lag730': True, 'yhat_upper': False, 'apparent_temperature_min_lag360': False, 'apparent_temperature_min_lag18': False, 'temperature_2m_mean': False, 'apparent_temperature_max': False, 'lag365': False, 'temperature_2m_max_lag60': True, 'lag1095': False, 'ma150': False, 'apparent_temperature_min_lag15': False, 'lag15': False, 'apparent_temperature_min_lag19': True, 'residualslag365': True, 'apparent_temperature_mean': True, 'yhat_lower': True, 'is_federal_holiday': False, 'apparent_temperature_min_lag180': True, 'apparent_temperature_min_lag17': False, 'apparent_temperature_min_lag330': True, 'residualslag15': True, 'ma90': False, 'Rat_Mitigation_Zone': True, 'snowfall_sum': False, 'precipitation_sum': False, 'dayofyear': True, 'month': False, 'dayofmonth': False, 'lag367': False, 'lag120': False, 'lag1825': True, 'lag60': False, 'lag362': False, 'year': False, 'Trash_Law': True, 'residualslag17': True, 'residualslag30': False, 'temperature_2m_max_lag14': False, 'apparent_temperature_min_lag30': False, 'quarter': True, 'temperature_2m_max_lag30': False, 'month_cos': False, 'New_Trash_Law': False, 'lag16': False, 'residualslag21': True, 'lag180': True, 'ma120': True, 'apparent_temperature_min_lag90': False, 'ma30': True, 'apparent_temperature_min_lag300': False, 'lag1460': True, 'apparent_temperature_min': True, 'residualslag16': True, 'temperature_2m_min': True, 'apparent_temperature_min_lag20': False, 'lag30': True, 'lag730': True, 'apparent_temperature_min_lag14': True, 'apparent_temperature_min_lag210': True, 'ma365': False, 'apparent_temperature_min_lag120': False, 'trend': False, 'ma180': True, 'apparent_temperature_min_lag270': True, 'residualslag730': True, 'residualslag18': True, 'lag363': False, 'residuals': False, 'ma60': True, 'temperature_2m_max': False, 'lag366': True, 'lag150': True, 'weekofyear': True, 'lag90': True, 'apparent_temperature_min_lag240': False, 'dayofweek': False, 'ma7': False, 'residualslag20': True, 'lag364': False}. Best is trial 299 with value: 4.32694914587703.

Trial starting: 321

[I 2026-03-15 17:59:05,552] Trial 312 finished with value: 4.415396750720174 and parameters: {'changepoint_prior_scale': 0.4295493080945177, 'seasonality_prior_scale': 1.5223184292525347, 'holidays_prior_scale': 0.5421559540052306, 'n_estimators': 794, 'max_depth': 7, 'learning_rate': 0.004207200377656009, 'subsample': 0.6635969272608075, 'colsample_bytree': 0.8630512071192089, 'gamma': 0.832544050749948, 'min_child_weight': 10, 'reg_lambda': 0.16107908277696018, 'reg_alpha': 0.18049948873676414, 'month_sin': True, 'apparent_temperature_min_lag150': False, 'apparent_temperature_min_lag21': False, 'apparent_temperature_min_lag16': True, 'apparent_temperature_min_lag365': True, 'dayofweek_cos': False, 'apparent_temperature_min_lag60': True, 'residualslag19': False, 'dayofweek_sin': True, 'Rat_Czar_Appointed': True, 'apparent_temperature_min_lag730': True, 'yhat_upper': False, 'apparent_temperature_min_lag360': False, 'apparent_temperature_min_lag18': False, 'temperature_2m_mean': False, 'apparent_temperature_max': False, 'lag365': False, 'temperature_2m_max_lag60': True, 'lag1095': False, 'ma150': False, 'apparent_temperature_min_lag15': False, 'lag15': False, 'apparent_temperature_min_lag19': True, 'residualslag365': True, 'apparent_temperature_mean': False, 'yhat_lower': True, 'is_federal_holiday': False, 'apparent_temperature_min_lag180': True, 'apparent_temperature_min_lag17': False, 'apparent_temperature_min_lag330': True, 'residualslag15': True, 'ma90': False, 'Rat_Mitigation_Zone': True, 'snowfall_sum': False, 'precipitation_sum': False, 'dayofyear': True, 'month': False, 'dayofmonth': False, 'lag367': False, 'lag120': False, 'lag1825': True, 'lag60': False, 'lag362': False, 'year': False, 'Trash_Law': True, 'residualslag17': True, 'residualslag30': False, 'temperature_2m_max_lag14': False, 'apparent_temperature_min_lag30': False, 'quarter': True, 'temperature_2m_max_lag30': False, 'month_cos': False, 'New_Trash_Law': False, 'lag16': False, 'residualslag21': True, 'lag180': True, 'ma120': True, 'apparent_temperature_min_lag90': False, 'ma30': True, 'apparent_temperature_min_lag300': False, 'lag1460': True, 'apparent_temperature_min': True, 'residualslag16': True, 'temperature_2m_min': True, 'apparent_temperature_min_lag20': False, 'lag30': True, 'lag730': True, 'apparent_temperature_min_lag14': True, 'apparent_temperature_min_lag210': True, 'ma365': False, 'apparent_temperature_min_lag120': False, 'trend': True, 'ma180': True, 'apparent_temperature_min_lag270': True, 'residualslag730': True, 'residualslag18': True, 'lag363': False, 'residuals': False, 'ma60': True, 'temperature_2m_max': False, 'lag366': True, 'lag150': True, 'weekofyear': True, 'lag90': True, 'apparent_temperature_min_lag240': True, 'dayofweek': False, 'ma7': False, 'residualslag20': True, 'lag364': False}. Best is trial 299 with value: 4.32694914587703.

Trial starting: 322

[I 2026-03-15 17:59:07,311] Trial 314 finished with value: 4.380440995542052 and parameters: {'changepoint_prior_scale': 0.4367449337473812, 'seasonality_prior_scale': 1.5862076648278496, 'holidays_prior_scale': 0.3653516830028899, 'n_estimators': 781, 'max_depth': 7, 'learning_rate': 0.002841699859070443, 'subsample': 0.6547151149833306, 'colsample_bytree': 0.865504650639279, 'gamma': 0.788725192045306, 'min_child_weight': 10, 'reg_lambda': 0.16154433592810938, 'reg_alpha': 0.18218055719601015, 'month_sin': True, 'apparent_temperature_min_lag150': False, 'apparent_temperature_min_lag21': False, 'apparent_temperature_min_lag16': True, 'apparent_temperature_min_lag365': True, 'dayofweek_cos': False, 'apparent_temperature_min_lag60': True, 'residualslag19': False, 'dayofweek_sin': True, 'Rat_Czar_Appointed': True, 'apparent_temperature_min_lag730': True, 'yhat_upper': False, 'apparent_temperature_min_lag360': False, 'apparent_temperature_min_lag18': False, 'temperature_2m_mean': False, 'apparent_temperature_max': False, 'lag365': False, 'temperature_2m_max_lag60': True, 'lag1095': False, 'ma150': False, 'apparent_temperature_min_lag15': False, 'lag15': False, 'apparent_temperature_min_lag19': True, 'residualslag365': True, 'apparent_temperature_mean': False, 'yhat_lower': True, 'is_federal_holiday': False, 'apparent_temperature_min_lag180': True, 'apparent_temperature_min_lag17': False, 'apparent_temperature_min_lag330': True, 'residualslag15': True, 'ma90': False, 'Rat_Mitigation_Zone': True, 'snowfall_sum': False, 'precipitation_sum': False, 'dayofyear': True, 'month': False, 'dayofmonth': False, 'lag367': False, 'lag120': False, 'lag1825': True, 'lag60': False, 'lag362': False, 'year': False, 'Trash_Law': True, 'residualslag17': True, 'residualslag30': False, 'temperature_2m_max_lag14': False, 'apparent_temperature_min_lag30': False, 'quarter': True, 'temperature_2m_max_lag30': False, 'month_cos': False, 'New_Trash_Law': False, 'lag16': False, 'residualslag21': False, 'lag180': True, 'ma120': True, 'apparent_temperature_min_lag90': False, 'ma30': True, 'apparent_temperature_min_lag300': False, 'lag1460': True, 'apparent_temperature_min': True, 'residualslag16': True, 'temperature_2m_min': True, 'apparent_temperature_min_lag20': False, 'lag30': True, 'lag730': True, 'apparent_temperature_min_lag14': True, 'apparent_temperature_min_lag210': True, 'ma365': False, 'apparent_temperature_min_lag120': False, 'trend': True, 'ma180': True, 'apparent_temperature_min_lag270': True, 'residualslag730': True, 'residualslag18': True, 'lag363': False, 'residuals': False, 'ma60': True, 'temperature_2m_max': False, 'lag366': True, 'lag150': True, 'weekofyear': True, 'lag90': True, 'apparent_temperature_min_lag240': True, 'dayofweek': False, 'ma7': False, 'residualslag20': True, 'lag364': False}. Best is trial 299 with value: 4.32694914587703.

Trial starting: 323

[I 2026-03-15 17:59:17,072] Trial 316 finished with value: 4.371789848914242 and parameters: {'changepoint_prior_scale': 0.4270018293919891, 'seasonality_prior_scale': 1.5582187983895157, 'holidays_prior_scale': 0.36321443202625797, 'n_estimators': 750, 'max_depth': 7, 'learning_rate': 0.002922221836014121, 'subsample': 0.6636132152819717, 'colsample_bytree': 0.9786562809477046, 'gamma': 0.8248221527969218, 'min_child_weight': 10, 'reg_lambda': 0.16076292202294132, 'reg_alpha': 0.11543679608107373, 'month_sin': True, 'apparent_temperature_min_lag150': False, 'apparent_temperature_min_lag21': False, 'apparent_temperature_min_lag16': True, 'apparent_temperature_min_lag365': True, 'dayofweek_cos': False, 'apparent_temperature_min_lag60': True, 'residualslag19': False, 'dayofweek_sin': True, 'Rat_Czar_Appointed': False, 'apparent_temperature_min_lag730': True, 'yhat_upper': False, 'apparent_temperature_min_lag360': False, 'apparent_temperature_min_lag18': False, 'temperature_2m_mean': False, 'apparent_temperature_max': True, 'lag365': False, 'temperature_2m_max_lag60': True, 'lag1095': False, 'ma150': False, 'apparent_temperature_min_lag15': False, 'lag15': False, 'apparent_temperature_min_lag19': True, 'residualslag365': True, 'apparent_temperature_mean': False, 'yhat_lower': False, 'is_federal_holiday': False, 'apparent_temperature_min_lag180': True, 'apparent_temperature_min_lag17': False, 'apparent_temperature_min_lag330': True, 'residualslag15': True, 'ma90': False, 'Rat_Mitigation_Zone': True, 'snowfall_sum': False, 'precipitation_sum': True, 'dayofyear': True, 'month': False, 'dayofmonth': False, 'lag367': False, 'lag120': False, 'lag1825': True, 'lag60': False, 'lag362': False, 'year': False, 'Trash_Law': True, 'residualslag17': True, 'residualslag30': False, 'temperature_2m_max_lag14': False, 'apparent_temperature_min_lag30': True, 'quarter': True, 'temperature_2m_max_lag30': False, 'month_cos': False, 'New_Trash_Law': False, 'lag16': False, 'residualslag21': True, 'lag180': True, 'ma120': True, 'apparent_temperature_min_lag90': False, 'ma30': True, 'apparent_temperature_min_lag300': False, 'lag1460': True, 'apparent_temperature_min': False, 'residualslag16': True, 'temperature_2m_min': True, 'apparent_temperature_min_lag20': True, 'lag30': True, 'lag730': True, 'apparent_temperature_min_lag14': True, 'apparent_temperature_min_lag210': True, 'ma365': False, 'apparent_temperature_min_lag120': False, 'trend': True, 'ma180': True, 'apparent_temperature_min_lag270': False, 'residualslag730': False, 'residualslag18': True, 'lag363': False, 'residuals': False, 'ma60': True, 'temperature_2m_max': False, 'lag366': True, 'lag150': True, 'weekofyear': True, 'lag90': True, 'apparent_temperature_min_lag240': True, 'dayofweek': False, 'ma7': False, 'residualslag20': True, 'lag364': False}. Best is trial 299 with value: 4.32694914587703.

Trial starting: 324

[I 2026-03-15 17:59:21,404] Trial 304 finished with value: 4.3618669432369135 and parameters: {'changepoint_prior_scale': 0.4036219357844589, 'seasonality_prior_scale': 1.3376095104341583, 'holidays_prior_scale': 0.28641395328958597, 'n_estimators': 888, 'max_depth': 7, 'learning_rate': 0.0033060123349031956, 'subsample': 0.6996579163094164, 'colsample_bytree': 0.8641151315500349, 'gamma': 0.8168242425252462, 'min_child_weight': 10, 'reg_lambda': 0.13720145791211322, 'reg_alpha': 0.30541016676911126, 'month_sin': True, 'apparent_temperature_min_lag150': False, 'apparent_temperature_min_lag21': False, 'apparent_temperature_min_lag16': True, 'apparent_temperature_min_lag365': True, 'dayofweek_cos': False, 'apparent_temperature_min_lag60': True, 'residualslag19': False, 'dayofweek_sin': True, 'Rat_Czar_Appointed': False, 'apparent_temperature_min_lag730': True, 'yhat_upper': False, 'apparent_temperature_min_lag360': False, 'apparent_temperature_min_lag18': False, 'temperature_2m_mean': False, 'apparent_temperature_max': False, 'lag365': False, 'temperature_2m_max_lag60': True, 'lag1095': False, 'ma150': False, 'apparent_temperature_min_lag15': False, 'lag15': False, 'apparent_temperature_min_lag19': True, 'residualslag365': True, 'apparent_temperature_mean': True, 'yhat_lower': True, 'is_federal_holiday': False, 'apparent_temperature_min_lag180': True, 'apparent_temperature_min_lag17': False, 'apparent_temperature_min_lag330': True, 'residualslag15': True, 'ma90': False, 'Rat_Mitigation_Zone': True, 'snowfall_sum': False, 'precipitation_sum': False, 'dayofyear': True, 'month': False, 'dayofmonth': False, 'lag367': False, 'lag120': False, 'lag1825': True, 'lag60': False, 'lag362': False, 'year': False, 'Trash_Law': True, 'residualslag17': True, 'residualslag30': False, 'temperature_2m_max_lag14': False, 'apparent_temperature_min_lag30': False, 'quarter': True, 'temperature_2m_max_lag30': False, 'month_cos': False, 'New_Trash_Law': False, 'lag16': False, 'residualslag21': True, 'lag180': True, 'ma120': True, 'apparent_temperature_min_lag90': False, 'ma30': True, 'apparent_temperature_min_lag300': False, 'lag1460': True, 'apparent_temperature_min': False, 'residualslag16': True, 'temperature_2m_min': True, 'apparent_temperature_min_lag20': False, 'lag30': True, 'lag730': True, 'apparent_temperature_min_lag14': True, 'apparent_temperature_min_lag210': True, 'ma365': False, 'apparent_temperature_min_lag120': False, 'trend': False, 'ma180': True, 'apparent_temperature_min_lag270': True, 'residualslag730': True, 'residualslag18': True, 'lag363': False, 'residuals': False, 'ma60': True, 'temperature_2m_max': False, 'lag366': True, 'lag150': True, 'weekofyear': True, 'lag90': True, 'apparent_temperature_min_lag240': False, 'dayofweek': False, 'ma7': False, 'residualslag20': True, 'lag364': False}. Best is trial 299 with value: 4.32694914587703.

Trial starting: 325

[I 2026-03-15 18:00:38,336] Trial 315 finished with value: 4.340821500527716 and parameters: {'changepoint_prior_scale': 0.43415851402262284, 'seasonality_prior_scale': 1.0345114601312266, 'holidays_prior_scale': 0.1759071415718536, 'n_estimators': 823, 'max_depth': 7, 'learning_rate': 0.004083897342375657, 'subsample': 0.6587968852289557, 'colsample_bytree': 0.8685175898033151, 'gamma': 0.8015308851064364, 'min_child_weight': 10, 'reg_lambda': 0.15746953886765563, 'reg_alpha': 0.17686116943519767, 'month_sin': True, 'apparent_temperature_min_lag150': False, 'apparent_temperature_min_lag21': False, 'apparent_temperature_min_lag16': True, 'apparent_temperature_min_lag365': True, 'dayofweek_cos': False, 'apparent_temperature_min_lag60': True, 'residualslag19': False, 'dayofweek_sin': True, 'Rat_Czar_Appointed': False, 'apparent_temperature_min_lag730': True, 'yhat_upper': False, 'apparent_temperature_min_lag360': False, 'apparent_temperature_min_lag18': False, 'temperature_2m_mean': False, 'apparent_temperature_max': True, 'lag365': False, 'temperature_2m_max_lag60': True, 'lag1095': False, 'ma150': False, 'apparent_temperature_min_lag15': False, 'lag15': False, 'apparent_temperature_min_lag19': True, 'residualslag365': True, 'apparent_temperature_mean': True, 'yhat_lower': False, 'is_federal_holiday': False, 'apparent_temperature_min_lag180': True, 'apparent_temperature_min_lag17': False, 'apparent_temperature_min_lag330': True, 'residualslag15': True, 'ma90': False, 'Rat_Mitigation_Zone': True, 'snowfall_sum': False, 'precipitation_sum': True, 'dayofyear': True, 'month': False, 'dayofmonth': False, 'lag367': False, 'lag120': False, 'lag1825': True, 'lag60': False, 'lag362': False, 'year': False, 'Trash_Law': True, 'residualslag17': True, 'residualslag30': False, 'temperature_2m_max_lag14': False, 'apparent_temperature_min_lag30': False, 'quarter': True, 'temperature_2m_max_lag30': False, 'month_cos': False, 'New_Trash_Law': False, 'lag16': False, 'residualslag21': True, 'lag180': True, 'ma120': True, 'apparent_temperature_min_lag90': False, 'ma30': True, 'apparent_temperature_min_lag300': False, 'lag1460': True, 'apparent_temperature_min': False, 'residualslag16': True, 'temperature_2m_min': True, 'apparent_temperature_min_lag20': False, 'lag30': True, 'lag730': True, 'apparent_temperature_min_lag14': True, 'apparent_temperature_min_lag210': True, 'ma365': False, 'apparent_temperature_min_lag120': False, 'trend': False, 'ma180': True, 'apparent_temperature_min_lag270': True, 'residualslag730': True, 'residualslag18': True, 'lag363': False, 'residuals': False, 'ma60': True, 'temperature_2m_max': False, 'lag366': True, 'lag150': True, 'weekofyear': True, 'lag90': True, 'apparent_temperature_min_lag240': False, 'dayofweek': False, 'ma7': False, 'residualslag20': True, 'lag364': False}. Best is trial 299 with value: 4.32694914587703.

Trial starting: 326

[I 2026-03-15 18:01:34,965] Trial 305 finished with value: 4.368184719112917 and parameters: {'changepoint_prior_scale': 0.43353739715615847, 'seasonality_prior_scale': 0.6030891002987872, 'holidays_prior_scale': 0.19717471548937446, 'n_estimators': 929, 'max_depth': 7, 'learning_rate': 0.003335378408708508, 'subsample': 0.7108980829661502, 'colsample_bytree': 0.9262705423185468, 'gamma': 0.8079631193761359, 'min_child_weight': 10, 'reg_lambda': 0.1417130401014624, 'reg_alpha': 0.30122998836215903, 'month_sin': True, 'apparent_temperature_min_lag150': False, 'apparent_temperature_min_lag21': False, 'apparent_temperature_min_lag16': True, 'apparent_temperature_min_lag365': True, 'dayofweek_cos': False, 'apparent_temperature_min_lag60': True, 'residualslag19': False, 'dayofweek_sin': True, 'Rat_Czar_Appointed': True, 'apparent_temperature_min_lag730': True, 'yhat_upper': False, 'apparent_temperature_min_lag360': False, 'apparent_temperature_min_lag18': False, 'temperature_2m_mean': False, 'apparent_temperature_max': False, 'lag365': False, 'temperature_2m_max_lag60': True, 'lag1095': False, 'ma150': False, 'apparent_temperature_min_lag15': False, 'lag15': False, 'apparent_temperature_min_lag19': True, 'residualslag365': True, 'apparent_temperature_mean': True, 'yhat_lower': True, 'is_federal_holiday': False, 'apparent_temperature_min_lag180': True, 'apparent_temperature_min_lag17': False, 'apparent_temperature_min_lag330': True, 'residualslag15': True, 'ma90': False, 'Rat_Mitigation_Zone': True, 'snowfall_sum': False, 'precipitation_sum': False, 'dayofyear': True, 'month': False, 'dayofmonth': False, 'lag367': False, 'lag120': False, 'lag1825': True, 'lag60': False, 'lag362': False, 'year': False, 'Trash_Law': True, 'residualslag17': True, 'residualslag30': False, 'temperature_2m_max_lag14': False, 'apparent_temperature_min_lag30': False, 'quarter': True, 'temperature_2m_max_lag30': False, 'month_cos': False, 'New_Trash_Law': False, 'lag16': False, 'residualslag21': True, 'lag180': True, 'ma120': True, 'apparent_temperature_min_lag90': False, 'ma30': True, 'apparent_temperature_min_lag300': False, 'lag1460': True, 'apparent_temperature_min': True, 'residualslag16': True, 'temperature_2m_min': True, 'apparent_temperature_min_lag20': False, 'lag30': True, 'lag730': True, 'apparent_temperature_min_lag14': True, 'apparent_temperature_min_lag210': True, 'ma365': False, 'apparent_temperature_min_lag120': False, 'trend': True, 'ma180': True, 'apparent_temperature_min_lag270': True, 'residualslag730': True, 'residualslag18': True, 'lag363': False, 'residuals': False, 'ma60': True, 'temperature_2m_max': False, 'lag366': True, 'lag150': True, 'weekofyear': True, 'lag90': True, 'apparent_temperature_min_lag240': True, 'dayofweek': False, 'ma7': False, 'residualslag20': True, 'lag364': False}. Best is trial 299 with value: 4.32694914587703.

Trial starting: 327

[I 2026-03-15 18:02:05,099] Trial 306 finished with value: 4.370670597599565 and parameters: {'changepoint_prior_scale': 0.4320513450862104, 'seasonality_prior_scale': 0.4442552155933739, 'holidays_prior_scale': 0.19994110442542545, 'n_estimators': 956, 'max_depth': 7, 'learning_rate': 0.0028396729033354647, 'subsample': 0.7238220216531557, 'colsample_bytree': 0.8625045335125076, 'gamma': 1.0107666902874624, 'min_child_weight': 10, 'reg_lambda': 0.13709488783574647, 'reg_alpha': 0.177385197889037, 'month_sin': True, 'apparent_temperature_min_lag150': False, 'apparent_temperature_min_lag21': False, 'apparent_temperature_min_lag16': True, 'apparent_temperature_min_lag365': True, 'dayofweek_cos': False, 'apparent_temperature_min_lag60': True, 'residualslag19': False, 'dayofweek_sin': True, 'Rat_Czar_Appointed': True, 'apparent_temperature_min_lag730': True, 'yhat_upper': False, 'apparent_temperature_min_lag360': False, 'apparent_temperature_min_lag18': False, 'temperature_2m_mean': False, 'apparent_temperature_max': False, 'lag365': False, 'temperature_2m_max_lag60': True, 'lag1095': False, 'ma150': False, 'apparent_temperature_min_lag15': False, 'lag15': False, 'apparent_temperature_min_lag19': True, 'residualslag365': True, 'apparent_temperature_mean': False, 'yhat_lower': True, 'is_federal_holiday': False, 'apparent_temperature_min_lag180': True, 'apparent_temperature_min_lag17': False, 'apparent_temperature_min_lag330': True, 'residualslag15': True, 'ma90': False, 'Rat_Mitigation_Zone': True, 'snowfall_sum': False, 'precipitation_sum': False, 'dayofyear': True, 'month': False, 'dayofmonth': False, 'lag367': False, 'lag120': False, 'lag1825': True, 'lag60': False, 'lag362': False, 'year': False, 'Trash_Law': True, 'residualslag17': True, 'residualslag30': False, 'temperature_2m_max_lag14': False, 'apparent_temperature_min_lag30': False, 'quarter': True, 'temperature_2m_max_lag30': False, 'month_cos': False, 'New_Trash_Law': False, 'lag16': False, 'residualslag21': True, 'lag180': True, 'ma120': True, 'apparent_temperature_min_lag90': False, 'ma30': True, 'apparent_temperature_min_lag300': False, 'lag1460': True, 'apparent_temperature_min': True, 'residualslag16': False, 'temperature_2m_min': True, 'apparent_temperature_min_lag20': False, 'lag30': True, 'lag730': True, 'apparent_temperature_min_lag14': True, 'apparent_temperature_min_lag210': True, 'ma365': False, 'apparent_temperature_min_lag120': False, 'trend': True, 'ma180': True, 'apparent_temperature_min_lag270': True, 'residualslag730': True, 'residualslag18': True, 'lag363': False, 'residuals': False, 'ma60': True, 'temperature_2m_max': False, 'lag366': True, 'lag150': True, 'weekofyear': True, 'lag90': True, 'apparent_temperature_min_lag240': True, 'dayofweek': False, 'ma7': False, 'residualslag20': True, 'lag364': False}. Best is trial 299 with value: 4.32694914587703.

Trial starting: 328

[I 2026-03-15 18:02:29,530] Trial 307 finished with value: 4.400867079358777 and parameters: {'changepoint_prior_scale': 0.42799229410730844, 'seasonality_prior_scale': 0.6001516054350904, 'holidays_prior_scale': 0.1799453461826853, 'n_estimators': 968, 'max_depth': 7, 'learning_rate': 0.0029768164781525065, 'subsample': 0.6649768657315012, 'colsample_bytree': 0.9252915707291901, 'gamma': 0.8023631014413948, 'min_child_weight': 10, 'reg_lambda': 0.15891828322200183, 'reg_alpha': 0.179534625320998, 'month_sin': True, 'apparent_temperature_min_lag150': False, 'apparent_temperature_min_lag21': False, 'apparent_temperature_min_lag16': True, 'apparent_temperature_min_lag365': True, 'dayofweek_cos': False, 'apparent_temperature_min_lag60': True, 'residualslag19': False, 'dayofweek_sin': True, 'Rat_Czar_Appointed': True, 'apparent_temperature_min_lag730': True, 'yhat_upper': False, 'apparent_temperature_min_lag360': False, 'apparent_temperature_min_lag18': False, 'temperature_2m_mean': False, 'apparent_temperature_max': False, 'lag365': False, 'temperature_2m_max_lag60': True, 'lag1095': False, 'ma150': False, 'apparent_temperature_min_lag15': False, 'lag15': False, 'apparent_temperature_min_lag19': True, 'residualslag365': True, 'apparent_temperature_mean': False, 'yhat_lower': True, 'is_federal_holiday': False, 'apparent_temperature_min_lag180': True, 'apparent_temperature_min_lag17': False, 'apparent_temperature_min_lag330': True, 'residualslag15': True, 'ma90': False, 'Rat_Mitigation_Zone': True, 'snowfall_sum': False, 'precipitation_sum': False, 'dayofyear': True, 'month': False, 'dayofmonth': False, 'lag367': False, 'lag120': False, 'lag1825': True, 'lag60': False, 'lag362': False, 'year': False, 'Trash_Law': True, 'residualslag17': True, 'residualslag30': False, 'temperature_2m_max_lag14': False, 'apparent_temperature_min_lag30': False, 'quarter': True, 'temperature_2m_max_lag30': False, 'month_cos': False, 'New_Trash_Law': False, 'lag16': False, 'residualslag21': True, 'lag180': True, 'ma120': True, 'apparent_temperature_min_lag90': False, 'ma30': True, 'apparent_temperature_min_lag300': False, 'lag1460': True, 'apparent_temperature_min': True, 'residualslag16': True, 'temperature_2m_min': True, 'apparent_temperature_min_lag20': False, 'lag30': True, 'lag730': True, 'apparent_temperature_min_lag14': True, 'apparent_temperature_min_lag210': True, 'ma365': False, 'apparent_temperature_min_lag120': False, 'trend': True, 'ma180': True, 'apparent_temperature_min_lag270': True, 'residualslag730': True, 'residualslag18': True, 'lag363': False, 'residuals': False, 'ma60': True, 'temperature_2m_max': False, 'lag366': True, 'lag150': True, 'weekofyear': True, 'lag90': True, 'apparent_temperature_min_lag240': True, 'dayofweek': False, 'ma7': False, 'residualslag20': True, 'lag364': False}. Best is trial 299 with value: 4.32694914587703.

Trial starting: 329

[I 2026-03-15 18:02:35,845] Trial 308 finished with value: 4.393239814999211 and parameters: {'changepoint_prior_scale': 0.4280926509807312, 'seasonality_prior_scale': 0.43262410627699144, 'holidays_prior_scale': 0.34893125246269135, 'n_estimators': 952, 'max_depth': 7, 'learning_rate': 0.004234225997940846, 'subsample': 0.6612009518282367, 'colsample_bytree': 0.8610451225205817, 'gamma': 0.9960316050771227, 'min_child_weight': 10, 'reg_lambda': 0.12440958635038168, 'reg_alpha': 0.18342565390967003, 'month_sin': True, 'apparent_temperature_min_lag150': False, 'apparent_temperature_min_lag21': False, 'apparent_temperature_min_lag16': True, 'apparent_temperature_min_lag365': True, 'dayofweek_cos': False, 'apparent_temperature_min_lag60': True, 'residualslag19': False, 'dayofweek_sin': True, 'Rat_Czar_Appointed': True, 'apparent_temperature_min_lag730': True, 'yhat_upper': False, 'apparent_temperature_min_lag360': False, 'apparent_temperature_min_lag18': False, 'temperature_2m_mean': False, 'apparent_temperature_max': False, 'lag365': False, 'temperature_2m_max_lag60': True, 'lag1095': False, 'ma150': False, 'apparent_temperature_min_lag15': False, 'lag15': False, 'apparent_temperature_min_lag19': True, 'residualslag365': True, 'apparent_temperature_mean': False, 'yhat_lower': True, 'is_federal_holiday': False, 'apparent_temperature_min_lag180': True, 'apparent_temperature_min_lag17': False, 'apparent_temperature_min_lag330': True, 'residualslag15': True, 'ma90': False, 'Rat_Mitigation_Zone': True, 'snowfall_sum': False, 'precipitation_sum': False, 'dayofyear': True, 'month': False, 'dayofmonth': False, 'lag367': False, 'lag120': False, 'lag1825': True, 'lag60': False, 'lag362': False, 'year': False, 'Trash_Law': True, 'residualslag17': True, 'residualslag30': False, 'temperature_2m_max_lag14': False, 'apparent_temperature_min_lag30': False, 'quarter': True, 'temperature_2m_max_lag30': False, 'month_cos': False, 'New_Trash_Law': False, 'lag16': False, 'residualslag21': False, 'lag180': True, 'ma120': True, 'apparent_temperature_min_lag90': False, 'ma30': True, 'apparent_temperature_min_lag300': False, 'lag1460': True, 'apparent_temperature_min': True, 'residualslag16': True, 'temperature_2m_min': True, 'apparent_temperature_min_lag20': False, 'lag30': True, 'lag730': True, 'apparent_temperature_min_lag14': True, 'apparent_temperature_min_lag210': True, 'ma365': False, 'apparent_temperature_min_lag120': False, 'trend': False, 'ma180': True, 'apparent_temperature_min_lag270': True, 'residualslag730': True, 'residualslag18': True, 'lag363': False, 'residuals': False, 'ma60': True, 'temperature_2m_max': False, 'lag366': True, 'lag150': True, 'weekofyear': True, 'lag90': True, 'apparent_temperature_min_lag240': True, 'dayofweek': False, 'ma7': False, 'residualslag20': True, 'lag364': False}. Best is trial 299 with value: 4.32694914587703.

Trial starting: 330

[I 2026-03-15 18:02:41,908] Trial 310 finished with value: 4.37057992257842 and parameters: {'changepoint_prior_scale': 0.4257912764332441, 'seasonality_prior_scale': 0.5983615634242795, 'holidays_prior_scale': 0.3528331790762106, 'n_estimators': 950, 'max_depth': 7, 'learning_rate': 0.002822590726903778, 'subsample': 0.6636493565882314, 'colsample_bytree': 0.8690459218441434, 'gamma': 0.8014697105935762, 'min_child_weight': 10, 'reg_lambda': 0.12376228530472413, 'reg_alpha': 0.3061125946754086, 'month_sin': True, 'apparent_temperature_min_lag150': False, 'apparent_temperature_min_lag21': False, 'apparent_temperature_min_lag16': True, 'apparent_temperature_min_lag365': True, 'dayofweek_cos': False, 'apparent_temperature_min_lag60': True, 'residualslag19': False, 'dayofweek_sin': True, 'Rat_Czar_Appointed': True, 'apparent_temperature_min_lag730': True, 'yhat_upper': False, 'apparent_temperature_min_lag360': False, 'apparent_temperature_min_lag18': False, 'temperature_2m_mean': False, 'apparent_temperature_max': False, 'lag365': False, 'temperature_2m_max_lag60': True, 'lag1095': False, 'ma150': False, 'apparent_temperature_min_lag15': False, 'lag15': False, 'apparent_temperature_min_lag19': True, 'residualslag365': True, 'apparent_temperature_mean': True, 'yhat_lower': True, 'is_federal_holiday': False, 'apparent_temperature_min_lag180': True, 'apparent_temperature_min_lag17': False, 'apparent_temperature_min_lag330': True, 'residualslag15': True, 'ma90': False, 'Rat_Mitigation_Zone': True, 'snowfall_sum': False, 'precipitation_sum': False, 'dayofyear': True, 'month': False, 'dayofmonth': False, 'lag367': False, 'lag120': False, 'lag1825': True, 'lag60': False, 'lag362': False, 'year': False, 'Trash_Law': True, 'residualslag17': True, 'residualslag30': False, 'temperature_2m_max_lag14': False, 'apparent_temperature_min_lag30': False, 'quarter': True, 'temperature_2m_max_lag30': False, 'month_cos': False, 'New_Trash_Law': False, 'lag16': False, 'residualslag21': False, 'lag180': True, 'ma120': True, 'apparent_temperature_min_lag90': False, 'ma30': True, 'apparent_temperature_min_lag300': False, 'lag1460': True, 'apparent_temperature_min': True, 'residualslag16': True, 'temperature_2m_min': True, 'apparent_temperature_min_lag20': False, 'lag30': True, 'lag730': True, 'apparent_temperature_min_lag14': True, 'apparent_temperature_min_lag210': True, 'ma365': False, 'apparent_temperature_min_lag120': False, 'trend': True, 'ma180': True, 'apparent_temperature_min_lag270': True, 'residualslag730': True, 'residualslag18': True, 'lag363': False, 'residuals': False, 'ma60': True, 'temperature_2m_max': False, 'lag366': True, 'lag150': True, 'weekofyear': True, 'lag90': True, 'apparent_temperature_min_lag240': False, 'dayofweek': False, 'ma7': False, 'residualslag20': True, 'lag364': False}. Best is trial 299 with value: 4.32694914587703.

Trial starting: 331

[I 2026-03-15 18:03:38,760] Trial 311 finished with value: 4.344669925975284 and parameters: {'changepoint_prior_scale': 0.4306933764801653, 'seasonality_prior_scale': 0.6036365196321005, 'holidays_prior_scale': 0.3461215112123471, 'n_estimators': 938, 'max_depth': 7, 'learning_rate': 0.0027982228321554153, 'subsample': 0.6615865083221558, 'colsample_bytree': 0.9071174892597891, 'gamma': 1.008504388788902, 'min_child_weight': 10, 'reg_lambda': 0.12476490523443917, 'reg_alpha': 0.294052250318623, 'month_sin': True, 'apparent_temperature_min_lag150': False, 'apparent_temperature_min_lag21': False, 'apparent_temperature_min_lag16': True, 'apparent_temperature_min_lag365': True, 'dayofweek_cos': False, 'apparent_temperature_min_lag60': True, 'residualslag19': False, 'dayofweek_sin': True, 'Rat_Czar_Appointed': True, 'apparent_temperature_min_lag730': True, 'yhat_upper': False, 'apparent_temperature_min_lag360': False, 'apparent_temperature_min_lag18': False, 'temperature_2m_mean': False, 'apparent_temperature_max': False, 'lag365': False, 'temperature_2m_max_lag60': True, 'lag1095': False, 'ma150': False, 'apparent_temperature_min_lag15': False, 'lag15': False, 'apparent_temperature_min_lag19': True, 'residualslag365': True, 'apparent_temperature_mean': True, 'yhat_lower': True, 'is_federal_holiday': False, 'apparent_temperature_min_lag180': True, 'apparent_temperature_min_lag17': False, 'apparent_temperature_min_lag330': True, 'residualslag15': True, 'ma90': False, 'Rat_Mitigation_Zone': True, 'snowfall_sum': False, 'precipitation_sum': False, 'dayofyear': True, 'month': False, 'dayofmonth': False, 'lag367': False, 'lag120': False, 'lag1825': True, 'lag60': False, 'lag362': False, 'year': False, 'Trash_Law': True, 'residualslag17': True, 'residualslag30': False, 'temperature_2m_max_lag14': False, 'apparent_temperature_min_lag30': False, 'quarter': True, 'temperature_2m_max_lag30': False, 'month_cos': False, 'New_Trash_Law': False, 'lag16': False, 'residualslag21': False, 'lag180': True, 'ma120': True, 'apparent_temperature_min_lag90': False, 'ma30': True, 'apparent_temperature_min_lag300': False, 'lag1460': True, 'apparent_temperature_min': True, 'residualslag16': False, 'temperature_2m_min': True, 'apparent_temperature_min_lag20': False, 'lag30': True, 'lag730': True, 'apparent_temperature_min_lag14': True, 'apparent_temperature_min_lag210': True, 'ma365': False, 'apparent_temperature_min_lag120': False, 'trend': True, 'ma180': True, 'apparent_temperature_min_lag270': True, 'residualslag730': True, 'residualslag18': True, 'lag363': False, 'residuals': False, 'ma60': True, 'temperature_2m_max': False, 'lag366': True, 'lag150': True, 'weekofyear': True, 'lag90': True, 'apparent_temperature_min_lag240': True, 'dayofweek': False, 'ma7': False, 'residualslag20': True, 'lag364': False}. Best is trial 299 with value: 4.32694914587703.

Trial starting: 332

[I 2026-03-15 18:06:59,853] Trial 309 finished with value: 4.385699592062497 and parameters: {'changepoint_prior_scale': 0.4287164487295735, 'seasonality_prior_scale': 0.6104311825474169, 'holidays_prior_scale': 0.3570922651290787, 'n_estimators': 1115, 'max_depth': 7, 'learning_rate': 0.004148678957529355, 'subsample': 0.6650512039739742, 'colsample_bytree': 0.8645931404444551, 'gamma': 1.0232943550103963, 'min_child_weight': 10, 'reg_lambda': 0.1574271779502339, 'reg_alpha': 0.177470789337336, 'month_sin': True, 'apparent_temperature_min_lag150': False, 'apparent_temperature_min_lag21': False, 'apparent_temperature_min_lag16': True, 'apparent_temperature_min_lag365': True, 'dayofweek_cos': False, 'apparent_temperature_min_lag60': True, 'residualslag19': False, 'dayofweek_sin': True, 'Rat_Czar_Appointed': True, 'apparent_temperature_min_lag730': True, 'yhat_upper': False, 'apparent_temperature_min_lag360': False, 'apparent_temperature_min_lag18': False, 'temperature_2m_mean': False, 'apparent_temperature_max': False, 'lag365': False, 'temperature_2m_max_lag60': True, 'lag1095': False, 'ma150': False, 'apparent_temperature_min_lag15': False, 'lag15': False, 'apparent_temperature_min_lag19': True, 'residualslag365': True, 'apparent_temperature_mean': False, 'yhat_lower': True, 'is_federal_holiday': False, 'apparent_temperature_min_lag180': True, 'apparent_temperature_min_lag17': False, 'apparent_temperature_min_lag330': True, 'residualslag15': True, 'ma90': False, 'Rat_Mitigation_Zone': True, 'snowfall_sum': False, 'precipitation_sum': False, 'dayofyear': True, 'month': False, 'dayofmonth': False, 'lag367': False, 'lag120': False, 'lag1825': True, 'lag60': False, 'lag362': False, 'year': False, 'Trash_Law': True, 'residualslag17': True, 'residualslag30': False, 'temperature_2m_max_lag14': False, 'apparent_temperature_min_lag30': False, 'quarter': True, 'temperature_2m_max_lag30': False, 'month_cos': False, 'New_Trash_Law': False, 'lag16': False, 'residualslag21': False, 'lag180': True, 'ma120': True, 'apparent_temperature_min_lag90': False, 'ma30': True, 'apparent_temperature_min_lag300': False, 'lag1460': True, 'apparent_temperature_min': True, 'residualslag16': True, 'temperature_2m_min': True, 'apparent_temperature_min_lag20': False, 'lag30': True, 'lag730': True, 'apparent_temperature_min_lag14': True, 'apparent_temperature_min_lag210': True, 'ma365': False, 'apparent_temperature_min_lag120': False, 'trend': True, 'ma180': True, 'apparent_temperature_min_lag270': True, 'residualslag730': True, 'residualslag18': True, 'lag363': False, 'residuals': False, 'ma60': True, 'temperature_2m_max': False, 'lag366': True, 'lag150': True, 'weekofyear': True, 'lag90': True, 'apparent_temperature_min_lag240': True, 'dayofweek': False, 'ma7': False, 'residualslag20': True, 'lag364': False}. Best is trial 299 with value: 4.32694914587703.

Trial starting: 333

[I 2026-03-15 18:08:35,806] Trial 318 finished with value: 4.362823543367334 and parameters: {'changepoint_prior_scale': 0.4291385739791765, 'seasonality_prior_scale': 1.5886338777740887, 'holidays_prior_scale': 0.351042473437089, 'n_estimators': 1111, 'max_depth': 7, 'learning_rate': 0.002906112118851181, 'subsample': 0.6643806738488282, 'colsample_bytree': 0.9853963913137463, 'gamma': 0.843743751203787, 'min_child_weight': 10, 'reg_lambda': 0.15473559856233735, 'reg_alpha': 0.12173683687422857, 'month_sin': True, 'apparent_temperature_min_lag150': False, 'apparent_temperature_min_lag21': False, 'apparent_temperature_min_lag16': True, 'apparent_temperature_min_lag365': True, 'dayofweek_cos': False, 'apparent_temperature_min_lag60': False, 'residualslag19': False, 'dayofweek_sin': True, 'Rat_Czar_Appointed': False, 'apparent_temperature_min_lag730': True, 'yhat_upper': False, 'apparent_temperature_min_lag360': False, 'apparent_temperature_min_lag18': False, 'temperature_2m_mean': False, 'apparent_temperature_max': True, 'lag365': False, 'temperature_2m_max_lag60': True, 'lag1095': False, 'ma150': False, 'apparent_temperature_min_lag15': False, 'lag15': False, 'apparent_temperature_min_lag19': True, 'residualslag365': True, 'apparent_temperature_mean': False, 'yhat_lower': False, 'is_federal_holiday': False, 'apparent_temperature_min_lag180': True, 'apparent_temperature_min_lag17': False, 'apparent_temperature_min_lag330': True, 'residualslag15': True, 'ma90': False, 'Rat_Mitigation_Zone': True, 'snowfall_sum': False, 'precipitation_sum': True, 'dayofyear': True, 'month': True, 'dayofmonth': False, 'lag367': False, 'lag120': False, 'lag1825': True, 'lag60': False, 'lag362': False, 'year': False, 'Trash_Law': True, 'residualslag17': True, 'residualslag30': False, 'temperature_2m_max_lag14': False, 'apparent_temperature_min_lag30': True, 'quarter': True, 'temperature_2m_max_lag30': False, 'month_cos': False, 'New_Trash_Law': True, 'lag16': False, 'residualslag21': True, 'lag180': True, 'ma120': False, 'apparent_temperature_min_lag90': False, 'ma30': True, 'apparent_temperature_min_lag300': False, 'lag1460': True, 'apparent_temperature_min': False, 'residualslag16': True, 'temperature_2m_min': True, 'apparent_temperature_min_lag20': True, 'lag30': True, 'lag730': True, 'apparent_temperature_min_lag14': True, 'apparent_temperature_min_lag210': True, 'ma365': True, 'apparent_temperature_min_lag120': False, 'trend': False, 'ma180': True, 'apparent_temperature_min_lag270': False, 'residualslag730': False, 'residualslag18': True, 'lag363': False, 'residuals': False, 'ma60': True, 'temperature_2m_max': False, 'lag366': True, 'lag150': True, 'weekofyear': True, 'lag90': True, 'apparent_temperature_min_lag240': False, 'dayofweek': False, 'ma7': True, 'residualslag20': True, 'lag364': False}. Best is trial 299 with value: 4.32694914587703.

Trial starting: 334

[I 2026-03-15 18:17:34,704] Trial 319 finished with value: 4.372637631940419 and parameters: {'changepoint_prior_scale': 0.42563478733718374, 'seasonality_prior_scale': 0.6094833391078464, 'holidays_prior_scale': 0.3612172152422689, 'n_estimators': 777, 'max_depth': 7, 'learning_rate': 0.002824451063941261, 'subsample': 0.6652063224136425, 'colsample_bytree': 0.9839894916286305, 'gamma': 1.5546317043519169, 'min_child_weight': 10, 'reg_lambda': 0.16106212711283288, 'reg_alpha': 0.1243985855805311, 'month_sin': True, 'apparent_temperature_min_lag150': False, 'apparent_temperature_min_lag21': False, 'apparent_temperature_min_lag16': True, 'apparent_temperature_min_lag365': True, 'dayofweek_cos': False, 'apparent_temperature_min_lag60': True, 'residualslag19': False, 'dayofweek_sin': True, 'Rat_Czar_Appointed': False, 'apparent_temperature_min_lag730': True, 'yhat_upper': False, 'apparent_temperature_min_lag360': False, 'apparent_temperature_min_lag18': False, 'temperature_2m_mean': False, 'apparent_temperature_max': True, 'lag365': False, 'temperature_2m_max_lag60': True, 'lag1095': False, 'ma150': False, 'apparent_temperature_min_lag15': False, 'lag15': False, 'apparent_temperature_min_lag19': True, 'residualslag365': True, 'apparent_temperature_mean': True, 'yhat_lower': False, 'is_federal_holiday': False, 'apparent_temperature_min_lag180': True, 'apparent_temperature_min_lag17': False, 'apparent_temperature_min_lag330': True, 'residualslag15': True, 'ma90': False, 'Rat_Mitigation_Zone': True, 'snowfall_sum': False, 'precipitation_sum': True, 'dayofyear': True, 'month': True, 'dayofmonth': False, 'lag367': False, 'lag120': False, 'lag1825': True, 'lag60': False, 'lag362': False, 'year': False, 'Trash_Law': True, 'residualslag17': True, 'residualslag30': False, 'temperature_2m_max_lag14': False, 'apparent_temperature_min_lag30': True, 'quarter': True, 'temperature_2m_max_lag30': False, 'month_cos': False, 'New_Trash_Law': True, 'lag16': False, 'residualslag21': True, 'lag180': True, 'ma120': False, 'apparent_temperature_min_lag90': False, 'ma30': True, 'apparent_temperature_min_lag300': False, 'lag1460': True, 'apparent_temperature_min': False, 'residualslag16': True, 'temperature_2m_min': True, 'apparent_temperature_min_lag20': False, 'lag30': True, 'lag730': True, 'apparent_temperature_min_lag14': True, 'apparent_temperature_min_lag210': True, 'ma365': True, 'apparent_temperature_min_lag120': False, 'trend': False, 'ma180': True, 'apparent_temperature_min_lag270': True, 'residualslag730': False, 'residualslag18': True, 'lag363': False, 'residuals': False, 'ma60': True, 'temperature_2m_max': False, 'lag366': True, 'lag150': True, 'weekofyear': True, 'lag90': True, 'apparent_temperature_min_lag240': True, 'dayofweek': False, 'ma7': False, 'residualslag20': True, 'lag364': False}. Best is trial 299 with value: 4.32694914587703.

Trial starting: 335

[I 2026-03-15 18:18:54,991] Trial 320 finished with value: 4.325775922204958 and parameters: {'changepoint_prior_scale': 0.43095780188009536, 'seasonality_prior_scale': 0.43760069171967947, 'holidays_prior_scale': 0.37119369702022226, 'n_estimators': 823, 'max_depth': 7, 'learning_rate': 0.0040838368595571516, 'subsample': 0.6610126981728464, 'colsample_bytree': 0.8648805678502527, 'gamma': 1.0184597084640472, 'min_child_weight': 10, 'reg_lambda': 0.12116968028901957, 'reg_alpha': 0.18255079720344983, 'month_sin': True, 'apparent_temperature_min_lag150': False, 'apparent_temperature_min_lag21': False, 'apparent_temperature_min_lag16': True, 'apparent_temperature_min_lag365': True, 'dayofweek_cos': False, 'apparent_temperature_min_lag60': True, 'residualslag19': False, 'dayofweek_sin': True, 'Rat_Czar_Appointed': False, 'apparent_temperature_min_lag730': True, 'yhat_upper': False, 'apparent_temperature_min_lag360': False, 'apparent_temperature_min_lag18': False, 'temperature_2m_mean': False, 'apparent_temperature_max': True, 'lag365': False, 'temperature_2m_max_lag60': True, 'lag1095': False, 'ma150': False, 'apparent_temperature_min_lag15': False, 'lag15': False, 'apparent_temperature_min_lag19': True, 'residualslag365': True, 'apparent_temperature_mean': True, 'yhat_lower': False, 'is_federal_holiday': False, 'apparent_temperature_min_lag180': True, 'apparent_temperature_min_lag17': False, 'apparent_temperature_min_lag330': True, 'residualslag15': True, 'ma90': False, 'Rat_Mitigation_Zone': True, 'snowfall_sum': False, 'precipitation_sum': True, 'dayofyear': True, 'month': False, 'dayofmonth': False, 'lag367': False, 'lag120': False, 'lag1825': True, 'lag60': False, 'lag362': False, 'year': False, 'Trash_Law': True, 'residualslag17': True, 'residualslag30': False, 'temperature_2m_max_lag14': False, 'apparent_temperature_min_lag30': False, 'quarter': True, 'temperature_2m_max_lag30': False, 'month_cos': False, 'New_Trash_Law': False, 'lag16': False, 'residualslag21': True, 'lag180': True, 'ma120': False, 'apparent_temperature_min_lag90': False, 'ma30': True, 'apparent_temperature_min_lag300': False, 'lag1460': True, 'apparent_temperature_min': False, 'residualslag16': True, 'temperature_2m_min': True, 'apparent_temperature_min_lag20': False, 'lag30': True, 'lag730': True, 'apparent_temperature_min_lag14': True, 'apparent_temperature_min_lag210': True, 'ma365': True, 'apparent_temperature_min_lag120': False, 'trend': False, 'ma180': True, 'apparent_temperature_min_lag270': True, 'residualslag730': True, 'residualslag18': True, 'lag363': False, 'residuals': False, 'ma60': True, 'temperature_2m_max': False, 'lag366': True, 'lag150': True, 'weekofyear': True, 'lag90': True, 'apparent_temperature_min_lag240': False, 'dayofweek': False, 'ma7': False, 'residualslag20': True, 'lag364': False}. Best is trial 320 with value: 4.325775922204958.

Trial starting: 336

[I 2026-03-15 18:19:59,067] Trial 321 finished with value: 4.330088855390948 and parameters: {'changepoint_prior_scale': 0.4286883163488761, 'seasonality_prior_scale': 0.44308039827245443, 'holidays_prior_scale': 0.2014167315839027, 'n_estimators': 798, 'max_depth': 7, 'learning_rate': 0.003953579343137927, 'subsample': 0.6628383391550923, 'colsample_bytree': 0.908147319952726, 'gamma': 1.6179161811219291, 'min_child_weight': 10, 'reg_lambda': 0.12326173858414825, 'reg_alpha': 0.124991235214394, 'month_sin': True, 'apparent_temperature_min_lag150': False, 'apparent_temperature_min_lag21': False, 'apparent_temperature_min_lag16': True, 'apparent_temperature_min_lag365': True, 'dayofweek_cos': False, 'apparent_temperature_min_lag60': True, 'residualslag19': False, 'dayofweek_sin': True, 'Rat_Czar_Appointed': False, 'apparent_temperature_min_lag730': True, 'yhat_upper': False, 'apparent_temperature_min_lag360': False, 'apparent_temperature_min_lag18': False, 'temperature_2m_mean': False, 'apparent_temperature_max': True, 'lag365': False, 'temperature_2m_max_lag60': True, 'lag1095': False, 'ma150': False, 'apparent_temperature_min_lag15': False, 'lag15': False, 'apparent_temperature_min_lag19': True, 'residualslag365': True, 'apparent_temperature_mean': True, 'yhat_lower': False, 'is_federal_holiday': False, 'apparent_temperature_min_lag180': True, 'apparent_temperature_min_lag17': False, 'apparent_temperature_min_lag330': True, 'residualslag15': True, 'ma90': False, 'Rat_Mitigation_Zone': True, 'snowfall_sum': False, 'precipitation_sum': True, 'dayofyear': True, 'month': False, 'dayofmonth': False, 'lag367': False, 'lag120': False, 'lag1825': True, 'lag60': False, 'lag362': False, 'year': False, 'Trash_Law': True, 'residualslag17': True, 'residualslag30': False, 'temperature_2m_max_lag14': False, 'apparent_temperature_min_lag30': False, 'quarter': True, 'temperature_2m_max_lag30': False, 'month_cos': False, 'New_Trash_Law': False, 'lag16': False, 'residualslag21': True, 'lag180': True, 'ma120': False, 'apparent_temperature_min_lag90': False, 'ma30': True, 'apparent_temperature_min_lag300': False, 'lag1460': True, 'apparent_temperature_min': False, 'residualslag16': True, 'temperature_2m_min': True, 'apparent_temperature_min_lag20': False, 'lag30': True, 'lag730': True, 'apparent_temperature_min_lag14': True, 'apparent_temperature_min_lag210': True, 'ma365': True, 'apparent_temperature_min_lag120': False, 'trend': False, 'ma180': True, 'apparent_temperature_min_lag270': True, 'residualslag730': False, 'residualslag18': True, 'lag363': False, 'residuals': False, 'ma60': True, 'temperature_2m_max': False, 'lag366': True, 'lag150': True, 'weekofyear': True, 'lag90': True, 'apparent_temperature_min_lag240': False, 'dayofweek': False, 'ma7': False, 'residualslag20': True, 'lag364': False}. Best is trial 320 with value: 4.325775922204958.

Trial starting: 337

[I 2026-03-15 18:21:09,083] Trial 322 finished with value: 4.3270842702010475 and parameters: {'changepoint_prior_scale': 0.4679670562482771, 'seasonality_prior_scale': 0.436812394555976, 'holidays_prior_scale': 0.20534684072536022, 'n_estimators': 812, 'max_depth': 7, 'learning_rate': 0.0028362885545436655, 'subsample': 0.6711762766158565, 'colsample_bytree': 0.9779586041462318, 'gamma': 1.0033883850420011, 'min_child_weight': 10, 'reg_lambda': 0.1239784370047308, 'reg_alpha': 0.2978187439985749, 'month_sin': True, 'apparent_temperature_min_lag150': False, 'apparent_temperature_min_lag21': False, 'apparent_temperature_min_lag16': True, 'apparent_temperature_min_lag365': True, 'dayofweek_cos': False, 'apparent_temperature_min_lag60': True, 'residualslag19': False, 'dayofweek_sin': True, 'Rat_Czar_Appointed': False, 'apparent_temperature_min_lag730': True, 'yhat_upper': False, 'apparent_temperature_min_lag360': False, 'apparent_temperature_min_lag18': False, 'temperature_2m_mean': False, 'apparent_temperature_max': True, 'lag365': False, 'temperature_2m_max_lag60': True, 'lag1095': False, 'ma150': False, 'apparent_temperature_min_lag15': False, 'lag15': False, 'apparent_temperature_min_lag19': True, 'residualslag365': True, 'apparent_temperature_mean': True, 'yhat_lower': False, 'is_federal_holiday': False, 'apparent_temperature_min_lag180': True, 'apparent_temperature_min_lag17': False, 'apparent_temperature_min_lag330': True, 'residualslag15': True, 'ma90': False, 'Rat_Mitigation_Zone': True, 'snowfall_sum': False, 'precipitation_sum': True, 'dayofyear': True, 'month': False, 'dayofmonth': False, 'lag367': False, 'lag120': False, 'lag1825': True, 'lag60': False, 'lag362': False, 'year': False, 'Trash_Law': True, 'residualslag17': True, 'residualslag30': False, 'temperature_2m_max_lag14': False, 'apparent_temperature_min_lag30': False, 'quarter': True, 'temperature_2m_max_lag30': False, 'month_cos': False, 'New_Trash_Law': False, 'lag16': False, 'residualslag21': True, 'lag180': True, 'ma120': False, 'apparent_temperature_min_lag90': False, 'ma30': True, 'apparent_temperature_min_lag300': False, 'lag1460': True, 'apparent_temperature_min': False, 'residualslag16': True, 'temperature_2m_min': True, 'apparent_temperature_min_lag20': False, 'lag30': True, 'lag730': True, 'apparent_temperature_min_lag14': True, 'apparent_temperature_min_lag210': True, 'ma365': True, 'apparent_temperature_min_lag120': False, 'trend': False, 'ma180': True, 'apparent_temperature_min_lag270': True, 'residualslag730': False, 'residualslag18': True, 'lag363': False, 'residuals': False, 'ma60': True, 'temperature_2m_max': False, 'lag366': True, 'lag150': True, 'weekofyear': True, 'lag90': True, 'apparent_temperature_min_lag240': False, 'dayofweek': False, 'ma7': False, 'residualslag20': True, 'lag364': False}. Best is trial 320 with value: 4.325775922204958.

Trial starting: 338

[I 2026-03-15 18:21:17,756] Trial 324 finished with value: 4.358252266056517 and parameters: {'changepoint_prior_scale': 0.39122069504402984, 'seasonality_prior_scale': 1.0288625131356544, 'holidays_prior_scale': 0.6058857877470739, 'n_estimators': 813, 'max_depth': 7, 'learning_rate': 0.0026352259418344405, 'subsample': 0.673101013791567, 'colsample_bytree': 0.9105120166232726, 'gamma': 1.0021576290538703, 'min_child_weight': 10, 'reg_lambda': 0.1250148674510345, 'reg_alpha': 0.300233680374496, 'month_sin': True, 'apparent_temperature_min_lag150': False, 'apparent_temperature_min_lag21': False, 'apparent_temperature_min_lag16': True, 'apparent_temperature_min_lag365': True, 'dayofweek_cos': False, 'apparent_temperature_min_lag60': True, 'residualslag19': False, 'dayofweek_sin': True, 'Rat_Czar_Appointed': False, 'apparent_temperature_min_lag730': True, 'yhat_upper': False, 'apparent_temperature_min_lag360': False, 'apparent_temperature_min_lag18': False, 'temperature_2m_mean': False, 'apparent_temperature_max': True, 'lag365': False, 'temperature_2m_max_lag60': True, 'lag1095': False, 'ma150': False, 'apparent_temperature_min_lag15': False, 'lag15': False, 'apparent_temperature_min_lag19': True, 'residualslag365': True, 'apparent_temperature_mean': True, 'yhat_lower': False, 'is_federal_holiday': False, 'apparent_temperature_min_lag180': True, 'apparent_temperature_min_lag17': False, 'apparent_temperature_min_lag330': True, 'residualslag15': True, 'ma90': False, 'Rat_Mitigation_Zone': True, 'snowfall_sum': False, 'precipitation_sum': True, 'dayofyear': True, 'month': False, 'dayofmonth': False, 'lag367': False, 'lag120': False, 'lag1825': True, 'lag60': False, 'lag362': False, 'year': False, 'Trash_Law': True, 'residualslag17': True, 'residualslag30': False, 'temperature_2m_max_lag14': False, 'apparent_temperature_min_lag30': False, 'quarter': True, 'temperature_2m_max_lag30': False, 'month_cos': False, 'New_Trash_Law': False, 'lag16': False, 'residualslag21': True, 'lag180': True, 'ma120': False, 'apparent_temperature_min_lag90': False, 'ma30': True, 'apparent_temperature_min_lag300': False, 'lag1460': True, 'apparent_temperature_min': False, 'residualslag16': True, 'temperature_2m_min': True, 'apparent_temperature_min_lag20': False, 'lag30': True, 'lag730': True, 'apparent_temperature_min_lag14': True, 'apparent_temperature_min_lag210': True, 'ma365': True, 'apparent_temperature_min_lag120': False, 'trend': False, 'ma180': True, 'apparent_temperature_min_lag270': True, 'residualslag730': True, 'residualslag18': True, 'lag363': False, 'residuals': False, 'ma60': True, 'temperature_2m_max': False, 'lag366': True, 'lag150': True, 'weekofyear': True, 'lag90': True, 'apparent_temperature_min_lag240': False, 'dayofweek': False, 'ma7': False, 'residualslag20': True, 'lag364': False}. Best is trial 320 with value: 4.325775922204958.

Trial starting: 339

[I 2026-03-15 18:21:45,782] Trial 325 finished with value: 4.320214741964585 and parameters: {'changepoint_prior_scale': 0.4700319633036724, 'seasonality_prior_scale': 0.6050219168776699, 'holidays_prior_scale': 0.18915238711749144, 'n_estimators': 841, 'max_depth': 7, 'learning_rate': 0.004132373860516509, 'subsample': 0.6711534662776886, 'colsample_bytree': 0.9083592853080739, 'gamma': 1.1803084108852202, 'min_child_weight': 10, 'reg_lambda': 0.12505975840883238, 'reg_alpha': 0.414565054093287, 'month_sin': True, 'apparent_temperature_min_lag150': False, 'apparent_temperature_min_lag21': False, 'apparent_temperature_min_lag16': True, 'apparent_temperature_min_lag365': True, 'dayofweek_cos': False, 'apparent_temperature_min_lag60': True, 'residualslag19': False, 'dayofweek_sin': True, 'Rat_Czar_Appointed': False, 'apparent_temperature_min_lag730': True, 'yhat_upper': False, 'apparent_temperature_min_lag360': False, 'apparent_temperature_min_lag18': False, 'temperature_2m_mean': False, 'apparent_temperature_max': True, 'lag365': False, 'temperature_2m_max_lag60': True, 'lag1095': False, 'ma150': False, 'apparent_temperature_min_lag15': False, 'lag15': False, 'apparent_temperature_min_lag19': True, 'residualslag365': True, 'apparent_temperature_mean': True, 'yhat_lower': False, 'is_federal_holiday': False, 'apparent_temperature_min_lag180': True, 'apparent_temperature_min_lag17': False, 'apparent_temperature_min_lag330': True, 'residualslag15': True, 'ma90': False, 'Rat_Mitigation_Zone': True, 'snowfall_sum': False, 'precipitation_sum': True, 'dayofyear': True, 'month': False, 'dayofmonth': False, 'lag367': False, 'lag120': False, 'lag1825': True, 'lag60': False, 'lag362': False, 'year': False, 'Trash_Law': True, 'residualslag17': True, 'residualslag30': False, 'temperature_2m_max_lag14': False, 'apparent_temperature_min_lag30': False, 'quarter': True, 'temperature_2m_max_lag30': False, 'month_cos': False, 'New_Trash_Law': False, 'lag16': False, 'residualslag21': True, 'lag180': True, 'ma120': False, 'apparent_temperature_min_lag90': False, 'ma30': True, 'apparent_temperature_min_lag300': False, 'lag1460': True, 'apparent_temperature_min': False, 'residualslag16': True, 'temperature_2m_min': True, 'apparent_temperature_min_lag20': False, 'lag30': True, 'lag730': True, 'apparent_temperature_min_lag14': True, 'apparent_temperature_min_lag210': True, 'ma365': True, 'apparent_temperature_min_lag120': False, 'trend': False, 'ma180': True, 'apparent_temperature_min_lag270': True, 'residualslag730': True, 'residualslag18': True, 'lag363': False, 'residuals': False, 'ma60': True, 'temperature_2m_max': False, 'lag366': True, 'lag150': True, 'weekofyear': True, 'lag90': True, 'apparent_temperature_min_lag240': False, 'dayofweek': False, 'ma7': False, 'residualslag20': True, 'lag364': False}. Best is trial 325 with value: 4.320214741964585.

Trial starting: 340

[I 2026-03-15 18:23:40,872] Trial 326 finished with value: 4.345119960860383 and parameters: {'changepoint_prior_scale': 0.3864973883273554, 'seasonality_prior_scale': 1.0074216328771557, 'holidays_prior_scale': 0.13707067869544645, 'n_estimators': 850, 'max_depth': 7, 'learning_rate': 0.00412856071081209, 'subsample': 0.7332774109421185, 'colsample_bytree': 0.82633581480508, 'gamma': 1.0342983573430697, 'min_child_weight': 9, 'reg_lambda': 0.12415671463379925, 'reg_alpha': 0.42203356767556843, 'month_sin': True, 'apparent_temperature_min_lag150': False, 'apparent_temperature_min_lag21': False, 'apparent_temperature_min_lag16': True, 'apparent_temperature_min_lag365': True, 'dayofweek_cos': False, 'apparent_temperature_min_lag60': True, 'residualslag19': False, 'dayofweek_sin': True, 'Rat_Czar_Appointed': False, 'apparent_temperature_min_lag730': True, 'yhat_upper': False, 'apparent_temperature_min_lag360': False, 'apparent_temperature_min_lag18': False, 'temperature_2m_mean': False, 'apparent_temperature_max': True, 'lag365': False, 'temperature_2m_max_lag60': True, 'lag1095': False, 'ma150': False, 'apparent_temperature_min_lag15': False, 'lag15': False, 'apparent_temperature_min_lag19': True, 'residualslag365': True, 'apparent_temperature_mean': True, 'yhat_lower': False, 'is_federal_holiday': False, 'apparent_temperature_min_lag180': True, 'apparent_temperature_min_lag17': False, 'apparent_temperature_min_lag330': True, 'residualslag15': True, 'ma90': False, 'Rat_Mitigation_Zone': True, 'snowfall_sum': False, 'precipitation_sum': True, 'dayofyear': True, 'month': False, 'dayofmonth': False, 'lag367': False, 'lag120': False, 'lag1825': True, 'lag60': False, 'lag362': False, 'year': False, 'Trash_Law': True, 'residualslag17': True, 'residualslag30': False, 'temperature_2m_max_lag14': False, 'apparent_temperature_min_lag30': False, 'quarter': True, 'temperature_2m_max_lag30': False, 'month_cos': False, 'New_Trash_Law': False, 'lag16': False, 'residualslag21': True, 'lag180': True, 'ma120': False, 'apparent_temperature_min_lag90': False, 'ma30': True, 'apparent_temperature_min_lag300': False, 'lag1460': True, 'apparent_temperature_min': False, 'residualslag16': True, 'temperature_2m_min': True, 'apparent_temperature_min_lag20': False, 'lag30': True, 'lag730': True, 'apparent_temperature_min_lag14': True, 'apparent_temperature_min_lag210': True, 'ma365': True, 'apparent_temperature_min_lag120': False, 'trend': False, 'ma180': True, 'apparent_temperature_min_lag270': True, 'residualslag730': True, 'residualslag18': True, 'lag363': False, 'residuals': False, 'ma60': True, 'temperature_2m_max': False, 'lag366': True, 'lag150': True, 'weekofyear': True, 'lag90': True, 'apparent_temperature_min_lag240': False, 'dayofweek': False, 'ma7': False, 'residualslag20': True, 'lag364': False}. Best is trial 325 with value: 4.320214741964585.

Trial starting: 341

[I 2026-03-15 18:23:44,233] Trial 328 finished with value: 4.360550841693605 and parameters: {'changepoint_prior_scale': 0.38083086689658957, 'seasonality_prior_scale': 1.0523260743812624, 'holidays_prior_scale': 0.14789033189725453, 'n_estimators': 806, 'max_depth': 7, 'learning_rate': 0.004061516528998474, 'subsample': 0.677121396191865, 'colsample_bytree': 0.8313859106272493, 'gamma': 1.6386782221520912, 'min_child_weight': 9, 'reg_lambda': 0.12424107539152522, 'reg_alpha': 0.4108581608185688, 'month_sin': True, 'apparent_temperature_min_lag150': False, 'apparent_temperature_min_lag21': False, 'apparent_temperature_min_lag16': False, 'apparent_temperature_min_lag365': True, 'dayofweek_cos': False, 'apparent_temperature_min_lag60': True, 'residualslag19': False, 'dayofweek_sin': True, 'Rat_Czar_Appointed': False, 'apparent_temperature_min_lag730': True, 'yhat_upper': False, 'apparent_temperature_min_lag360': False, 'apparent_temperature_min_lag18': False, 'temperature_2m_mean': False, 'apparent_temperature_max': True, 'lag365': False, 'temperature_2m_max_lag60': True, 'lag1095': False, 'ma150': False, 'apparent_temperature_min_lag15': False, 'lag15': False, 'apparent_temperature_min_lag19': True, 'residualslag365': True, 'apparent_temperature_mean': True, 'yhat_lower': False, 'is_federal_holiday': False, 'apparent_temperature_min_lag180': True, 'apparent_temperature_min_lag17': False, 'apparent_temperature_min_lag330': True, 'residualslag15': True, 'ma90': False, 'Rat_Mitigation_Zone': True, 'snowfall_sum': False, 'precipitation_sum': True, 'dayofyear': True, 'month': False, 'dayofmonth': False, 'lag367': False, 'lag120': False, 'lag1825': True, 'lag60': False, 'lag362': False, 'year': False, 'Trash_Law': True, 'residualslag17': True, 'residualslag30': False, 'temperature_2m_max_lag14': False, 'apparent_temperature_min_lag30': False, 'quarter': True, 'temperature_2m_max_lag30': False, 'month_cos': False, 'New_Trash_Law': False, 'lag16': False, 'residualslag21': True, 'lag180': True, 'ma120': False, 'apparent_temperature_min_lag90': False, 'ma30': True, 'apparent_temperature_min_lag300': False, 'lag1460': True, 'apparent_temperature_min': False, 'residualslag16': True, 'temperature_2m_min': True, 'apparent_temperature_min_lag20': False, 'lag30': True, 'lag730': True, 'apparent_temperature_min_lag14': True, 'apparent_temperature_min_lag210': False, 'ma365': True, 'apparent_temperature_min_lag120': False, 'trend': False, 'ma180': True, 'apparent_temperature_min_lag270': True, 'residualslag730': True, 'residualslag18': True, 'lag363': False, 'residuals': False, 'ma60': True, 'temperature_2m_max': False, 'lag366': True, 'lag150': True, 'weekofyear': True, 'lag90': True, 'apparent_temperature_min_lag240': False, 'dayofweek': False, 'ma7': False, 'residualslag20': True, 'lag364': False}. Best is trial 325 with value: 4.320214741964585.

Trial starting: 342

[I 2026-03-15 18:24:21,643] Trial 329 finished with value: 4.3876210146825 and parameters: {'changepoint_prior_scale': 0.38667737111587075, 'seasonality_prior_scale': 1.031021106132912, 'holidays_prior_scale': 0.24181869097214678, 'n_estimators': 815, 'max_depth': 7, 'learning_rate': 0.004130748638755677, 'subsample': 0.7362543066995308, 'colsample_bytree': 0.825532555488425, 'gamma': 1.5526765693823548, 'min_child_weight': 9, 'reg_lambda': 0.12415932510705271, 'reg_alpha': 0.13101861373841237, 'month_sin': True, 'apparent_temperature_min_lag150': False, 'apparent_temperature_min_lag21': False, 'apparent_temperature_min_lag16': False, 'apparent_temperature_min_lag365': True, 'dayofweek_cos': False, 'apparent_temperature_min_lag60': True, 'residualslag19': False, 'dayofweek_sin': True, 'Rat_Czar_Appointed': False, 'apparent_temperature_min_lag730': True, 'yhat_upper': False, 'apparent_temperature_min_lag360': False, 'apparent_temperature_min_lag18': False, 'temperature_2m_mean': False, 'apparent_temperature_max': True, 'lag365': False, 'temperature_2m_max_lag60': True, 'lag1095': False, 'ma150': False, 'apparent_temperature_min_lag15': False, 'lag15': False, 'apparent_temperature_min_lag19': True, 'residualslag365': True, 'apparent_temperature_mean': True, 'yhat_lower': False, 'is_federal_holiday': False, 'apparent_temperature_min_lag180': True, 'apparent_temperature_min_lag17': False, 'apparent_temperature_min_lag330': True, 'residualslag15': True, 'ma90': False, 'Rat_Mitigation_Zone': True, 'snowfall_sum': False, 'precipitation_sum': True, 'dayofyear': True, 'month': False, 'dayofmonth': False, 'lag367': False, 'lag120': False, 'lag1825': True, 'lag60': False, 'lag362': False, 'year': False, 'Trash_Law': True, 'residualslag17': True, 'residualslag30': False, 'temperature_2m_max_lag14': False, 'apparent_temperature_min_lag30': False, 'quarter': True, 'temperature_2m_max_lag30': False, 'month_cos': False, 'New_Trash_Law': False, 'lag16': False, 'residualslag21': True, 'lag180': True, 'ma120': False, 'apparent_temperature_min_lag90': False, 'ma30': True, 'apparent_temperature_min_lag300': False, 'lag1460': True, 'apparent_temperature_min': False, 'residualslag16': True, 'temperature_2m_min': True, 'apparent_temperature_min_lag20': False, 'lag30': True, 'lag730': True, 'apparent_temperature_min_lag14': True, 'apparent_temperature_min_lag210': False, 'ma365': True, 'apparent_temperature_min_lag120': False, 'trend': False, 'ma180': True, 'apparent_temperature_min_lag270': True, 'residualslag730': True, 'residualslag18': True, 'lag363': False, 'residuals': False, 'ma60': True, 'temperature_2m_max': False, 'lag366': True, 'lag150': True, 'weekofyear': True, 'lag90': True, 'apparent_temperature_min_lag240': False, 'dayofweek': False, 'ma7': False, 'residualslag20': True, 'lag364': False}. Best is trial 325 with value: 4.320214741964585.

Trial starting: 343

[I 2026-03-15 18:24:45,693] Trial 331 finished with value: 4.357006992515039 and parameters: {'changepoint_prior_scale': 0.3888965712835704, 'seasonality_prior_scale': 1.0223185567723954, 'holidays_prior_scale': 0.09409417956223075, 'n_estimators': 822, 'max_depth': 7, 'learning_rate': 0.0039476439856725816, 'subsample': 0.6785746377904004, 'colsample_bytree': 0.8281678827113548, 'gamma': 1.5907871570718974, 'min_child_weight': 9, 'reg_lambda': 0.12423389357574019, 'reg_alpha': 0.2987850603534702, 'month_sin': True, 'apparent_temperature_min_lag150': False, 'apparent_temperature_min_lag21': False, 'apparent_temperature_min_lag16': False, 'apparent_temperature_min_lag365': True, 'dayofweek_cos': False, 'apparent_temperature_min_lag60': True, 'residualslag19': False, 'dayofweek_sin': True, 'Rat_Czar_Appointed': False, 'apparent_temperature_min_lag730': True, 'yhat_upper': False, 'apparent_temperature_min_lag360': False, 'apparent_temperature_min_lag18': False, 'temperature_2m_mean': False, 'apparent_temperature_max': True, 'lag365': False, 'temperature_2m_max_lag60': True, 'lag1095': False, 'ma150': False, 'apparent_temperature_min_lag15': False, 'lag15': False, 'apparent_temperature_min_lag19': True, 'residualslag365': True, 'apparent_temperature_mean': True, 'yhat_lower': False, 'is_federal_holiday': False, 'apparent_temperature_min_lag180': True, 'apparent_temperature_min_lag17': False, 'apparent_temperature_min_lag330': True, 'residualslag15': True, 'ma90': False, 'Rat_Mitigation_Zone': True, 'snowfall_sum': False, 'precipitation_sum': True, 'dayofyear': True, 'month': False, 'dayofmonth': False, 'lag367': False, 'lag120': False, 'lag1825': True, 'lag60': False, 'lag362': False, 'year': False, 'Trash_Law': True, 'residualslag17': True, 'residualslag30': False, 'temperature_2m_max_lag14': False, 'apparent_temperature_min_lag30': False, 'quarter': True, 'temperature_2m_max_lag30': False, 'month_cos': False, 'New_Trash_Law': False, 'lag16': False, 'residualslag21': True, 'lag180': True, 'ma120': False, 'apparent_temperature_min_lag90': False, 'ma30': True, 'apparent_temperature_min_lag300': False, 'lag1460': True, 'apparent_temperature_min': False, 'residualslag16': True, 'temperature_2m_min': True, 'apparent_temperature_min_lag20': False, 'lag30': True, 'lag730': True, 'apparent_temperature_min_lag14': True, 'apparent_temperature_min_lag210': False, 'ma365': True, 'apparent_temperature_min_lag120': False, 'trend': False, 'ma180': True, 'apparent_temperature_min_lag270': True, 'residualslag730': True, 'residualslag18': True, 'lag363': False, 'residuals': False, 'ma60': True, 'temperature_2m_max': False, 'lag366': True, 'lag150': True, 'weekofyear': True, 'lag90': True, 'apparent_temperature_min_lag240': False, 'dayofweek': False, 'ma7': False, 'residualslag20': True, 'lag364': False}. Best is trial 325 with value: 4.320214741964585.

Trial starting: 344

[I 2026-03-15 18:24:55,784] Trial 327 finished with value: 4.349038143615048 and parameters: {'changepoint_prior_scale': 0.38450647738045896, 'seasonality_prior_scale': 0.7402503116170482, 'holidays_prior_scale': 0.17660470965318878, 'n_estimators': 827, 'max_depth': 7, 'learning_rate': 0.0038784334143281344, 'subsample': 0.678514083939223, 'colsample_bytree': 0.8342760621355857, 'gamma': 1.0075254547743469, 'min_child_weight': 9, 'reg_lambda': 0.12474919101518178, 'reg_alpha': 0.123041280517591, 'month_sin': True, 'apparent_temperature_min_lag150': False, 'apparent_temperature_min_lag21': False, 'apparent_temperature_min_lag16': False, 'apparent_temperature_min_lag365': True, 'dayofweek_cos': False, 'apparent_temperature_min_lag60': True, 'residualslag19': False, 'dayofweek_sin': True, 'Rat_Czar_Appointed': False, 'apparent_temperature_min_lag730': True, 'yhat_upper': False, 'apparent_temperature_min_lag360': False, 'apparent_temperature_min_lag18': False, 'temperature_2m_mean': False, 'apparent_temperature_max': True, 'lag365': False, 'temperature_2m_max_lag60': True, 'lag1095': False, 'ma150': False, 'apparent_temperature_min_lag15': False, 'lag15': False, 'apparent_temperature_min_lag19': True, 'residualslag365': True, 'apparent_temperature_mean': True, 'yhat_lower': False, 'is_federal_holiday': False, 'apparent_temperature_min_lag180': True, 'apparent_temperature_min_lag17': False, 'apparent_temperature_min_lag330': True, 'residualslag15': True, 'ma90': False, 'Rat_Mitigation_Zone': True, 'snowfall_sum': False, 'precipitation_sum': True, 'dayofyear': True, 'month': False, 'dayofmonth': False, 'lag367': False, 'lag120': False, 'lag1825': True, 'lag60': False, 'lag362': False, 'year': False, 'Trash_Law': True, 'residualslag17': True, 'residualslag30': False, 'temperature_2m_max_lag14': False, 'apparent_temperature_min_lag30': False, 'quarter': True, 'temperature_2m_max_lag30': False, 'month_cos': False, 'New_Trash_Law': False, 'lag16': False, 'residualslag21': True, 'lag180': True, 'ma120': False, 'apparent_temperature_min_lag90': False, 'ma30': True, 'apparent_temperature_min_lag300': False, 'lag1460': True, 'apparent_temperature_min': False, 'residualslag16': True, 'temperature_2m_min': True, 'apparent_temperature_min_lag20': False, 'lag30': True, 'lag730': True, 'apparent_temperature_min_lag14': True, 'apparent_temperature_min_lag210': True, 'ma365': True, 'apparent_temperature_min_lag120': False, 'trend': False, 'ma180': True, 'apparent_temperature_min_lag270': True, 'residualslag730': True, 'residualslag18': True, 'lag363': False, 'residuals': False, 'ma60': True, 'temperature_2m_max': False, 'lag366': True, 'lag150': True, 'weekofyear': True, 'lag90': True, 'apparent_temperature_min_lag240': False, 'dayofweek': False, 'ma7': False, 'residualslag20': True, 'lag364': False}. Best is trial 325 with value: 4.320214741964585.

Trial starting: 345

[I 2026-03-15 18:25:41,840] Trial 323 finished with value: 4.343146330669172 and parameters: {'changepoint_prior_scale': 0.38749149253694065, 'seasonality_prior_scale': 0.45070781163776574, 'holidays_prior_scale': 0.20680835327764477, 'n_estimators': 973, 'max_depth': 7, 'learning_rate': 0.002654346820211914, 'subsample': 0.6722191313156617, 'colsample_bytree': 0.8294068256845274, 'gamma': 0.9929700626048572, 'min_child_weight': 10, 'reg_lambda': 0.12307417119552304, 'reg_alpha': 0.40858744489101706, 'month_sin': True, 'apparent_temperature_min_lag150': False, 'apparent_temperature_min_lag21': False, 'apparent_temperature_min_lag16': True, 'apparent_temperature_min_lag365': True, 'dayofweek_cos': False, 'apparent_temperature_min_lag60': True, 'residualslag19': False, 'dayofweek_sin': True, 'Rat_Czar_Appointed': False, 'apparent_temperature_min_lag730': True, 'yhat_upper': False, 'apparent_temperature_min_lag360': False, 'apparent_temperature_min_lag18': False, 'temperature_2m_mean': False, 'apparent_temperature_max': True, 'lag365': False, 'temperature_2m_max_lag60': True, 'lag1095': False, 'ma150': False, 'apparent_temperature_min_lag15': False, 'lag15': False, 'apparent_temperature_min_lag19': True, 'residualslag365': True, 'apparent_temperature_mean': True, 'yhat_lower': False, 'is_federal_holiday': False, 'apparent_temperature_min_lag180': True, 'apparent_temperature_min_lag17': False, 'apparent_temperature_min_lag330': True, 'residualslag15': True, 'ma90': False, 'Rat_Mitigation_Zone': True, 'snowfall_sum': False, 'precipitation_sum': True, 'dayofyear': True, 'month': False, 'dayofmonth': False, 'lag367': False, 'lag120': False, 'lag1825': True, 'lag60': False, 'lag362': False, 'year': False, 'Trash_Law': True, 'residualslag17': True, 'residualslag30': False, 'temperature_2m_max_lag14': False, 'apparent_temperature_min_lag30': False, 'quarter': True, 'temperature_2m_max_lag30': False, 'month_cos': False, 'New_Trash_Law': False, 'lag16': False, 'residualslag21': True, 'lag180': True, 'ma120': False, 'apparent_temperature_min_lag90': False, 'ma30': True, 'apparent_temperature_min_lag300': False, 'lag1460': True, 'apparent_temperature_min': False, 'residualslag16': True, 'temperature_2m_min': True, 'apparent_temperature_min_lag20': False, 'lag30': True, 'lag730': True, 'apparent_temperature_min_lag14': True, 'apparent_temperature_min_lag210': True, 'ma365': True, 'apparent_temperature_min_lag120': False, 'trend': False, 'ma180': True, 'apparent_temperature_min_lag270': True, 'residualslag730': True, 'residualslag18': True, 'lag363': False, 'residuals': False, 'ma60': True, 'temperature_2m_max': False, 'lag366': True, 'lag150': True, 'weekofyear': True, 'lag90': True, 'apparent_temperature_min_lag240': False, 'dayofweek': False, 'ma7': False, 'residualslag20': True, 'lag364': False}. Best is trial 325 with value: 4.320214741964585.

Trial starting: 346

[I 2026-03-15 18:25:44,661] Trial 330 finished with value: 4.346503098608749 and parameters: {'changepoint_prior_scale': 0.38529257218528495, 'seasonality_prior_scale': 1.0255285499743243, 'holidays_prior_scale': 0.15599694096576397, 'n_estimators': 834, 'max_depth': 7, 'learning_rate': 0.0037988333857763195, 'subsample': 0.6753192439124094, 'colsample_bytree': 0.8327033764644776, 'gamma': 1.1745603263771471, 'min_child_weight': 9, 'reg_lambda': 0.10020776386394754, 'reg_alpha': 0.4269043717225044, 'month_sin': True, 'apparent_temperature_min_lag150': False, 'apparent_temperature_min_lag21': False, 'apparent_temperature_min_lag16': False, 'apparent_temperature_min_lag365': True, 'dayofweek_cos': False, 'apparent_temperature_min_lag60': True, 'residualslag19': False, 'dayofweek_sin': True, 'Rat_Czar_Appointed': False, 'apparent_temperature_min_lag730': True, 'yhat_upper': False, 'apparent_temperature_min_lag360': False, 'apparent_temperature_min_lag18': False, 'temperature_2m_mean': False, 'apparent_temperature_max': True, 'lag365': False, 'temperature_2m_max_lag60': True, 'lag1095': False, 'ma150': False, 'apparent_temperature_min_lag15': False, 'lag15': False, 'apparent_temperature_min_lag19': True, 'residualslag365': True, 'apparent_temperature_mean': True, 'yhat_lower': False, 'is_federal_holiday': False, 'apparent_temperature_min_lag180': True, 'apparent_temperature_min_lag17': False, 'apparent_temperature_min_lag330': True, 'residualslag15': True, 'ma90': False, 'Rat_Mitigation_Zone': True, 'snowfall_sum': False, 'precipitation_sum': True, 'dayofyear': True, 'month': False, 'dayofmonth': False, 'lag367': False, 'lag120': False, 'lag1825': True, 'lag60': False, 'lag362': False, 'year': False, 'Trash_Law': True, 'residualslag17': True, 'residualslag30': False, 'temperature_2m_max_lag14': False, 'apparent_temperature_min_lag30': False, 'quarter': True, 'temperature_2m_max_lag30': False, 'month_cos': False, 'New_Trash_Law': False, 'lag16': False, 'residualslag21': True, 'lag180': True, 'ma120': False, 'apparent_temperature_min_lag90': False, 'ma30': True, 'apparent_temperature_min_lag300': False, 'lag1460': True, 'apparent_temperature_min': False, 'residualslag16': True, 'temperature_2m_min': True, 'apparent_temperature_min_lag20': False, 'lag30': True, 'lag730': True, 'apparent_temperature_min_lag14': True, 'apparent_temperature_min_lag210': False, 'ma365': True, 'apparent_temperature_min_lag120': False, 'trend': False, 'ma180': True, 'apparent_temperature_min_lag270': True, 'residualslag730': True, 'residualslag18': True, 'lag363': False, 'residuals': False, 'ma60': True, 'temperature_2m_max': False, 'lag366': True, 'lag150': True, 'weekofyear': True, 'lag90': True, 'apparent_temperature_min_lag240': False, 'dayofweek': False, 'ma7': False, 'residualslag20': True, 'lag364': False}. Best is trial 325 with value: 4.320214741964585.

Trial starting: 347

[I 2026-03-15 18:27:15,373] Trial 332 finished with value: 4.380251583476573 and parameters: {'changepoint_prior_scale': 0.4655640222101024, 'seasonality_prior_scale': 1.032742249997796, 'holidays_prior_scale': 0.15721817079423808, 'n_estimators': 826, 'max_depth': 7, 'learning_rate': 0.0025304559984154224, 'subsample': 0.7351267478108302, 'colsample_bytree': 0.8320883711171528, 'gamma': 3.9651360147536336, 'min_child_weight': 9, 'reg_lambda': 0.12273857966792866, 'reg_alpha': 0.30619894454117014, 'month_sin': True, 'apparent_temperature_min_lag150': False, 'apparent_temperature_min_lag21': False, 'apparent_temperature_min_lag16': False, 'apparent_temperature_min_lag365': True, 'dayofweek_cos': False, 'apparent_temperature_min_lag60': True, 'residualslag19': False, 'dayofweek_sin': True, 'Rat_Czar_Appointed': False, 'apparent_temperature_min_lag730': True, 'yhat_upper': False, 'apparent_temperature_min_lag360': False, 'apparent_temperature_min_lag18': False, 'temperature_2m_mean': False, 'apparent_temperature_max': True, 'lag365': False, 'temperature_2m_max_lag60': True, 'lag1095': False, 'ma150': False, 'apparent_temperature_min_lag15': False, 'lag15': False, 'apparent_temperature_min_lag19': True, 'residualslag365': True, 'apparent_temperature_mean': True, 'yhat_lower': False, 'is_federal_holiday': False, 'apparent_temperature_min_lag180': True, 'apparent_temperature_min_lag17': False, 'apparent_temperature_min_lag330': True, 'residualslag15': True, 'ma90': False, 'Rat_Mitigation_Zone': True, 'snowfall_sum': False, 'precipitation_sum': True, 'dayofyear': True, 'month': False, 'dayofmonth': False, 'lag367': False, 'lag120': False, 'lag1825': True, 'lag60': False, 'lag362': False, 'year': False, 'Trash_Law': True, 'residualslag17': True, 'residualslag30': False, 'temperature_2m_max_lag14': False, 'apparent_temperature_min_lag30': False, 'quarter': True, 'temperature_2m_max_lag30': False, 'month_cos': False, 'New_Trash_Law': False, 'lag16': False, 'residualslag21': True, 'lag180': True, 'ma120': False, 'apparent_temperature_min_lag90': False, 'ma30': True, 'apparent_temperature_min_lag300': False, 'lag1460': True, 'apparent_temperature_min': False, 'residualslag16': True, 'temperature_2m_min': True, 'apparent_temperature_min_lag20': False, 'lag30': True, 'lag730': True, 'apparent_temperature_min_lag14': True, 'apparent_temperature_min_lag210': False, 'ma365': True, 'apparent_temperature_min_lag120': False, 'trend': False, 'ma180': True, 'apparent_temperature_min_lag270': True, 'residualslag730': True, 'residualslag18': True, 'lag363': False, 'residuals': False, 'ma60': True, 'temperature_2m_max': False, 'lag366': True, 'lag150': True, 'weekofyear': True, 'lag90': True, 'apparent_temperature_min_lag240': False, 'dayofweek': False, 'ma7': False, 'residualslag20': True, 'lag364': False}. Best is trial 325 with value: 4.320214741964585.

Trial starting: 348

In [ ]:
best_features

In [ ]:
best_hyperparams

In [ ]:
prophet_keys = ["changepoint_prior_scale", "seasonality_prior_scale", "holidays_prior_scale"]

# extract subset
best_prophet_params = {k: best_hyperparams[k] for k in prophet_keys if k in best_hyperparams}


xgb_keys = ['n_estimators', 'max_depth', 'learning_rate', 'subsample', 'colsample_bytree', 'gamma', 'min_child_weight', 'reg_lambda', 'reg_alpha'] 

# extract subset
best_xgb_params = {k: best_hyperparams[k] for k in xgb_keys if k in best_hyperparams}

# Cross Validate if Hybrid Model Performs as well as Claimed


We cross validate to check that there is a genuine improvement on the model's performance. Again, we saw that Prophet performed the best and we want to compare Prophet vs. this Hybrid model vs. NeuralProphet. Since our work in 1modeling_experiments.ipynb did not even try to tune XGBoost's parameters and features to see if there is an improvement, we have done it here.

In [ ]:
# this is the time series split we will work with
tscv = TimeSeriesSplit(gap=0, max_train_size=None, n_splits=26, test_size=14)

# we import the data and clean it for future use
rs = pd.read_csv('../../scr/data/cleaned_rat_sightings_data/all_cleaned_rat_sightings.csv')
rs['created_date'] = pd.to_datetime(rs['created_date']) 
# mark cutoff dates, and also rename columns
rs = rs[rs['created_date']<'2025-03-01']
rs = rs[rs['created_date']>='2020-01-01']
rs = rs[rs['borough']=='MANHATTAN']
rs = rs.groupby([rs['created_date'].dt.date]).size().reset_index(name='count')
rs.rename(columns={'created_date': 'ds', 'count': 'y'}, inplace=True)

In [ ]:
save = rs['ds'].copy().values
rs = rs.set_index('ds')
rs.index = pd.to_datetime(rs.index)
rs['ds']=save
rs = create_features(rs)
rs = add_cyclic(rs)
rs = add_lags(rs)
rs = add_seasonal_lags(rs)
rs = add_moving_averages(rs)
rs = add_weather_data(rs,wd)
rs = add_more_weather_feature(rs)
rs = add_federal_holidays(rs, custom_holidays = ['12-31'])
rs = add_law_flag(rs, law_name='Trash_Law', start_date = '2024-03-01')
rs = add_law_flag(rs, law_name = 'New_Trash_Law', start_date = '2024-11-01')
rs = add_law_flag(rs, law_name='Rat_Mitigation_Zone', start_date = '2023-07-07')
rs = add_law_flag(rs, law_name='Rat_Czar_Appointed', start_date = '2023-04-12')
rs

In [ ]:
FEATURES = best_features

In [ ]:
results = []

for i, (train_index, test_index) in enumerate(tscv.split(rs)):

    train = rs.iloc[train_index].copy()
    test = rs.iloc[test_index].copy()

    model = Prophet(**best_prophet_params, holidays=holidays)
    model.add_country_holidays(country_name='US')
    model.fit(train)

    train_future = model.make_future_dataframe(periods=0, freq='D')
    train_forecast = model.predict(train_future)

    train_residuals = train['y'].values - train_forecast['yhat'].values

    residuals_df = pd.DataFrame({'ds': train['ds'],'y': train_residuals})

    train['residuals'] = train_residuals

    add_new_lags(train, 'residuals')

    train['trend'] = train_forecast['trend'].values
    train['yhat_lower'] = train_forecast['yhat_lower'].values
    train['yhat_upper'] = train_forecast['yhat_upper'].values

    X_train_residuals = train[FEATURES]
    y_train_residuals = residuals_df['y']

    # Train XGBoost
    xgb_model = xgb.XGBRegressor(**best_xgb_params)
    xgb_model.fit(X_train_residuals, y_train_residuals)

    # Prepare Test Data
    test['residuals'] = np.nan # need to add this otherwise it won't run

    dummy = pd.concat([train, test], axis=0)

    add_new_lags(dummy, 'residuals') # need to add the lags that test can actually see

    test = dummy.iloc[test_index].copy() # cut out the test set again

    # Prophet Forecast
    future = model.make_future_dataframe(periods=len(test), freq='D')
    prophet_forecast = model.predict(future)

    # add outputs of Prophet for use in the XGBoost model
    test.loc[:, 'trend'] = prophet_forecast[-len(test):]['trend'].values
    test.loc[:, 'yhat_lower'] = prophet_forecast[-len(test):]['yhat_lower'].values
    test.loc[:, 'yhat_upper'] = prophet_forecast[-len(test):]['yhat_upper'].values

    X_test = test[FEATURES]

    xgb_residual_preds = xgb_model.predict(X_test)

    y_pred = np.round(prophet_forecast['yhat'][-len(test):].values + xgb_residual_preds)
    y_true = test['y'].values

    rmse = np.sqrt(mean_squared_error(y_true, y_pred))
    results.append(rmse)    
    # Store the results for this fold

# Convert the results into a DataFrame
prophet_xgb_results_df = pd.DataFrame(results, columns=["RMSE"])

In [ ]:
mean_rmse = prophet_xgb_results_df['RMSE'].mean()
prophet_xgb_results_df.loc['mean'] = [mean_rmse]

# Prophet + XGBoost Results

In [ ]:
prophet_xgb_results_df