In the previous notebook 1models_citywide.ipynb, we found that the Prophet and Prophet+XGBoost models performed well in terms of forecasting rat sightings by day citywide. Since a Prophet+XGBoost model is an upgrade to the Prophet model, we also consider the NeuralProphet model to see if it provides any improvements. In this notebook, we will do some more feature engineering and hyperparameter tuning to determine which is a more satisfactory model.

Our work in tuning and training the XGBoosted Prophet model can be found in the notebook 4.0XGBoosted_Prophet.

This notebook will have Prophet and NeuralProphet

# Import Packages

In [9]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import datetime

from sklearn.model_selection import TimeSeriesSplit
from sklearn.metrics import mean_squared_error, mean_absolute_percentage_error
from sklearn.linear_model import LinearRegression

from prophet import Prophet
from pandas.tseries.holiday import USFederalHolidayCalendar
from prophet.diagnostics import cross_validation, performance_metrics
from prophet.plot import plot_cross_validation_metric
from prophet.plot import add_changepoints_to_plot
from prophet.plot import plot_plotly, plot_components_plotly
import itertools

import warnings
from statsmodels.tools.sm_exceptions import ConvergenceWarning
warnings.simplefilter('ignore', ConvergenceWarning)

import optuna
from neuralprophet import NeuralProphet
import logging

# Prophet

## Import the data

In [10]:
# this is the time series split we will work with
tscv = TimeSeriesSplit(gap=0, max_train_size=None, n_splits=26, test_size=14)


# we import the data and clean it for future use
rs = pd.read_csv('../../scr/data/cleaned_rat_sightings_data/all_cleaned_rat_sightings.csv')
rs['created_date'] = pd.to_datetime(rs['created_date']) 
rs['closed_date'] = pd.to_datetime(rs['closed_date'])
rs['resolution_action_updated_date'] = pd.to_datetime(rs['resolution_action_updated_date'])
# mark cutoff dates, and also rename columns
rs = rs[rs['created_date']<'2025-03-01']
rs = rs[rs['created_date']>='2020-01-01']
rs = rs.groupby([rs['created_date'].dt.date]).size().reset_index(name='count')
rs.rename(columns={'created_date': 'ds', 'count': 'y'}, inplace=True)

## Prepare Prophet

In [11]:
date_range = pd.date_range(start="2020-01-01", end="2025-02-28")

# Generate US federal holidays
calendar = USFederalHolidayCalendar()
holidays = calendar.holidays(start=date_range.min(), end=date_range.max())

federal_holidays = pd.DataFrame({
    'holiday': 'federal_us',
    'ds': pd.to_datetime(holidays),
    'lower_window': 0,
    'upper_window': 1})

holidays = federal_holidays

In [12]:
rs_saved = rs.copy()
df = rs.copy()

## Walkforward Cross-validation for Prophet

In [13]:
# this is the time series split we will work with
tscv = TimeSeriesSplit(gap=0, max_train_size=None, n_splits=26, test_size=14)


# we import the data and clean it for future use
rs = pd.read_csv('../../scr/data/cleaned_rat_sightings_data/all_cleaned_rat_sightings.csv')
rs['created_date'] = pd.to_datetime(rs['created_date']) 
# mark cutoff dates, and also rename columns
rs = rs[rs['created_date']<'2025-03-01']
rs = rs[rs['created_date']>='2020-01-01']
rs = rs.groupby([rs['created_date'].dt.date]).size().reset_index(name='count')
rs.rename(columns={'created_date': 'ds', 'count': 'y'}, inplace=True)

date_range = pd.date_range(start="2020-01-01", end="2025-02-28")

# Generate US federal holidays
calendar = USFederalHolidayCalendar()
holidays = calendar.holidays(start=date_range.min(), end=date_range.max())

federal_holidays = pd.DataFrame({
    'holiday': 'federal_us',
    'ds': pd.to_datetime(holidays),
    'lower_window': 0,
    'upper_window': 1})

holidays = federal_holidays

In [14]:
# Rename columns for Prophet model
rs.rename(columns={'created_date': 'ds', 'count': 'y'}, inplace=True)
results = []

for i, (train_index, test_index) in enumerate(tscv.split(rs)):
    train = rs.iloc[train_index]
    test = rs.iloc[test_index]
    
    model = Prophet(holidays=holidays)
    model.add_country_holidays(country_name='US')

    model.fit(train)
    
    future = model.make_future_dataframe(periods=len(test), freq='D')
    forecast = model.predict(future)
    
    # Obtain predicted values and compare against the actuals.
    y_pred = forecast['yhat'][-len(test):].values
    y_pred = np.round(y_pred)
    y_true = test['y'].values
    
    rmse = np.sqrt(mean_squared_error(y_true, y_pred))
    mape = mean_absolute_percentage_error(y_true, y_pred)
    
    # Append results
    results.append({'fold': i, 'rmse': rmse, 'mape': mape})

prophet_results_df = pd.DataFrame(results)
prophet_results_df.loc['mean'] = ['mean',  prophet_results_df['rmse'].mean(), prophet_results_df['mape'].mean()]
prophet_results_df

09:43:13 - cmdstanpy - INFO - Chain [1] start processing
09:43:14 - cmdstanpy - INFO - Chain [1] done processing
09:43:14 - cmdstanpy - INFO - Chain [1] start processing
09:43:14 - cmdstanpy - INFO - Chain [1] done processing
09:43:15 - cmdstanpy - INFO - Chain [1] start processing
09:43:15 - cmdstanpy - INFO - Chain [1] done processing
09:43:15 - cmdstanpy - INFO - Chain [1] start processing
09:43:16 - cmdstanpy - INFO - Chain [1] done processing
09:43:16 - cmdstanpy - INFO - Chain [1] start processing
09:43:16 - cmdstanpy - INFO - Chain [1] done processing
09:43:17 - cmdstanpy - INFO - Chain [1] start processing
09:43:17 - cmdstanpy - INFO - Chain [1] done processing
09:43:18 - cmdstanpy - INFO - Chain [1] start processing
09:43:18 - cmdstanpy - INFO - Chain [1] done processing
09:43:18 - cmdstanpy - INFO - Chain [1] start processing
09:43:18 - cmdstanpy - INFO - Chain [1] done processing
09:43:19 - cmdstanpy - INFO - Chain [1] start processing
09:43:19 - cmdstanpy - INFO - Chain [1] done processing
09:43:20 - cmdstanpy - INFO - Chain [1] start processing
09:43:20 - cmdstanpy - INFO - Chain [1] done processing
09:43:21 - cmdstanpy - INFO - Chain [1] start processing
09:43:21 - cmdstanpy - INFO - Chain [1] done processing
09:43:22 - cmdstanpy - INFO - Chain [1] start processing
09:43:22 - cmdstanpy - INFO - Chain [1] done processing
09:43:22 - cmdstanpy - INFO - Chain [1] start processing
09:43:23 - cmdstanpy - INFO - Chain [1] done processing
09:43:23 - cmdstanpy - INFO - Chain [1] start processing
09:43:24 - cmdstanpy - INFO - Chain [1] done processing
09:43:24 - cmdstanpy - INFO - Chain [1] start processing
09:43:25 - cmdstanpy - INFO - Chain [1] done processing
09:43:25 - cmdstanpy - INFO - Chain [1] start processing
09:43:25 - cmdstanpy - INFO - Chain [1] done processing
09:43:26 - cmdstanpy - INFO - Chain [1] start processing
09:43:26 - cmdstanpy - INFO - Chain [1] done processing
09:43:27 - cmdstanpy - INFO - Chain [1] start processing
09:43:27 - cmdstanpy - INFO - Chain [1] done processing
09:43:28 - cmdstanpy - INFO - Chain [1] start processing
09:43:28 - cmdstanpy - INFO - Chain [1] done processing
09:43:28 - cmdstanpy - INFO - Chain [1] start processing
09:43:29 - cmdstanpy - INFO - Chain [1] done processing
09:43:29 - cmdstanpy - INFO - Chain [1] start processing
09:43:29 - cmdstanpy - INFO - Chain [1] done processing
09:43:30 - cmdstanpy - INFO - Chain [1] start processing
09:43:30 - cmdstanpy - INFO - Chain [1] done processing
09:43:31 - cmdstanpy - INFO - Chain [1] start processing
09:43:31 - cmdstanpy - INFO - Chain [1] done processing
09:43:31 - cmdstanpy - INFO - Chain [1] start processing
09:43:32 - cmdstanpy - INFO - Chain [1] done processing
09:43:32 - cmdstanpy - INFO - Chain [1] start processing
09:43:32 - cmdstanpy - INFO - Chain [1] done processing
09:43:33 - cmdstanpy - INFO - Chain [1] start processing
09:43:33 - cmdstanpy - INFO - Chain [1] done processing

      fold       rmse      mape
0        0  11.470459  0.156538
1        1  12.674496  0.209585
2        2  10.406042  0.147927
3        3  14.667749  0.144359
4        4  13.314868  0.122128
5        5  18.357560  0.175779
6        6  14.774495  0.138124
7        7  13.236853  0.123056
8        8  13.352367  0.181920
9        9  11.193110  0.125593
10      10  17.241975  0.135462
11      11  12.412551  0.153388
12      12  14.535670  0.113468
13      13  12.366429  0.137606
14      14  13.215251  0.105376
15      15  11.433035  0.127730
16      16  14.890073  0.210483
17      17  10.312960  0.153641
18      18   9.192388  0.148747
19      19  11.408017  0.250945
20      20   9.787018  0.219728
21      21  19.283598  0.645493
22      22  17.136011  0.378714
23      23  13.309503  0.251642
24      24  10.319884  0.203874
25      25   9.141741  0.182631
mean  mean  13.055158  0.190151

The results here should be very similar to the ones found in 1modeling_experiments.ipynb.

# Neural Prophet

## Import Packages

In [17]:
np.NaN = np.nan


# the following packages are meant to turn off a bunch of the warnings and ERRORs that pop up while running NeuralProphet.
# the errors that do show up are not all that important and a lot is due to outdated packages.
import warnings
import logging

warnings.filterwarnings("ignore")

logging.getLogger("neuralprophet").setLevel(logging.ERROR)
logging.getLogger("pytorch_lightning").setLevel(logging.ERROR)
logging.getLogger("NP").setLevel(logging.ERROR)

## Import Data

In [18]:
rs = pd.read_csv('../../scr/data/cleaned_rat_sightings_data/all_cleaned_rat_sightings.csv')
rs['created_date'] = pd.to_datetime(rs['created_date']) 
rs['closed_date'] = pd.to_datetime(rs['closed_date'])
rs['resolution_action_updated_date'] = pd.to_datetime(rs['resolution_action_updated_date'])
# mark cutoff dates, and also rename columns
rs = rs[rs['created_date']<'2025-03-01']
rs = rs[rs['created_date']>='2020-01-01']
rs = rs.groupby([rs['created_date'].dt.date]).size().reset_index(name='count')
rs.rename(columns={'created_date': 'ds', 'count': 'y'}, inplace=True)

In [19]:
## Add weather data.
import requests

lat, lon = 40.7831, -73.9712
start = "2020-01-01"
end   = "2025-02-28"

url = (
    "https://archive-api.open-meteo.com/v1/archive"
    f"?latitude={lat}&longitude={lon}"
    f"&start_date={start}&end_date={end}"
    "&daily=temperature_2m_max,temperature_2m_min,temperature_2m_mean,"
    "apparent_temperature_max,apparent_temperature_min,apparent_temperature_mean,"
    "precipitation_sum,snowfall_sum"
    "&timezone=America/New_York"
)

response = requests.get(url)
data = response.json()

if 'error' in data:
    nd = pd.read_csv("weatherdata.csv")
    nd = nd.set_index('date')
    wd = nd
    
else:
    wd = pd.DataFrame(data["daily"])
    wd["date"] = pd.to_datetime(wd["time"])
    wd = wd.set_index("date")

## Optuna for Hyperparameter Tuning for Neural Prophet

Uncomment the following codeblock if one wants to attempt to optimize the hyperparameters again!

In [ ]:
# Suppress cmdstanpy info logs
logging.getLogger("cmdstanpy").setLevel(logging.WARNING)


regressed_features = ['apparent_temperature_max', 'apparent_temperature_min', 'snowfall_sum']


wd = wd.reset_index(drop=True).rename(columns={"time": "ds"})
wd["ds"] = pd.to_datetime(wd["ds"])
rs["ds"] = pd.to_datetime(rs["ds"])

rs = rs.merge(
    wd[['ds'] + regressed_features],
    on="ds",
    how="left"
)

tscv = TimeSeriesSplit(gap=0, max_train_size=None, n_splits=2, test_size=14)


def objective(trial):
    regressor_lags = {
        'apparent_temperature_max': trial.suggest_int('lag_temp_max', 1, 30),
        'apparent_temperature_min': trial.suggest_int('lag_temp_min', 1, 30),
        'snowfall_sum': trial.suggest_int('lag_snowfall', 1, 7),
    }
    n_lags = trial.suggest_int('n_lags', 1, 21)
    epochs = trial.suggest_int('epochs', 50, 200)
    learning_rate = trial.suggest_float('learning_rate', 0.001, 0.5, log=True)
    batch_size = trial.suggest_int('batch_size', 20, 128)
    ar_reg = trial.suggest_float('ar_reg', 0.5, 3)
    fold_rmses = []
    for i, (train_idx, test_idx) in enumerate(tscv.split(rs)):

        train = rs.iloc[train_idx].copy()
        test = rs.iloc[test_idx].copy()
        
        existing_regressors = [col for col in regressed_features if col in train.columns]
        train = train.dropna(subset=["y"] + existing_regressors)
        test = test.dropna(subset=existing_regressors)
        
        # Skip fold if too few rows
        if len(train) < 20 or len(test) < 1:
            continue
        
        model = NeuralProphet(
            yearly_seasonality=True,
            weekly_seasonality=True,
            n_lags=n_lags,
            epochs=epochs,
            ar_reg = ar_reg,
            accelerator="auto",   # uses GPU if available
            learning_rate=learning_rate,
            batch_size=batch_size
        )
        model.add_country_holidays(country_name="US")
        for col in existing_regressors:
            model.add_lagged_regressor(col, n_lags=regressor_lags[col])
        
        model.fit(train, freq="D", progress="off")
        future = pd.concat([
            train[['ds','y'] + existing_regressors],
            test[['ds','y']].merge(wd[['ds'] + existing_regressors], on="ds", how="left")
        ])
        future = future.dropna(subset=existing_regressors)
        forecast = model.predict(future)
        
        y_pred = forecast["yhat1"].iloc[-len(test):].values
        y_true = test["y"].values
        
        rmse = np.sqrt(mean_squared_error(y_true, y_pred))
        fold_rmses.append(rmse)

        intermediate_score = np.mean(fold_rmses)
        trial.report(intermediate_score, i)
        if trial.should_prune():
            raise optuna.TrialPruned()
        
    return np.mean(fold_rmses) if fold_rmses else float("inf")

study = optuna.create_study(direction="minimize")
study.optimize(objective, n_trials=25)  # adjust n_trials as needed



best_params = study.best_params

[I 2026-03-14 09:46:41,192] A new study created in memory with name: no-name-3b5da4f1-d2c3-4f27-9b35-76597d570e2d

Training: 0it [00:00, ?it/s]

Predicting: 20it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 20it [00:00, ?it/s]

[I 2026-03-14 09:49:07,978] Trial 0 finished with value: 12.635105051250957 and parameters: {'lag_temp_max': 28, 'lag_temp_min': 6, 'lag_snowfall': 7, 'n_lags': 2, 'epochs': 100, 'learning_rate': 0.0012743321911794351, 'batch_size': 96, 'ar_reg': 1.1473229025979839}. Best is trial 0 with value: 12.635105051250957.

Training: 0it [00:00, ?it/s]

Predicting: 16it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 16it [00:00, ?it/s]

[I 2026-03-14 09:53:25,544] Trial 1 finished with value: 16.843230720342813 and parameters: {'lag_temp_max': 12, 'lag_temp_min': 19, 'lag_snowfall': 1, 'n_lags': 10, 'epochs': 197, 'learning_rate': 0.002721394636001311, 'batch_size': 117, 'ar_reg': 1.2613126902689917}. Best is trial 0 with value: 12.635105051250957.

Training: 0it [00:00, ?it/s]

Predicting: 17it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 17it [00:00, ?it/s]

[I 2026-03-14 09:57:43,067] Trial 2 finished with value: 7.910250172749286 and parameters: {'lag_temp_max': 28, 'lag_temp_min': 13, 'lag_snowfall': 4, 'n_lags': 6, 'epochs': 169, 'learning_rate': 0.20414859784806372, 'batch_size': 111, 'ar_reg': 2.1899886187516535}. Best is trial 2 with value: 7.910250172749286.

Training: 0it [00:00, ?it/s]

Predicting: 26it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 27it [00:00, ?it/s]

[I 2026-03-14 10:00:00,506] Trial 3 finished with value: 8.300783370492109 and parameters: {'lag_temp_max': 8, 'lag_temp_min': 17, 'lag_snowfall': 7, 'n_lags': 3, 'epochs': 55, 'learning_rate': 0.04161511259627139, 'batch_size': 71, 'ar_reg': 2.495578694650514}. Best is trial 2 with value: 7.910250172749286.

Training: 0it [00:00, ?it/s]

Predicting: 23it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 23it [00:00, ?it/s]

[I 2026-03-14 10:06:40,922] Trial 4 finished with value: 8.855220435175202 and parameters: {'lag_temp_max': 2, 'lag_temp_min': 22, 'lag_snowfall': 6, 'n_lags': 12, 'epochs': 150, 'learning_rate': 0.2850076099491535, 'batch_size': 82, 'ar_reg': 1.591522449413616}. Best is trial 2 with value: 7.910250172749286.

Training: 0it [00:00, ?it/s]

Predicting: 25it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 25it [00:00, ?it/s]

[I 2026-03-14 10:12:31,011] Trial 5 finished with value: 8.201098113684637 and parameters: {'lag_temp_max': 27, 'lag_temp_min': 19, 'lag_snowfall': 4, 'n_lags': 11, 'epochs': 90, 'learning_rate': 0.059995456756848614, 'batch_size': 74, 'ar_reg': 2.733536338463585}. Best is trial 2 with value: 7.910250172749286.

Training: 0it [00:00, ?it/s]

Predicting: 26it [00:00, ?it/s]

[I 2026-03-14 10:15:13,824] Trial 6 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 28it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 28it [00:00, ?it/s]

[I 2026-03-14 10:23:26,547] Trial 7 finished with value: 7.837832144125411 and parameters: {'lag_temp_max': 6, 'lag_temp_min': 16, 'lag_snowfall': 7, 'n_lags': 12, 'epochs': 175, 'learning_rate': 0.02082295286498502, 'batch_size': 67, 'ar_reg': 2.7870067936345633}. Best is trial 7 with value: 7.837832144125411.

Training: 0it [00:00, ?it/s]

Predicting: 15it [00:00, ?it/s]

[I 2026-03-14 10:24:54,806] Trial 8 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 15it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 15it [00:00, ?it/s]

[I 2026-03-14 10:31:17,696] Trial 9 finished with value: 11.618198997799375 and parameters: {'lag_temp_max': 3, 'lag_temp_min': 7, 'lag_snowfall': 5, 'n_lags': 19, 'epochs': 199, 'learning_rate': 0.001942795327574699, 'batch_size': 128, 'ar_reg': 2.4963155658932297}. Best is trial 7 with value: 7.837832144125411.

Training: 0it [00:00, ?it/s]

Predicting: 54it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 0it [00:00, ?it/s]

[I 2026-03-14 10:36:46,892] Trial 10 pruned.

Training: 0it [00:00, ?it/s]

In [ ]:
print("Best Parameters", best_params)
print("Best RMSE:", study.best_value)

We ran an initialize Optuna hyperparameter tunning to get some ideal of what the optimal choices for lags would be. To speed up the process, we chose to use n_splits = 2 and training_size = 14. We also set n_trials to 25. More robust tuning can be found in 4tune.ipynb. Explanations for the feature choices can be found in another notebook.
Recorded below the best parameters we found after a 3 hour run of the previous code.

In [ ]:
# best_params =  {'lag_temp_max': 30, 'lag_temp_min': 5, 'lag_snowfall': 1, 'n_lags': 16, 'epochs': 60, 'learning_rate': 0.2986532324899507, 'batch_size': 128, 'ar_reg': 2.132925719127823}

## Walkforward Cross-validation for NeuralProphet

In [19]:
rs = pd.read_csv('../../scr/data/cleaned_rat_sightings_data/all_cleaned_rat_sightings.csv')
rs['created_date'] = pd.to_datetime(rs['created_date']) 
rs['closed_date'] = pd.to_datetime(rs['closed_date'])
rs['resolution_action_updated_date'] = pd.to_datetime(rs['resolution_action_updated_date'])
# mark cutoff dates, and also rename columns
rs = rs[rs['created_date']<'2025-03-01']
rs = rs[rs['created_date']>='2020-01-01']
rs = rs.groupby([rs['created_date'].dt.date]).size().reset_index(name='count')
rs.rename(columns={'created_date': 'ds', 'count': 'y'}, inplace=True)

## Add weather data.
import requests

lat, lon = 40.7831, -73.9712
start = "2020-01-01"
end   = "2025-02-28"

url = (
    "https://archive-api.open-meteo.com/v1/archive"
    f"?latitude={lat}&longitude={lon}"
    f"&start_date={start}&end_date={end}"
    "&daily=temperature_2m_max,temperature_2m_min,temperature_2m_mean,"
    "apparent_temperature_max,apparent_temperature_min,apparent_temperature_mean,"
    "precipitation_sum,snowfall_sum"
    "&timezone=America/New_York"
)

response = requests.get(url)
data = response.json()


if 'error' in data:
    nd = pd.read_csv("weatherdata.csv")
    nd = nd.set_index('date')
    wd = nd
    
else:
    wd = pd.DataFrame(data["daily"])
    wd["date"] = pd.to_datetime(wd["time"])
    wd = wd.set_index("date")

In [ ]:
tscv = TimeSeriesSplit(gap=0, max_train_size=None, n_splits=26, test_size=14)

regressed_features = ['apparent_temperature_max', 'apparent_temperature_min','snowfall_sum']


wd = wd.reset_index(drop=True).rename(columns={"time": "ds"})
wd["ds"] = pd.to_datetime(wd["ds"])
rs["ds"] = pd.to_datetime(rs["ds"])

rs = rs.merge(
    wd[['ds'] + regressed_features],
    on="ds",
    how="left"
)

lags_for_regressed_features = dict()
lags_for_regressed_features['apparent_temperature_max'] = best_params['lag_temp_max']
lags_for_regressed_features['apparent_temperature_min'] = best_params['lag_temp_min']
lags_for_regressed_features['snowfall_sum'] = best_params['lag_snowfall']


results = []

for i, (train_index, test_index) in enumerate(tscv.split(rs)):

    train = rs.iloc[train_index].copy()
    train = train.dropna(subset=["y"])

    test = rs.iloc[test_index].copy()


    model = NeuralProphet(yearly_seasonality=True, 
                          weekly_seasonality=True, 
                          learning_rate = best_params['learning_rate'],
                          epochs = best_params['epochs'],
                          n_lags= best_params['n_lags'],
                          ar_reg=best_params['ar_reg'],
                          accelerator="auto",   # uses GPU if available
                          batch_size= best_params['batch_size']
                          )
    model = model.add_country_holidays(country_name="US")
    for column in regressed_features:
        model.add_lagged_regressor(column, n_lags=lags_for_regressed_features[column])
        
    model.fit(train, freq="D", progress="off")

    # build dataframe containing future regressors
    future = pd.concat([train[['ds','y'] + regressed_features], test[['ds','y']].merge(wd[['ds'] + regressed_features], on="ds", how="left")])
    forecast = model.predict(future)

    y_pred = forecast["yhat1"].iloc[-len(test):].values
    y_true = test["y"].values

    rmse = np.sqrt(mean_squared_error(y_true, y_pred))
    mape = mean_absolute_percentage_error(y_true, y_pred)

    results.append({"fold": i, "rmse": rmse, "mape": mape})

Training: 0it [00:00, ?it/s]

Predicting: 12it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 12it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 12it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 12it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 13it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 13it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 13it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 13it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 13it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 13it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 13it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 13it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 13it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 14it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 14it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 14it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 14it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 14it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 14it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 14it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 14it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 14it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 15it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 15it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 15it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 15it [00:00, ?it/s]

      fold       rmse      mape
0        0   9.932557  0.149994
1        1  12.462153  0.209307
2        2  10.594196  0.149988
3        3  15.425828  0.184719
4        4  11.850922  0.113024
5        5  14.020658  0.129323
6        6  15.765160  0.166797
7        7  14.642460  0.127769
8        8   9.026603  0.108886
9        9  10.409399  0.092136
10      10  14.523203  0.125219
11      11  15.166935  0.167318
12      12  11.737397  0.097297
13      13  15.396651  0.184740
14      14  13.830072  0.129025
15      15  10.631022  0.120095
16      16  14.033746  0.189070
17      17   8.186863  0.125155
18      18  11.204081  0.158053
19      19  10.401198  0.224283
20      20   9.946923  0.231014
21      21  12.709663  0.425180
22      22  11.808182  0.258707
23      23  11.782814  0.235368
24      24   7.844580  0.161331
25      25   6.498899  0.117312
mean  mean  11.916622  0.168504

In [24]:
neural_prophet_results_df = pd.DataFrame(results)
neural_prophet_results_df.loc["mean"] = ["mean", neural_prophet_results_df["rmse"].mean(), neural_prophet_results_df["mape"].mean()]
neural_prophet_results_df

      fold       rmse      mape
0        0   9.932557  0.149994
1        1  12.462153  0.209307
2        2  10.594196  0.149988
3        3  15.425828  0.184719
4        4  11.850922  0.113024
5        5  14.020658  0.129323
6        6  15.765160  0.166797
7        7  14.642460  0.127769
8        8   9.026603  0.108886
9        9  10.409399  0.092136
10      10  14.523203  0.125219
11      11  15.166935  0.167318
12      12  11.737397  0.097297
13      13  15.396651  0.184740
14      14  13.830072  0.129025
15      15  10.631022  0.120095
16      16  14.033746  0.189070
17      17   8.186863  0.125155
18      18  11.204081  0.158053
19      19  10.401198  0.224283
20      20   9.946923  0.231014
21      21  12.709663  0.425180
22      22  11.808182  0.258707
23      23  11.782814  0.235368
24      24   7.844580  0.161331
25      25   6.498899  0.117312
mean  mean  11.916622  0.168504

An average RMSE of 11.9166 for NeuralProphet is a slight improvement over Prophet's RMSE of 12.681.

## Train the Model

In [ ]:
rs = pd.read_csv('../../scr/data/cleaned_rat_sightings_data/all_cleaned_rat_sightings.csv')
rs['created_date'] = pd.to_datetime(rs['created_date']) 
rs['closed_date'] = pd.to_datetime(rs['closed_date'])
rs['resolution_action_updated_date'] = pd.to_datetime(rs['resolution_action_updated_date'])
# mark cutoff dates, and also rename columns
rs = rs[rs['created_date']>='2020-01-01']
rs = rs.groupby([rs['created_date'].dt.date]).size().reset_index(name='count')
rs.rename(columns={'created_date': 'ds', 'count': 'y'}, inplace=True)

# Weather data
# The forecasted weather values are the naive forecast i.e. we take the last observed day and assume that these are good predictions for the next 14 days.
# Better weather data might help improve the model.

lat, lon = 40.7831, -73.9712
last_date = rs['ds'].max()
start = "2020-01-01"
end   = last_date.strftime("%Y-%m-%d")  # use last date of rs

url = (
    "https://archive-api.open-meteo.com/v1/archive"
    f"?latitude={lat}&longitude={lon}"
    f"&start_date={start}&end_date={end}"
    "&daily=temperature_2m_max,temperature_2m_min,temperature_2m_mean,"
    "apparent_temperature_max,apparent_temperature_min,apparent_temperature_mean,"
    "precipitation_sum,snowfall_sum"
    "&timezone=America/New_York"
)

response = requests.get(url)
data = response.json()

if 'error' in data:
    nd = pd.read_csv("weatherdata.csv")
    nd['ds'] = pd.to_datetime(nd['date'])
    wd = nd.drop(columns=['date'])
else:
    wd = pd.DataFrame(data["daily"])
    wd["ds"] = pd.to_datetime(wd["time"])
    wd = wd.drop(columns=["time"])

wd = wd.reset_index(drop=True)
future_dates = pd.date_range(start=last_date + pd.Timedelta(days=1),
                             periods=14,
                             freq='D')

last_row = wd.iloc[-1]
wd_14 = pd.DataFrame([last_row.values] * 14, columns=wd.columns)
wd_14['ds'] = future_dates 
wd_14 = wd_14.reset_index(drop=True)




tscv = TimeSeriesSplit(gap=0, max_train_size=None, n_splits=26, test_size=14)

regressed_features = ['apparent_temperature_max', 'apparent_temperature_min','snowfall_sum']


wd = wd.reset_index(drop=True).rename(columns={"time": "ds"})
wd["ds"] = pd.to_datetime(wd["ds"])
rs["ds"] = pd.to_datetime(rs["ds"])

rs = rs.merge(
    wd[['ds'] + regressed_features],
    on="ds",
    how="left"
)

lags_for_regressed_features = dict()
lags_for_regressed_features['apparent_temperature_max'] = best_params['lag_temp_max']
lags_for_regressed_features['apparent_temperature_min'] = best_params['lag_temp_min']
lags_for_regressed_features['snowfall_sum'] = best_params['lag_snowfall']

In [21]:
model = NeuralProphet(yearly_seasonality=True, 
                          weekly_seasonality=True, 
                          batch_size = best_params['batch_size'],
                          ar_reg=best_params['ar_reg'],
                          learning_rate = best_params['learning_rate'],
                          epochs = best_params['epochs'],
                          n_lags= best_params['n_lags']
                          )
model = model.add_country_holidays(country_name="US")
for column in regressed_features:
    model.add_lagged_regressor(column, n_lags=lags_for_regressed_features[column])
        
model.fit(rs, freq="D", progress="off")

new_rs = rs.copy()

new_rs = new_rs.drop(columns=['y'])

forecast = model.predict(rs)

Training: 0it [00:00, ?it/s]

Predicting: 15it [00:00, ?it/s]

## Plots and Evaluation of the Model

In [22]:
model.plot(forecast)

ERROR - (NP.plotly.plot) - plotly-resampler is not installed. Please install it to use the resampler.

In [23]:
model.plot_parameters()

ERROR - (NP.plotly.plot_parameters) - plotly-resampler is not installed. Please install it to use the resampler.