In the previous notebook 1models_citywide.ipynb, we found that the Prophet and Prophet+XGBoost models performed well in terms of forecasting rat sightings by day citywide. Since a Prophet+XGBoost model is an upgrade to the Prophet model, we also consider the NeuralProphet model to see if it provides any improvements. In this notebook, we will do some more feature engineering and hyperparameter tuning to determine which is a more satisfactory model.

Our work in tuning and training the XGBoosted Prophet model can be found in the notebook 4.0XGBoosted_Prophet.

This notebook will have Prophet and NeuralProphet

# Import Packages

In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import datetime

from sklearn.model_selection import TimeSeriesSplit
from sklearn.metrics import mean_squared_error, mean_absolute_percentage_error
from sklearn.linear_model import LinearRegression

from prophet import Prophet
from pandas.tseries.holiday import USFederalHolidayCalendar
from prophet.diagnostics import cross_validation, performance_metrics
from prophet.plot import plot_cross_validation_metric
from prophet.plot import add_changepoints_to_plot
from prophet.plot import plot_plotly, plot_components_plotly
import itertools

import warnings
from statsmodels.tools.sm_exceptions import ConvergenceWarning
warnings.simplefilter('ignore', ConvergenceWarning)

import optuna
from neuralprophet import NeuralProphet
import logging

# Prophet

## Import the data

In [4]:
# this is the time series split we will work with
tscv = TimeSeriesSplit(gap=0, max_train_size=None, n_splits=26, test_size=14)


# we import the data and clean it for future use
rs = pd.read_csv('../../scr/data/cleaned_rat_sightings_data/all_cleaned_rat_sightings.csv')
rs['created_date'] = pd.to_datetime(rs['created_date']) 
rs['closed_date'] = pd.to_datetime(rs['closed_date'])
rs['resolution_action_updated_date'] = pd.to_datetime(rs['resolution_action_updated_date'])
# mark cutoff dates, and also rename columns
rs = rs[rs['created_date']<'2025-03-01']
rs = rs[rs['created_date']>='2020-01-01']
rs = rs.groupby([rs['created_date'].dt.date]).size().reset_index(name='count')
rs.rename(columns={'created_date': 'ds', 'count': 'y'}, inplace=True)

## Prepare Prophet

In [5]:
date_range = pd.date_range(start="2020-01-01", end="2025-02-28")

# Generate US federal holidays
calendar = USFederalHolidayCalendar()
holidays = calendar.holidays(start=date_range.min(), end=date_range.max())

federal_holidays = pd.DataFrame({
    'holiday': 'federal_us',
    'ds': pd.to_datetime(holidays),
    'lower_window': 0,
    'upper_window': 1})

holidays = federal_holidays

In [6]:
rs_saved = rs.copy()
df = rs.copy()

## Walkforward Cross-validation for Prophet

In [7]:
# this is the time series split we will work with
tscv = TimeSeriesSplit(gap=0, max_train_size=None, n_splits=26, test_size=14)


# we import the data and clean it for future use
rs = pd.read_csv('../../scr/data/cleaned_rat_sightings_data/all_cleaned_rat_sightings.csv')
rs['created_date'] = pd.to_datetime(rs['created_date']) 
# mark cutoff dates, and also rename columns
rs = rs[rs['created_date']<'2025-03-01']
rs = rs[rs['created_date']>='2020-01-01']
rs = rs.groupby([rs['created_date'].dt.date]).size().reset_index(name='count')
rs.rename(columns={'created_date': 'ds', 'count': 'y'}, inplace=True)

date_range = pd.date_range(start="2020-01-01", end="2025-02-28")

# Generate US federal holidays
calendar = USFederalHolidayCalendar()
holidays = calendar.holidays(start=date_range.min(), end=date_range.max())

federal_holidays = pd.DataFrame({
    'holiday': 'federal_us',
    'ds': pd.to_datetime(holidays),
    'lower_window': 0,
    'upper_window': 1})

holidays = federal_holidays

In [8]:
# Rename columns for Prophet model
rs.rename(columns={'created_date': 'ds', 'count': 'y'}, inplace=True)
results = []

for i, (train_index, test_index) in enumerate(tscv.split(rs)):
    train = rs.iloc[train_index]
    test = rs.iloc[test_index]
    
    model = Prophet(holidays=holidays)
    model.add_country_holidays(country_name='US')

    model.fit(train)
    
    future = model.make_future_dataframe(periods=len(test), freq='D')
    forecast = model.predict(future)
    
    # Obtain predicted values and compare against the actuals.
    y_pred = forecast['yhat'][-len(test):].values
    y_pred = np.round(y_pred)
    y_true = test['y'].values
    
    rmse = np.sqrt(mean_squared_error(y_true, y_pred))
    mape = mean_absolute_percentage_error(y_true, y_pred)
    
    # Append results
    results.append({'fold': i, 'rmse': rmse, 'mape': mape})

prophet_results_df = pd.DataFrame(results)
prophet_results_df.loc['mean'] = ['mean',  prophet_results_df['rmse'].mean(), prophet_results_df['mape'].mean()]
prophet_results_df

10:45:39 - cmdstanpy - INFO - Chain [1] start processing
10:45:40 - cmdstanpy - INFO - Chain [1] done processing
10:45:40 - cmdstanpy - INFO - Chain [1] start processing
10:45:40 - cmdstanpy - INFO - Chain [1] done processing
10:45:41 - cmdstanpy - INFO - Chain [1] start processing
10:45:41 - cmdstanpy - INFO - Chain [1] done processing
10:45:42 - cmdstanpy - INFO - Chain [1] start processing
10:45:42 - cmdstanpy - INFO - Chain [1] done processing
10:45:43 - cmdstanpy - INFO - Chain [1] start processing
10:45:43 - cmdstanpy - INFO - Chain [1] done processing
10:45:44 - cmdstanpy - INFO - Chain [1] start processing
10:45:44 - cmdstanpy - INFO - Chain [1] done processing
10:45:44 - cmdstanpy - INFO - Chain [1] start processing
10:45:45 - cmdstanpy - INFO - Chain [1] done processing
10:45:45 - cmdstanpy - INFO - Chain [1] start processing
10:45:45 - cmdstanpy - INFO - Chain [1] done processing
10:45:46 - cmdstanpy - INFO - Chain [1] start processing
10:45:46 - cmdstanpy - INFO - Chain [1] done processing
10:45:47 - cmdstanpy - INFO - Chain [1] start processing
10:45:47 - cmdstanpy - INFO - Chain [1] done processing
10:45:48 - cmdstanpy - INFO - Chain [1] start processing
10:45:48 - cmdstanpy - INFO - Chain [1] done processing
10:45:49 - cmdstanpy - INFO - Chain [1] start processing
10:45:49 - cmdstanpy - INFO - Chain [1] done processing
10:45:49 - cmdstanpy - INFO - Chain [1] start processing
10:45:50 - cmdstanpy - INFO - Chain [1] done processing
10:45:50 - cmdstanpy - INFO - Chain [1] start processing
10:45:50 - cmdstanpy - INFO - Chain [1] done processing
10:45:51 - cmdstanpy - INFO - Chain [1] start processing
10:45:51 - cmdstanpy - INFO - Chain [1] done processing
10:45:52 - cmdstanpy - INFO - Chain [1] start processing
10:45:52 - cmdstanpy - INFO - Chain [1] done processing
10:45:53 - cmdstanpy - INFO - Chain [1] start processing
10:45:53 - cmdstanpy - INFO - Chain [1] done processing
10:45:53 - cmdstanpy - INFO - Chain [1] start processing
10:45:54 - cmdstanpy - INFO - Chain [1] done processing
10:45:54 - cmdstanpy - INFO - Chain [1] start processing
10:45:54 - cmdstanpy - INFO - Chain [1] done processing
10:45:55 - cmdstanpy - INFO - Chain [1] start processing
10:45:55 - cmdstanpy - INFO - Chain [1] done processing
10:45:56 - cmdstanpy - INFO - Chain [1] start processing
10:45:56 - cmdstanpy - INFO - Chain [1] done processing
10:45:57 - cmdstanpy - INFO - Chain [1] start processing
10:45:57 - cmdstanpy - INFO - Chain [1] done processing
10:45:58 - cmdstanpy - INFO - Chain [1] start processing
10:45:58 - cmdstanpy - INFO - Chain [1] done processing
10:45:59 - cmdstanpy - INFO - Chain [1] start processing
10:45:59 - cmdstanpy - INFO - Chain [1] done processing
10:46:00 - cmdstanpy - INFO - Chain [1] start processing
10:46:00 - cmdstanpy - INFO - Chain [1] done processing
10:46:00 - cmdstanpy - INFO - Chain [1] start processing
10:46:01 - cmdstanpy - INFO - Chain [1] done processing

      fold       rmse      mape
0        0  11.373528  0.155572
1        1  12.674496  0.209585
2        2  10.406042  0.147927
3        3  14.904458  0.145775
4        4  13.349692  0.123262
5        5  18.375061  0.176610
6        6  14.577380  0.135599
7        7  13.274573  0.124853
8        8  13.296079  0.181355
9        9  11.237692  0.126173
10      10  17.177643  0.134621
11      11  12.558435  0.156107
12      12  14.640941  0.115763
13      13  12.264933  0.136724
14      14  13.215251  0.105376
15      15  11.433035  0.127730
16      16  14.902061  0.211884
17      17  10.312960  0.153641
18      18   9.114353  0.145503
19      19  11.643514  0.250326
20      20   9.859731  0.222433
21      21  19.283598  0.645493
22      22  17.136011  0.378714
23      23  13.443001  0.251439
24      24  10.319884  0.203874
25      25   9.238893  0.184511
mean  mean  13.077432  0.190417

The results here should be very similar to the ones found in 1modeling_experiments.ipynb.

# Neural Prophet

## Import Packages

In [9]:
np.NaN = np.nan


# the following packages are meant to turn off a bunch of the warnings and ERRORs that pop up while running NeuralProphet.
# the errors that do show up are not all that important and a lot is due to outdated packages.
import warnings
import logging

warnings.filterwarnings("ignore")

logging.getLogger("neuralprophet").setLevel(logging.ERROR)
logging.getLogger("pytorch_lightning").setLevel(logging.ERROR)
logging.getLogger("NP").setLevel(logging.ERROR)

## Import Data

In [10]:
rs = pd.read_csv('../../scr/data/cleaned_rat_sightings_data/all_cleaned_rat_sightings.csv')
rs['created_date'] = pd.to_datetime(rs['created_date']) 
rs['closed_date'] = pd.to_datetime(rs['closed_date'])
rs['resolution_action_updated_date'] = pd.to_datetime(rs['resolution_action_updated_date'])
# mark cutoff dates, and also rename columns
rs = rs[rs['created_date']<'2025-03-01']
rs = rs[rs['created_date']>='2020-01-01']
rs = rs.groupby([rs['created_date'].dt.date]).size().reset_index(name='count')
rs.rename(columns={'created_date': 'ds', 'count': 'y'}, inplace=True)

In [11]:
## Add weather data.
import requests

lat, lon = 40.7831, -73.9712
start = "2020-01-01"
end   = "2025-02-28"

url = (
    "https://archive-api.open-meteo.com/v1/archive"
    f"?latitude={lat}&longitude={lon}"
    f"&start_date={start}&end_date={end}"
    "&daily=temperature_2m_max,temperature_2m_min,temperature_2m_mean,"
    "apparent_temperature_max,apparent_temperature_min,apparent_temperature_mean,"
    "precipitation_sum,snowfall_sum"
    "&timezone=America/New_York"
)

response = requests.get(url)
data = response.json()

if 'error' in data:
    nd = pd.read_csv("weatherdata.csv")
    nd = nd.set_index('date')
    wd = nd
    
else:
    wd = pd.DataFrame(data["daily"])
    wd["date"] = pd.to_datetime(wd["time"])
    wd = wd.set_index("date")

## Optuna for Hyperparameter Tuning for Neural Prophet

Uncomment the following codeblock if one wants to attempt to optimize the hyperparameters again!

In [12]:
# Suppress cmdstanpy info logs
logging.getLogger("cmdstanpy").setLevel(logging.WARNING)


regressed_features = ['apparent_temperature_max', 'apparent_temperature_min', 'snowfall_sum']


wd = wd.reset_index(drop=True).rename(columns={"time": "ds"})
wd["ds"] = pd.to_datetime(wd["ds"])
rs["ds"] = pd.to_datetime(rs["ds"])

rs = rs.merge(
    wd[['ds'] + regressed_features],
    on="ds",
    how="left"
)

tscv = TimeSeriesSplit(gap=0, max_train_size=None, n_splits=2, test_size=14)


def objective(trial):
    regressor_lags = {
        'apparent_temperature_max': trial.suggest_int('lag_temp_max', 1, 30),
        'apparent_temperature_min': trial.suggest_int('lag_temp_min', 1, 30),
        'snowfall_sum': trial.suggest_int('lag_snowfall', 1, 7),
    }
    n_lags = trial.suggest_int('n_lags', 1, 21)
    epochs = trial.suggest_int('epochs', 50, 200)
    learning_rate = trial.suggest_float('learning_rate', 0.001, 0.5, log=True)
    batch_size = trial.suggest_int('batch_size', 20, 128)
    ar_reg = trial.suggest_float('ar_reg', 0.5, 3)
    fold_rmses = []
    for i, (train_idx, test_idx) in enumerate(tscv.split(rs)):

        train = rs.iloc[train_idx].copy()
        test = rs.iloc[test_idx].copy()
        
        existing_regressors = [col for col in regressed_features if col in train.columns]
        train = train.dropna(subset=["y"] + existing_regressors)
        test = test.dropna(subset=existing_regressors)
        
        # Skip fold if too few rows
        if len(train) < 20 or len(test) < 1:
            continue
        
        model = NeuralProphet(
            yearly_seasonality=True,
            weekly_seasonality=True,
            n_lags=n_lags,
            epochs=epochs,
            ar_reg = ar_reg,
            accelerator="auto",   # uses GPU if available
            learning_rate=learning_rate,
            batch_size=batch_size
        )
        model.add_country_holidays(country_name="US")
        for col in existing_regressors:
            model.add_lagged_regressor(col, n_lags=regressor_lags[col])
        
        model.fit(train, freq="D", progress="off")
        future = pd.concat([
            train[['ds','y'] + existing_regressors],
            test[['ds','y']].merge(wd[['ds'] + existing_regressors], on="ds", how="left")
        ])
        future = future.dropna(subset=existing_regressors)
        forecast = model.predict(future)
        
        y_pred = forecast["yhat1"].iloc[-len(test):].values
        y_true = test["y"].values
        
        rmse = np.sqrt(mean_squared_error(y_true, y_pred))
        fold_rmses.append(rmse)

        intermediate_score = np.mean(fold_rmses)
        trial.report(intermediate_score, i)
        if trial.should_prune():
            raise optuna.TrialPruned()
        
    return np.mean(fold_rmses) if fold_rmses else float("inf")

study = optuna.create_study(direction="minimize")
study.optimize(objective, n_trials=25)  # adjust n_trials as needed



best_params = study.best_params

[I 2026-03-14 10:46:04,356] A new study created in memory with name: no-name-dfafc5e0-c004-4f48-8a37-7fa25eaa5866

Training: 0it [00:00, ?it/s]

Predicting: 32it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 32it [00:00, ?it/s]

[I 2026-03-14 10:47:51,595] Trial 0 finished with value: 6.783658512258119 and parameters: {'lag_temp_max': 22, 'lag_temp_min': 18, 'lag_snowfall': 5, 'n_lags': 19, 'epochs': 160, 'learning_rate': 0.0150970404781446, 'batch_size': 58, 'ar_reg': 0.6113894062493148}. Best is trial 0 with value: 6.783658512258119.

Training: 0it [00:00, ?it/s]

Predicting: 24it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 24it [00:00, ?it/s]

[I 2026-03-14 10:49:04,965] Trial 1 finished with value: 11.430585677250168 and parameters: {'lag_temp_max': 24, 'lag_temp_min': 24, 'lag_snowfall': 2, 'n_lags': 11, 'epochs': 138, 'learning_rate': 0.004378814278650235, 'batch_size': 77, 'ar_reg': 2.1632811466982202}. Best is trial 0 with value: 6.783658512258119.

Training: 0it [00:00, ?it/s]

Predicting: 21it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 21it [00:00, ?it/s]

[I 2026-03-14 10:49:42,010] Trial 2 finished with value: 7.360186935241843 and parameters: {'lag_temp_max': 15, 'lag_temp_min': 23, 'lag_snowfall': 6, 'n_lags': 17, 'epochs': 74, 'learning_rate': 0.032062603745274115, 'batch_size': 89, 'ar_reg': 2.4436248523282735}. Best is trial 0 with value: 6.783658512258119.

Training: 0it [00:00, ?it/s]

Predicting: 20it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 20it [00:00, ?it/s]

[I 2026-03-14 10:51:04,459] Trial 3 finished with value: 9.236418917989418 and parameters: {'lag_temp_max': 4, 'lag_temp_min': 18, 'lag_snowfall': 7, 'n_lags': 1, 'epochs': 188, 'learning_rate': 0.006497136059819482, 'batch_size': 94, 'ar_reg': 0.9750352635678592}. Best is trial 0 with value: 6.783658512258119.

Training: 0it [00:00, ?it/s]

Predicting: 20it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 20it [00:00, ?it/s]

[I 2026-03-14 10:52:33,651] Trial 4 finished with value: 7.265675728111907 and parameters: {'lag_temp_max': 12, 'lag_temp_min': 18, 'lag_snowfall': 5, 'n_lags': 21, 'epochs': 189, 'learning_rate': 0.13264760441895904, 'batch_size': 94, 'ar_reg': 1.3802102289530864}. Best is trial 0 with value: 6.783658512258119.

Training: 0it [00:00, ?it/s]

Predicting: 16it [00:00, ?it/s]

[I 2026-03-14 10:53:01,054] Trial 5 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 74it [00:00, ?it/s]

[I 2026-03-14 10:54:05,025] Trial 6 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 38it [00:00, ?it/s]

[I 2026-03-14 10:55:04,166] Trial 7 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 16it [00:00, ?it/s]

[I 2026-03-14 10:55:25,892] Trial 8 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 22it [00:00, ?it/s]

[I 2026-03-14 10:56:00,973] Trial 9 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 36it [00:00, ?it/s]

[I 2026-03-14 10:56:20,035] Trial 10 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 31it [00:00, ?it/s]

[I 2026-03-14 10:57:18,717] Trial 11 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 18it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 19it [00:00, ?it/s]

[I 2026-03-14 10:58:23,424] Trial 12 finished with value: 7.351266901660504 and parameters: {'lag_temp_max': 24, 'lag_temp_min': 13, 'lag_snowfall': 5, 'n_lags': 16, 'epochs': 166, 'learning_rate': 0.16543541600168257, 'batch_size': 102, 'ar_reg': 0.5444134935430249}. Best is trial 0 with value: 6.783658512258119.

Training: 0it [00:00, ?it/s]

Predicting: 58it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 58it [00:00, ?it/s]

[I 2026-03-14 11:01:24,210] Trial 13 finished with value: 7.2252468861581 and parameters: {'lag_temp_max': 12, 'lag_temp_min': 8, 'lag_snowfall': 3, 'n_lags': 18, 'epochs': 183, 'learning_rate': 0.1086571969156734, 'batch_size': 32, 'ar_reg': 1.3640387311706985}. Best is trial 0 with value: 6.783658512258119.

Training: 0it [00:00, ?it/s]

Predicting: 71it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 72it [00:00, ?it/s]

[I 2026-03-14 11:04:47,235] Trial 14 finished with value: 6.900214271646496 and parameters: {'lag_temp_max': 20, 'lag_temp_min': 5, 'lag_snowfall': 3, 'n_lags': 14, 'epochs': 170, 'learning_rate': 0.012852043166001435, 'batch_size': 26, 'ar_reg': 0.9293966670736017}. Best is trial 0 with value: 6.783658512258119.

Training: 0it [00:00, ?it/s]

Predicting: 49it [00:00, ?it/s]

[I 2026-03-14 11:05:58,013] Trial 15 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 92it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 93it [00:00, ?it/s]

[I 2026-03-14 11:08:50,844] Trial 16 finished with value: 7.08156839153769 and parameters: {'lag_temp_max': 20, 'lag_temp_min': 6, 'lag_snowfall': 3, 'n_lags': 13, 'epochs': 115, 'learning_rate': 0.013368300880942145, 'batch_size': 20, 'ar_reg': 0.8582376744189699}. Best is trial 0 with value: 6.783658512258119.

Training: 0it [00:00, ?it/s]

Predicting: 29it [00:00, ?it/s]

[I 2026-03-14 11:09:33,440] Trial 17 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 43it [00:00, ?it/s]

[I 2026-03-14 11:10:18,440] Trial 18 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 27it [00:00, ?it/s]

[I 2026-03-14 11:11:01,919] Trial 19 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 56it [00:00, ?it/s]

[I 2026-03-14 11:12:11,226] Trial 20 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 74it [00:00, ?it/s]

[I 2026-03-14 11:13:14,216] Trial 21 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 92it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 93it [00:00, ?it/s]

[I 2026-03-14 11:16:13,574] Trial 22 finished with value: 7.018480904992289 and parameters: {'lag_temp_max': 18, 'lag_temp_min': 10, 'lag_snowfall': 3, 'n_lags': 14, 'epochs': 122, 'learning_rate': 0.009031204926929033, 'batch_size': 20, 'ar_reg': 0.7868843740376612}. Best is trial 0 with value: 6.783658512258119.

Training: 0it [00:00, ?it/s]

Predicting: 35it [00:00, ?it/s]

[I 2026-03-14 11:16:53,948] Trial 23 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 45it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 46it [00:00, ?it/s]

[I 2026-03-14 11:18:07,382] Trial 24 finished with value: 6.742950976386451 and parameters: {'lag_temp_max': 26, 'lag_temp_min': 14, 'lag_snowfall': 2, 'n_lags': 19, 'epochs': 96, 'learning_rate': 0.008812303834002938, 'batch_size': 41, 'ar_reg': 0.7174730261023233}. Best is trial 24 with value: 6.742950976386451.

Using Optuna with TimeSeriesSplit of n_splits=2 and test_size=14, we got the following as our best parameters. This is solely meant for a quick test run. We will tune this more in 4tune.ipynb if we determine that NeuralProphet is the better performing model.

In [13]:
print("Best Parameters", best_params)
print("Best RMSE:", study.best_value)

Best Parameters {'lag_temp_max': 26, 'lag_temp_min': 14, 'lag_snowfall': 2, 'n_lags': 19, 'epochs': 96, 'learning_rate': 0.008812303834002938, 'batch_size': 41, 'ar_reg': 0.7174730261023233}
Best RMSE: 6.742950976386451

We ran an initialize Optuna hyperparameter tunning to get some ideal of what the optimal choices for lags would be. To speed up the process, we chose to use n_splits = 2 and training_size = 14. We also set n_trials to 25. More robust tuning can be found in 4tune.ipynb. Explanations for the feature choices can be found in another notebook.
Recorded below the best parameters we found after a 3 hour run of the previous code.

In [14]:
# best_params =  {'lag_temp_max': 30, 'lag_temp_min': 5, 'lag_snowfall': 1, 'n_lags': 16, 'epochs': 60, 'learning_rate': 0.2986532324899507, 'batch_size': 128, 'ar_reg': 2.132925719127823}

## Walkforward Cross-validation for NeuralProphet

In [15]:
rs = pd.read_csv('../../scr/data/cleaned_rat_sightings_data/all_cleaned_rat_sightings.csv')
rs['created_date'] = pd.to_datetime(rs['created_date']) 
rs['closed_date'] = pd.to_datetime(rs['closed_date'])
rs['resolution_action_updated_date'] = pd.to_datetime(rs['resolution_action_updated_date'])
# mark cutoff dates, and also rename columns
rs = rs[rs['created_date']<'2025-03-01']
rs = rs[rs['created_date']>='2020-01-01']
rs = rs.groupby([rs['created_date'].dt.date]).size().reset_index(name='count')
rs.rename(columns={'created_date': 'ds', 'count': 'y'}, inplace=True)

## Add weather data.
import requests

lat, lon = 40.7831, -73.9712
start = "2020-01-01"
end   = "2025-02-28"

url = (
    "https://archive-api.open-meteo.com/v1/archive"
    f"?latitude={lat}&longitude={lon}"
    f"&start_date={start}&end_date={end}"
    "&daily=temperature_2m_max,temperature_2m_min,temperature_2m_mean,"
    "apparent_temperature_max,apparent_temperature_min,apparent_temperature_mean,"
    "precipitation_sum,snowfall_sum"
    "&timezone=America/New_York"
)

response = requests.get(url)
data = response.json()


if 'error' in data:
    nd = pd.read_csv("weatherdata.csv")
    nd = nd.set_index('date')
    wd = nd
    
else:
    wd = pd.DataFrame(data["daily"])
    wd["date"] = pd.to_datetime(wd["time"])
    wd = wd.set_index("date")

In [16]:
tscv = TimeSeriesSplit(gap=0, max_train_size=None, n_splits=26, test_size=14)

regressed_features = ['apparent_temperature_max', 'apparent_temperature_min','snowfall_sum']


wd = wd.reset_index(drop=True).rename(columns={"time": "ds"})
wd["ds"] = pd.to_datetime(wd["ds"])
rs["ds"] = pd.to_datetime(rs["ds"])

rs = rs.merge(
    wd[['ds'] + regressed_features],
    on="ds",
    how="left"
)

lags_for_regressed_features = dict()
lags_for_regressed_features['apparent_temperature_max'] = best_params['lag_temp_max']
lags_for_regressed_features['apparent_temperature_min'] = best_params['lag_temp_min']
lags_for_regressed_features['snowfall_sum'] = best_params['lag_snowfall']


results = []

for i, (train_index, test_index) in enumerate(tscv.split(rs)):

    train = rs.iloc[train_index].copy()
    train = train.dropna(subset=["y"])

    test = rs.iloc[test_index].copy()


    model = NeuralProphet(yearly_seasonality=True, 
                          weekly_seasonality=True, 
                          learning_rate = best_params['learning_rate'],
                          epochs = best_params['epochs'],
                          n_lags= best_params['n_lags'],
                          ar_reg=best_params['ar_reg'],
                          accelerator="auto",   # uses GPU if available
                          batch_size= best_params['batch_size']
                          )
    model = model.add_country_holidays(country_name="US")
    for column in regressed_features:
        model.add_lagged_regressor(column, n_lags=lags_for_regressed_features[column])
        
    model.fit(train, freq="D", progress="off")

    # build dataframe containing future regressors
    future = pd.concat([train[['ds','y'] + regressed_features], test[['ds','y']].merge(wd[['ds'] + regressed_features], on="ds", how="left")])
    forecast = model.predict(future)

    y_pred = forecast["yhat1"].iloc[-len(test):].values
    y_true = test["y"].values

    rmse = np.sqrt(mean_squared_error(y_true, y_pred))
    mape = mean_absolute_percentage_error(y_true, y_pred)

    results.append({"fold": i, "rmse": rmse, "mape": mape})

Training: 0it [00:00, ?it/s]

Predicting: 37it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 37it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 38it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 38it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 38it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 39it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 39it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 39it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 40it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 40it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 40it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 41it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 41it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 41it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 42it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 42it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 42it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 43it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 43it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 43it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 44it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 44it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 44it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 45it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 45it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 46it [00:00, ?it/s]

## Results for Neural Prophet

In [17]:
neural_prophet_results_df = pd.DataFrame(results)
neural_prophet_results_df.loc["mean"] = ["mean", neural_prophet_results_df["rmse"].mean(), neural_prophet_results_df["mape"].mean()]
neural_prophet_results_df

      fold       rmse      mape
0        0   9.597519  0.136218
1        1  14.550181  0.258540
2        2  12.671366  0.192878
3        3  12.634174  0.149601
4        4  12.430234  0.099233
5        5  14.211490  0.134306
6        6  18.012476  0.172856
7        7  15.695304  0.137526
8        8  10.966079  0.141822
9        9  11.439435  0.107440
10      10  15.929506  0.141044
11      11  14.126615  0.163903
12      12  12.973527  0.111231
13      13  14.479845  0.174952
14      14  15.862379  0.147797
15      15  10.743105  0.133722
16      16  14.967792  0.209649
17      17  12.044640  0.201192
18      18  11.519741  0.161968
19      19  11.309384  0.260374
20      20  11.286643  0.246253
21      21  12.472254  0.412940
22      22  13.824678  0.304705
23      23  10.703835  0.223528
24      24  10.172424  0.233783
25      25   6.979267  0.138214
mean  mean  12.753996  0.184449