# Forecasts

This note book can be run all at once. Do not attempt to run anything out of order. A couple of comments are in order.

**Summary of what is Forecasted and Models Chosen.**

a. The Citywide Forecast uses a hybrid XGBoost and Prophet model.

b. The forecast method for all of the other boroughs uses the Prophet model. *We choose not to use the best model for each borough for the following reason:* the "better" models have a massively increased run time! Attempting to run the best models for each borough would inevitably lead to the kernel running this notebook to crash due to memory issues. Since we saw in our modeling comparisons that the improvements over Prophet are quite minimal, we shall stick to Prophet for modeling the boroughs here and only use the hybrid XGBoost and Prophet model for the citywide forecast.

**Explanation of the Table at the End.** At the end of this notebook, one sees a displayed table of the forecasted number of 311 rat sightings based on the models chosen. Note, however, that if one adds up the forecasted rat sightings in each borough, one *does not always get that it equals the forecasted number of rat sightings citywide*. This is *not a mistake*! We have models for each borough and a separate model for citywide rat sightings. Each model originally makes a forecast which originally need not be an integer. For the purposes of making an integer-valeud forecast, we round the forecasted number to the nearest integer. Due to rounding errors and the citywide modeling being done separately, one gets this seemingly odd discrepency. For this reason, there is a column titled "Summed Citywide Forecast" which simply sums up each borough's forecast.

## Import Packages

In [322]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import datetime

from sklearn.model_selection import TimeSeriesSplit
from sklearn.metrics import mean_squared_error, mean_absolute_percentage_error
from sklearn.linear_model import LinearRegression

from prophet import Prophet
from pandas.tseries.holiday import USFederalHolidayCalendar
from prophet.diagnostics import cross_validation, performance_metrics
from prophet.plot import plot_cross_validation_metric
from prophet.plot import add_changepoints_to_plot
import itertools

import warnings
from statsmodels.tools.sm_exceptions import ConvergenceWarning
warnings.simplefilter('ignore', ConvergenceWarning)

import xgboost as xgb
from xgboost import plot_importance

## Citywide

### Load the Data

In [323]:
# we import the data and clean it for future use
rs = pd.read_csv('../scr/data/rat_sightings_data/Updated_Rat_Sightings_NYC.csv')
rs['Created Date'] = pd.to_datetime(rs['Created Date'], format='%m/%d/%Y %I:%M:%S %p', errors='coerce')
rs = rs[rs['Created Date']>='2020-01-01']
rs = rs.groupby([rs['Created Date'].dt.date]).size().reset_index(name='count')
rs.rename(columns={'Created Date': 'ds', 'count': 'y'}, inplace=True)
df = rs.copy() # we will use df for our forecast with prophet
today = rs['ds'].max()

### Make Features

In [324]:
def create_features(df):
    # create time series features based on time series index.
    df = df.copy()
    df['dayofweek'] = df.index.dayofweek
    df['quarter'] = df.index.quarter
    df['month'] = df.index.month
    df['year'] = df.index.year
    df['dayofyear'] = df.index.dayofyear
    df['dayofmonth'] = df.index.day
    df['weekofyear'] = df.index.isocalendar().week
    return df

def add_cyclic(df):
    # features to handly cyclic behavior
    target_map = df['y'].to_dict()
    df['dayofweek_sin'] = np.sin(2 * np.pi * df['dayofweek']/7)
    df['dayofweek_cos'] = np.cos(2 * np.pi * df['dayofweek']/7)
    df['month_sin'] = np.sin(2 * np.pi * df['month']/12)
    df['month_cos'] = np.cos(2 * np.pi * df['month']/12)
    return df

def add_lags(df):
    # lags
    target_map = df['y'].to_dict()
    df['lag15'] = (df.index - pd.Timedelta('15 days')).map(target_map)
    df['lag16'] = (df.index - pd.Timedelta('16 days')).map(target_map)
    return df

def add_seasonal_lags(df):
    # lags of various lengths for different levels of seasonality
    target_map = df['y'].to_dict()
    df['lag30'] = (df.index - pd.Timedelta('30 days')).map(target_map)
    df['lag60'] = (df.index - pd.Timedelta('60 days')).map(target_map)
    df['lag90'] = (df.index - pd.Timedelta('90 days')).map(target_map)
    df['lag120'] = (df.index - pd.Timedelta('120 days')).map(target_map)
    df['lag150'] = (df.index - pd.Timedelta('150 days')).map(target_map)
    df['lag180'] = (df.index - pd.Timedelta('180 days')).map(target_map)

    df['lag362'] = (df.index - pd.Timedelta('365 days')).map(target_map)
    df['lag363'] = (df.index - pd.Timedelta('365 days')).map(target_map)
    df['lag364'] = (df.index - pd.Timedelta('365 days')).map(target_map)
    df['lag365'] = (df.index - pd.Timedelta('365 days')).map(target_map)
    df['lag366'] = (df.index - pd.Timedelta('365 days')).map(target_map)
    df['lag367'] = (df.index - pd.Timedelta('365 days')).map(target_map)
    
    df['lag730'] = (df.index - pd.Timedelta('730 days')).map(target_map)
    df['lag1095'] = (df.index - pd.Timedelta('1095 days')).map(target_map)
    df['lag1460'] = (df.index - pd.Timedelta('1460 days')).map(target_map)
    df['lag1825'] = (df.index - pd.Timedelta('1825 days')).map(target_map)
    return df

def add_moving_averages(df):
    df = df.copy()
    df = df.sort_index()
    
    # Moving averages (using previous values only)
    # Must shift by 14 days because we do not want to let there be temporal leakage in our evaluations
    df['ma7'] = df['y'].shift(14).rolling(window=7).mean()
    df['ma30'] = df['y'].shift(14).rolling(window=30).mean()
    df['ma60'] = df['y'].shift(14).rolling(window=60).mean()
    df['ma90'] = df['y'].shift(14).rolling(window=90).mean()
    df['ma120'] = df['y'].shift(14).rolling(window=120).mean()
    df['ma150'] = df['y'].shift(14).rolling(window=150).mean()
    df['ma180'] = df['y'].shift(14).rolling(window=180).mean()
    df['ma365'] = df['y'].shift(14).rolling(window=365).mean()
    
    return df

In [325]:
## Add weather data.

import requests
import pandas as pd

lat, lon = 40.7831, -73.9712
start = "2020-01-01"
end   = "2025-02-28"

url = (
    "https://archive-api.open-meteo.com/v1/archive"
    f"?latitude={lat}&longitude={lon}"
    f"&start_date={start}&end_date={end}"
    "&daily=temperature_2m_max,temperature_2m_min,temperature_2m_mean,"
    "apparent_temperature_max,apparent_temperature_min,apparent_temperature_mean,"
    "precipitation_sum,snowfall_sum"
    "&timezone=America/New_York"
)

response = requests.get(url)
data = response.json()

if 'error' in data:
    nd = pd.read_csv("weatherdata.csv")
    nd = nd.set_index('date')
    wd = nd
    
else:
    wd = pd.DataFrame(data["daily"])
    wd["date"] = pd.to_datetime(wd["time"])
    wd = wd.set_index("date")

In [326]:
def add_weather_data(df, wd):
    df = df.copy()
    wd = wd.copy()
    
    # Ensure datetime index
    df.index = pd.to_datetime(df.index)
    wd.index = pd.to_datetime(wd.index)
    
    # Drop unnecessary columns
    if "time" in wd.columns:
        wd = wd.drop(columns=["time"])
    
    # Remove overlapping columns to avoid join errors
    overlap = wd.columns.intersection(df.columns)
    wd = wd.drop(columns=overlap)
    
    # Join on date index
    df = df.join(wd, how="left")
    
    return df

def add_more_weather_feature(df):
    target_map = df['apparent_temperature_min'].to_dict()
    df['apparent_temperature_min_lag14'] = (df.index - pd.Timedelta('14 days')).map(target_map)
    df['apparent_temperature_min_lag15'] = (df.index - pd.Timedelta('15 days')).map(target_map)
    df['apparent_temperature_min_lag16'] = (df.index - pd.Timedelta('16 days')).map(target_map)
    df['apparent_temperature_min_lag17'] = (df.index - pd.Timedelta('17 days')).map(target_map)
    df['apparent_temperature_min_lag18'] = (df.index - pd.Timedelta('18 days')).map(target_map)
    df['apparent_temperature_min_lag19'] = (df.index - pd.Timedelta('19 days')).map(target_map)
    df['apparent_temperature_min_lag20'] = (df.index - pd.Timedelta('20 days')).map(target_map)
    df['apparent_temperature_min_lag21'] = (df.index - pd.Timedelta('21 days')).map(target_map)

    df['apparent_temperature_min_lag30'] = (df.index - pd.Timedelta('30 days')).map(target_map)
    df['apparent_temperature_min_lag60'] = (df.index - pd.Timedelta('60 days')).map(target_map)
    df['apparent_temperature_min_lag90'] = (df.index - pd.Timedelta('90 days')).map(target_map)
    df['apparent_temperature_min_lag120'] = (df.index - pd.Timedelta('120 days')).map(target_map)
    df['apparent_temperature_min_lag150'] = (df.index - pd.Timedelta('150 days')).map(target_map)
    df['apparent_temperature_min_lag180'] = (df.index - pd.Timedelta('180 days')).map(target_map)
    df['apparent_temperature_min_lag210'] = (df.index - pd.Timedelta('210 days')).map(target_map)
    df['apparent_temperature_min_lag240'] = (df.index - pd.Timedelta('240 days')).map(target_map)
    df['apparent_temperature_min_lag270'] = (df.index - pd.Timedelta('270 days')).map(target_map)
    df['apparent_temperature_min_lag300'] = (df.index - pd.Timedelta('300 days')).map(target_map)
    df['apparent_temperature_min_lag330'] = (df.index - pd.Timedelta('330 days')).map(target_map)
    df['apparent_temperature_min_lag360'] = (df.index - pd.Timedelta('360 days')).map(target_map)
    df['apparent_temperature_min_lag365'] = (df.index - pd.Timedelta('365 days')).map(target_map)
    df['apparent_temperature_min_lag730'] = (df.index - pd.Timedelta('730 days')).map(target_map)

    target_map = df['temperature_2m_max'].to_dict()
    df['temperature_2m_max_lag14'] = (df.index - pd.Timedelta('14 days')).map(target_map)
    df['temperature_2m_max_lag30'] = (df.index - pd.Timedelta('30 days')).map(target_map)
    df['temperature_2m_max_lag60'] = (df.index - pd.Timedelta('60 days')).map(target_map)

    return df

In [327]:
date_range = pd.date_range(start="2020-01-01", end=today)

# Generate US federal holidays
calendar = USFederalHolidayCalendar()
holidays = calendar.holidays(start=date_range.min(), end=date_range.max())

federal_holidays = pd.DataFrame({
    'holiday': 'federal_us',
    'ds': pd.to_datetime(holidays),
    'lower_window': 0,
    'upper_window': 1})

holidays = federal_holidays

In [328]:
from pandas.tseries.holiday import USFederalHolidayCalendar

def add_federal_holidays(df, custom_holidays=None):
    df = df.copy()
    
    # Ensure datetime index
    df.index = pd.to_datetime(df.index)
    
    cal = USFederalHolidayCalendar()
    holidays = cal.holidays(start=df.index.min(), end=df.index.max())
    
    if custom_holidays:
        for d in custom_holidays:
            if len(d) == 5:  # MM-DD format handling
                years = df.index.year.unique()
                for y in years:
                    holidays = holidays.append(pd.to_datetime([f"{y}-{d}"]))
            else:  # YYYY-MM-DD format handling
                holidays = holidays.append(pd.to_datetime([d]))
    
    holidays = holidays.drop_duplicates().sort_values()
    
    df["is_federal_holiday"] = df.index.isin(holidays).astype(int)
    
    return df

In [329]:
def add_law_flag(df, law_name: str, start_date: str):
    # Adds a binary column to indicate when a new law is active.
    df = df.copy()
    df.index = pd.to_datetime(df.index)
    start_dt = pd.to_datetime(start_date)
    # Create binary column: 1 if date >= start_date, else 0
    df[law_name] = (df.index >= start_dt).astype(int)
    
    return df

In [330]:
def add_new_lags(df, x):
    # lags
    target_map = df[x].to_dict()
    df[f'{x}lag15'] = (df.index - pd.Timedelta('15 days')).map(target_map)
    df[f'{x}lag16'] = (df.index - pd.Timedelta('16 days')).map(target_map)
    df[f'{x}lag16'] = (df.index - pd.Timedelta('15 days')).map(target_map)
    df[f'{x}lag17'] = (df.index - pd.Timedelta('16 days')).map(target_map)
    df[f'{x}lag18'] = (df.index - pd.Timedelta('15 days')).map(target_map)
    df[f'{x}lag19'] = (df.index - pd.Timedelta('16 days')).map(target_map)
    df[f'{x}lag20'] = (df.index - pd.Timedelta('15 days')).map(target_map)
    df[f'{x}lag21'] = (df.index - pd.Timedelta('16 days')).map(target_map)

    df[f'{x}lag30'] = (df.index - pd.Timedelta('15 days')).map(target_map)
    df[f'{x}lag365'] = (df.index - pd.Timedelta('16 days')).map(target_map)
    df[f'{x}lag730'] = (df.index - pd.Timedelta('15 days')).map(target_map)
    return df

In [331]:
FEATURES = ['apparent_temperature_min_lag30',
            'apparent_temperature_min_lag60',
            'apparent_temperature_min_lag120',
            'apparent_temperature_min_lag365',
            'apparent_temperature_min_lag730',
            'dayofyear', 'temperature_2m_max_lag14', 'temperature_2m_max_lag30',
            'temperature_2m_max_lag60', 
            'is_federal_holiday', 
            'lag15', 'lag16', 'lag30', 'lag60', 'lag90', 'lag120', 'lag150', 
            'lag180', 
            'lag362', 'lag363', 'lag364', 'lag365', 'lag366', 'lag367',
            'residualslag15', 'residualslag16', 'residualslag17',
            'residualslag18', 'residualslag19', 'residualslag20', 'residualslag21',
            'residualslag30', 'residualslag365', 'residualslag730', 
            'trend', 'yhat_lower', 'yhat_upper', 
            ]

In [332]:
save = rs['ds'].copy().values
rs = rs.set_index('ds')
rs.index = pd.to_datetime(rs.index)
rs['ds']=save

In [333]:
# Number of future days to add
forecast_horizon = 14
last_date = rs.index.max()
future_dates = pd.date_range(start=last_date + pd.Timedelta(days=1), periods=forecast_horizon, freq='D')
future_df = pd.DataFrame(index=future_dates)
future_df['y'] = np.nan
future_df['ds'] = future_df.index.strftime('%Y-%m-%d')
rs_extended = pd.concat([rs, future_df], axis=0)
rs = rs_extended.copy()

In [334]:
rs = create_features(rs)
rs = add_cyclic(rs)
rs = add_lags(rs)
rs = add_seasonal_lags(rs)
rs = add_moving_averages(rs)
rs = add_weather_data(rs,wd)
rs = add_more_weather_feature(rs)
rs = add_federal_holidays(rs, custom_holidays = ['12-31'])
rs = add_law_flag(rs, law_name='Trash_Law', start_date = '2024-03-01')
rs = add_law_flag(rs, law_name = 'New_Trash_Law', start_date = '2024-11-01')
rs = add_law_flag(rs, law_name='Rat_Mitigation_Zone', start_date = '2023-07-07')
rs = add_law_flag(rs, law_name='Rat_Czar_Appointed', start_date = '2023-04-12')

### Load Parameters to Use

In [335]:
ALL_FEATURES = {'dayofweek', 'quarter', 'month', 'year', 'dayofyear',
       'dayofmonth', 'weekofyear', 'dayofweek_sin', 'dayofweek_cos',
       'month_sin', 'month_cos', 'lag15', 'lag16', 'lag30', 'lag60', 'lag90',
       'lag120', 'lag150', 'lag180', 'lag362', 'lag363', 'lag364', 'lag365',
       'lag366', 'lag367', 'lag730', 'lag1095', 'lag1460', 'lag1825', 'ma7',
       'ma30', 'ma60', 'ma90', 'ma120', 'ma150', 'ma180', 'ma365',
       'temperature_2m_max', 'temperature_2m_min', 'temperature_2m_mean',
       'apparent_temperature_max', 'apparent_temperature_min',
       'apparent_temperature_mean', 'precipitation_sum', 'snowfall_sum',
       'apparent_temperature_min_lag14', 'apparent_temperature_min_lag15',
       'apparent_temperature_min_lag16', 'apparent_temperature_min_lag17',
       'apparent_temperature_min_lag18', 'apparent_temperature_min_lag19',
       'apparent_temperature_min_lag20', 'apparent_temperature_min_lag21',
       'apparent_temperature_min_lag30', 'apparent_temperature_min_lag60',
       'apparent_temperature_min_lag90', 'apparent_temperature_min_lag120',
       'apparent_temperature_min_lag150', 'apparent_temperature_min_lag180',
       'apparent_temperature_min_lag210', 'apparent_temperature_min_lag240',
       'apparent_temperature_min_lag270', 'apparent_temperature_min_lag300',
       'apparent_temperature_min_lag330', 'apparent_temperature_min_lag360',
       'apparent_temperature_min_lag365', 'apparent_temperature_min_lag730',
       'temperature_2m_max_lag14', 'temperature_2m_max_lag30',
       'temperature_2m_max_lag60', 'is_federal_holiday', 'Trash_Law',
       'New_Trash_Law', 'Rat_Mitigation_Zone', 'Rat_Czar_Appointed',
       'residuals', 'residualslag15', 'residualslag16', 'residualslag17',
       'residualslag18', 'residualslag19', 'residualslag20', 'residualslag21',
       'residualslag30', 'residualslag365', 'residualslag730', 'trend',
       'yhat_lower', 'yhat_upper'}

In [336]:
import os
import optuna

# Relative path to the folder containing the DB
db_folder = "citywide"
db_file = f"xgbprophet_model26.db"
storage_path = f"sqlite:///{os.path.join(db_folder, db_file)}"

# Load the study from the correct directory
study = optuna.load_study(study_name="hybrid_model_feature_parameter_search", storage=storage_path)

# Get parameters
best_params = study.best_params
# Separate features and hyperparameters
best_features = [f for f in ALL_FEATURES if study.best_params.get(f, False)]
best_hyperparams = {k: v for k, v in study.best_params.items() if k not in ALL_FEATURES}

In [337]:
prophet_keys = ["changepoint_prior_scale", "seasonality_prior_scale", "holidays_prior_scale"]
best_prophet_params = {k: best_hyperparams[k] for k in prophet_keys if k in best_hyperparams}


xgb_keys = ['n_estimators', 'max_depth', 'learning_rate', 'subsample', 'colsample_bytree', 'gamma', 'min_child_weight', 'reg_lambda', 'reg_alpha'] 
best_xgb_params = {k: best_hyperparams[k] for k in xgb_keys if k in best_hyperparams}

### Make the Forecast

In [338]:
# make the prophet forecast first

model = Prophet(**best_prophet_params, holidays=holidays)
model.add_country_holidays(country_name='US')
model.fit(df)

19:29:38 - cmdstanpy - INFO - Chain [1] start processing
19:29:38 - cmdstanpy - INFO - Chain [1] done processing

In [339]:
train_rs = rs[:-14].copy()

train_future = model.make_future_dataframe(periods=0, freq='D')
train_forecast = model.predict(train_future)

train_residuals = train_rs['y'].values - train_forecast['yhat'].values

residuals_df = pd.DataFrame({'ds': train_rs['ds'],'y': train_residuals})

train_rs['residuals'] = train_residuals

add_new_lags(train_rs, 'residuals')

train_rs['trend'] = train_forecast['trend'].values
train_rs['yhat_lower'] = train_forecast['yhat_lower'].values
train_rs['yhat_upper'] = train_forecast['yhat_upper'].values

X_train_residuals = train_rs[FEATURES]
y_train_residuals = residuals_df['y']

In [340]:
test = rs[-14:].copy()

xgb_model = xgb.XGBRegressor(**best_xgb_params)
xgb_model.fit(X_train_residuals, y_train_residuals)

# Prepare Test Data
test['residuals'] = np.nan # need to add this otherwise it won't run

dummy = pd.concat([train_rs, test], axis=0)

add_new_lags(dummy, 'residuals') # need to add the lags that test can actually see

test = dummy.iloc[-14:].copy() # cut out the test set again

In [341]:
# Prophet Forecast
future = model.make_future_dataframe(periods=forecast_horizon, freq='D')
prophet_forecast = model.predict(future)

# add outputs of Prophet for use in the XGBoost model
test.loc[:, 'trend'] = prophet_forecast[-forecast_horizon:]['trend'].values
test.loc[:, 'yhat_lower'] = prophet_forecast[-forecast_horizon:]['yhat_lower'].values
test.loc[:, 'yhat_upper'] = prophet_forecast[-forecast_horizon:]['yhat_upper'].values

X_test = test[FEATURES]

xgb_residual_preds = xgb_model.predict(X_test)

y_pred = np.round(prophet_forecast['yhat'][-forecast_horizon:].values + xgb_residual_preds)

In [342]:
future_dates = rs['ds'].iloc[-len(y_pred):].values  # last n rows, n = len(y_pred)

citywide_forecast = pd.DataFrame({'ds': future_dates, 'yhat': y_pred})

citywide_forecast

            ds  yhat
0   2026-03-14  25.0
1   2026-03-15  26.0
2   2026-03-16  44.0
3   2026-03-17  45.0
4   2026-03-18  43.0
5   2026-03-19  42.0
6   2026-03-20  36.0
7   2026-03-21  22.0
8   2026-03-22  24.0
9   2026-03-23  45.0
10  2026-03-24  44.0
11  2026-03-25  43.0
12  2026-03-26  39.0
13  2026-03-27  35.0

## Manhattan

In [343]:
rs = pd.read_csv('../scr/data/rat_sightings_data/Updated_Rat_Sightings_NYC.csv')
rs.columns
rs = rs[['Borough', 'Created Date']]

rs.columns = [t.partition('(')[0].strip().lower().replace(' ', '_') for t in rs.columns] #apply to column headers
rs['created_date'] = pd.to_datetime(rs['created_date'], format='%m/%d/%Y %I:%M:%S %p', errors='coerce')

rs = rs[rs['created_date']>='2020-01-01']
rs = rs[rs['borough']=='MANHATTAN']

rs['ds'] = rs['created_date'].dt.date
rs = rs.groupby('ds').size().reset_index(name='y')
rs['ds'] = pd.to_datetime(rs['ds'])

full_range = pd.date_range(start='2020-01-01', end=today)

# Reindex to include all dates and fill missing y with 0
rs = rs.set_index('ds').reindex(full_range, fill_value=0).rename_axis('ds').reset_index()

In [344]:
df = rs.copy()
df['ds'] = pd.to_datetime(df['ds'])
df = df[['ds', 'y']]

calendar = USFederalHolidayCalendar()
holidays = pd.DataFrame({
    'holiday': 'federal_us',
    'ds': pd.to_datetime(calendar.holidays(start=df['ds'].min(), end=df['ds'].max())),
    'lower_window': 0,
    'upper_window': 1
})

model = Prophet(daily_seasonality=True, yearly_seasonality=True, holidays=holidays)
model.fit(df)

forecast_horizon = 14
future = model.make_future_dataframe(periods=forecast_horizon, freq='D')

forecast = model.predict(future)

manhattan_forecast = np.round(forecast[['ds', 'yhat']].tail(forecast_horizon).reset_index(drop=True))

manhattan_forecast

19:29:43 - cmdstanpy - INFO - Chain [1] start processing
19:29:43 - cmdstanpy - INFO - Chain [1] done processing

           ds  yhat
0  2026-03-14   6.0
1  2026-03-15   8.0
2  2026-03-16  14.0
3  2026-03-17  13.0
4  2026-03-18  13.0
5  2026-03-19  12.0
6  2026-03-20  11.0
7  2026-03-21   6.0
8  2026-03-22   8.0
9  2026-03-23  14.0
10 2026-03-24  12.0
11 2026-03-25  12.0
12 2026-03-26  12.0
13 2026-03-27  11.0

## Brooklyn

In [345]:
rs = pd.read_csv('../scr/data/rat_sightings_data/Updated_Rat_Sightings_NYC.csv')
rs.columns
rs = rs[['Borough', 'Created Date']]


rs.columns = [t.partition('(')[0].strip().lower().replace(' ', '_') for t in rs.columns] #apply to column headers

rs['created_date'] = pd.to_datetime(rs['created_date'], format='%m/%d/%Y %I:%M:%S %p', errors='coerce')


rs = rs[rs['created_date']>='2020-01-01']

rs = rs[rs['borough']=='BROOKLYN']


rs['ds'] = rs['created_date'].dt.date
rs = rs.groupby('ds').size().reset_index(name='y')
rs['ds'] = pd.to_datetime(rs['ds'])

full_range = pd.date_range(start='2020-01-01', end=today)

# Reindex to include all dates and fill missing y with 0
rs = rs.set_index('ds').reindex(full_range, fill_value=0).rename_axis('ds').reset_index()

In [346]:
df = rs.copy()
df['ds'] = pd.to_datetime(df['ds'])
df = df[['ds', 'y']]

calendar = USFederalHolidayCalendar()
holidays = pd.DataFrame({
    'holiday': 'federal_us',
    'ds': pd.to_datetime(calendar.holidays(start=df['ds'].min(), end=df['ds'].max())),
    'lower_window': 0,
    'upper_window': 1
})

model = Prophet(daily_seasonality=True, yearly_seasonality=True, holidays=holidays)
model.fit(df)

forecast_horizon = 14
future = model.make_future_dataframe(periods=forecast_horizon, freq='D')

forecast = model.predict(future)

brooklyn_forecast = np.round(forecast[['ds', 'yhat']].tail(forecast_horizon).reset_index(drop=True))

brooklyn_forecast

19:29:44 - cmdstanpy - INFO - Chain [1] start processing
19:29:45 - cmdstanpy - INFO - Chain [1] done processing

           ds  yhat
0  2026-03-14   6.0
1  2026-03-15   7.0
2  2026-03-16  17.0
3  2026-03-17  17.0
4  2026-03-18  16.0
5  2026-03-19  16.0
6  2026-03-20  12.0
7  2026-03-21   5.0
8  2026-03-22   6.0
9  2026-03-23  17.0
10 2026-03-24  17.0
11 2026-03-25  16.0
12 2026-03-26  16.0
13 2026-03-27  12.0

## Staten Island

The number of rat sightings in Staten Island on any given day often is 0. Due to the sparsity of the data, we recognize that a daily forecast of two weeks might be unhelpful and so we provide in addition a weekly forecast.

1. For daily data, Prophet performed the best.

2. For weekly data, the baseline 4 year seasonal average model actually performed the best.

### Daily

In [347]:
rs = pd.read_csv('../scr/data/rat_sightings_data/Updated_Rat_Sightings_NYC.csv')
rs.columns
rs = rs[['Borough', 'Created Date']]


rs.columns = [t.partition('(')[0].strip().lower().replace(' ', '_') for t in rs.columns] #apply to column headers

rs['created_date'] = pd.to_datetime(rs['created_date'], format='%m/%d/%Y %I:%M:%S %p', errors='coerce')

rs = rs[rs['created_date']>='2020-01-01']

rs = rs[rs['borough']=='STATEN ISLAND']

rs['ds'] = rs['created_date'].dt.date
rs = rs.groupby('ds').size().reset_index(name='y')
rs['ds'] = pd.to_datetime(rs['ds'])

# Date range from 2020-01-01 to today
full_range = pd.date_range(start='2020-01-01', end=today)

# Reindex to include all dates and fill missing y with 0
rs = rs.set_index('ds').reindex(full_range, fill_value=0).rename_axis('ds').reset_index()

In [348]:
model = Prophet(changepoint_prior_scale=0.5, seasonality_prior_scale=2) # parameters chosen from 2models_statenIsland_prophet.ipynb
model.fit(rs)
future = model.make_future_dataframe(periods=14)
forecast = model.predict(future)
daily_staten_island_forecast = (forecast[['ds', 'yhat']].tail(14).assign(yhat=lambda x: x['yhat'].round().clip(lower=0).astype(int)))
daily_staten_island_forecast

19:29:46 - cmdstanpy - INFO - Chain [1] start processing
19:29:46 - cmdstanpy - INFO - Chain [1] done processing

             ds  yhat
2264 2026-03-14     1
2265 2026-03-15     1
2266 2026-03-16     1
2267 2026-03-17     1
2268 2026-03-18     1
2269 2026-03-19     1
2270 2026-03-20     1
2271 2026-03-21     1
2272 2026-03-22     1
2273 2026-03-23     1
2274 2026-03-24     1
2275 2026-03-25     1
2276 2026-03-26     1
2277 2026-03-27     1

### Weekly

In [349]:
rs = pd.read_csv('../scr/data/rat_sightings_data/Updated_Rat_Sightings_NYC.csv')
rs.columns
rs = rs[['Borough', 'Created Date']]


rs.columns = [t.partition('(')[0].strip().lower().replace(' ', '_') for t in rs.columns] #apply to column headers

rs['created_date'] = pd.to_datetime(rs['created_date'], format='%m/%d/%Y %I:%M:%S %p', errors='coerce')


rs = rs[rs['created_date']>='2020-01-01']

rs = rs[rs['borough']=='STATEN ISLAND']

rs['ds'] = rs['created_date'].dt.date
rs = rs.groupby('ds').size().reset_index(name='y')
rs['ds'] = pd.to_datetime(rs['ds'])

# Date range from 2020-01-01 to today
full_range = pd.date_range(start='2020-01-01', end=today)

# Reindex to include all dates and fill missing y with 0
rs = rs.set_index('ds').reindex(full_range, fill_value=0).rename_axis('ds').reset_index()

## Resample to weekly
rs_weekly = rs.set_index('ds').resample('W')['y'].mean().fillna(0).reset_index().rename(columns={'y': 'weekly_avg'})
## Rename columns for Prophet
rs_weekly.rename(columns={'created_date': 'ds', 'weekly_avg': 'y'}, inplace=True)
rs_weekly

            ds         y
0   2020-01-05  0.600000
1   2020-01-12  1.285714
2   2020-01-19  1.285714
3   2020-01-26  0.571429
4   2020-02-02  1.142857
..         ...       ...
319 2026-02-15  1.285714
320 2026-02-22  0.285714
321 2026-03-01  0.285714
322 2026-03-08  1.714286
323 2026-03-15  1.600000

[324 rows x 2 columns]

## Queens

In [350]:
rs = pd.read_csv('../scr/data/rat_sightings_data/Updated_Rat_Sightings_NYC.csv')
rs.columns
rs = rs[['Borough', 'Created Date']]
rs.columns = [t.partition('(')[0].strip().lower().replace(' ', '_') for t in rs.columns] #apply to column headers

rs['created_date'] = pd.to_datetime(rs['created_date'], format='%m/%d/%Y %I:%M:%S %p', errors='coerce')

rs = rs[rs['created_date']>='2020-01-01']
rs = rs[rs['borough']=='QUEENS']

rs['ds'] = rs['created_date'].dt.date
rs = rs.groupby('ds').size().reset_index(name='y')
rs['ds'] = pd.to_datetime(rs['ds'])

# Date range from 2020-01-01 to today
full_range = pd.date_range(start='2020-01-01', end=today)

# Reindex to include all dates and fill missing y with 0
rs = rs.set_index('ds').reindex(full_range, fill_value=0).rename_axis('ds').reset_index()

In [351]:
model = Prophet(changepoint_prior_scale=0.5, seasonality_prior_scale=2) # parameters chosen from 2models_statenIsland_prophet.ipynb
model.fit(rs)
future = model.make_future_dataframe(periods=14)
forecast = model.predict(future)
queens_forecast = (forecast[['ds', 'yhat']].tail(14).assign(yhat=lambda x: x['yhat'].round().clip(lower=0).astype(int)))
queens_forecast

19:29:49 - cmdstanpy - INFO - Chain [1] start processing
19:29:49 - cmdstanpy - INFO - Chain [1] done processing

             ds  yhat
2264 2026-03-14     3
2265 2026-03-15     3
2266 2026-03-16     8
2267 2026-03-17     8
2268 2026-03-18     7
2269 2026-03-19     7
2270 2026-03-20     6
2271 2026-03-21     3
2272 2026-03-22     3
2273 2026-03-23     8
2274 2026-03-24     7
2275 2026-03-25     7
2276 2026-03-26     7
2277 2026-03-27     6

## Bronx

In [352]:
rs = pd.read_csv('../scr/data/rat_sightings_data/Updated_Rat_Sightings_NYC.csv')
rs.columns
rs = rs[['Borough', 'Created Date']]
rs.columns = [t.partition('(')[0].strip().lower().replace(' ', '_') for t in rs.columns] #apply to column headers

rs['created_date'] = pd.to_datetime(rs['created_date'], format='%m/%d/%Y %I:%M:%S %p', errors='coerce')

rs = rs[rs['created_date']>='2020-01-01']
rs = rs[rs['borough']=='BRONX']

rs['ds'] = rs['created_date'].dt.date
rs = rs.groupby('ds').size().reset_index(name='y')
rs['ds'] = pd.to_datetime(rs['ds'])

# Date range from 2020-01-01 to today
full_range = pd.date_range(start='2020-01-01', end=today)

# Reindex to include all dates and fill missing y with 0
rs = rs.set_index('ds').reindex(full_range, fill_value=0).rename_axis('ds').reset_index()

In [353]:
model = Prophet(changepoint_prior_scale=0.5, seasonality_prior_scale=2) # parameters chosen from 2models_statenIsland_prophet.ipynb
model.fit(rs)
future = model.make_future_dataframe(periods=14)
forecast = model.predict(future)
bronx_forecast = (forecast[['ds', 'yhat']].tail(14).assign(yhat=lambda x: x['yhat'].round().clip(lower=0).astype(int)))
bronx_forecast

19:29:51 - cmdstanpy - INFO - Chain [1] start processing
19:29:51 - cmdstanpy - INFO - Chain [1] done processing

             ds  yhat
2264 2026-03-14     4
2265 2026-03-15     4
2266 2026-03-16     8
2267 2026-03-17     8
2268 2026-03-18     8
2269 2026-03-19     8
2270 2026-03-20     6
2271 2026-03-21     4
2272 2026-03-22     3
2273 2026-03-23     8
2274 2026-03-24     8
2275 2026-03-25     7
2276 2026-03-26     7
2277 2026-03-27     6

# Collected Forecasts

In [354]:
dfs = {"Citywide": citywide_forecast, "Manhattan": manhattan_forecast, "Brooklyn": brooklyn_forecast,
       "Daily Staten Island": daily_staten_island_forecast, "Queens": queens_forecast, "Bronx": bronx_forecast,}

ds = citywide_forecast['ds']

# Build final DataFrame by column-wise assignment and round to int
final_df = pd.DataFrame({'Date': ds})
for name, df in dfs.items():
    final_df[name] = np.round(df['yhat'].values).astype(int)

borough_columns = ["Manhattan", "Brooklyn", "Daily Staten Island", "Queens", "Bronx"]
final_df["Summed Citywide"] = final_df[borough_columns].sum(axis=1).astype(int)

final_df

,Date,Citywide,Manhattan,Brooklyn,Daily Staten Island,Queens,Bronx,Summed Citywide
0,2026-03-14,25,6,6,1,3,4,20
1,2026-03-15,26,8,7,1,3,4,23
2,2026-03-16,44,14,17,1,8,8,48
3,2026-03-17,45,13,17,1,8,8,47
4,2026-03-18,43,13,16,1,7,8,45
5,2026-03-19,42,12,16,1,7,8,44
6,2026-03-20,36,11,12,1,6,6,36
7,2026-03-21,22,6,5,1,3,4,19
8,2026-03-22,24,8,6,1,3,3,21
9,2026-03-23,45,14,17,1,8,8,48
10,2026-03-24,44,12,17,1,7,8,45
11,2026-03-25,43,12,16,1,7,7,43
12,2026-03-26,39,12,16,1,7,7,43
13,2026-03-27,35,11,12,1,6,6,36