In the previous notebook models_citywide.ipynb, we found that the Prophet and NeuralProphet models performed well in terms of forecasting rat sightings by day citywide. In this notebook, we will do some more feature engineering and hyperparameter tuning to obtain a more optimal model.

Because we wish this to be reusable, we will write things for Prophet and NeuralProphet separately.

# Import Packages

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import datetime

from sklearn.model_selection import TimeSeriesSplit
from sklearn.metrics import mean_squared_error, mean_absolute_percentage_error
from sklearn.linear_model import LinearRegression

from prophet import Prophet
from pandas.tseries.holiday import USFederalHolidayCalendar
from prophet.diagnostics import cross_validation, performance_metrics
from prophet.plot import plot_cross_validation_metric
from prophet.plot import add_changepoints_to_plot
from prophet.plot import plot_plotly, plot_components_plotly
import itertools

import warnings
from statsmodels.tools.sm_exceptions import ConvergenceWarning
warnings.simplefilter('ignore', ConvergenceWarning)

import optuna
from neuralprophet import NeuralProphet
import logging

Importing plotly failed. Interactive plots will not work.
Importing plotly failed. Interactive plots will not work.

# Prophet

## Import the data

In [20]:
# this is the time series split we will work with
tscv = TimeSeriesSplit(gap=0, max_train_size=None, n_splits=26, test_size=14)


# we import the data and clean it for future use
rs = pd.read_csv('../scr/data/cleaned_rat_sightings_data/all_cleaned_rat_sightings.csv')
rs['created_date'] = pd.to_datetime(rs['created_date']) 
rs['closed_date'] = pd.to_datetime(rs['closed_date'])
rs['resolution_action_updated_date'] = pd.to_datetime(rs['resolution_action_updated_date'])
# mark cutoff dates, and also rename columns
rs = rs[rs['created_date']<'2026-03-01']
rs = rs[rs['created_date']>='2020-01-01']
rs = rs.groupby([rs['created_date'].dt.date]).size().reset_index(name='count')
rs.rename(columns={'created_date': 'ds', 'count': 'y'}, inplace=True)
# This is should be 2251 which equals the number of days from 2020-01-01 to 2026-02-28
print(len(rs)==2251)

True

## Prepare Prophet

In [21]:
date_range = pd.date_range(start="2020-01-01", end="2026-02-28")

# Generate US federal holidays
calendar = USFederalHolidayCalendar()
holidays = calendar.holidays(start=date_range.min(), end=date_range.max())

federal_holidays = pd.DataFrame({
    'holiday': 'federal_us',
    'ds': pd.to_datetime(holidays),
    'lower_window': 0,
    'upper_window': 1})

holidays = federal_holidays

In [22]:
rs_saved = rs.copy()
df = rs.copy()

## Optuna for Hyperparameter Tuning for Prophet

In [23]:
import logging
logging.getLogger("cmdstanpy").setLevel(logging.WARNING)

In [24]:
## To tune for hyperparameters, add more possible parameters to the dictionary below and add more values to it.
## So far, the I've been able to get is {'changepoint_prior_scale': 0.1, 'seasonality_prior_scale': 5}

init_days = '2054 days'
cv_period = '14 days'
forecast_horizon = '14 days'

param_grid = {  
    'changepoint_prior_scale': [0.1, 1],
    'seasonality_prior_scale': [0.1, 1, 5, 10],
}

# Generate all combinations of parameters
all_params = [dict(zip(param_grid.keys(), v)) for v in itertools.product(*param_grid.values())]
rmses = []  # Store the RMSEs for each params here
performance = []

# Use cross validation to evaluate all parameters
for params in all_params:
    params['holidays'] = holidays
    m = Prophet(**params).fit(df)  # Fit model with given params
    df_cv = cross_validation(m, initial = init_days, period=cv_period, horizon = forecast_horizon)
    df_p = performance_metrics(df_cv, rolling_window=14)
    performance.append(df_p)
    rmses.append(df_p['rmse'].values[0])

# Find the best parameters
tuning_results = pd.DataFrame(all_params)
tuning_results['rmse'] = rmses

best_params = all_params[np.argmin(rmses)]

17:43:19 - cmdstanpy - INFO - Chain [1] start processing
17:43:19 - cmdstanpy - INFO - Chain [1] done processing

  0%|          | 0/14 [00:00<?, ?it/s]

17:43:19 - cmdstanpy - INFO - Chain [1] start processing
17:43:19 - cmdstanpy - INFO - Chain [1] done processing
17:43:20 - cmdstanpy - INFO - Chain [1] start processing
17:43:20 - cmdstanpy - INFO - Chain [1] done processing
17:43:20 - cmdstanpy - INFO - Chain [1] start processing
17:43:20 - cmdstanpy - INFO - Chain [1] done processing
17:43:21 - cmdstanpy - INFO - Chain [1] start processing
17:43:21 - cmdstanpy - INFO - Chain [1] done processing
17:43:21 - cmdstanpy - INFO - Chain [1] start processing
17:43:21 - cmdstanpy - INFO - Chain [1] done processing
17:43:22 - cmdstanpy - INFO - Chain [1] start processing
17:43:22 - cmdstanpy - INFO - Chain [1] done processing

KeyboardInterrupt:

In [ ]:
new_performance = pd.concat(performance, ignore_index=True)

# Round numeric columns for readability
numeric_cols = ["mse", "rmse", "mae", "mape", "mdape", "smape", "coverage"]
new_performance[numeric_cols] = new_performance[numeric_cols].round(4)


new_performance

  horizon       mse     rmse     mae    mape   mdape   smape  coverage
0 14 days  142.2601  11.9273  9.6061  0.3244  0.2428  0.3052    0.8827
1 14 days  141.3321  11.8883  9.5662  0.3234  0.2431  0.3053    0.8673
2 14 days  141.3546  11.8893  9.5800  0.3239  0.2432  0.3056    0.8827
3 14 days  141.1426  11.8803  9.5672  0.3234  0.2436  0.3045    0.8878
4 14 days  146.4931  12.1034  9.6572  0.3269  0.2385  0.3383    0.8520
5 14 days  145.7510  12.0727  9.6467  0.3264  0.2358  0.3389    0.8571
6 14 days  145.6748  12.0696  9.6284  0.3260  0.2361  0.3387    0.8571
7 14 days  146.1802  12.0905  9.6539  0.3266  0.2370  0.3392    0.8622

## Train the Model

In [ ]:
m = Prophet(**best_params)
m.add_country_holidays(country_name='US')
m.fit(df)
future = m.make_future_dataframe(periods=14)
forecast = m.predict(future)

17:27:57 - cmdstanpy - INFO - Chain [1] start processing
17:27:57 - cmdstanpy - INFO - Chain [1] done processing

## Plots and Evaluation of the Model

In [ ]:
fig1 = plot_plotly(m, forecast)
fig1.show()

fig2 = plot_components_plotly(m, forecast)
fig2.show()

# Neural Prophet

## Import Packages

In [2]:
np.NaN = np.nan


# the following packages are meant to turn off a bunch of the warnings and ERRORs that pop up while running NeuralProphet.
# the errors that do show up are not all that important and a lot is due to outdated packages.
import warnings
import logging

warnings.filterwarnings("ignore")

logging.getLogger("neuralprophet").setLevel(logging.ERROR)
logging.getLogger("pytorch_lightning").setLevel(logging.ERROR)
logging.getLogger("NP").setLevel(logging.ERROR)

## Import Data

In [3]:
rs = pd.read_csv('../scr/data/cleaned_rat_sightings_data/all_cleaned_rat_sightings.csv')
rs['created_date'] = pd.to_datetime(rs['created_date']) 
rs['closed_date'] = pd.to_datetime(rs['closed_date'])
rs['resolution_action_updated_date'] = pd.to_datetime(rs['resolution_action_updated_date'])
# mark cutoff dates, and also rename columns
rs = rs[rs['created_date']<'2026-03-01']
rs = rs[rs['created_date']>='2020-01-01']
rs = rs.groupby([rs['created_date'].dt.date]).size().reset_index(name='count')
rs.rename(columns={'created_date': 'ds', 'count': 'y'}, inplace=True)

In [4]:
## Add weather data.
import requests

lat, lon = 40.7831, -73.9712
start = "2020-01-01"
end   = "2026-02-28"

url = (
    "https://archive-api.open-meteo.com/v1/archive"
    f"?latitude={lat}&longitude={lon}"
    f"&start_date={start}&end_date={end}"
    "&daily=temperature_2m_max,temperature_2m_min,temperature_2m_mean,"
    "apparent_temperature_max,apparent_temperature_min,apparent_temperature_mean,"
    "precipitation_sum,snowfall_sum"
    "&timezone=America/New_York"
)

response = requests.get(url)
data = response.json()

if 'error' in data:
    nd = pd.read_csv("weatherdata.csv")
    nd = nd.set_index('date')
    wd = nd
    
else:
    wd = pd.DataFrame(data["daily"])
    wd["date"] = pd.to_datetime(wd["time"])
    wd = wd.set_index("date")

## Optuna for Hyperparameter Tuning for Neural Prophet

In [5]:
# Suppress cmdstanpy info logs
logging.getLogger("cmdstanpy").setLevel(logging.WARNING)


regressed_features = ['apparent_temperature_max', 'apparent_temperature_min', 'snowfall_sum']


wd = wd.reset_index(drop=True).rename(columns={"time": "ds"})
wd["ds"] = pd.to_datetime(wd["ds"])
rs["ds"] = pd.to_datetime(rs["ds"])

rs = rs.merge(
    wd[['ds'] + regressed_features],
    on="ds",
    how="left"
)

tscv = TimeSeriesSplit(gap=0, max_train_size=None, n_splits=2, test_size=14)


def objective(trial):
    regressor_lags = {
        'apparent_temperature_max': trial.suggest_int('lag_temp_max', 1, 30),
        'apparent_temperature_min': trial.suggest_int('lag_temp_min', 1, 30),
        'snowfall_sum': trial.suggest_int('lag_snowfall', 1, 7),
    }
    n_lags = trial.suggest_int('n_lags', 1, 21)
    epochs = trial.suggest_int('epochs', 50, 250)
    learning_rate = trial.suggest_float('learning_rate', 0.001, 0.5, log=True)
    batch_size = trial.suggest_int('batch_size', 20, 128)
    ar_reg = trial.suggest_float('ar_reg', 0.5, 3)
    fold_rmses = []
    for i, (train_idx, test_idx) in enumerate(tscv.split(rs)):

        train = rs.iloc[train_idx].copy()
        test = rs.iloc[test_idx].copy()
        
        existing_regressors = [col for col in regressed_features if col in train.columns]
        train = train.dropna(subset=["y"] + existing_regressors)
        test = test.dropna(subset=existing_regressors)
        
        # Skip fold if too few rows
        if len(train) < 20 or len(test) < 1:
            continue
        
        model = NeuralProphet(
            yearly_seasonality=True,
            weekly_seasonality=True,
            n_lags=n_lags,
            epochs=epochs,
            ar_reg = ar_reg,
            accelerator="auto",   # uses GPU if available
            learning_rate=learning_rate,
            batch_size=batch_size
        )
        model.add_country_holidays(country_name="US")
        for col in existing_regressors:
            model.add_lagged_regressor(col, n_lags=regressor_lags[col])
        
        model.fit(train, freq="D", progress="off")
        future = pd.concat([
            train[['ds','y'] + existing_regressors],
            test[['ds','y']].merge(wd[['ds'] + existing_regressors], on="ds", how="left")
        ])
        future = future.dropna(subset=existing_regressors)
        forecast = model.predict(future)
        
        y_pred = forecast["yhat1"].iloc[-len(test):].values
        y_true = test["y"].values
        
        rmse = np.sqrt(mean_squared_error(y_true, y_pred))
        fold_rmses.append(rmse)

        intermediate_score = np.mean(fold_rmses)
        trial.report(intermediate_score, i)
        if trial.should_prune():
            raise optuna.TrialPruned()
        
    return np.mean(fold_rmses) if fold_rmses else float("inf")

study = optuna.create_study(direction="minimize")
study.optimize(objective, n_trials=500)  # adjust n_trials as needed



best_params = study.best_params

[I 2026-03-07 19:19:22,582] A new study created in memory with name: no-name-f7c705c8-7a84-449d-995b-b6b5aab3039b

Training: 0it [00:00, ?it/s]

Predicting: 29it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 29it [00:00, ?it/s]

[I 2026-03-07 19:20:38,205] Trial 0 finished with value: 9.531885186919546 and parameters: {'lag_temp_max': 27, 'lag_temp_min': 11, 'lag_snowfall': 5, 'n_lags': 14, 'epochs': 200, 'learning_rate': 0.08140540151843777, 'batch_size': 77, 'ar_reg': 0.9498741065654785}. Best is trial 0 with value: 9.531885186919546.

Training: 0it [00:00, ?it/s]

Predicting: 21it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 22it [00:00, ?it/s]

[I 2026-03-07 19:21:34,762] Trial 1 finished with value: 10.704722568633105 and parameters: {'lag_temp_max': 18, 'lag_temp_min': 17, 'lag_snowfall': 4, 'n_lags': 6, 'epochs': 214, 'learning_rate': 0.2127885328025326, 'batch_size': 105, 'ar_reg': 2.1563048028645295}. Best is trial 0 with value: 9.531885186919546.

Training: 0it [00:00, ?it/s]

Predicting: 30it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 30it [00:00, ?it/s]

[I 2026-03-07 19:22:02,421] Trial 2 finished with value: 13.931941167934554 and parameters: {'lag_temp_max': 19, 'lag_temp_min': 21, 'lag_snowfall': 7, 'n_lags': 1, 'epochs': 95, 'learning_rate': 0.3246070950362632, 'batch_size': 74, 'ar_reg': 0.9246486617990869}. Best is trial 0 with value: 9.531885186919546.

Training: 0it [00:00, ?it/s]

Predicting: 23it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 23it [00:00, ?it/s]

[I 2026-03-07 19:22:53,899] Trial 3 finished with value: 12.337938579064687 and parameters: {'lag_temp_max': 27, 'lag_temp_min': 25, 'lag_snowfall': 2, 'n_lags': 12, 'epochs': 182, 'learning_rate': 0.0020632953486835735, 'batch_size': 99, 'ar_reg': 2.468179287547447}. Best is trial 0 with value: 9.531885186919546.

Training: 0it [00:00, ?it/s]

Predicting: 64it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 64it [00:00, ?it/s]

[I 2026-03-07 19:24:21,047] Trial 4 finished with value: 11.94801366101946 and parameters: {'lag_temp_max': 5, 'lag_temp_min': 4, 'lag_snowfall': 4, 'n_lags': 7, 'epochs': 147, 'learning_rate': 0.3971007233833884, 'batch_size': 35, 'ar_reg': 2.7903152778619615}. Best is trial 0 with value: 9.531885186919546.

Training: 0it [00:00, ?it/s]

Predicting: 25it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 25it [00:00, ?it/s]

[I 2026-03-07 19:25:27,790] Trial 5 finished with value: 11.34487807068725 and parameters: {'lag_temp_max': 6, 'lag_temp_min': 30, 'lag_snowfall': 3, 'n_lags': 19, 'epochs': 204, 'learning_rate': 0.0025086418800728057, 'batch_size': 91, 'ar_reg': 1.2135887901758806}. Best is trial 0 with value: 9.531885186919546.

Training: 0it [00:00, ?it/s]

Predicting: 20it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 21it [00:00, ?it/s]

[I 2026-03-07 19:26:15,166] Trial 6 finished with value: 9.251665611844814 and parameters: {'lag_temp_max': 25, 'lag_temp_min': 12, 'lag_snowfall': 1, 'n_lags': 15, 'epochs': 182, 'learning_rate': 0.03645710804565232, 'batch_size': 110, 'ar_reg': 0.9999295359602371}. Best is trial 6 with value: 9.251665611844814.

Training: 0it [00:00, ?it/s]

Predicting: 21it [00:00, ?it/s]

[I 2026-03-07 19:26:42,461] Trial 7 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 21it [00:00, ?it/s]

[I 2026-03-07 19:26:55,770] Trial 8 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 41it [00:00, ?it/s]

[I 2026-03-07 19:27:28,867] Trial 9 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 18it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 19it [00:00, ?it/s]

[I 2026-03-07 19:28:09,058] Trial 10 finished with value: 9.227026150688255 and parameters: {'lag_temp_max': 12, 'lag_temp_min': 3, 'lag_snowfall': 2, 'n_lags': 21, 'epochs': 137, 'learning_rate': 0.03487797210357714, 'batch_size': 123, 'ar_reg': 0.638256319620671}. Best is trial 10 with value: 9.227026150688255.

Training: 0it [00:00, ?it/s]

Predicting: 18it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 18it [00:00, ?it/s]

[I 2026-03-07 19:28:51,432] Trial 11 finished with value: 9.056933083384545 and parameters: {'lag_temp_max': 13, 'lag_temp_min': 1, 'lag_snowfall': 2, 'n_lags': 21, 'epochs': 135, 'learning_rate': 0.03752727977662611, 'batch_size': 128, 'ar_reg': 0.5844419903328935}. Best is trial 11 with value: 9.056933083384545.

Training: 0it [00:00, ?it/s]

Predicting: 18it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 18it [00:00, ?it/s]

[I 2026-03-07 19:29:30,767] Trial 12 finished with value: 9.034599845688078 and parameters: {'lag_temp_max': 12, 'lag_temp_min': 2, 'lag_snowfall': 3, 'n_lags': 21, 'epochs': 126, 'learning_rate': 0.015763083161719326, 'batch_size': 124, 'ar_reg': 0.5218675786062648}. Best is trial 12 with value: 9.034599845688078.

Training: 0it [00:00, ?it/s]

Predicting: 18it [00:00, ?it/s]

[I 2026-03-07 19:29:39,677] Trial 13 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 18it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 18it [00:00, ?it/s]

[I 2026-03-07 19:30:18,185] Trial 14 finished with value: 10.28654714347965 and parameters: {'lag_temp_max': 10, 'lag_temp_min': 6, 'lag_snowfall': 5, 'n_lags': 21, 'epochs': 119, 'learning_rate': 0.08799746143622045, 'batch_size': 124, 'ar_reg': 1.8286548198017083}. Best is trial 12 with value: 9.034599845688078.

Training: 0it [00:00, ?it/s]

Predicting: 106it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 106it [00:00, ?it/s]

[I 2026-03-07 19:32:13,929] Trial 15 finished with value: 9.663932443233332 and parameters: {'lag_temp_max': 14, 'lag_temp_min': 7, 'lag_snowfall': 3, 'n_lags': 17, 'epochs': 112, 'learning_rate': 0.007373995272892206, 'batch_size': 21, 'ar_reg': 1.706064847520069}. Best is trial 12 with value: 9.034599845688078.

Training: 0it [00:00, ?it/s]

Predicting: 26it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 26it [00:00, ?it/s]

[I 2026-03-07 19:32:35,057] Trial 16 finished with value: 9.502502023898797 and parameters: {'lag_temp_max': 1, 'lag_temp_min': 1, 'lag_snowfall': 2, 'n_lags': 10, 'epochs': 60, 'learning_rate': 0.07898122637200931, 'batch_size': 86, 'ar_reg': 0.7160325279818618}. Best is trial 12 with value: 9.034599845688078.

Training: 0it [00:00, ?it/s]

Predicting: 37it [00:00, ?it/s]

[I 2026-03-07 19:33:31,446] Trial 17 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 19it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 19it [00:00, ?it/s]

[I 2026-03-07 19:34:08,431] Trial 18 finished with value: 9.749130899486737 and parameters: {'lag_temp_max': 15, 'lag_temp_min': 15, 'lag_snowfall': 3, 'n_lags': 16, 'epochs': 127, 'learning_rate': 0.006493915514512913, 'batch_size': 118, 'ar_reg': 0.5405250183992487}. Best is trial 12 with value: 9.034599845688078.

Training: 0it [00:00, ?it/s]

Predicting: 24it [00:00, ?it/s]

[I 2026-03-07 19:34:33,379] Trial 19 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 38it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 39it [00:00, ?it/s]

[I 2026-03-07 19:35:17,933] Trial 20 finished with value: 9.6908070138065 and parameters: {'lag_temp_max': 30, 'lag_temp_min': 8, 'lag_snowfall': 6, 'n_lags': 21, 'epochs': 97, 'learning_rate': 0.026753666600592696, 'batch_size': 58, 'ar_reg': 1.3539407684487705}. Best is trial 12 with value: 9.034599845688078.

Training: 0it [00:00, ?it/s]

Predicting: 19it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 19it [00:00, ?it/s]

[I 2026-03-07 19:36:04,081] Trial 21 finished with value: 9.204479082006642 and parameters: {'lag_temp_max': 12, 'lag_temp_min': 3, 'lag_snowfall': 2, 'n_lags': 21, 'epochs': 137, 'learning_rate': 0.046972188517618856, 'batch_size': 118, 'ar_reg': 0.6452936842707908}. Best is trial 12 with value: 9.034599845688078.

Training: 0it [00:00, ?it/s]

Predicting: 20it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 20it [00:00, ?it/s]

[I 2026-03-07 19:36:57,674] Trial 22 finished with value: 9.478763994917909 and parameters: {'lag_temp_max': 8, 'lag_temp_min': 3, 'lag_snowfall': 2, 'n_lags': 19, 'epochs': 149, 'learning_rate': 0.05833353479527406, 'batch_size': 115, 'ar_reg': 0.7386753691119377}. Best is trial 12 with value: 9.034599845688078.

Training: 0it [00:00, ?it/s]

Predicting: 18it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 18it [00:00, ?it/s]

[I 2026-03-07 19:37:23,437] Trial 23 finished with value: 9.552044374404323 and parameters: {'lag_temp_max': 13, 'lag_temp_min': 1, 'lag_snowfall': 3, 'n_lags': 21, 'epochs': 74, 'learning_rate': 0.12213764300103523, 'batch_size': 127, 'ar_reg': 0.7750563207027225}. Best is trial 12 with value: 9.034599845688078.

Training: 0it [00:00, ?it/s]

Predicting: 20it [00:00, ?it/s]

[I 2026-03-07 19:37:43,907] Trial 24 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 22it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 22it [00:00, ?it/s]

[I 2026-03-07 19:38:28,278] Trial 25 finished with value: 9.487865143084003 and parameters: {'lag_temp_max': 17, 'lag_temp_min': 8, 'lag_snowfall': 4, 'n_lags': 19, 'epochs': 138, 'learning_rate': 0.05096677591887544, 'batch_size': 101, 'ar_reg': 1.1743239442419808}. Best is trial 12 with value: 9.034599845688078.

Training: 0it [00:00, ?it/s]

Predicting: 19it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 19it [00:00, ?it/s]

[I 2026-03-07 19:39:26,006] Trial 26 finished with value: 9.387105781623703 and parameters: {'lag_temp_max': 11, 'lag_temp_min': 1, 'lag_snowfall': 2, 'n_lags': 20, 'epochs': 166, 'learning_rate': 0.1627500376724429, 'batch_size': 117, 'ar_reg': 1.6871160964821164}. Best is trial 12 with value: 9.034599845688078.

Training: 0it [00:00, ?it/s]

Predicting: 23it [00:00, ?it/s]

[I 2026-03-07 19:39:46,734] Trial 27 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 28it [00:00, ?it/s]

[I 2026-03-07 19:40:00,158] Trial 28 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 20it [00:00, ?it/s]

[I 2026-03-07 19:40:25,458] Trial 29 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 34it [00:00, ?it/s]

[I 2026-03-07 19:40:46,214] Trial 30 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 19it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 19it [00:00, ?it/s]

[I 2026-03-07 19:41:33,746] Trial 31 finished with value: 9.18802640727358 and parameters: {'lag_temp_max': 12, 'lag_temp_min': 3, 'lag_snowfall': 2, 'n_lags': 21, 'epochs': 137, 'learning_rate': 0.03304300459823824, 'batch_size': 121, 'ar_reg': 0.6508042802489706}. Best is trial 12 with value: 9.034599845688078.

Training: 0it [00:00, ?it/s]

Predicting: 19it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 19it [00:00, ?it/s]

[I 2026-03-07 19:42:26,181] Trial 32 finished with value: 9.104164407383092 and parameters: {'lag_temp_max': 9, 'lag_temp_min': 5, 'lag_snowfall': 2, 'n_lags': 20, 'epochs': 157, 'learning_rate': 0.01714322674636074, 'batch_size': 122, 'ar_reg': 0.5043229450091331}. Best is trial 12 with value: 9.034599845688078.

Training: 0it [00:00, ?it/s]

Predicting: 18it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 18it [00:00, ?it/s]

[I 2026-03-07 19:43:16,810] Trial 33 finished with value: 9.026577503212964 and parameters: {'lag_temp_max': 8, 'lag_temp_min': 18, 'lag_snowfall': 3, 'n_lags': 18, 'epochs': 155, 'learning_rate': 0.01641809551910393, 'batch_size': 128, 'ar_reg': 0.894973201253765}. Best is trial 33 with value: 9.026577503212964.

Training: 0it [00:00, ?it/s]

Predicting: 18it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 18it [00:00, ?it/s]

[I 2026-03-07 19:44:07,340] Trial 34 finished with value: 9.16314588217755 and parameters: {'lag_temp_max': 9, 'lag_temp_min': 18, 'lag_snowfall': 3, 'n_lags': 18, 'epochs': 157, 'learning_rate': 0.013221496713795146, 'batch_size': 127, 'ar_reg': 0.8922453923653025}. Best is trial 33 with value: 9.026577503212964.

Training: 0it [00:00, ?it/s]

Predicting: 22it [00:00, ?it/s]

[I 2026-03-07 19:44:40,690] Trial 35 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 18it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 18it [00:00, ?it/s]

[I 2026-03-07 19:45:45,444] Trial 36 finished with value: 8.766892181620866 and parameters: {'lag_temp_max': 4, 'lag_temp_min': 18, 'lag_snowfall': 3, 'n_lags': 18, 'epochs': 193, 'learning_rate': 0.021723187504496866, 'batch_size': 128, 'ar_reg': 0.8599373931610116}. Best is trial 36 with value: 8.766892181620866.

Training: 0it [00:00, ?it/s]

Predicting: 18it [00:00, ?it/s]

[I 2026-03-07 19:46:17,162] Trial 37 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 49it [00:00, ?it/s]

[I 2026-03-07 19:47:09,839] Trial 38 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 20it [00:00, ?it/s]

[I 2026-03-07 19:47:43,052] Trial 39 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 22it [00:00, ?it/s]

[I 2026-03-07 19:48:11,882] Trial 40 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 19it [00:00, ?it/s]

[I 2026-03-07 19:48:38,834] Trial 41 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 19it [00:00, ?it/s]

[I 2026-03-07 19:49:09,015] Trial 42 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 21it [00:00, ?it/s]

[I 2026-03-07 19:49:31,419] Trial 43 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 20it [00:00, ?it/s]

[I 2026-03-07 19:50:08,542] Trial 44 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 18it [00:00, ?it/s]

[I 2026-03-07 19:50:32,914] Trial 45 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 21it [00:00, ?it/s]

[I 2026-03-07 19:50:51,634] Trial 46 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 18it [00:00, ?it/s]

[I 2026-03-07 19:51:14,023] Trial 47 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 30it [00:00, ?it/s]

[I 2026-03-07 19:51:53,056] Trial 48 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 19it [00:00, ?it/s]

[I 2026-03-07 19:52:23,224] Trial 49 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 24it [00:00, ?it/s]

[I 2026-03-07 19:53:01,991] Trial 50 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 18it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 18it [00:00, ?it/s]

[I 2026-03-07 19:53:59,610] Trial 51 finished with value: 9.689737147706012 and parameters: {'lag_temp_max': 9, 'lag_temp_min': 17, 'lag_snowfall': 3, 'n_lags': 18, 'epochs': 158, 'learning_rate': 0.014814366290278658, 'batch_size': 125, 'ar_reg': 0.9087075136192235}. Best is trial 36 with value: 8.766892181620866.

Training: 0it [00:00, ?it/s]

Predicting: 18it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 18it [00:00, ?it/s]

[I 2026-03-07 19:54:53,568] Trial 52 finished with value: 10.232895489290296 and parameters: {'lag_temp_max': 11, 'lag_temp_min': 18, 'lag_snowfall': 3, 'n_lags': 20, 'epochs': 145, 'learning_rate': 0.014041162453398759, 'batch_size': 128, 'ar_reg': 0.8069920627236182}. Best is trial 36 with value: 8.766892181620866.

Training: 0it [00:00, ?it/s]

Predicting: 18it [00:00, ?it/s]

[I 2026-03-07 19:55:23,406] Trial 53 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 20it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 20it [00:00, ?it/s]

[I 2026-03-07 19:56:06,679] Trial 54 finished with value: 9.536563462827576 and parameters: {'lag_temp_max': 8, 'lag_temp_min': 17, 'lag_snowfall': 4, 'n_lags': 15, 'epochs': 132, 'learning_rate': 0.01136617234704113, 'batch_size': 114, 'ar_reg': 1.0596700638394783}. Best is trial 36 with value: 8.766892181620866.

Training: 0it [00:00, ?it/s]

Predicting: 19it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 19it [00:00, ?it/s]

[I 2026-03-07 19:56:45,594] Trial 55 finished with value: 9.022399729636223 and parameters: {'lag_temp_max': 11, 'lag_temp_min': 10, 'lag_snowfall': 2, 'n_lags': 13, 'epochs': 120, 'learning_rate': 0.0278312539280738, 'batch_size': 121, 'ar_reg': 0.8465757660353456}. Best is trial 36 with value: 8.766892181620866.

Training: 0it [00:00, ?it/s]

Predicting: 19it [00:00, ?it/s]

[I 2026-03-07 19:57:05,979] Trial 56 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 18it [00:00, ?it/s]

[I 2026-03-07 19:57:23,315] Trial 57 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 93it [00:00, ?it/s]

[I 2026-03-07 19:58:09,014] Trial 58 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 21it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 21it [00:00, ?it/s]

[I 2026-03-07 19:59:04,535] Trial 59 finished with value: 9.193629467516466 and parameters: {'lag_temp_max': 16, 'lag_temp_min': 7, 'lag_snowfall': 2, 'n_lags': 21, 'epochs': 116, 'learning_rate': 0.02836533064202492, 'batch_size': 108, 'ar_reg': 0.8374156232940908}. Best is trial 36 with value: 8.766892181620866.

Training: 0it [00:00, ?it/s]

Predicting: 19it [00:00, ?it/s]

[I 2026-03-07 19:59:35,727] Trial 60 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 18it [00:00, ?it/s]

[I 2026-03-07 20:00:09,877] Trial 61 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 19it [00:00, ?it/s]

[I 2026-03-07 20:00:41,596] Trial 62 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 20it [00:00, ?it/s]

[I 2026-03-07 20:01:09,401] Trial 63 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 18it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 18it [00:00, ?it/s]

[I 2026-03-07 20:02:11,660] Trial 64 finished with value: 9.023406031435933 and parameters: {'lag_temp_max': 5, 'lag_temp_min': 20, 'lag_snowfall': 2, 'n_lags': 21, 'epochs': 162, 'learning_rate': 0.012704590895761028, 'batch_size': 125, 'ar_reg': 1.0137336259930279}. Best is trial 36 with value: 8.766892181620866.

Training: 0it [00:00, ?it/s]

Predicting: 18it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 18it [00:00, ?it/s]

[I 2026-03-07 20:03:08,055] Trial 65 finished with value: 8.490668174139643 and parameters: {'lag_temp_max': 6, 'lag_temp_min': 23, 'lag_snowfall': 1, 'n_lags': 21, 'epochs': 144, 'learning_rate': 0.043752747818248686, 'batch_size': 124, 'ar_reg': 1.002719111920354}. Best is trial 65 with value: 8.490668174139643.

Training: 0it [00:00, ?it/s]

Predicting: 20it [00:00, ?it/s]

[I 2026-03-07 20:03:32,027] Trial 66 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 18it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 18it [00:00, ?it/s]

[I 2026-03-07 20:04:12,860] Trial 67 finished with value: 8.666463885643802 and parameters: {'lag_temp_max': 2, 'lag_temp_min': 21, 'lag_snowfall': 1, 'n_lags': 21, 'epochs': 105, 'learning_rate': 0.044239906021733555, 'batch_size': 125, 'ar_reg': 1.0466533603974193}. Best is trial 65 with value: 8.490668174139643.

Training: 0it [00:00, ?it/s]

Predicting: 18it [00:00, ?it/s]

[I 2026-03-07 20:04:30,620] Trial 68 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 19it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 20it [00:00, ?it/s]

[I 2026-03-07 20:05:12,413] Trial 69 finished with value: 8.756810145516344 and parameters: {'lag_temp_max': 2, 'lag_temp_min': 24, 'lag_snowfall': 1, 'n_lags': 19, 'epochs': 104, 'learning_rate': 0.04582152858101485, 'batch_size': 116, 'ar_reg': 1.2623892801725722}. Best is trial 65 with value: 8.490668174139643.

Training: 0it [00:00, ?it/s]

Predicting: 20it [00:00, ?it/s]

[I 2026-03-07 20:05:29,326] Trial 70 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 19it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 19it [00:00, ?it/s]

[I 2026-03-07 20:06:09,204] Trial 71 finished with value: 8.611360212270561 and parameters: {'lag_temp_max': 4, 'lag_temp_min': 20, 'lag_snowfall': 1, 'n_lags': 19, 'epochs': 100, 'learning_rate': 0.050507584624469415, 'batch_size': 118, 'ar_reg': 1.0935586894245812}. Best is trial 65 with value: 8.490668174139643.

Training: 0it [00:00, ?it/s]

Predicting: 19it [00:00, ?it/s]

[I 2026-03-07 20:06:23,897] Trial 72 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 20it [00:00, ?it/s]

[I 2026-03-07 20:06:41,520] Trial 73 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 19it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 19it [00:00, ?it/s]

[I 2026-03-07 20:07:13,760] Trial 74 finished with value: 8.661810706574425 and parameters: {'lag_temp_max': 5, 'lag_temp_min': 20, 'lag_snowfall': 1, 'n_lags': 19, 'epochs': 80, 'learning_rate': 0.13416585420958235, 'batch_size': 120, 'ar_reg': 1.427014030188003}. Best is trial 65 with value: 8.490668174139643.

Training: 0it [00:00, ?it/s]

Predicting: 22it [00:00, ?it/s]

[I 2026-03-07 20:07:27,524] Trial 75 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 19it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 19it [00:00, ?it/s]

[I 2026-03-07 20:08:00,595] Trial 76 finished with value: 9.120317583758005 and parameters: {'lag_temp_max': 2, 'lag_temp_min': 21, 'lag_snowfall': 1, 'n_lags': 20, 'epochs': 82, 'learning_rate': 0.14144732709700686, 'batch_size': 120, 'ar_reg': 1.5578467426097231}. Best is trial 65 with value: 8.490668174139643.

Training: 0it [00:00, ?it/s]

Predicting: 33it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 33it [00:00, ?it/s]

[I 2026-03-07 20:08:45,177] Trial 77 finished with value: 8.969784312100286 and parameters: {'lag_temp_max': 6, 'lag_temp_min': 27, 'lag_snowfall': 1, 'n_lags': 21, 'epochs': 93, 'learning_rate': 0.29005479661772937, 'batch_size': 67, 'ar_reg': 1.1826398461131657}. Best is trial 65 with value: 8.490668174139643.

Training: 0it [00:00, ?it/s]

Predicting: 36it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 37it [00:00, ?it/s]

[I 2026-03-07 20:09:33,085] Trial 78 finished with value: 9.229108971686326 and parameters: {'lag_temp_max': 4, 'lag_temp_min': 29, 'lag_snowfall': 1, 'n_lags': 20, 'epochs': 94, 'learning_rate': 0.3597281551402956, 'batch_size': 61, 'ar_reg': 1.203261378685445}. Best is trial 65 with value: 8.490668174139643.

Training: 0it [00:00, ?it/s]

Predicting: 48it [00:00, ?it/s]

[I 2026-03-07 20:09:54,105] Trial 79 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 33it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 33it [00:00, ?it/s]

[I 2026-03-07 20:10:41,822] Trial 80 finished with value: 9.067431019179669 and parameters: {'lag_temp_max': 6, 'lag_temp_min': 26, 'lag_snowfall': 1, 'n_lags': 21, 'epochs': 100, 'learning_rate': 0.46009450735554713, 'batch_size': 67, 'ar_reg': 1.2678390909686759}. Best is trial 65 with value: 8.490668174139643.

Training: 0it [00:00, ?it/s]

Predicting: 28it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 28it [00:00, ?it/s]

[I 2026-03-07 20:11:20,022] Trial 81 finished with value: 8.299791965370568 and parameters: {'lag_temp_max': 5, 'lag_temp_min': 20, 'lag_snowfall': 1, 'n_lags': 21, 'epochs': 89, 'learning_rate': 0.3136587720781301, 'batch_size': 80, 'ar_reg': 1.1701360120475477}. Best is trial 81 with value: 8.299791965370568.

Training: 0it [00:00, ?it/s]

Predicting: 33it [00:00, ?it/s]

[I 2026-03-07 20:11:40,649] Trial 82 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 31it [00:00, ?it/s]

[I 2026-03-07 20:12:01,745] Trial 83 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 42it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 42it [00:00, ?it/s]

[I 2026-03-07 20:12:31,605] Trial 84 finished with value: 8.487391713245879 and parameters: {'lag_temp_max': 6, 'lag_temp_min': 24, 'lag_snowfall': 1, 'n_lags': 21, 'epochs': 51, 'learning_rate': 0.2642886131501327, 'batch_size': 53, 'ar_reg': 1.1114410262048446}. Best is trial 81 with value: 8.299791965370568.

Training: 0it [00:00, ?it/s]

Predicting: 27it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 27it [00:00, ?it/s]

[I 2026-03-07 20:13:06,328] Trial 85 finished with value: 8.610250804508194 and parameters: {'lag_temp_max': 6, 'lag_temp_min': 24, 'lag_snowfall': 1, 'n_lags': 21, 'epochs': 81, 'learning_rate': 0.28097286998027876, 'batch_size': 84, 'ar_reg': 1.8281520472014363}. Best is trial 81 with value: 8.299791965370568.

Training: 0it [00:00, ?it/s]

Predicting: 28it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 28it [00:00, ?it/s]

[I 2026-03-07 20:13:31,062] Trial 86 finished with value: 8.305826878106364 and parameters: {'lag_temp_max': 1, 'lag_temp_min': 24, 'lag_snowfall': 1, 'n_lags': 19, 'epochs': 55, 'learning_rate': 0.2588787250573518, 'batch_size': 81, 'ar_reg': 1.857027454885108}. Best is trial 81 with value: 8.299791965370568.

Training: 0it [00:00, ?it/s]

Predicting: 27it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 27it [00:00, ?it/s]

[I 2026-03-07 20:13:55,142] Trial 87 finished with value: 9.302834169861994 and parameters: {'lag_temp_max': 1, 'lag_temp_min': 24, 'lag_snowfall': 1, 'n_lags': 19, 'epochs': 56, 'learning_rate': 0.2534416943984626, 'batch_size': 82, 'ar_reg': 1.8883781075588917}. Best is trial 81 with value: 8.299791965370568.

Training: 0it [00:00, ?it/s]

Predicting: 26it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 26it [00:00, ?it/s]

[I 2026-03-07 20:14:17,922] Trial 88 finished with value: 9.328090596229055 and parameters: {'lag_temp_max': 3, 'lag_temp_min': 24, 'lag_snowfall': 1, 'n_lags': 21, 'epochs': 52, 'learning_rate': 0.3961173944381103, 'batch_size': 86, 'ar_reg': 1.796174610533321}. Best is trial 81 with value: 8.299791965370568.

Training: 0it [00:00, ?it/s]

Predicting: 29it [00:00, ?it/s]

[I 2026-03-07 20:14:32,671] Trial 89 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 25it [00:00, ?it/s]

[I 2026-03-07 20:14:49,166] Trial 90 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 28it [00:00, ?it/s]

[I 2026-03-07 20:15:03,042] Trial 91 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 26it [00:00, ?it/s]

[I 2026-03-07 20:15:15,201] Trial 92 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 45it [00:00, ?it/s]

[I 2026-03-07 20:15:28,934] Trial 93 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 29it [00:00, ?it/s]

[I 2026-03-07 20:15:40,628] Trial 94 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 25it [00:00, ?it/s]

[I 2026-03-07 20:15:55,040] Trial 95 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 41it [00:00, ?it/s]

[I 2026-03-07 20:16:17,046] Trial 96 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 71it [00:00, ?it/s]

[I 2026-03-07 20:16:57,507] Trial 97 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 58it [00:00, ?it/s]

[I 2026-03-07 20:17:22,157] Trial 98 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 24it [00:00, ?it/s]

[I 2026-03-07 20:17:33,943] Trial 99 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 32it [00:00, ?it/s]

[I 2026-03-07 20:17:55,168] Trial 100 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 36it [00:00, ?it/s]

[I 2026-03-07 20:18:20,643] Trial 101 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 28it [00:00, ?it/s]

[I 2026-03-07 20:18:44,478] Trial 102 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 30it [00:00, ?it/s]

[I 2026-03-07 20:19:06,841] Trial 103 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 35it [00:00, ?it/s]

[I 2026-03-07 20:19:28,111] Trial 104 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 43it [00:00, ?it/s]

[I 2026-03-07 20:19:55,467] Trial 105 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 26it [00:00, ?it/s]

[I 2026-03-07 20:20:18,492] Trial 106 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 29it [00:00, ?it/s]

[I 2026-03-07 20:20:38,027] Trial 107 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 38it [00:00, ?it/s]

[I 2026-03-07 20:21:41,928] Trial 108 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 18it [00:00, ?it/s]

[I 2026-03-07 20:21:55,235] Trial 109 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 32it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 32it [00:00, ?it/s]

[I 2026-03-07 20:22:49,303] Trial 110 finished with value: 8.867146069356263 and parameters: {'lag_temp_max': 2, 'lag_temp_min': 27, 'lag_snowfall': 1, 'n_lags': 20, 'epochs': 111, 'learning_rate': 0.28195873832800716, 'batch_size': 70, 'ar_reg': 1.1919934839096717}. Best is trial 81 with value: 8.299791965370568.

Training: 0it [00:00, ?it/s]

Predicting: 31it [00:00, ?it/s]

[I 2026-03-07 20:23:15,208] Trial 111 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 38it [00:00, ?it/s]

[I 2026-03-07 20:23:41,224] Trial 112 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 54it [00:00, ?it/s]

[I 2026-03-07 20:24:14,961] Trial 113 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 18it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 18it [00:00, ?it/s]

[I 2026-03-07 20:25:01,545] Trial 114 finished with value: 8.709901335930553 and parameters: {'lag_temp_max': 5, 'lag_temp_min': 28, 'lag_snowfall': 1, 'n_lags': 21, 'epochs': 112, 'learning_rate': 0.024591730842523966, 'batch_size': 123, 'ar_reg': 1.0101391691521124}. Best is trial 81 with value: 8.299791965370568.

Training: 0it [00:00, ?it/s]

Predicting: 18it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 19it [00:00, ?it/s]

[I 2026-03-07 20:25:51,026] Trial 115 finished with value: 9.208761402754043 and parameters: {'lag_temp_max': 1, 'lag_temp_min': 29, 'lag_snowfall': 1, 'n_lags': 20, 'epochs': 119, 'learning_rate': 0.02329492199410941, 'batch_size': 122, 'ar_reg': 1.0052024662612649}. Best is trial 81 with value: 8.299791965370568.

Training: 0it [00:00, ?it/s]

Predicting: 19it [00:00, ?it/s]

[I 2026-03-07 20:26:07,674] Trial 116 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 19it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 20it [00:00, ?it/s]

[I 2026-03-07 20:27:02,828] Trial 117 finished with value: 8.782642563575546 and parameters: {'lag_temp_max': 2, 'lag_temp_min': 18, 'lag_snowfall': 1, 'n_lags': 21, 'epochs': 127, 'learning_rate': 0.03296076175455959, 'batch_size': 116, 'ar_reg': 1.7364775289855994}. Best is trial 81 with value: 8.299791965370568.

Training: 0it [00:00, ?it/s]

Predicting: 20it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 20it [00:00, ?it/s]

[I 2026-03-07 20:27:57,743] Trial 118 finished with value: 8.712990567967045 and parameters: {'lag_temp_max': 4, 'lag_temp_min': 16, 'lag_snowfall': 1, 'n_lags': 21, 'epochs': 125, 'learning_rate': 0.02961201044020915, 'batch_size': 114, 'ar_reg': 2.061973226171963}. Best is trial 81 with value: 8.299791965370568.

Training: 0it [00:00, ?it/s]

Predicting: 20it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 20it [00:00, ?it/s]

[I 2026-03-07 20:28:59,058] Trial 119 finished with value: 9.136962236471788 and parameters: {'lag_temp_max': 4, 'lag_temp_min': 17, 'lag_snowfall': 2, 'n_lags': 21, 'epochs': 141, 'learning_rate': 0.027593997424207442, 'batch_size': 114, 'ar_reg': 2.0474071281845614}. Best is trial 81 with value: 8.299791965370568.

Training: 0it [00:00, ?it/s]

Predicting: 18it [00:00, ?it/s]

[I 2026-03-07 20:29:19,799] Trial 120 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 19it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 20it [00:00, ?it/s]

[I 2026-03-07 20:30:14,827] Trial 121 finished with value: 8.623559219238397 and parameters: {'lag_temp_max': 3, 'lag_temp_min': 18, 'lag_snowfall': 1, 'n_lags': 21, 'epochs': 129, 'learning_rate': 0.031559247983838495, 'batch_size': 116, 'ar_reg': 1.9281072349162178}. Best is trial 81 with value: 8.299791965370568.

Training: 0it [00:00, ?it/s]

Predicting: 20it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 20it [00:00, ?it/s]

[I 2026-03-07 20:31:09,521] Trial 122 finished with value: 8.89653423673595 and parameters: {'lag_temp_max': 4, 'lag_temp_min': 20, 'lag_snowfall': 1, 'n_lags': 21, 'epochs': 125, 'learning_rate': 0.0411730793867316, 'batch_size': 111, 'ar_reg': 1.8948583180267293}. Best is trial 81 with value: 8.299791965370568.

Training: 0it [00:00, ?it/s]

Predicting: 19it [00:00, ?it/s]

[I 2026-03-07 20:31:37,655] Trial 123 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 19it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 19it [00:00, ?it/s]

[I 2026-03-07 20:32:28,947] Trial 124 finished with value: 8.912424926881062 and parameters: {'lag_temp_max': 5, 'lag_temp_min': 18, 'lag_snowfall': 1, 'n_lags': 21, 'epochs': 122, 'learning_rate': 0.020262359049052443, 'batch_size': 117, 'ar_reg': 1.809607296894998}. Best is trial 81 with value: 8.299791965370568.

Training: 0it [00:00, ?it/s]

Predicting: 21it [00:00, ?it/s]

[I 2026-03-07 20:32:50,481] Trial 125 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 18it [00:00, ?it/s]

[I 2026-03-07 20:33:11,022] Trial 126 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 19it [00:00, ?it/s]

[I 2026-03-07 20:33:38,527] Trial 127 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 20it [00:00, ?it/s]

[I 2026-03-07 20:34:08,474] Trial 128 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 21it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 21it [00:00, ?it/s]

[I 2026-03-07 20:35:05,908] Trial 129 finished with value: 9.004686913969831 and parameters: {'lag_temp_max': 4, 'lag_temp_min': 14, 'lag_snowfall': 1, 'n_lags': 21, 'epochs': 128, 'learning_rate': 0.045533244426776684, 'batch_size': 110, 'ar_reg': 1.8944675681925471}. Best is trial 81 with value: 8.299791965370568.

Training: 0it [00:00, ?it/s]

Predicting: 18it [00:00, ?it/s]

[I 2026-03-07 20:35:16,333] Trial 130 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 19it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 20it [00:00, ?it/s]

[I 2026-03-07 20:36:05,056] Trial 131 finished with value: 8.909997800659642 and parameters: {'lag_temp_max': 2, 'lag_temp_min': 18, 'lag_snowfall': 1, 'n_lags': 21, 'epochs': 127, 'learning_rate': 0.03550806211079407, 'batch_size': 116, 'ar_reg': 1.9739875399790623}. Best is trial 81 with value: 8.299791965370568.

Training: 0it [00:00, ?it/s]

Predicting: 18it [00:00, ?it/s]

[I 2026-03-07 20:36:26,825] Trial 132 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 19it [00:00, ?it/s]

[I 2026-03-07 20:36:52,175] Trial 133 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 19it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 19it [00:00, ?it/s]

[I 2026-03-07 20:37:34,882] Trial 134 finished with value: 8.200483710548522 and parameters: {'lag_temp_max': 2, 'lag_temp_min': 19, 'lag_snowfall': 1, 'n_lags': 21, 'epochs': 120, 'learning_rate': 0.048538319954256746, 'batch_size': 122, 'ar_reg': 1.7207528895993582}. Best is trial 134 with value: 8.200483710548522.

Training: 0it [00:00, ?it/s]

Predicting: 18it [00:00, ?it/s]

[I 2026-03-07 20:37:47,369] Trial 135 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 18it [00:00, ?it/s]

[I 2026-03-07 20:38:05,060] Trial 136 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 19it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 19it [00:00, ?it/s]

[I 2026-03-07 20:38:25,196] Trial 137 finished with value: 8.565564815188429 and parameters: {'lag_temp_max': 4, 'lag_temp_min': 22, 'lag_snowfall': 1, 'n_lags': 20, 'epochs': 60, 'learning_rate': 0.04888897862833028, 'batch_size': 121, 'ar_reg': 1.0377378946408033}. Best is trial 134 with value: 8.200483710548522.

Training: 0it [00:00, ?it/s]

Predicting: 25it [00:00, ?it/s]

[I 2026-03-07 20:38:34,777] Trial 138 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 28it [00:00, ?it/s]

[I 2026-03-07 20:38:53,252] Trial 139 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 19it [00:00, ?it/s]

[I 2026-03-07 20:39:05,384] Trial 140 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 19it [00:00, ?it/s]

[I 2026-03-07 20:39:13,785] Trial 141 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 18it [00:00, ?it/s]

[I 2026-03-07 20:39:27,748] Trial 142 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 19it [00:00, ?it/s]

[I 2026-03-07 20:39:40,416] Trial 143 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 20it [00:00, ?it/s]

[I 2026-03-07 20:39:58,543] Trial 144 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 19it [00:00, ?it/s]

[I 2026-03-07 20:40:07,396] Trial 145 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 18it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 18it [00:00, ?it/s]

[I 2026-03-07 20:40:26,116] Trial 146 finished with value: 9.247395518005893 and parameters: {'lag_temp_max': 3, 'lag_temp_min': 24, 'lag_snowfall': 2, 'n_lags': 21, 'epochs': 64, 'learning_rate': 0.01808891221315725, 'batch_size': 128, 'ar_reg': 0.8696587308202125}. Best is trial 134 with value: 8.200483710548522.

Training: 0it [00:00, ?it/s]

Predicting: 23it [00:00, ?it/s]

[I 2026-03-07 20:40:42,660] Trial 147 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 18it [00:00, ?it/s]

[I 2026-03-07 20:40:50,342] Trial 148 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 18it [00:00, ?it/s]

[I 2026-03-07 20:41:08,957] Trial 149 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 19it [00:00, ?it/s]

[I 2026-03-07 20:41:22,394] Trial 150 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 20it [00:00, ?it/s]

[I 2026-03-07 20:41:41,838] Trial 151 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 27it [00:00, ?it/s]

[I 2026-03-07 20:42:02,142] Trial 152 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 19it [00:00, ?it/s]

[I 2026-03-07 20:42:13,609] Trial 153 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 19it [00:00, ?it/s]

[I 2026-03-07 20:42:29,624] Trial 154 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 72it [00:00, ?it/s]

[I 2026-03-07 20:43:15,319] Trial 155 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 21it [00:00, ?it/s]

[I 2026-03-07 20:43:39,423] Trial 156 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 19it [00:00, ?it/s]

[I 2026-03-07 20:43:53,171] Trial 157 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 20it [00:00, ?it/s]

[I 2026-03-07 20:44:29,043] Trial 158 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 28it [00:00, ?it/s]

[I 2026-03-07 20:44:49,306] Trial 159 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 22it [00:00, ?it/s]

[I 2026-03-07 20:45:00,144] Trial 160 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 19it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 19it [00:00, ?it/s]

[I 2026-03-07 20:45:41,593] Trial 161 finished with value: 8.940472002038547 and parameters: {'lag_temp_max': 2, 'lag_temp_min': 29, 'lag_snowfall': 1, 'n_lags': 20, 'epochs': 111, 'learning_rate': 0.2539697098695363, 'batch_size': 118, 'ar_reg': 1.14356957509885}. Best is trial 134 with value: 8.200483710548522.

Training: 0it [00:00, ?it/s]

Predicting: 25it [00:00, ?it/s]

[I 2026-03-07 20:46:06,115] Trial 162 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 30it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 30it [00:00, ?it/s]

[I 2026-03-07 20:47:00,056] Trial 163 finished with value: 8.6882352809238 and parameters: {'lag_temp_max': 3, 'lag_temp_min': 24, 'lag_snowfall': 1, 'n_lags': 21, 'epochs': 113, 'learning_rate': 0.3033866410653288, 'batch_size': 75, 'ar_reg': 1.003896463157024}. Best is trial 134 with value: 8.200483710548522.

Training: 0it [00:00, ?it/s]

Predicting: 29it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 30it [00:00, ?it/s]

[I 2026-03-07 20:47:54,041] Trial 164 finished with value: 8.62865181083118 and parameters: {'lag_temp_max': 3, 'lag_temp_min': 24, 'lag_snowfall': 1, 'n_lags': 21, 'epochs': 118, 'learning_rate': 0.30599417715924515, 'batch_size': 76, 'ar_reg': 1.032209378083355}. Best is trial 134 with value: 8.200483710548522.

Training: 0it [00:00, ?it/s]

Predicting: 29it [00:00, ?it/s]

[I 2026-03-07 20:48:19,190] Trial 165 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 30it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 30it [00:00, ?it/s]

[I 2026-03-07 20:49:08,410] Trial 166 finished with value: 8.50876014332778 and parameters: {'lag_temp_max': 4, 'lag_temp_min': 25, 'lag_snowfall': 1, 'n_lags': 21, 'epochs': 107, 'learning_rate': 0.4194271416981137, 'batch_size': 74, 'ar_reg': 1.0738906373702872}. Best is trial 134 with value: 8.200483710548522.

Training: 0it [00:00, ?it/s]

Predicting: 31it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 31it [00:00, ?it/s]

[I 2026-03-07 20:50:01,115] Trial 167 finished with value: 8.733273653193809 and parameters: {'lag_temp_max': 3, 'lag_temp_min': 24, 'lag_snowfall': 1, 'n_lags': 21, 'epochs': 107, 'learning_rate': 0.39435788251704074, 'batch_size': 72, 'ar_reg': 1.0411608237737329}. Best is trial 134 with value: 8.200483710548522.

Training: 0it [00:00, ?it/s]

Predicting: 31it [00:00, ?it/s]

[I 2026-03-07 20:50:27,442] Trial 168 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 29it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 30it [00:00, ?it/s]

[I 2026-03-07 20:51:21,238] Trial 169 finished with value: 11.677503458261066 and parameters: {'lag_temp_max': 3, 'lag_temp_min': 23, 'lag_snowfall': 1, 'n_lags': 21, 'epochs': 118, 'learning_rate': 0.4925935321404247, 'batch_size': 76, 'ar_reg': 0.9157069718571389}. Best is trial 134 with value: 8.200483710548522.

Training: 0it [00:00, ?it/s]

Predicting: 28it [00:00, ?it/s]

[I 2026-03-07 20:51:45,013] Trial 170 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 29it [00:00, ?it/s]

[I 2026-03-07 20:52:07,158] Trial 171 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 28it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 28it [00:00, ?it/s]

[I 2026-03-07 20:52:50,426] Trial 172 finished with value: 9.873828908491618 and parameters: {'lag_temp_max': 5, 'lag_temp_min': 25, 'lag_snowfall': 1, 'n_lags': 20, 'epochs': 105, 'learning_rate': 0.42140001109631897, 'batch_size': 81, 'ar_reg': 1.0919183929885048}. Best is trial 134 with value: 8.200483710548522.

Training: 0it [00:00, ?it/s]

Predicting: 32it [00:00, ?it/s]

[I 2026-03-07 20:53:15,721] Trial 173 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 30it [00:00, ?it/s]

[I 2026-03-07 20:53:37,167] Trial 174 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 28it [00:00, ?it/s]

[I 2026-03-07 20:53:54,135] Trial 175 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 27it [00:00, ?it/s]

[I 2026-03-07 20:54:13,439] Trial 176 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 31it [00:00, ?it/s]

[I 2026-03-07 20:54:33,994] Trial 177 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 35it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 35it [00:00, ?it/s]

[I 2026-03-07 20:55:27,693] Trial 178 finished with value: 8.691044379910604 and parameters: {'lag_temp_max': 5, 'lag_temp_min': 25, 'lag_snowfall': 1, 'n_lags': 20, 'epochs': 117, 'learning_rate': 0.44102806991234944, 'batch_size': 64, 'ar_reg': 1.1059827403125075}. Best is trial 134 with value: 8.200483710548522.

Training: 0it [00:00, ?it/s]

Predicting: 31it [00:00, ?it/s]

[I 2026-03-07 20:55:55,557] Trial 179 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 40it [00:00, ?it/s]

[I 2026-03-07 20:56:28,748] Trial 180 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 35it [00:00, ?it/s]

[I 2026-03-07 20:56:58,611] Trial 181 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 35it [00:00, ?it/s]

[I 2026-03-07 20:57:22,968] Trial 182 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 33it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 33it [00:00, ?it/s]

[I 2026-03-07 20:58:13,436] Trial 183 finished with value: 8.6824306722399 and parameters: {'lag_temp_max': 5, 'lag_temp_min': 22, 'lag_snowfall': 1, 'n_lags': 21, 'epochs': 111, 'learning_rate': 0.37615076131110486, 'batch_size': 68, 'ar_reg': 1.067362039874083}. Best is trial 134 with value: 8.200483710548522.

Training: 0it [00:00, ?it/s]

Predicting: 33it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 33it [00:00, ?it/s]

[I 2026-03-07 20:59:04,755] Trial 184 finished with value: 8.733474452759852 and parameters: {'lag_temp_max': 5, 'lag_temp_min': 22, 'lag_snowfall': 1, 'n_lags': 21, 'epochs': 113, 'learning_rate': 0.39101962235012183, 'batch_size': 68, 'ar_reg': 1.0590824903779552}. Best is trial 134 with value: 8.200483710548522.

Training: 0it [00:00, ?it/s]

Predicting: 34it [00:00, ?it/s]

[I 2026-03-07 20:59:29,581] Trial 185 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 29it [00:00, ?it/s]

[I 2026-03-07 20:59:58,055] Trial 186 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 32it [00:00, ?it/s]

[I 2026-03-07 21:00:21,427] Trial 187 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 31it [00:00, ?it/s]

[I 2026-03-07 21:00:40,667] Trial 188 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 33it [00:00, ?it/s]

[I 2026-03-07 21:00:53,633] Trial 189 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 30it [00:00, ?it/s]

[I 2026-03-07 21:01:20,562] Trial 190 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 32it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 33it [00:00, ?it/s]

[I 2026-03-07 21:02:11,193] Trial 191 finished with value: 8.580691715864411 and parameters: {'lag_temp_max': 5, 'lag_temp_min': 22, 'lag_snowfall': 1, 'n_lags': 21, 'epochs': 110, 'learning_rate': 0.40657421856724235, 'batch_size': 69, 'ar_reg': 1.0588239471958563}. Best is trial 134 with value: 8.200483710548522.

Training: 0it [00:00, ?it/s]

Predicting: 33it [00:00, ?it/s]

[I 2026-03-07 21:02:36,418] Trial 192 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 47it [00:00, ?it/s]

[I 2026-03-07 21:03:05,931] Trial 193 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 43it [00:00, ?it/s]

[I 2026-03-07 21:03:37,366] Trial 194 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 28it [00:00, ?it/s]

[I 2026-03-07 21:03:56,644] Trial 195 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 31it [00:00, ?it/s]

[I 2026-03-07 21:04:18,740] Trial 196 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 30it [00:00, ?it/s]

[I 2026-03-07 21:04:44,160] Trial 197 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 29it [00:00, ?it/s]

[I 2026-03-07 21:04:59,083] Trial 198 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 18it [00:00, ?it/s]

[I 2026-03-07 21:05:19,187] Trial 199 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 37it [00:00, ?it/s]

[I 2026-03-07 21:05:52,824] Trial 200 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 32it [00:00, ?it/s]

[I 2026-03-07 21:06:17,104] Trial 201 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 34it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 35it [00:00, ?it/s]

[I 2026-03-07 21:06:41,485] Trial 202 finished with value: 8.989688700253561 and parameters: {'lag_temp_max': 4, 'lag_temp_min': 22, 'lag_snowfall': 1, 'n_lags': 21, 'epochs': 50, 'learning_rate': 0.4717481929861334, 'batch_size': 65, 'ar_reg': 1.0304725007697575}. Best is trial 134 with value: 8.200483710548522.

Training: 0it [00:00, ?it/s]

Predicting: 33it [00:00, ?it/s]

[I 2026-03-07 21:07:08,771] Trial 203 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 31it [00:00, ?it/s]

[I 2026-03-07 21:07:33,752] Trial 204 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 27it [00:00, ?it/s]

[I 2026-03-07 21:07:58,735] Trial 205 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 33it [00:00, ?it/s]

[I 2026-03-07 21:08:29,382] Trial 206 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 18it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 18it [00:00, ?it/s]

[I 2026-03-07 21:08:59,625] Trial 207 finished with value: 8.98785720272863 and parameters: {'lag_temp_max': 5, 'lag_temp_min': 24, 'lag_snowfall': 1, 'n_lags': 21, 'epochs': 77, 'learning_rate': 0.3271317355175498, 'batch_size': 123, 'ar_reg': 0.984346353251311}. Best is trial 134 with value: 8.200483710548522.

Training: 0it [00:00, ?it/s]

Predicting: 31it [00:00, ?it/s]

[I 2026-03-07 21:09:26,308] Trial 208 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 38it [00:00, ?it/s]

[I 2026-03-07 21:09:50,473] Trial 209 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 19it [00:00, ?it/s]

[I 2026-03-07 21:10:10,427] Trial 210 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 19it [00:00, ?it/s]

[I 2026-03-07 21:10:32,826] Trial 211 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 29it [00:00, ?it/s]

[I 2026-03-07 21:10:53,655] Trial 212 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 32it [00:00, ?it/s]

[I 2026-03-07 21:11:18,870] Trial 213 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 18it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 18it [00:00, ?it/s]

[I 2026-03-07 21:11:41,225] Trial 214 finished with value: 8.27995640150791 and parameters: {'lag_temp_max': 2, 'lag_temp_min': 23, 'lag_snowfall': 1, 'n_lags': 21, 'epochs': 59, 'learning_rate': 0.05138137926707069, 'batch_size': 124, 'ar_reg': 1.2489276636204845}. Best is trial 134 with value: 8.200483710548522.

Training: 0it [00:00, ?it/s]

Predicting: 18it [00:00, ?it/s]

[I 2026-03-07 21:11:52,592] Trial 215 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 19it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 19it [00:00, ?it/s]

[I 2026-03-07 21:12:18,791] Trial 216 finished with value: 8.321272131906152 and parameters: {'lag_temp_max': 5, 'lag_temp_min': 23, 'lag_snowfall': 1, 'n_lags': 21, 'epochs': 68, 'learning_rate': 0.07304268178731721, 'batch_size': 121, 'ar_reg': 1.0546993846363573}. Best is trial 134 with value: 8.200483710548522.

Training: 0it [00:00, ?it/s]

Predicting: 18it [00:00, ?it/s]

[I 2026-03-07 21:12:31,472] Trial 217 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 19it [00:00, ?it/s]

[I 2026-03-07 21:12:45,174] Trial 218 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 18it [00:00, ?it/s]

[I 2026-03-07 21:12:55,663] Trial 219 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 19it [00:00, ?it/s]

[I 2026-03-07 21:13:04,436] Trial 220 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 18it [00:00, ?it/s]

[I 2026-03-07 21:13:13,998] Trial 221 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 19it [00:00, ?it/s]

[I 2026-03-07 21:13:24,689] Trial 222 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 30it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 30it [00:00, ?it/s]

[I 2026-03-07 21:13:51,998] Trial 223 finished with value: 10.618977880960948 and parameters: {'lag_temp_max': 6, 'lag_temp_min': 24, 'lag_snowfall': 1, 'n_lags': 21, 'epochs': 67, 'learning_rate': 0.33664947649437527, 'batch_size': 74, 'ar_reg': 1.0152256140703377}. Best is trial 134 with value: 8.200483710548522.

Training: 0it [00:00, ?it/s]

Predicting: 19it [00:00, ?it/s]

[I 2026-03-07 21:14:11,378] Trial 224 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 19it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 19it [00:00, ?it/s]

[I 2026-03-07 21:14:45,023] Trial 225 finished with value: 8.70335350035485 and parameters: {'lag_temp_max': 5, 'lag_temp_min': 21, 'lag_snowfall': 1, 'n_lags': 21, 'epochs': 87, 'learning_rate': 0.37156866934844923, 'batch_size': 117, 'ar_reg': 1.0681649525048857}. Best is trial 134 with value: 8.200483710548522.

Training: 0it [00:00, ?it/s]

Predicting: 19it [00:00, ?it/s]

[I 2026-03-07 21:14:57,834] Trial 226 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 19it [00:00, ?it/s]

[I 2026-03-07 21:15:11,580] Trial 227 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 19it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 19it [00:00, ?it/s]

[I 2026-03-07 21:15:44,693] Trial 228 finished with value: 8.149892569607967 and parameters: {'lag_temp_max': 6, 'lag_temp_min': 25, 'lag_snowfall': 1, 'n_lags': 21, 'epochs': 87, 'learning_rate': 0.3208297495494284, 'batch_size': 122, 'ar_reg': 1.0892333159676995}. Best is trial 228 with value: 8.149892569607967.

Training: 0it [00:00, ?it/s]

Predicting: 18it [00:00, ?it/s]

[I 2026-03-07 21:16:01,012] Trial 229 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 18it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 18it [00:00, ?it/s]

[I 2026-03-07 21:16:32,441] Trial 230 finished with value: 8.378547899888918 and parameters: {'lag_temp_max': 7, 'lag_temp_min': 30, 'lag_snowfall': 1, 'n_lags': 20, 'epochs': 87, 'learning_rate': 0.27803137449278686, 'batch_size': 127, 'ar_reg': 1.1015338520092683}. Best is trial 228 with value: 8.149892569607967.

Training: 0it [00:00, ?it/s]

Predicting: 18it [00:00, ?it/s]

[I 2026-03-07 21:16:48,483] Trial 231 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 18it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 18it [00:00, ?it/s]

[I 2026-03-07 21:17:16,860] Trial 232 finished with value: 9.302675913968214 and parameters: {'lag_temp_max': 8, 'lag_temp_min': 29, 'lag_snowfall': 1, 'n_lags': 20, 'epochs': 78, 'learning_rate': 0.2327682584724065, 'batch_size': 124, 'ar_reg': 1.1366774698611812}. Best is trial 228 with value: 8.149892569607967.

Training: 0it [00:00, ?it/s]

Predicting: 19it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 19it [00:00, ?it/s]

[I 2026-03-07 21:17:48,718] Trial 233 finished with value: 8.630739831538698 and parameters: {'lag_temp_max': 6, 'lag_temp_min': 25, 'lag_snowfall': 1, 'n_lags': 21, 'epochs': 84, 'learning_rate': 0.30531666716124006, 'batch_size': 121, 'ar_reg': 1.0989622711045586}. Best is trial 228 with value: 8.149892569607967.

Training: 0it [00:00, ?it/s]

Predicting: 18it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 18it [00:00, ?it/s]

[I 2026-03-07 21:18:18,502] Trial 234 finished with value: 8.651123564146106 and parameters: {'lag_temp_max': 6, 'lag_temp_min': 30, 'lag_snowfall': 1, 'n_lags': 21, 'epochs': 83, 'learning_rate': 0.3080771560016816, 'batch_size': 126, 'ar_reg': 1.2145963483353692}. Best is trial 228 with value: 8.149892569607967.

Training: 0it [00:00, ?it/s]

Predicting: 18it [00:00, ?it/s]

[I 2026-03-07 21:18:33,363] Trial 235 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 53it [00:00, ?it/s]

[I 2026-03-07 21:18:59,572] Trial 236 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 19it [00:00, ?it/s]

[I 2026-03-07 21:19:16,591] Trial 237 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 18it [00:00, ?it/s]

[I 2026-03-07 21:19:32,201] Trial 238 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 18it [00:00, ?it/s]

[I 2026-03-07 21:19:49,050] Trial 239 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 18it [00:00, ?it/s]

[I 2026-03-07 21:20:03,371] Trial 240 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 18it [00:00, ?it/s]

[I 2026-03-07 21:20:18,410] Trial 241 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 19it [00:00, ?it/s]

[I 2026-03-07 21:20:32,253] Trial 242 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 18it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 18it [00:00, ?it/s]

[I 2026-03-07 21:21:00,640] Trial 243 finished with value: 8.501087792342563 and parameters: {'lag_temp_max': 6, 'lag_temp_min': 29, 'lag_snowfall': 1, 'n_lags': 21, 'epochs': 92, 'learning_rate': 0.24553337297211364, 'batch_size': 124, 'ar_reg': 0.9640064528172927}. Best is trial 228 with value: 8.149892569607967.

Training: 0it [00:00, ?it/s]

Predicting: 18it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 18it [00:00, ?it/s]

[I 2026-03-07 21:21:29,318] Trial 244 finished with value: 8.664500899178499 and parameters: {'lag_temp_max': 7, 'lag_temp_min': 30, 'lag_snowfall': 1, 'n_lags': 21, 'epochs': 92, 'learning_rate': 0.23888142170683413, 'batch_size': 125, 'ar_reg': 0.9521687892327939}. Best is trial 228 with value: 8.149892569607967.

Training: 0it [00:00, ?it/s]

Predicting: 18it [00:00, ?it/s]

[I 2026-03-07 21:21:40,512] Trial 245 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 18it [00:00, ?it/s]

[I 2026-03-07 21:21:54,912] Trial 246 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 18it [00:00, ?it/s]

[I 2026-03-07 21:22:09,005] Trial 247 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 18it [00:00, ?it/s]

[I 2026-03-07 21:22:24,811] Trial 248 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 18it [00:00, ?it/s]

[I 2026-03-07 21:22:39,043] Trial 249 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 18it [00:00, ?it/s]

[I 2026-03-07 21:22:54,745] Trial 250 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 18it [00:00, ?it/s]

[I 2026-03-07 21:23:11,264] Trial 251 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 19it [00:00, ?it/s]

[I 2026-03-07 21:23:22,500] Trial 252 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 28it [00:00, ?it/s]

[I 2026-03-07 21:23:42,661] Trial 253 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 18it [00:00, ?it/s]

[I 2026-03-07 21:23:55,353] Trial 254 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 18it [00:00, ?it/s]

[I 2026-03-07 21:24:11,074] Trial 255 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 19it [00:00, ?it/s]

[I 2026-03-07 21:24:22,904] Trial 256 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 19it [00:00, ?it/s]

[I 2026-03-07 21:24:33,263] Trial 257 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 29it [00:00, ?it/s]

[I 2026-03-07 21:24:52,138] Trial 258 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 26it [00:00, ?it/s]

[I 2026-03-07 21:25:11,234] Trial 259 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 19it [00:00, ?it/s]

[I 2026-03-07 21:25:26,362] Trial 260 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 44it [00:00, ?it/s]

[I 2026-03-07 21:25:49,970] Trial 261 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 18it [00:00, ?it/s]

[I 2026-03-07 21:26:00,701] Trial 262 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 24it [00:00, ?it/s]

[I 2026-03-07 21:26:11,891] Trial 263 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 18it [00:00, ?it/s]

[I 2026-03-07 21:26:38,413] Trial 264 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 18it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 19it [00:00, ?it/s]

[I 2026-03-07 21:27:14,372] Trial 265 finished with value: 8.55930172082341 and parameters: {'lag_temp_max': 5, 'lag_temp_min': 29, 'lag_snowfall': 1, 'n_lags': 21, 'epochs': 95, 'learning_rate': 0.3508363620022141, 'batch_size': 122, 'ar_reg': 0.9383034959977299}. Best is trial 228 with value: 8.149892569607967.

Training: 0it [00:00, ?it/s]

Predicting: 18it [00:00, ?it/s]

[I 2026-03-07 21:27:32,460] Trial 266 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 19it [00:00, ?it/s]

[I 2026-03-07 21:27:50,620] Trial 267 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 27it [00:00, ?it/s]

[I 2026-03-07 21:28:11,730] Trial 268 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 18it [00:00, ?it/s]

[I 2026-03-07 21:28:28,986] Trial 269 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 19it [00:00, ?it/s]

[I 2026-03-07 21:28:45,010] Trial 270 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 28it [00:00, ?it/s]

[I 2026-03-07 21:28:56,717] Trial 271 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 18it [00:00, ?it/s]

[I 2026-03-07 21:29:10,049] Trial 272 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 18it [00:00, ?it/s]

[I 2026-03-07 21:29:24,261] Trial 273 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 19it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 19it [00:00, ?it/s]

[I 2026-03-07 21:29:59,427] Trial 274 finished with value: 8.661908688141626 and parameters: {'lag_temp_max': 4, 'lag_temp_min': 23, 'lag_snowfall': 1, 'n_lags': 21, 'epochs': 95, 'learning_rate': 0.04144369823899802, 'batch_size': 119, 'ar_reg': 1.077929887452728}. Best is trial 228 with value: 8.149892569607967.

Training: 0it [00:00, ?it/s]

Predicting: 19it [00:00, ?it/s]

[I 2026-03-07 21:30:17,827] Trial 275 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 19it [00:00, ?it/s]

[I 2026-03-07 21:30:48,155] Trial 276 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 19it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 19it [00:00, ?it/s]

[I 2026-03-07 21:31:26,712] Trial 277 finished with value: 8.702775812766472 and parameters: {'lag_temp_max': 5, 'lag_temp_min': 22, 'lag_snowfall': 1, 'n_lags': 21, 'epochs': 100, 'learning_rate': 0.044294495659120685, 'batch_size': 120, 'ar_reg': 1.0865457043059508}. Best is trial 228 with value: 8.149892569607967.

Training: 0it [00:00, ?it/s]

Predicting: 19it [00:00, ?it/s]

[I 2026-03-07 21:31:43,200] Trial 278 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 18it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 18it [00:00, ?it/s]

[I 2026-03-07 21:32:18,313] Trial 279 finished with value: 8.506700353515603 and parameters: {'lag_temp_max': 6, 'lag_temp_min': 23, 'lag_snowfall': 1, 'n_lags': 21, 'epochs': 94, 'learning_rate': 0.062098025245567616, 'batch_size': 124, 'ar_reg': 1.0667122242309324}. Best is trial 228 with value: 8.149892569607967.

Training: 0it [00:00, ?it/s]

Predicting: 18it [00:00, ?it/s]

[I 2026-03-07 21:32:32,865] Trial 280 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 19it [00:00, ?it/s]

[I 2026-03-07 21:32:49,805] Trial 281 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 18it [00:00, ?it/s]

[I 2026-03-07 21:33:07,481] Trial 282 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 18it [00:00, ?it/s]

[I 2026-03-07 21:33:19,287] Trial 283 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 19it [00:00, ?it/s]

[I 2026-03-07 21:33:35,759] Trial 284 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 69it [00:00, ?it/s]

[I 2026-03-07 21:34:11,446] Trial 285 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 19it [00:00, ?it/s]

[I 2026-03-07 21:34:26,864] Trial 286 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 18it [00:00, ?it/s]

[I 2026-03-07 21:34:45,165] Trial 287 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 18it [00:00, ?it/s]

[I 2026-03-07 21:34:55,173] Trial 288 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 19it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 19it [00:00, ?it/s]

[I 2026-03-07 21:35:22,578] Trial 289 finished with value: 8.810423644286796 and parameters: {'lag_temp_max': 5, 'lag_temp_min': 23, 'lag_snowfall': 1, 'n_lags': 21, 'epochs': 71, 'learning_rate': 0.04641876725667915, 'batch_size': 120, 'ar_reg': 0.8631679159943905}. Best is trial 228 with value: 8.149892569607967.

Training: 0it [00:00, ?it/s]

Predicting: 20it [00:00, ?it/s]

[I 2026-03-07 21:35:40,371] Trial 290 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 18it [00:00, ?it/s]

[I 2026-03-07 21:35:55,340] Trial 291 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 18it [00:00, ?it/s]

[I 2026-03-07 21:36:10,576] Trial 292 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 22it [00:00, ?it/s]

[I 2026-03-07 21:36:23,389] Trial 293 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 26it [00:00, ?it/s]

[I 2026-03-07 21:36:51,793] Trial 294 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 18it [00:00, ?it/s]

[I 2026-03-07 21:37:20,875] Trial 295 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 19it [00:00, ?it/s]

[I 2026-03-07 21:37:40,370] Trial 296 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 19it [00:00, ?it/s]

[I 2026-03-07 21:37:55,741] Trial 297 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 19it [00:00, ?it/s]

[I 2026-03-07 21:38:08,778] Trial 298 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 28it [00:00, ?it/s]

[I 2026-03-07 21:38:29,691] Trial 299 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 23it [00:00, ?it/s]

[I 2026-03-07 21:38:46,503] Trial 300 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 18it [00:00, ?it/s]

[I 2026-03-07 21:39:00,731] Trial 301 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 40it [00:00, ?it/s]

[I 2026-03-07 21:39:23,080] Trial 302 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 18it [00:00, ?it/s]

[I 2026-03-07 21:39:40,759] Trial 303 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 19it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 19it [00:00, ?it/s]

[I 2026-03-07 21:40:01,185] Trial 304 finished with value: 8.631491404388207 and parameters: {'lag_temp_max': 7, 'lag_temp_min': 20, 'lag_snowfall': 1, 'n_lags': 21, 'epochs': 54, 'learning_rate': 0.05945880570173884, 'batch_size': 120, 'ar_reg': 0.9984349912108256}. Best is trial 228 with value: 8.149892569607967.

Training: 0it [00:00, ?it/s]

Predicting: 101it [00:00, ?it/s]

[I 2026-03-07 21:40:26,237] Trial 305 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 19it [00:00, ?it/s]

[I 2026-03-07 21:40:36,473] Trial 306 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 19it [00:00, ?it/s]

[I 2026-03-07 21:40:47,643] Trial 307 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 19it [00:00, ?it/s]

[I 2026-03-07 21:40:59,749] Trial 308 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 20it [00:00, ?it/s]

[I 2026-03-07 21:41:10,921] Trial 309 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 19it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 20it [00:00, ?it/s]

[I 2026-03-07 21:41:31,317] Trial 310 finished with value: 8.26959658264441 and parameters: {'lag_temp_max': 6, 'lag_temp_min': 24, 'lag_snowfall': 1, 'n_lags': 20, 'epochs': 53, 'learning_rate': 0.05353808948998662, 'batch_size': 116, 'ar_reg': 1.1239325193516507}. Best is trial 228 with value: 8.149892569607967.

Training: 0it [00:00, ?it/s]

Predicting: 19it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 19it [00:00, ?it/s]

[I 2026-03-07 21:41:51,023] Trial 311 finished with value: 8.980671587804057 and parameters: {'lag_temp_max': 6, 'lag_temp_min': 24, 'lag_snowfall': 6, 'n_lags': 19, 'epochs': 53, 'learning_rate': 0.05183491506030001, 'batch_size': 117, 'ar_reg': 1.136375871678028}. Best is trial 228 with value: 8.149892569607967.

Training: 0it [00:00, ?it/s]

Predicting: 20it [00:00, ?it/s]

[I 2026-03-07 21:42:00,659] Trial 312 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 20it [00:00, ?it/s]

[I 2026-03-07 21:42:11,366] Trial 313 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 19it [00:00, ?it/s]

[I 2026-03-07 21:42:22,259] Trial 314 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 20it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 20it [00:00, ?it/s]

[I 2026-03-07 21:42:43,635] Trial 315 finished with value: 9.28110916715552 and parameters: {'lag_temp_max': 25, 'lag_temp_min': 23, 'lag_snowfall': 1, 'n_lags': 20, 'epochs': 55, 'learning_rate': 0.4042365672670274, 'batch_size': 115, 'ar_reg': 1.074317170280899}. Best is trial 228 with value: 8.149892569607967.

Training: 0it [00:00, ?it/s]

Predicting: 19it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 19it [00:00, ?it/s]

[I 2026-03-07 21:43:03,832] Trial 316 finished with value: 8.984451289698853 and parameters: {'lag_temp_max': 5, 'lag_temp_min': 19, 'lag_snowfall': 1, 'n_lags': 21, 'epochs': 53, 'learning_rate': 0.06825553702902842, 'batch_size': 118, 'ar_reg': 1.9936872766117322}. Best is trial 228 with value: 8.149892569607967.

Training: 0it [00:00, ?it/s]

Predicting: 19it [00:00, ?it/s]

[I 2026-03-07 21:43:14,788] Trial 317 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 19it [00:00, ?it/s]

[I 2026-03-07 21:43:29,677] Trial 318 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 19it [00:00, ?it/s]

[I 2026-03-07 21:43:40,041] Trial 319 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 54it [00:00, ?it/s]

[I 2026-03-07 21:44:00,000] Trial 320 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 82it [00:00, ?it/s]

[I 2026-03-07 21:44:31,088] Trial 321 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 21it [00:00, ?it/s]

[I 2026-03-07 21:44:40,986] Trial 322 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 29it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 29it [00:00, ?it/s]

[I 2026-03-07 21:45:13,823] Trial 323 finished with value: 8.394497121172964 and parameters: {'lag_temp_max': 7, 'lag_temp_min': 20, 'lag_snowfall': 1, 'n_lags': 20, 'epochs': 81, 'learning_rate': 0.3235691427854732, 'batch_size': 78, 'ar_reg': 1.2129208139077363}. Best is trial 228 with value: 8.149892569607967.

Training: 0it [00:00, ?it/s]

Predicting: 28it [00:00, ?it/s]

[I 2026-03-07 21:45:29,873] Trial 324 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 25it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 25it [00:00, ?it/s]

[I 2026-03-07 21:45:57,059] Trial 325 finished with value: 9.420632467551984 and parameters: {'lag_temp_max': 8, 'lag_temp_min': 19, 'lag_snowfall': 1, 'n_lags': 19, 'epochs': 74, 'learning_rate': 0.43061607291772663, 'batch_size': 91, 'ar_reg': 1.2277398703320865}. Best is trial 228 with value: 8.149892569607967.

Training: 0it [00:00, ?it/s]

Predicting: 29it [00:00, ?it/s]

[I 2026-03-07 21:46:09,955] Trial 326 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 27it [00:00, ?it/s]

[I 2026-03-07 21:46:25,591] Trial 327 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 28it [00:00, ?it/s]

[I 2026-03-07 21:46:41,813] Trial 328 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 29it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 30it [00:00, ?it/s]

[I 2026-03-07 21:47:13,247] Trial 329 finished with value: 8.91797528223373 and parameters: {'lag_temp_max': 7, 'lag_temp_min': 20, 'lag_snowfall': 1, 'n_lags': 18, 'epochs': 77, 'learning_rate': 0.28036260578581285, 'batch_size': 76, 'ar_reg': 1.1527923777066091}. Best is trial 228 with value: 8.149892569607967.

Training: 0it [00:00, ?it/s]

Predicting: 27it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 27it [00:00, ?it/s]

[I 2026-03-07 21:47:46,262] Trial 330 finished with value: 8.983997107373852 and parameters: {'lag_temp_max': 6, 'lag_temp_min': 25, 'lag_snowfall': 1, 'n_lags': 20, 'epochs': 85, 'learning_rate': 0.31197746791816583, 'batch_size': 84, 'ar_reg': 1.7977217940834702}. Best is trial 228 with value: 8.149892569607967.

Training: 0it [00:00, ?it/s]

Predicting: 29it [00:00, ?it/s]

[I 2026-03-07 21:47:59,987] Trial 331 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 18it [00:00, ?it/s]

[I 2026-03-07 21:48:10,692] Trial 332 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 18it [00:00, ?it/s]

[I 2026-03-07 21:48:34,529] Trial 333 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 18it [00:00, ?it/s]

[I 2026-03-07 21:48:49,227] Trial 334 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 62it [00:00, ?it/s]

[I 2026-03-07 21:49:35,622] Trial 335 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 18it [00:00, ?it/s]

[I 2026-03-07 21:49:49,677] Trial 336 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 27it [00:00, ?it/s]

[I 2026-03-07 21:50:18,208] Trial 337 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 19it [00:00, ?it/s]

[I 2026-03-07 21:50:30,734] Trial 338 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 29it [00:00, ?it/s]

[I 2026-03-07 21:50:41,150] Trial 339 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 19it [00:00, ?it/s]

[I 2026-03-07 21:50:52,699] Trial 340 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 18it [00:00, ?it/s]

[I 2026-03-07 21:51:02,424] Trial 341 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 26it [00:00, ?it/s]

[I 2026-03-07 21:51:48,064] Trial 342 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 18it [00:00, ?it/s]

[I 2026-03-07 21:52:04,097] Trial 343 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 19it [00:00, ?it/s]

[I 2026-03-07 21:52:17,649] Trial 344 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 49it [00:00, ?it/s]

[I 2026-03-07 21:53:02,245] Trial 345 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 22it [00:00, ?it/s]

[I 2026-03-07 21:53:16,339] Trial 346 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 30it [00:00, ?it/s]

[I 2026-03-07 21:54:03,161] Trial 347 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 19it [00:00, ?it/s]

[I 2026-03-07 21:54:14,281] Trial 348 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 19it [00:00, ?it/s]

[I 2026-03-07 21:54:23,778] Trial 349 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 18it [00:00, ?it/s]

[I 2026-03-07 21:54:38,319] Trial 350 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 28it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 28it [00:00, ?it/s]

[I 2026-03-07 21:55:11,148] Trial 351 finished with value: 9.411715708551466 and parameters: {'lag_temp_max': 10, 'lag_temp_min': 26, 'lag_snowfall': 1, 'n_lags': 20, 'epochs': 85, 'learning_rate': 0.30345231046321824, 'batch_size': 80, 'ar_reg': 1.0156021796801888}. Best is trial 228 with value: 8.149892569607967.

Training: 0it [00:00, ?it/s]

Predicting: 18it [00:00, ?it/s]

[I 2026-03-07 21:55:28,273] Trial 352 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 18it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 18it [00:00, ?it/s]

[I 2026-03-07 21:56:00,011] Trial 353 finished with value: 9.432857149551555 and parameters: {'lag_temp_max': 3, 'lag_temp_min': 20, 'lag_snowfall': 4, 'n_lags': 21, 'epochs': 90, 'learning_rate': 0.45349057181347496, 'batch_size': 125, 'ar_reg': 1.300446154077311}. Best is trial 228 with value: 8.149892569607967.

Training: 0it [00:00, ?it/s]

Predicting: 42it [00:00, ?it/s]

[I 2026-03-07 21:56:16,235] Trial 354 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 19it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 19it [00:00, ?it/s]

[I 2026-03-07 21:56:36,520] Trial 355 finished with value: 9.492452300386436 and parameters: {'lag_temp_max': 4, 'lag_temp_min': 17, 'lag_snowfall': 1, 'n_lags': 21, 'epochs': 53, 'learning_rate': 0.06937795782489538, 'batch_size': 120, 'ar_reg': 0.8963449224028716}. Best is trial 228 with value: 8.149892569607967.

Training: 0it [00:00, ?it/s]

Predicting: 20it [00:00, ?it/s]

[I 2026-03-07 21:57:00,274] Trial 356 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 20it [00:00, ?it/s]

[I 2026-03-07 21:57:18,235] Trial 357 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 19it [00:00, ?it/s]

[I 2026-03-07 21:57:43,668] Trial 358 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 19it [00:00, ?it/s]

[I 2026-03-07 21:57:54,533] Trial 359 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 18it [00:00, ?it/s]

[I 2026-03-07 21:58:10,681] Trial 360 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 29it [00:00, ?it/s]

[I 2026-03-07 21:58:24,055] Trial 361 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 18it [00:00, ?it/s]

[I 2026-03-07 21:58:36,814] Trial 362 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 30it [00:00, ?it/s]

[I 2026-03-07 21:58:51,739] Trial 363 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 19it [00:00, ?it/s]

[I 2026-03-07 21:59:10,759] Trial 364 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 19it [00:00, ?it/s]

[I 2026-03-07 21:59:32,559] Trial 365 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 18it [00:00, ?it/s]

[I 2026-03-07 21:59:41,057] Trial 366 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 27it [00:00, ?it/s]

[I 2026-03-07 21:59:58,287] Trial 367 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 18it [00:00, ?it/s]

[I 2026-03-07 22:00:13,825] Trial 368 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 19it [00:00, ?it/s]

[I 2026-03-07 22:00:29,309] Trial 369 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 18it [00:00, ?it/s]

[I 2026-03-07 22:00:40,028] Trial 370 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 19it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 20it [00:00, ?it/s]

[I 2026-03-07 22:00:59,400] Trial 371 finished with value: 8.780695166963284 and parameters: {'lag_temp_max': 5, 'lag_temp_min': 30, 'lag_snowfall': 1, 'n_lags': 21, 'epochs': 50, 'learning_rate': 0.3626238116177034, 'batch_size': 116, 'ar_reg': 1.707297038153925}. Best is trial 228 with value: 8.149892569607967.

Training: 0it [00:00, ?it/s]

Predicting: 19it [00:00, ?it/s]

[I 2026-03-07 22:01:08,986] Trial 372 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 45it [00:00, ?it/s]

[I 2026-03-07 22:01:41,376] Trial 373 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 21it [00:00, ?it/s]

[I 2026-03-07 22:01:57,264] Trial 374 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 18it [00:00, ?it/s]

[I 2026-03-07 22:02:13,388] Trial 375 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 29it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 29it [00:00, ?it/s]

[I 2026-03-07 22:02:36,529] Trial 376 finished with value: 8.574281252343305 and parameters: {'lag_temp_max': 3, 'lag_temp_min': 28, 'lag_snowfall': 1, 'n_lags': 21, 'epochs': 56, 'learning_rate': 0.04654697452982816, 'batch_size': 77, 'ar_reg': 1.054760845185851}. Best is trial 228 with value: 8.149892569607967.

Training: 0it [00:00, ?it/s]

Predicting: 29it [00:00, ?it/s]

[I 2026-03-07 22:02:47,489] Trial 377 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 31it [00:00, ?it/s]

[I 2026-03-07 22:02:59,826] Trial 378 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 28it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 28it [00:00, ?it/s]

[I 2026-03-07 22:03:25,181] Trial 379 finished with value: 8.796335759244847 and parameters: {'lag_temp_max': 2, 'lag_temp_min': 28, 'lag_snowfall': 1, 'n_lags': 21, 'epochs': 63, 'learning_rate': 0.05046850506124447, 'batch_size': 80, 'ar_reg': 1.009943860484934}. Best is trial 228 with value: 8.149892569607967.

Training: 0it [00:00, ?it/s]

Predicting: 29it [00:00, ?it/s]

[I 2026-03-07 22:03:36,768] Trial 380 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 29it [00:00, ?it/s]

[I 2026-03-07 22:03:47,992] Trial 381 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 27it [00:00, ?it/s]

[I 2026-03-07 22:03:58,041] Trial 382 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 30it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 30it [00:00, ?it/s]

[I 2026-03-07 22:04:23,083] Trial 383 finished with value: 8.404575588769255 and parameters: {'lag_temp_max': 9, 'lag_temp_min': 26, 'lag_snowfall': 1, 'n_lags': 20, 'epochs': 61, 'learning_rate': 0.03266876984505262, 'batch_size': 74, 'ar_reg': 0.9689466233821722}. Best is trial 228 with value: 8.149892569607967.

Training: 0it [00:00, ?it/s]

Predicting: 31it [00:00, ?it/s]

[I 2026-03-07 22:05:04,111] Trial 384 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 30it [00:00, ?it/s]

[I 2026-03-07 22:05:17,042] Trial 385 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 29it [00:00, ?it/s]

[I 2026-03-07 22:05:30,351] Trial 386 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 30it [00:00, ?it/s]

[I 2026-03-07 22:05:42,936] Trial 387 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 31it [00:00, ?it/s]

[I 2026-03-07 22:05:55,249] Trial 388 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 28it [00:00, ?it/s]

[I 2026-03-07 22:06:06,306] Trial 389 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 28it [00:00, ?it/s]

[I 2026-03-07 22:06:17,199] Trial 390 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 31it [00:00, ?it/s]

[I 2026-03-07 22:06:30,682] Trial 391 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 29it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 29it [00:00, ?it/s]

[I 2026-03-07 22:06:54,400] Trial 392 finished with value: 9.653963424533716 and parameters: {'lag_temp_max': 4, 'lag_temp_min': 24, 'lag_snowfall': 2, 'n_lags': 21, 'epochs': 61, 'learning_rate': 0.48985614682404505, 'batch_size': 77, 'ar_reg': 1.0506207827470049}. Best is trial 228 with value: 8.149892569607967.

Training: 0it [00:00, ?it/s]

Predicting: 28it [00:00, ?it/s]

[I 2026-03-07 22:07:11,622] Trial 393 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 30it [00:00, ?it/s]

[I 2026-03-07 22:07:31,863] Trial 394 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 31it [00:00, ?it/s]

[I 2026-03-07 22:07:54,163] Trial 395 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 25it [00:00, ?it/s]

[I 2026-03-07 22:08:11,181] Trial 396 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 38it [00:00, ?it/s]

[I 2026-03-07 22:08:23,856] Trial 397 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 27it [00:00, ?it/s]

[I 2026-03-07 22:08:44,832] Trial 398 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 29it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 29it [00:00, ?it/s]

[I 2026-03-07 22:09:04,342] Trial 399 finished with value: 8.654178434080832 and parameters: {'lag_temp_max': 6, 'lag_temp_min': 27, 'lag_snowfall': 1, 'n_lags': 21, 'epochs': 52, 'learning_rate': 0.06567524384428373, 'batch_size': 78, 'ar_reg': 2.0979612986560467}. Best is trial 228 with value: 8.149892569607967.

Training: 0it [00:00, ?it/s]

Predicting: 37it [00:00, ?it/s]

[I 2026-03-07 22:09:17,070] Trial 400 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 20it [00:00, ?it/s]

[I 2026-03-07 22:09:27,688] Trial 401 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 58it [00:00, ?it/s]

[I 2026-03-07 22:10:27,059] Trial 402 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 19it [00:00, ?it/s]

[I 2026-03-07 22:10:40,970] Trial 403 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 19it [00:00, ?it/s]

[I 2026-03-07 22:11:00,305] Trial 404 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 30it [00:00, ?it/s]

[I 2026-03-07 22:11:13,990] Trial 405 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 18it [00:00, ?it/s]

[I 2026-03-07 22:11:30,643] Trial 406 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 26it [00:00, ?it/s]

[I 2026-03-07 22:11:54,652] Trial 407 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 24it [00:00, ?it/s]

[I 2026-03-07 22:12:12,609] Trial 408 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 19it [00:00, ?it/s]

[I 2026-03-07 22:12:22,427] Trial 409 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 18it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 19it [00:00, ?it/s]

[I 2026-03-07 22:12:45,411] Trial 410 finished with value: 8.411946159426826 and parameters: {'lag_temp_max': 30, 'lag_temp_min': 6, 'lag_snowfall': 1, 'n_lags': 21, 'epochs': 63, 'learning_rate': 0.28697252202734974, 'batch_size': 122, 'ar_reg': 1.0904258921857022}. Best is trial 228 with value: 8.149892569607967.

Training: 0it [00:00, ?it/s]

Predicting: 18it [00:00, ?it/s]

[I 2026-03-07 22:12:56,039] Trial 411 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 19it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 19it [00:00, ?it/s]

[I 2026-03-07 22:13:17,100] Trial 412 finished with value: 8.499634946758512 and parameters: {'lag_temp_max': 4, 'lag_temp_min': 6, 'lag_snowfall': 1, 'n_lags': 20, 'epochs': 64, 'learning_rate': 0.31857700483221824, 'batch_size': 122, 'ar_reg': 1.0920963427821575}. Best is trial 228 with value: 8.149892569607967.

Training: 0it [00:00, ?it/s]

Predicting: 18it [00:00, ?it/s]

[I 2026-03-07 22:13:28,750] Trial 413 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 29it [00:00, ?it/s]

[I 2026-03-07 22:13:41,367] Trial 414 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 23it [00:00, ?it/s]

[I 2026-03-07 22:13:52,861] Trial 415 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 32it [00:00, ?it/s]

[I 2026-03-07 22:14:07,782] Trial 416 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 18it [00:00, ?it/s]

[I 2026-03-07 22:14:18,899] Trial 417 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 28it [00:00, ?it/s]

[I 2026-03-07 22:14:32,350] Trial 418 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 18it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 18it [00:00, ?it/s]

[I 2026-03-07 22:14:53,945] Trial 419 finished with value: 8.550374505050403 and parameters: {'lag_temp_max': 26, 'lag_temp_min': 8, 'lag_snowfall': 1, 'n_lags': 20, 'epochs': 59, 'learning_rate': 0.3354216720396255, 'batch_size': 123, 'ar_reg': 1.9130172432784645}. Best is trial 228 with value: 8.149892569607967.

Training: 0it [00:00, ?it/s]

Predicting: 18it [00:00, ?it/s]

[I 2026-03-07 22:15:04,702] Trial 420 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 19it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 19it [00:00, ?it/s]

[I 2026-03-07 22:15:28,026] Trial 421 finished with value: 9.003357562741705 and parameters: {'lag_temp_max': 22, 'lag_temp_min': 5, 'lag_snowfall': 1, 'n_lags': 19, 'epochs': 63, 'learning_rate': 0.4408355078678396, 'batch_size': 122, 'ar_reg': 1.9272383084708022}. Best is trial 228 with value: 8.149892569607967.

Training: 0it [00:00, ?it/s]

Predicting: 18it [00:00, ?it/s]

[I 2026-03-07 22:15:38,418] Trial 422 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 19it [00:00, ?it/s]

[I 2026-03-07 22:15:48,120] Trial 423 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 18it [00:00, ?it/s]

[I 2026-03-07 22:15:58,474] Trial 424 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 19it [00:00, ?it/s]

[I 2026-03-07 22:16:09,405] Trial 425 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 18it [00:00, ?it/s]

[I 2026-03-07 22:16:21,957] Trial 426 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 19it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 19it [00:00, ?it/s]

[I 2026-03-07 22:16:46,056] Trial 427 finished with value: 8.540546571602318 and parameters: {'lag_temp_max': 27, 'lag_temp_min': 6, 'lag_snowfall': 1, 'n_lags': 20, 'epochs': 64, 'learning_rate': 0.4464183144906967, 'batch_size': 120, 'ar_reg': 1.8153437655549785}. Best is trial 228 with value: 8.149892569607967.

Training: 0it [00:00, ?it/s]

Predicting: 19it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 19it [00:00, ?it/s]

[I 2026-03-07 22:17:09,794] Trial 428 finished with value: 8.116485839187831 and parameters: {'lag_temp_max': 27, 'lag_temp_min': 6, 'lag_snowfall': 1, 'n_lags': 19, 'epochs': 65, 'learning_rate': 0.42417358916938563, 'batch_size': 121, 'ar_reg': 1.840334889565835}. Best is trial 428 with value: 8.116485839187831.

Training: 0it [00:00, ?it/s]

Predicting: 18it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 18it [00:00, ?it/s]

[I 2026-03-07 22:17:34,263] Trial 429 finished with value: 8.690270607668003 and parameters: {'lag_temp_max': 27, 'lag_temp_min': 6, 'lag_snowfall': 1, 'n_lags': 19, 'epochs': 69, 'learning_rate': 0.4888493454138338, 'batch_size': 125, 'ar_reg': 1.736382286678465}. Best is trial 428 with value: 8.116485839187831.

Training: 0it [00:00, ?it/s]

Predicting: 19it [00:00, ?it/s]

[I 2026-03-07 22:17:46,629] Trial 430 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 18it [00:00, ?it/s]

[I 2026-03-07 22:18:15,095] Trial 431 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 18it [00:00, ?it/s]

[I 2026-03-07 22:18:26,429] Trial 432 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 18it [00:00, ?it/s]

[I 2026-03-07 22:18:37,148] Trial 433 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 19it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 19it [00:00, ?it/s]

[I 2026-03-07 22:19:00,157] Trial 434 finished with value: 8.542782229290705 and parameters: {'lag_temp_max': 27, 'lag_temp_min': 6, 'lag_snowfall': 1, 'n_lags': 20, 'epochs': 62, 'learning_rate': 0.4837316930231774, 'batch_size': 120, 'ar_reg': 1.8956295315187828}. Best is trial 428 with value: 8.116485839187831.

Training: 0it [00:00, ?it/s]

Predicting: 19it [00:00, ?it/s]

[I 2026-03-07 22:19:11,805] Trial 435 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 19it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 19it [00:00, ?it/s]

[I 2026-03-07 22:19:33,011] Trial 436 finished with value: 9.075242266761661 and parameters: {'lag_temp_max': 27, 'lag_temp_min': 7, 'lag_snowfall': 1, 'n_lags': 19, 'epochs': 58, 'learning_rate': 0.42956863098887116, 'batch_size': 120, 'ar_reg': 1.7960762756054558}. Best is trial 428 with value: 8.116485839187831.

Training: 0it [00:00, ?it/s]

Predicting: 18it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 18it [00:00, ?it/s]

[I 2026-03-07 22:19:56,998] Trial 437 finished with value: 8.751872053728155 and parameters: {'lag_temp_max': 26, 'lag_temp_min': 5, 'lag_snowfall': 3, 'n_lags': 20, 'epochs': 66, 'learning_rate': 0.46485250005580625, 'batch_size': 123, 'ar_reg': 1.8708621137817667}. Best is trial 428 with value: 8.116485839187831.

Training: 0it [00:00, ?it/s]

Predicting: 19it [00:00, ?it/s]

[I 2026-03-07 22:20:08,854] Trial 438 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 40it [00:00, ?it/s]

[I 2026-03-07 22:20:24,268] Trial 439 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 18it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 18it [00:00, ?it/s]

[I 2026-03-07 22:20:44,457] Trial 440 finished with value: 8.411612994551621 and parameters: {'lag_temp_max': 30, 'lag_temp_min': 6, 'lag_snowfall': 1, 'n_lags': 18, 'epochs': 56, 'learning_rate': 0.38686226740042406, 'batch_size': 124, 'ar_reg': 1.8487484084032242}. Best is trial 428 with value: 8.116485839187831.

Training: 0it [00:00, ?it/s]

Predicting: 18it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 18it [00:00, ?it/s]

[I 2026-03-07 22:21:04,776] Trial 441 finished with value: 8.627401290181327 and parameters: {'lag_temp_max': 30, 'lag_temp_min': 7, 'lag_snowfall': 1, 'n_lags': 19, 'epochs': 56, 'learning_rate': 0.375433469004751, 'batch_size': 126, 'ar_reg': 1.8388324966090517}. Best is trial 428 with value: 8.116485839187831.

Training: 0it [00:00, ?it/s]

Predicting: 18it [00:00, ?it/s]

[I 2026-03-07 22:21:32,853] Trial 442 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 18it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 19it [00:00, ?it/s]

[I 2026-03-07 22:21:49,800] Trial 443 finished with value: 8.461126952918079 and parameters: {'lag_temp_max': 30, 'lag_temp_min': 6, 'lag_snowfall': 1, 'n_lags': 18, 'epochs': 55, 'learning_rate': 0.4059067703866741, 'batch_size': 122, 'ar_reg': 1.9182265981326083}. Best is trial 428 with value: 8.116485839187831.

Training: 0it [00:00, ?it/s]

Predicting: 18it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 19it [00:00, ?it/s]

[I 2026-03-07 22:22:07,596] Trial 444 finished with value: 8.035123720764302 and parameters: {'lag_temp_max': 30, 'lag_temp_min': 6, 'lag_snowfall': 1, 'n_lags': 18, 'epochs': 59, 'learning_rate': 0.42513492458372, 'batch_size': 122, 'ar_reg': 1.9583904404139472}. Best is trial 444 with value: 8.035123720764302.

Training: 0it [00:00, ?it/s]

Predicting: 18it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 18it [00:00, ?it/s]

[I 2026-03-07 22:22:24,032] Trial 445 finished with value: 8.045696718242738 and parameters: {'lag_temp_max': 29, 'lag_temp_min': 6, 'lag_snowfall': 1, 'n_lags': 18, 'epochs': 54, 'learning_rate': 0.4271270190726409, 'batch_size': 128, 'ar_reg': 1.9737930769538874}. Best is trial 444 with value: 8.035123720764302.

Training: 0it [00:00, ?it/s]

Predicting: 18it [00:00, ?it/s]

[I 2026-03-07 22:22:32,184] Trial 446 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 18it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 18it [00:00, ?it/s]

[I 2026-03-07 22:22:48,529] Trial 447 finished with value: 8.714956514309154 and parameters: {'lag_temp_max': 30, 'lag_temp_min': 7, 'lag_snowfall': 1, 'n_lags': 18, 'epochs': 53, 'learning_rate': 0.40413514697109726, 'batch_size': 126, 'ar_reg': 1.9865685194156955}. Best is trial 444 with value: 8.035123720764302.

Training: 0it [00:00, ?it/s]

Predicting: 18it [00:00, ?it/s]

[I 2026-03-07 22:22:57,715] Trial 448 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 18it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 18it [00:00, ?it/s]

[I 2026-03-07 22:23:14,352] Trial 449 finished with value: 8.979376806600767 and parameters: {'lag_temp_max': 29, 'lag_temp_min': 6, 'lag_snowfall': 1, 'n_lags': 18, 'epochs': 56, 'learning_rate': 0.4957171181750918, 'batch_size': 125, 'ar_reg': 1.9571368167980614}. Best is trial 444 with value: 8.035123720764302.

Training: 0it [00:00, ?it/s]

Predicting: 18it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 18it [00:00, ?it/s]

[I 2026-03-07 22:23:29,790] Trial 450 finished with value: 7.928949696608401 and parameters: {'lag_temp_max': 28, 'lag_temp_min': 5, 'lag_snowfall': 1, 'n_lags': 18, 'epochs': 50, 'learning_rate': 0.4211970714186209, 'batch_size': 124, 'ar_reg': 1.9217472831888767}. Best is trial 450 with value: 7.928949696608401.

Training: 0it [00:00, ?it/s]

Predicting: 18it [00:00, ?it/s]

[I 2026-03-07 22:23:37,588] Trial 451 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 18it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 18it [00:00, ?it/s]

[I 2026-03-07 22:23:53,883] Trial 452 finished with value: 8.424062733729503 and parameters: {'lag_temp_max': 28, 'lag_temp_min': 5, 'lag_snowfall': 2, 'n_lags': 17, 'epochs': 50, 'learning_rate': 0.39067456253675753, 'batch_size': 125, 'ar_reg': 2.0437812022145105}. Best is trial 450 with value: 7.928949696608401.

Training: 0it [00:00, ?it/s]

Predicting: 18it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 18it [00:00, ?it/s]

[I 2026-03-07 22:24:12,099] Trial 453 finished with value: 10.311625404738281 and parameters: {'lag_temp_max': 28, 'lag_temp_min': 6, 'lag_snowfall': 1, 'n_lags': 18, 'epochs': 50, 'learning_rate': 0.3803042115636664, 'batch_size': 128, 'ar_reg': 2.140198475472768}. Best is trial 450 with value: 7.928949696608401.

Training: 0it [00:00, ?it/s]

Predicting: 18it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 18it [00:00, ?it/s]

[I 2026-03-07 22:24:31,116] Trial 454 finished with value: 7.796620920175238 and parameters: {'lag_temp_max': 30, 'lag_temp_min': 5, 'lag_snowfall': 2, 'n_lags': 17, 'epochs': 53, 'learning_rate': 0.40606215328277906, 'batch_size': 125, 'ar_reg': 2.0819087013847106}. Best is trial 454 with value: 7.796620920175238.

Training: 0it [00:00, ?it/s]

Predicting: 18it [00:00, ?it/s]

[I 2026-03-07 22:24:40,492] Trial 455 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 18it [00:00, ?it/s]

[I 2026-03-07 22:24:49,316] Trial 456 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 18it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 18it [00:00, ?it/s]

[I 2026-03-07 22:25:08,680] Trial 457 finished with value: 8.572723965397504 and parameters: {'lag_temp_max': 30, 'lag_temp_min': 7, 'lag_snowfall': 2, 'n_lags': 17, 'epochs': 54, 'learning_rate': 0.37793739448968977, 'batch_size': 125, 'ar_reg': 2.0922896088962886}. Best is trial 454 with value: 7.796620920175238.

Training: 0it [00:00, ?it/s]

Predicting: 18it [00:00, ?it/s]

[I 2026-03-07 22:25:18,332] Trial 458 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 18it [00:00, ?it/s]

[I 2026-03-07 22:25:27,442] Trial 459 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 18it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 18it [00:00, ?it/s]

[I 2026-03-07 22:25:45,744] Trial 460 finished with value: 8.546061267845772 and parameters: {'lag_temp_max': 28, 'lag_temp_min': 4, 'lag_snowfall': 2, 'n_lags': 18, 'epochs': 50, 'learning_rate': 0.4100780151604896, 'batch_size': 126, 'ar_reg': 2.2128640590461166}. Best is trial 454 with value: 7.796620920175238.

Training: 0it [00:00, ?it/s]

Predicting: 18it [00:00, ?it/s]

[I 2026-03-07 22:25:55,634] Trial 461 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 18it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 18it [00:00, ?it/s]

[I 2026-03-07 22:26:15,170] Trial 462 finished with value: 8.867089128171205 and parameters: {'lag_temp_max': 30, 'lag_temp_min': 5, 'lag_snowfall': 2, 'n_lags': 18, 'epochs': 54, 'learning_rate': 0.4261596767238074, 'batch_size': 128, 'ar_reg': 1.9482989691674613}. Best is trial 454 with value: 7.796620920175238.

Training: 0it [00:00, ?it/s]

Predicting: 18it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 18it [00:00, ?it/s]

[I 2026-03-07 22:26:35,038] Trial 463 finished with value: 8.67538963956757 and parameters: {'lag_temp_max': 29, 'lag_temp_min': 4, 'lag_snowfall': 2, 'n_lags': 18, 'epochs': 56, 'learning_rate': 0.3240740648504077, 'batch_size': 126, 'ar_reg': 2.115067586056849}. Best is trial 454 with value: 7.796620920175238.

Training: 0it [00:00, ?it/s]

Predicting: 18it [00:00, ?it/s]

[I 2026-03-07 22:26:44,262] Trial 464 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 18it [00:00, ?it/s]

[I 2026-03-07 22:26:53,889] Trial 465 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 85it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 85it [00:00, ?it/s]

[I 2026-03-07 22:27:42,053] Trial 466 finished with value: 8.980436711483971 and parameters: {'lag_temp_max': 30, 'lag_temp_min': 2, 'lag_snowfall': 2, 'n_lags': 18, 'epochs': 54, 'learning_rate': 0.3279054050199962, 'batch_size': 26, 'ar_reg': 1.9376764111781009}. Best is trial 454 with value: 7.796620920175238.

Training: 0it [00:00, ?it/s]

Predicting: 18it [00:00, ?it/s]

[I 2026-03-07 22:27:51,160] Trial 467 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 18it [00:00, ?it/s]

[I 2026-03-07 22:28:01,341] Trial 468 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 18it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 18it [00:00, ?it/s]

[I 2026-03-07 22:28:22,732] Trial 469 finished with value: 8.384952650843935 and parameters: {'lag_temp_max': 30, 'lag_temp_min': 6, 'lag_snowfall': 1, 'n_lags': 18, 'epochs': 60, 'learning_rate': 0.3554216736685479, 'batch_size': 128, 'ar_reg': 2.0636853080197026}. Best is trial 454 with value: 7.796620920175238.

Training: 0it [00:00, ?it/s]

Predicting: 18it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 18it [00:00, ?it/s]

[I 2026-03-07 22:28:42,947] Trial 470 finished with value: 8.228658360993395 and parameters: {'lag_temp_max': 30, 'lag_temp_min': 6, 'lag_snowfall': 1, 'n_lags': 17, 'epochs': 58, 'learning_rate': 0.299162047846162, 'batch_size': 126, 'ar_reg': 2.086139439321433}. Best is trial 454 with value: 7.796620920175238.

Training: 0it [00:00, ?it/s]

Predicting: 18it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 18it [00:00, ?it/s]

[I 2026-03-07 22:29:04,295] Trial 471 finished with value: 8.472603365178566 and parameters: {'lag_temp_max': 30, 'lag_temp_min': 6, 'lag_snowfall': 1, 'n_lags': 17, 'epochs': 60, 'learning_rate': 0.287058901364213, 'batch_size': 127, 'ar_reg': 2.081223690786495}. Best is trial 454 with value: 7.796620920175238.

Training: 0it [00:00, ?it/s]

Predicting: 18it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 18it [00:00, ?it/s]

[I 2026-03-07 22:29:24,794] Trial 472 finished with value: 8.396706972529568 and parameters: {'lag_temp_max': 30, 'lag_temp_min': 6, 'lag_snowfall': 1, 'n_lags': 16, 'epochs': 59, 'learning_rate': 0.3178347624752282, 'batch_size': 128, 'ar_reg': 2.0920458700378863}. Best is trial 454 with value: 7.796620920175238.

Training: 0it [00:00, ?it/s]

Predicting: 18it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 18it [00:00, ?it/s]

[I 2026-03-07 22:29:45,425] Trial 473 finished with value: 8.201802444130871 and parameters: {'lag_temp_max': 30, 'lag_temp_min': 5, 'lag_snowfall': 1, 'n_lags': 16, 'epochs': 60, 'learning_rate': 0.3016946265324863, 'batch_size': 127, 'ar_reg': 2.1332600949427927}. Best is trial 454 with value: 7.796620920175238.

Training: 0it [00:00, ?it/s]

Predicting: 18it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 18it [00:00, ?it/s]

[I 2026-03-07 22:30:06,116] Trial 474 finished with value: 8.428604737249115 and parameters: {'lag_temp_max': 30, 'lag_temp_min': 5, 'lag_snowfall': 1, 'n_lags': 16, 'epochs': 59, 'learning_rate': 0.30396954340603555, 'batch_size': 128, 'ar_reg': 2.156688169040213}. Best is trial 454 with value: 7.796620920175238.

Training: 0it [00:00, ?it/s]

Predicting: 18it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 18it [00:00, ?it/s]

[I 2026-03-07 22:30:27,042] Trial 475 finished with value: 7.787986585116568 and parameters: {'lag_temp_max': 30, 'lag_temp_min': 5, 'lag_snowfall': 1, 'n_lags': 16, 'epochs': 60, 'learning_rate': 0.2986532324899507, 'batch_size': 128, 'ar_reg': 2.132925719127823}. Best is trial 475 with value: 7.787986585116568.

Training: 0it [00:00, ?it/s]

Predicting: 18it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 18it [00:00, ?it/s]

[I 2026-03-07 22:30:47,590] Trial 476 finished with value: 8.50340970453967 and parameters: {'lag_temp_max': 30, 'lag_temp_min': 5, 'lag_snowfall': 1, 'n_lags': 16, 'epochs': 59, 'learning_rate': 0.34378514888649586, 'batch_size': 128, 'ar_reg': 2.0817862058526404}. Best is trial 475 with value: 7.787986585116568.

Training: 0it [00:00, ?it/s]

Predicting: 18it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 18it [00:00, ?it/s]

[I 2026-03-07 22:31:08,178] Trial 477 finished with value: 9.124187454752295 and parameters: {'lag_temp_max': 30, 'lag_temp_min': 5, 'lag_snowfall': 1, 'n_lags': 15, 'epochs': 59, 'learning_rate': 0.3048562410576973, 'batch_size': 128, 'ar_reg': 2.2431882571456243}. Best is trial 475 with value: 7.787986585116568.

Training: 0it [00:00, ?it/s]

Predicting: 18it [00:00, ?it/s]

[I 2026-03-07 22:31:18,589] Trial 478 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 18it [00:00, ?it/s]

[I 2026-03-07 22:31:30,221] Trial 479 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 18it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 18it [00:00, ?it/s]

[I 2026-03-07 22:31:53,129] Trial 480 finished with value: 8.237364282668821 and parameters: {'lag_temp_max': 30, 'lag_temp_min': 4, 'lag_snowfall': 1, 'n_lags': 17, 'epochs': 65, 'learning_rate': 0.3742364602134856, 'batch_size': 128, 'ar_reg': 2.206789626601615}. Best is trial 475 with value: 7.787986585116568.

Training: 0it [00:00, ?it/s]

Predicting: 18it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 18it [00:00, ?it/s]

[I 2026-03-07 22:32:15,825] Trial 481 finished with value: 8.840947105386773 and parameters: {'lag_temp_max': 30, 'lag_temp_min': 4, 'lag_snowfall': 1, 'n_lags': 16, 'epochs': 65, 'learning_rate': 0.2934434637348757, 'batch_size': 128, 'ar_reg': 2.177345547392441}. Best is trial 475 with value: 7.787986585116568.

Training: 0it [00:00, ?it/s]

Predicting: 18it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 18it [00:00, ?it/s]

[I 2026-03-07 22:32:39,208] Trial 482 finished with value: 9.011089252913793 and parameters: {'lag_temp_max': 29, 'lag_temp_min': 4, 'lag_snowfall': 1, 'n_lags': 17, 'epochs': 68, 'learning_rate': 0.35058881039383605, 'batch_size': 128, 'ar_reg': 2.315264789331639}. Best is trial 475 with value: 7.787986585116568.

Training: 0it [00:00, ?it/s]

Predicting: 18it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 18it [00:00, ?it/s]

[I 2026-03-07 22:33:00,707] Trial 483 finished with value: 8.530441823913705 and parameters: {'lag_temp_max': 29, 'lag_temp_min': 4, 'lag_snowfall': 1, 'n_lags': 16, 'epochs': 62, 'learning_rate': 0.3047738533004284, 'batch_size': 126, 'ar_reg': 2.152377268990978}. Best is trial 475 with value: 7.787986585116568.

Training: 0it [00:00, ?it/s]

Predicting: 18it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 18it [00:00, ?it/s]

[I 2026-03-07 22:33:18,573] Trial 484 finished with value: 8.311334494165997 and parameters: {'lag_temp_max': 30, 'lag_temp_min': 3, 'lag_snowfall': 1, 'n_lags': 15, 'epochs': 59, 'learning_rate': 0.3600185332093638, 'batch_size': 126, 'ar_reg': 2.2202728873342563}. Best is trial 475 with value: 7.787986585116568.

Training: 0it [00:00, ?it/s]

Predicting: 18it [00:00, ?it/s]

[I 2026-03-07 22:33:28,369] Trial 485 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 18it [00:00, ?it/s]

[I 2026-03-07 22:33:39,021] Trial 486 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 18it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 18it [00:00, ?it/s]

[I 2026-03-07 22:34:03,790] Trial 487 finished with value: 8.994608010351651 and parameters: {'lag_temp_max': 30, 'lag_temp_min': 3, 'lag_snowfall': 1, 'n_lags': 17, 'epochs': 72, 'learning_rate': 0.3361016644929062, 'batch_size': 126, 'ar_reg': 2.090375302294588}. Best is trial 475 with value: 7.787986585116568.

Training: 0it [00:00, ?it/s]

Predicting: 18it [00:00, ?it/s]

[I 2026-03-07 22:34:15,299] Trial 488 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 18it [00:00, ?it/s]

[I 2026-03-07 22:34:23,865] Trial 489 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 18it [00:00, ?it/s]

[I 2026-03-07 22:34:35,940] Trial 490 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 18it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 18it [00:00, ?it/s]

[I 2026-03-07 22:34:57,581] Trial 491 finished with value: 8.922256765406878 and parameters: {'lag_temp_max': 30, 'lag_temp_min': 7, 'lag_snowfall': 1, 'n_lags': 16, 'epochs': 62, 'learning_rate': 0.32725659936540485, 'batch_size': 128, 'ar_reg': 2.2834372427146308}. Best is trial 475 with value: 7.787986585116568.

Training: 0it [00:00, ?it/s]

Predicting: 18it [00:00, ?it/s]

[I 2026-03-07 22:35:06,033] Trial 492 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 18it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 18it [00:00, ?it/s]

[I 2026-03-07 22:35:29,017] Trial 493 finished with value: 8.711790536783226 and parameters: {'lag_temp_max': 30, 'lag_temp_min': 3, 'lag_snowfall': 5, 'n_lags': 17, 'epochs': 65, 'learning_rate': 0.4004357972595075, 'batch_size': 126, 'ar_reg': 2.2208488760916825}. Best is trial 475 with value: 7.787986585116568.

Training: 0it [00:00, ?it/s]

Predicting: 18it [00:00, ?it/s]

[I 2026-03-07 22:35:39,223] Trial 494 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 18it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 18it [00:00, ?it/s]

[I 2026-03-07 22:36:01,160] Trial 495 finished with value: 8.908512197596998 and parameters: {'lag_temp_max': 28, 'lag_temp_min': 5, 'lag_snowfall': 1, 'n_lags': 17, 'epochs': 62, 'learning_rate': 0.3355908466258434, 'batch_size': 128, 'ar_reg': 2.072214974557873}. Best is trial 475 with value: 7.787986585116568.

Training: 0it [00:00, ?it/s]

Predicting: 18it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 18it [00:00, ?it/s]

[I 2026-03-07 22:36:19,287] Trial 496 finished with value: 8.790678993092978 and parameters: {'lag_temp_max': 29, 'lag_temp_min': 4, 'lag_snowfall': 1, 'n_lags': 18, 'epochs': 50, 'learning_rate': 0.276549660829299, 'batch_size': 125, 'ar_reg': 2.1350628672562744}. Best is trial 475 with value: 7.787986585116568.

Training: 0it [00:00, ?it/s]

Predicting: 18it [00:00, ?it/s]

[I 2026-03-07 22:36:28,954] Trial 497 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 18it [00:00, ?it/s]

[I 2026-03-07 22:36:41,377] Trial 498 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 18it [00:00, ?it/s]

[I 2026-03-07 22:36:51,898] Trial 499 pruned.

In [6]:
print("Best Parameters", best_params)
print("Best RMSE:", study.best_value)

Best Parameters {'lag_temp_max': 30, 'lag_temp_min': 5, 'lag_snowfall': 1, 'n_lags': 16, 'epochs': 60, 'learning_rate': 0.2986532324899507, 'batch_size': 128, 'ar_reg': 2.132925719127823}
Best RMSE: 7.787986585116568

We write this down since it took a lot of effort (a 3 hours+ run).

Best Parameters {'lag_temp_max': 30, 'lag_temp_min': 5, 'lag_snowfall': 1, 'n_lags': 16, 'epochs': 60, 'learning_rate': 0.2986532324899507, 'batch_size': 128, 'ar_reg': 2.132925719127823}
Best RMSE: 7.787986585116568

In [18]:
# best_params =  {'lag_temp_max': 30, 'lag_temp_min': 5, 'lag_snowfall': 1, 'n_lags': 16, 'epochs': 60, 'learning_rate': 0.2986532324899507, 'batch_size': 128, 'ar_reg': 2.132925719127823}

## Check for Improvement of Model

In [13]:
rs = pd.read_csv('../scr/data/cleaned_rat_sightings_data/all_cleaned_rat_sightings.csv')
rs['created_date'] = pd.to_datetime(rs['created_date']) 
rs['closed_date'] = pd.to_datetime(rs['closed_date'])
rs['resolution_action_updated_date'] = pd.to_datetime(rs['resolution_action_updated_date'])
# mark cutoff dates, and also rename columns
rs = rs[rs['created_date']<'2026-03-01']
rs = rs[rs['created_date']>='2020-01-01']
rs = rs.groupby([rs['created_date'].dt.date]).size().reset_index(name='count')
rs.rename(columns={'created_date': 'ds', 'count': 'y'}, inplace=True)

## Add weather data.
import requests

lat, lon = 40.7831, -73.9712
start = "2020-01-01"
end   = "2026-02-28"

url = (
    "https://archive-api.open-meteo.com/v1/archive"
    f"?latitude={lat}&longitude={lon}"
    f"&start_date={start}&end_date={end}"
    "&daily=temperature_2m_max,temperature_2m_min,temperature_2m_mean,"
    "apparent_temperature_max,apparent_temperature_min,apparent_temperature_mean,"
    "precipitation_sum,snowfall_sum"
    "&timezone=America/New_York"
)

response = requests.get(url)
data = response.json()

In [14]:
tscv = TimeSeriesSplit(gap=0, max_train_size=None, n_splits=26, test_size=14)

regressed_features = ['apparent_temperature_max', 'apparent_temperature_min','snowfall_sum']


wd = wd.reset_index(drop=True).rename(columns={"time": "ds"})
wd["ds"] = pd.to_datetime(wd["ds"])
rs["ds"] = pd.to_datetime(rs["ds"])

rs = rs.merge(
    wd[['ds'] + regressed_features],
    on="ds",
    how="left"
)

lags_for_regressed_features = dict()
lags_for_regressed_features['apparent_temperature_max'] = best_params['lag_temp_max']
lags_for_regressed_features['apparent_temperature_min'] = best_params['lag_temp_min']
lags_for_regressed_features['snowfall_sum'] = best_params['lag_snowfall']


results = []

for i, (train_index, test_index) in enumerate(tscv.split(rs)):

    train = rs.iloc[train_index].copy()
    train = train.dropna(subset=["y"])

    test = rs.iloc[test_index].copy()


    model = NeuralProphet(yearly_seasonality=True, 
                          weekly_seasonality=True, 
                          learning_rate = best_params['learning_rate'],
                          epochs = best_params['epochs'],
                          n_lags= best_params['n_lags'],
                          ar_reg=best_params['ar_reg'],
                          accelerator="auto",   # uses GPU if available
                          batch_size= best_params['batch_size']
                          )
    model = model.add_country_holidays(country_name="US")
    for column in regressed_features:
        model.add_lagged_regressor(column, n_lags=lags_for_regressed_features[column])
        
    model.fit(train, freq="D", progress="off")

    # build dataframe containing future regressors
    future = pd.concat([train[['ds','y'] + regressed_features], test[['ds','y']].merge(wd[['ds'] + regressed_features], on="ds", how="left")])
    forecast = model.predict(future)

    y_pred = forecast["yhat1"].iloc[-len(test):].values
    y_true = test["y"].values

    rmse = np.sqrt(mean_squared_error(y_true, y_pred))
    mape = mean_absolute_percentage_error(y_true, y_pred)

    results.append({"fold": i, "rmse": rmse, "mape": mape})

neural_prophet_results_df = pd.DataFrame(results)
neural_prophet_results_df.loc["mean"] = ["mean", neural_prophet_results_df["rmse"].mean(), neural_prophet_results_df["mape"].mean()]
neural_prophet_results_df

Training: 0it [00:00, ?it/s]

Predicting: 15it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 15it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 15it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 15it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 15it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 16it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 16it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 16it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 16it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 16it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 16it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 16it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 16it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 16it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 17it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 17it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 17it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 17it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 17it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 17it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 17it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 17it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 17it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 18it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 18it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 18it [00:00, ?it/s]

      fold       rmse      mape
0        0  12.405271  0.201331
1        1   5.973257  0.084623
2        2   8.739509  0.145644
3        3  10.624402  0.150318
4        4  12.685225  0.163310
5        5  12.311997  0.152793
6        6  12.916432  0.160648
7        7  15.012399  0.185965
8        8  12.094142  0.162436
9        9   7.655632  0.091560
10      10  11.443205  0.160985
11      11   9.284629  0.123707
12      12  12.091647  0.104697
13      13  12.832820  0.140480
14      14  15.518547  0.275776
15      15   8.268808  0.150226
16      16   9.931859  0.190420
17      17   9.376215  0.331395
18      18  10.518279  0.230661
19      19  10.894690  0.256783
20      20  11.118942  0.435756
21      21   7.686100  0.371661
22      22   9.525283  0.251032
23      23   6.932523  0.360150
24      24   7.121450  0.271745
25      25  10.852109  0.379236
mean  mean  10.531360  0.212821

## Train the Model

In [37]:
model = NeuralProphet(yearly_seasonality=True, 
                          weekly_seasonality=True, 
                          # batch_size = best_params['batch_size'],
                          ar_reg=best_params['ar_reg'],
                          learning_rate = best_params['learning_rate'],
                          epochs = best_params['epochs'],
                          n_lags= best_params['n_lags']
                          )
model = model.add_country_holidays(country_name="US")
for column in regressed_features:
    model.add_lagged_regressor(column, n_lags=lags_for_regressed_features[column])
        
model.fit(rs, freq="D", progress="off")

new_rs = rs.copy()

new_rs = new_rs.drop(columns=['y'])

forecast = model.predict(rs)

Training: 0it [00:00, ?it/s]

Predicting: 35it [00:00, ?it/s]

## Plots and Evaluation of the Model

In [38]:
model.plot(forecast)

ERROR - (NP.plotly.plot) - plotly-resampler is not installed. Please install it to use the resampler.

In [39]:
model.plot_parameters()

ERROR - (NP.plotly.plot_parameters) - plotly-resampler is not installed. Please install it to use the resampler.