# Modeling Daily Rat Sightings in Manhattan

In [1]:
# import packages
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import datetime

from sklearn.model_selection import TimeSeriesSplit
from sklearn.metrics import mean_squared_error, mean_absolute_percentage_error


from prophet import Prophet
from pandas.tseries.holiday import USFederalHolidayCalendar
from prophet.diagnostics import cross_validation, performance_metrics
from prophet.plot import plot_cross_validation_metric
from prophet.plot import add_changepoints_to_plot
import itertools

import warnings
from statsmodels.tools.sm_exceptions import ConvergenceWarning
warnings.simplefilter('ignore', ConvergenceWarning)

## Importing the Data

In [2]:
tscv = TimeSeriesSplit(gap=0, max_train_size=None, n_splits=26, test_size=14)

In [3]:
rs = pd.read_csv('../scr/data/cleaned_rat_sightings_data/all_daily_borough_rs.csv')
rs['created_date'] = pd.to_datetime(rs['created_date'])

In [4]:
# Start by cutting off data before 2020-01-01 and after 2026-02-28.
rs = rs[rs['created_date']<'2026-03-01']
rs = rs[rs['created_date']>='2020-01-01']

In [5]:
## Restrict to MANHATTAN

rs = rs[rs['borough']=='MANHATTAN']

rs

      created_date    borough  count
2       2020-01-01  MANHATTAN      4
7       2020-01-02  MANHATTAN      7
12      2020-01-03  MANHATTAN     16
17      2020-01-04  MANHATTAN     10
21      2020-01-05  MANHATTAN      5
...            ...        ...    ...
10611   2026-02-24  MANHATTAN      7
10616   2026-02-25  MANHATTAN      8
10620   2026-02-26  MANHATTAN      9
10625   2026-02-27  MANHATTAN     17
10629   2026-02-28  MANHATTAN      5

[2250 rows x 3 columns]

In [6]:
## Drop the column with borough

rs = rs.drop(columns=['borough'])

rs

      created_date  count
2       2020-01-01      4
7       2020-01-02      7
12      2020-01-03     16
17      2020-01-04     10
21      2020-01-05      5
...            ...    ...
10611   2026-02-24      7
10616   2026-02-25      8
10620   2026-02-26      9
10625   2026-02-27     17
10629   2026-02-28      5

[2250 rows x 2 columns]

In [7]:
## There are 2251 days from 2020-01-01 to 2026-02-28 inclusive. So if this number is <2251, we must make sure to add in 0's.

len(rs)

2250

In [8]:
## We find the missing row and add it in.
## There's probably a better way to find in the missing dates and update it. This is a sort of hacky solution.

date_range = pd.date_range(start=rs['created_date'].min(), end=rs['created_date'].max(), freq='D')
complete_dates_df = pd.DataFrame(date_range, columns=['created_date'])
rs = pd.merge(complete_dates_df, rs, on='created_date', how='left')
rs['count'] = rs['count'].fillna(0).astype(int)
rs = rs.sort_values(by='created_date').reset_index(drop=True)

rs

     created_date  count
0      2020-01-01      4
1      2020-01-02      7
2      2020-01-03     16
3      2020-01-04     10
4      2020-01-05      5
...           ...    ...
2246   2026-02-24      7
2247   2026-02-25      8
2248   2026-02-26      9
2249   2026-02-27     17
2250   2026-02-28      5

[2251 rows x 2 columns]

## Baseline Seasonal Average Model

In [9]:
years_back_use = 4
day_window_use = 4

In [10]:
def seasonal_average_forecast(data, target_dates, years_back=years_back_use, day_window=day_window_use):
    df = data.copy()
    # ensure datetime type
    df["created_date"] = pd.to_datetime(df["created_date"])
    df["doy"] = df["created_date"].dt.dayofyear
    df["year"] = df["created_date"].dt.year

    forecasts = []
    for target_date in target_dates:
        target_doy = target_date.dayofyear
        target_year = target_date.year
        mask = ((df["year"] >= target_year - years_back) & (df["year"] < target_year) & (np.abs(df["doy"] - target_doy) <= day_window))
        forecasts.append(df.loc[mask, "count"].mean())
    return pd.Series(forecasts, index=target_dates)

In [11]:
results = []

rs["created_date"] = pd.to_datetime(rs["created_date"])

for i, (train_index, test_index) in enumerate(tscv.split(rs)):
    
    train = rs.iloc[train_index].copy()
    test = rs.iloc[test_index].copy()
    
    # Target dates = the dates we want to forecast. There are 14 days.
    target_dates = test["created_date"]
    
    # Seasonal forecast using only the training data (we will go back 5 years and take the average and use a day_window of 5 as well.)
    y_pred = seasonal_average_forecast(data=train, target_dates=target_dates, years_back=years_back_use,day_window=day_window_use)

    # We take the true values.
    y_true = test["count"].values
    
    # Compute the metrics
    rmse = np.sqrt(mean_squared_error(y_true, y_pred))
    mape = mean_absolute_percentage_error(y_true, y_pred)
    
    # Append the results of the metrics to the table as well as the fold number.
    results.append({"fold": i, "rmse": rmse, "mape": mape})

# Convert the data to a table for readability.
baseline_results_df = pd.DataFrame(results)

# We also include a new row which consists of the average RMSE and MAPE over each fold.
baseline_results_df.loc["mean"] = ["mean", baseline_results_df["rmse"].mean(), baseline_results_df["mape"].mean()]

baseline_results_df

      fold       rmse          mape
0        0   6.110015  5.187832e-01
1        1   4.792049  1.711072e-01
2        2   4.519542  3.200928e-01
3        3   5.820867  4.201764e-01
4        4   5.803395  3.171943e-01
5        5   7.330541  5.227390e-01
6        6   5.947332  3.256959e-01
7        7   6.018142  2.473551e-01
8        8   6.515253  3.696147e-01
9        9   7.840324  5.171844e-01
10      10   9.310988  6.290299e-01
11      11   8.895986  6.089048e-01
12      12   8.002407  4.195949e-01
13      13   6.797736  4.752848e-01
14      14   7.611748  5.331502e-01
15      15   8.421691  8.997112e-01
16      16   7.654961  7.062848e-01
17      17  10.062572  1.681684e+00
18      18   7.677977  9.293678e-01
19      19   6.678495  3.824485e+15
20      20   6.710397  1.169345e+00
21      21   6.719962  1.850322e+00
22      22   5.608994  5.981685e-01
23      23   7.456576  1.286946e+00
24      24   8.015235  1.393778e+00
25      25   6.383076  8.871942e-01
mean  mean   7.027164  1.470956e+14

## Year Ago Rolling 4 Week Average

In [12]:
rs.rename(columns={'created_date': 'ds', 'count': 'y'}, inplace=True)

## Just saving a copy for later
rs_saved = rs.copy()

In [13]:
# Tired of writing np.sqrt or typing a long name.
def rmse(y_true, y_pred):
    return np.sqrt(mean_squared_error(y_true, y_pred))

results = []

for fold, (train_index, test_index) in enumerate(tscv.split(rs)):
    train = rs.iloc[train_index]
    test = rs.iloc[test_index]

    # Calculate the 4-week rolling average for the training data
    train_sorted = train.sort_values('ds') # making sure to sort it by date
    train_sorted['rolling_4w'] = train_sorted['y'].rolling(window=4, min_periods=1).mean()

    # This part of the code makes the predictions. We use the 'rolling_4w' column of the training set.
    y_pred = []
    y_true = test['y'].values

    for idx, row in test.iterrows():
        # Predict using the latest rolling average from the train data
        prediction = train_sorted['rolling_4w'].iloc[-1]  # Last value in the train rolling avg
        y_pred.append(prediction)
        
    # Calculate RMSE and MAPE for this fold
    fold_rmse = rmse(y_true, y_pred)
    fold_mape = mean_absolute_percentage_error(y_true, y_pred)
    
    results.append({'fold': fold, 'rmse': fold_rmse, 'mape': fold_mape})

rolling4w_results_df = pd.DataFrame(results)

# Optional: add a row for the overall average RMSE and MAPE
overall_rmse = rolling4w_results_df['rmse'].mean()
overall_mape = rolling4w_results_df['mape'].mean()
rolling4w_results_df.loc['mean'] = ['mean', overall_rmse, overall_mape]

In [14]:
rolling4w_results_df

      fold      rmse          mape
0        0  5.355238  4.252300e-01
1        1  8.373001  3.625078e-01
2        2  3.894823  2.717289e-01
3        3  5.993300  3.107589e-01
4        4  6.008922  2.453872e-01
5        5  7.652614  5.443236e-01
6        6  8.599730  3.345505e-01
7        7  8.957738  2.841237e-01
8        8  6.800735  3.947767e-01
9        9  5.257647  2.856080e-01
10      10  5.630751  2.703794e-01
11      11  5.490251  2.610070e-01
12      12  8.568526  1.992474e-01
13      13  6.602894  3.529541e-01
14      14  5.500000  3.884974e-01
15      15  6.366065  6.639706e-01
16      16  4.689464  4.302836e-01
17      17  7.188781  1.202054e+00
18      18  3.668154  4.107391e-01
19      19  5.628372  3.699385e+15
20      20  2.950484  4.992334e-01
21      21  4.156535  1.274620e+00
22      22  5.229552  3.352837e-01
23      23  3.935870  6.316356e-01
24      24  2.041970  2.220805e-01
25      25  5.143477  4.251677e-01
mean  mean  5.757111  1.422841e+14

## Prophet Model

In [15]:
# Create a date range covering 2020 through end of 2025
date_range = pd.date_range(start="2020-01-01", end="2026-02-28")

# Generate US federal holidays
calendar = USFederalHolidayCalendar()
holidays = calendar.holidays(start=date_range.min(), end=date_range.max())

# Build the DataFrame in the same structure as your original
federal_holidays = pd.DataFrame({
    'holiday': 'federal_us',
    'ds': pd.to_datetime(holidays),
    'lower_window': 0,
    'upper_window': 1,
})

holidays = federal_holidays

In [16]:
# Rename columns for Prophet model
rs.rename(columns={'created_date': 'ds', 'count': 'y'}, inplace=True)
results = []

for i, (train_index, test_index) in enumerate(tscv.split(rs)):
    train = rs.iloc[train_index]
    test = rs.iloc[test_index]
    
    model = Prophet(holidays=holidays)
    model.add_country_holidays(country_name='US')

    model.fit(train)
    
    future = model.make_future_dataframe(periods=len(test), freq='D')
    forecast = model.predict(future)
    
    # Obtain predicted values and compare against the actuals.
    y_pred = forecast['yhat'][-len(test):].values
    y_true = test['y'].values
    
    # Calculate RMSE
    rmse = np.sqrt(mean_squared_error(y_true, y_pred))
    
    # Calculate MAPE
    mape = mean_absolute_percentage_error(y_true, y_pred)
    
    # Append results
    results.append({'fold': i, 'rmse': rmse, 'mape': mape})

# Convert results to a datafrane
prophet_results_df = pd.DataFrame(results)

01:20:29 - cmdstanpy - INFO - Chain [1] start processing
01:20:29 - cmdstanpy - INFO - Chain [1] done processing
01:20:29 - cmdstanpy - INFO - Chain [1] start processing
01:20:30 - cmdstanpy - INFO - Chain [1] done processing
01:20:30 - cmdstanpy - INFO - Chain [1] start processing
01:20:30 - cmdstanpy - INFO - Chain [1] done processing
01:20:31 - cmdstanpy - INFO - Chain [1] start processing
01:20:31 - cmdstanpy - INFO - Chain [1] done processing
01:20:32 - cmdstanpy - INFO - Chain [1] start processing
01:20:32 - cmdstanpy - INFO - Chain [1] done processing
01:20:33 - cmdstanpy - INFO - Chain [1] start processing
01:20:33 - cmdstanpy - INFO - Chain [1] done processing
01:20:34 - cmdstanpy - INFO - Chain [1] start processing
01:20:34 - cmdstanpy - INFO - Chain [1] done processing
01:20:35 - cmdstanpy - INFO - Chain [1] start processing
01:20:35 - cmdstanpy - INFO - Chain [1] done processing
01:20:36 - cmdstanpy - INFO - Chain [1] start processing
01:20:36 - cmdstanpy - INFO - Chain [1] done processing
01:20:37 - cmdstanpy - INFO - Chain [1] start processing
01:20:37 - cmdstanpy - INFO - Chain [1] done processing
01:20:38 - cmdstanpy - INFO - Chain [1] start processing
01:20:38 - cmdstanpy - INFO - Chain [1] done processing
01:20:39 - cmdstanpy - INFO - Chain [1] start processing
01:20:39 - cmdstanpy - INFO - Chain [1] done processing
01:20:40 - cmdstanpy - INFO - Chain [1] start processing
01:20:40 - cmdstanpy - INFO - Chain [1] done processing
01:20:41 - cmdstanpy - INFO - Chain [1] start processing
01:20:41 - cmdstanpy - INFO - Chain [1] done processing
01:20:42 - cmdstanpy - INFO - Chain [1] start processing
01:20:42 - cmdstanpy - INFO - Chain [1] done processing
01:20:43 - cmdstanpy - INFO - Chain [1] start processing
01:20:43 - cmdstanpy - INFO - Chain [1] done processing
01:20:43 - cmdstanpy - INFO - Chain [1] start processing
01:20:43 - cmdstanpy - INFO - Chain [1] done processing
01:20:44 - cmdstanpy - INFO - Chain [1] start processing
01:20:45 - cmdstanpy - INFO - Chain [1] done processing
01:20:45 - cmdstanpy - INFO - Chain [1] start processing
01:20:45 - cmdstanpy - INFO - Chain [1] done processing
01:20:46 - cmdstanpy - INFO - Chain [1] start processing
01:20:46 - cmdstanpy - INFO - Chain [1] done processing
01:20:47 - cmdstanpy - INFO - Chain [1] start processing
01:20:47 - cmdstanpy - INFO - Chain [1] done processing
01:20:48 - cmdstanpy - INFO - Chain [1] start processing
01:20:48 - cmdstanpy - INFO - Chain [1] done processing
01:20:49 - cmdstanpy - INFO - Chain [1] start processing
01:20:49 - cmdstanpy - INFO - Chain [1] done processing
01:20:50 - cmdstanpy - INFO - Chain [1] start processing
01:20:50 - cmdstanpy - INFO - Chain [1] done processing
01:20:51 - cmdstanpy - INFO - Chain [1] start processing
01:20:51 - cmdstanpy - INFO - Chain [1] done processing
01:20:52 - cmdstanpy - INFO - Chain [1] start processing
01:20:53 - cmdstanpy - INFO - Chain [1] done processing

In [17]:
prophet_results_df.loc['mean'] = ['mean',  prophet_results_df['rmse'].mean(), prophet_results_df['mape'].mean()]

In [18]:
prophet_results_df

      fold      rmse          mape
0        0  4.648000  3.493749e-01
1        1  7.456070  3.300603e-01
2        2  3.755772  2.504353e-01
3        3  3.921697  2.842048e-01
4        4  4.491096  1.853417e-01
5        5  6.057690  3.874641e-01
6        6  5.067045  2.375071e-01
7        7  6.354280  1.923037e-01
8        8  5.992057  2.824904e-01
9        9  5.324755  3.432802e-01
10      10  5.579764  3.596880e-01
11      11  5.457583  3.605216e-01
12      12  6.856154  2.277337e-01
13      13  5.010714  2.967229e-01
14      14  6.310236  4.131089e-01
15      15  4.629287  4.523299e-01
16      16  4.280261  3.321512e-01
17      17  5.843399  8.980077e-01
18      18  4.408426  4.870380e-01
19      19  2.938349  2.441334e+14
20      20  3.631120  5.092911e-01
21      21  3.330654  6.930523e-01
22      22  3.519925  2.842049e-01
23      23  3.451783  5.167387e-01
24      24  3.772100  5.915224e-01
25      25  4.581812  5.565141e-01
mean  mean  4.871924  9.389747e+12

## SARIMA Model with auto_arima parameters.

In [19]:
pip install pmdarima

Requirement already satisfied: pmdarima in /opt/anaconda3/envs/erdos_ds_environment/lib/python3.12/site-packages (2.1.1)
Requirement already satisfied: joblib>=0.11 in /opt/anaconda3/envs/erdos_ds_environment/lib/python3.12/site-packages (from pmdarima) (1.5.3)
Requirement already satisfied: Cython!=0.29.18,!=0.29.31,>=0.29 in /opt/anaconda3/envs/erdos_ds_environment/lib/python3.12/site-packages (from pmdarima) (3.2.4)
Requirement already satisfied: numpy>=1.21.6 in /opt/anaconda3/envs/erdos_ds_environment/lib/python3.12/site-packages (from pmdarima) (1.26.4)
Requirement already satisfied: pandas>=0.19 in /opt/anaconda3/envs/erdos_ds_environment/lib/python3.12/site-packages (from pmdarima) (2.3.3)
Requirement already satisfied: scikit-learn>=0.22 in /opt/anaconda3/envs/erdos_ds_environment/lib/python3.12/site-packages (from pmdarima) (1.8.0)
Requirement already satisfied: scipy>=1.13.0 in /opt/anaconda3/envs/erdos_ds_environment/lib/python3.12/site-packages (from pmdarima) (1.15.3)
Requirement already satisfied: statsmodels>=0.14.5 in /opt/anaconda3/envs/erdos_ds_environment/lib/python3.12/site-packages (from pmdarima) (0.14.6)
Requirement already satisfied: urllib3 in /opt/anaconda3/envs/erdos_ds_environment/lib/python3.12/site-packages (from pmdarima) (2.6.3)
Requirement already satisfied: setuptools!=50.0.0,>=42 in /opt/anaconda3/envs/erdos_ds_environment/lib/python3.12/site-packages (from pmdarima) (80.10.2)
Requirement already satisfied: packaging>=17.1 in /opt/anaconda3/envs/erdos_ds_environment/lib/python3.12/site-packages (from pmdarima) (26.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/anaconda3/envs/erdos_ds_environment/lib/python3.12/site-packages (from pandas>=0.19->pmdarima) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /opt/anaconda3/envs/erdos_ds_environment/lib/python3.12/site-packages (from pandas>=0.19->pmdarima) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /opt/anaconda3/envs/erdos_ds_environment/lib/python3.12/site-packages (from pandas>=0.19->pmdarima) (2025.3)
Requirement already satisfied: six>=1.5 in /opt/anaconda3/envs/erdos_ds_environment/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas>=0.19->pmdarima) (1.17.0)
Requirement already satisfied: threadpoolctl>=3.2.0 in /opt/anaconda3/envs/erdos_ds_environment/lib/python3.12/site-packages (from scikit-learn>=0.22->pmdarima) (3.6.0)
Requirement already satisfied: patsy>=0.5.6 in /opt/anaconda3/envs/erdos_ds_environment/lib/python3.12/site-packages (from statsmodels>=0.14.5->pmdarima) (1.0.2)
Note: you may need to restart the kernel to use updated packages.

In [20]:
from pmdarima import auto_arima

In [21]:
def fourier_terms(df, period, n_terms):
    t = np.arange(1, len(df) + 1)
    fourier_df = pd.DataFrame()
    
    for i in range(1, n_terms + 1):
        fourier_df[f'sin_{i}'] = np.sin(2 * np.pi * i * t / period)
        fourier_df[f'cos_{i}'] = np.cos(2 * np.pi * i * t / period)
    
    return fourier_df

In [22]:
# Number of Fourier terms and period (365 for yearly seasonality)
n_terms = 5  # Number of terms for Fourier Terms
period = 365

In [23]:
# Generate Fourier terms and putting it into a list
fourier_train = fourier_terms(rs, period, n_terms)

# Name it exog since it will serve as exogenous features for SARIMAX. This is the X.
exog = fourier_train

In [24]:
from statsmodels.tsa.statespace.sarimax import SARIMAX

# Make sure the columns for SARIMA model are renamed.
rs.rename(columns={'created_date': 'ds', 'count': 'y'}, inplace=True)

results = []

# Loop through each fold
for i, (train_index, test_index) in enumerate(tscv.split(rs)):
    train = rs.iloc[train_index]
    test = rs.iloc[test_index]

    exog_train = exog.iloc[train_index]
    exog_test = exog.iloc[test_index]

    orders = (2,1,3)
    seasonal_orders = (0,0,0,0)

    # model_auto = auto_arima(train['y'], 
    #                         exog=exog_train,  # Exogenous Fourier terms for training data
    #                         seasonal=True, 
    #                         # m=7,  # we choose 7 since we can at least model weekly seasonality. yearly seasonality would not be able to run.
    #                         trace=True, 
    #                         stepwise=True,  # stepwise search to speed up
    #                         suppress_warnings=True, 
    #                         # n_jobs=-1,  # use all available cores for parallel processing
    #                         maxiter=100,  # limit the number of iterations (really important for run time)
    #                         max_p=3, 
    #                         max_q=3, 
    #                         max_P=2, 
    #                         max_Q=2, 
    #                         max_d=2, 
    #                         max_D=1)
    # orders = model_auto.order  # (p, d, q)
    # seasonal_orders = model_auto.seasonal_order  # (P, D, Q, s)
    
    # Fit the SARIMAX model with the exogenous features (Fourier terms)
    model_sarimax = SARIMAX(train['y'], 
                            order=orders,  
                            seasonal_order=seasonal_orders,  
                            exog=exog_train,  # Exogenous Fourier terms for training data
                            enforce_stationarity=False,
                            enforce_invertibility=False)
    
    model_fit = model_sarimax.fit(disp=False)
    
    # Predict for the test period. Have to remember to subtract 1 to get the correct index.
    y_pred = model_fit.predict(start=len(train), end=len(train)+len(test)-1, exog=exog_test, dynamic=False)
    y_true = test['y'].values
    
    rmse = np.sqrt(mean_squared_error(y_true, y_pred))
    mape = mean_absolute_percentage_error(y_true, y_pred)
    results.append({'fold': i, 'rmse': rmse, 'mape': mape})

sarima_results_df = pd.DataFrame(results)

In [25]:
sarima_results_df.loc['mean'] = ['mean',  sarima_results_df['rmse'].mean(), sarima_results_df['mape'].mean()]

In [26]:
sarima_results_df

      fold      rmse          mape
0        0  5.005975  3.369476e-01
1        1  6.167581  2.451594e-01
2        2  5.362712  3.859427e-01
3        3  4.759396  3.416060e-01
4        4  5.142934  2.450909e-01
5        5  6.763359  4.694163e-01
6        6  5.268748  2.352967e-01
7        7  7.005431  2.224091e-01
8        8  7.018665  4.072846e-01
9        9  5.902277  3.881165e-01
10      10  5.960499  3.722656e-01
11      11  5.466420  3.678337e-01
12      12  7.820472  1.960797e-01
13      13  5.952080  3.592433e-01
14      14  5.675855  3.647973e-01
15      15  4.410161  4.548879e-01
16      16  4.123681  3.578910e-01
17      17  4.693388  6.544846e-01
18      18  3.973114  3.661534e-01
19      19  3.970715  2.730803e+15
20      20  2.490315  4.017614e-01
21      21  3.663106  1.031922e+00
22      22  4.507117  2.816386e-01
23      23  3.858648  6.185217e-01
24      24  4.099142  6.913284e-01
25      25  4.002693  3.811827e-01
mean  mean  5.117865  1.050309e+14

## Holt-Winters Model

In [27]:
from statsmodels.tsa.holtwinters import ExponentialSmoothing

In [28]:
rs.rename(columns={'created_date': 'ds', 'count': 'y'}, inplace=True)
results = []
for i, (train_index, test_index) in enumerate(tscv.split(rs)):
    train = rs.iloc[train_index]
    test = rs.iloc[test_index]
    
    # First we fit the Holt-Winters Exponential Smoothing Model to the training data
    holt_winters = ExponentialSmoothing(train['y'], seasonal='add', seasonal_periods=365).fit(optimized=True)
    
    y_pred = holt_winters.forecast(len(test))
    y_true = test['y'].values
    
    rmse = np.sqrt(mean_squared_error(y_true, y_pred))
    mape = mean_absolute_percentage_error(y_true, y_pred)
    results.append({'fold': i, 'rmse': rmse, 'mape': mape})

hw_results_df = pd.DataFrame(results)

In [29]:
hw_results_df.loc['mean'] = ['mean',  hw_results_df['rmse'].mean(), hw_results_df['mape'].mean()]

In [30]:
hw_results_df

      fold      rmse          mape
0        0  5.734597  4.516267e-01
1        1  7.631673  3.116474e-01
2        2  6.044236  4.149782e-01
3        3  6.727356  4.865189e-01
4        4  7.228770  3.555821e-01
5        5  6.924762  4.295341e-01
6        6  6.502953  2.740456e-01
7        7  8.699943  3.076210e-01
8        8  5.846188  2.962146e-01
9        9  8.228982  5.333166e-01
10      10  7.666488  4.326266e-01
11      11  6.025826  3.671231e-01
12      12  8.317778  2.419009e-01
13      13  5.970340  3.783984e-01
14      14  5.823659  3.510820e-01
15      15  5.930965  6.164632e-01
16      16  4.239823  3.409041e-01
17      17  6.139685  9.310572e-01
18      18  4.469317  3.980163e-01
19      19  5.035023  3.052718e+15
20      20  3.217969  4.192029e-01
21      21  5.351250  1.053995e+00
22      22  4.529289  4.117205e-01
23      23  4.037067  5.935925e-01
24      24  2.763491  4.001561e-01
25      25  3.852078  3.583591e-01
mean  mean  5.882289  1.174122e+14

## XGBoost Model

The XGBoost model requires a bit more preparatory work. Our current dataframe rs is quite bare. We will need to add features for use.

In [31]:
import xgboost as xgb
from xgboost import plot_importance

In [32]:
rs

             ds   y
0    2020-01-01   4
1    2020-01-02   7
2    2020-01-03  16
3    2020-01-04  10
4    2020-01-05   5
...         ...  ..
2246 2026-02-24   7
2247 2026-02-25   8
2248 2026-02-26   9
2249 2026-02-27  17
2250 2026-02-28   5

[2251 rows x 2 columns]

### Adding Features to XGBoost

In [33]:
def create_features(df):
    """
    Create time series features based on time series index.
    """
    df = df.copy()
    df['dayofweek'] = df.index.dayofweek
    df['quarter'] = df.index.quarter
    df['month'] = df.index.month
    df['year'] = df.index.year
    df['dayofyear'] = df.index.dayofyear
    df['dayofmonth'] = df.index.day
    df['weekofyear'] = df.index.isocalendar().week
    return df

def add_cyclic(df):
    target_map = df['y'].to_dict()
    df['dayofweek_sin'] = np.sin(2 * np.pi * df['dayofweek']/7)
    df['dayofweek_cos'] = np.cos(2 * np.pi * df['dayofweek']/7)
    df['month_sin'] = np.sin(2 * np.pi * df['month']/12)
    df['month_cos'] = np.cos(2 * np.pi * df['month']/12)
    return df

def add_lags(df):
    target_map = df['y'].to_dict()
    df['lag1'] = (df.index - pd.Timedelta('1 days')).map(target_map)
    df['lag2'] = (df.index - pd.Timedelta('2 days')).map(target_map)
    df['lag3'] = (df.index - pd.Timedelta('3 days')).map(target_map)
    df['lag4'] = (df.index - pd.Timedelta('4 days')).map(target_map)
    df['lag5'] = (df.index - pd.Timedelta('5 days')).map(target_map)
    df['lag6'] = (df.index - pd.Timedelta('6 days')).map(target_map)
    df['lag7'] = (df.index - pd.Timedelta('7 days')).map(target_map)
    df['lag8'] = (df.index - pd.Timedelta('8 days')).map(target_map)
    df['lag9'] = (df.index - pd.Timedelta('9 days')).map(target_map)
    df['lag10'] = (df.index - pd.Timedelta('10 days')).map(target_map)
    df['lag11'] = (df.index - pd.Timedelta('11 days')).map(target_map)
    df['lag12'] = (df.index - pd.Timedelta('12 days')).map(target_map)
    df['lag13'] = (df.index - pd.Timedelta('13 days')).map(target_map)
    df['lag14'] = (df.index - pd.Timedelta('14 days')).map(target_map)
    return df

def add_seasonal_lags(df):
    target_map = df['y'].to_dict()
    df['lag30'] = (df.index - pd.Timedelta('30 days')).map(target_map)
    df['lag60'] = (df.index - pd.Timedelta('60 days')).map(target_map)
    df['lag90'] = (df.index - pd.Timedelta('90 days')).map(target_map)
    df['lag120'] = (df.index - pd.Timedelta('120 days')).map(target_map)
    df['lag150'] = (df.index - pd.Timedelta('150 days')).map(target_map)
    df['lag180'] = (df.index - pd.Timedelta('180 days')).map(target_map)

    df['lag362'] = (df.index - pd.Timedelta('365 days')).map(target_map)
    df['lag363'] = (df.index - pd.Timedelta('365 days')).map(target_map)
    df['lag364'] = (df.index - pd.Timedelta('365 days')).map(target_map)
    df['lag365'] = (df.index - pd.Timedelta('365 days')).map(target_map)
    df['lag366'] = (df.index - pd.Timedelta('365 days')).map(target_map)
    df['lag367'] = (df.index - pd.Timedelta('365 days')).map(target_map)
    
    df['lag730'] = (df.index - pd.Timedelta('730 days')).map(target_map)
    df['lag1095'] = (df.index - pd.Timedelta('1095 days')).map(target_map)
    df['lag1460'] = (df.index - pd.Timedelta('1460 days')).map(target_map)
    df['lag1825'] = (df.index - pd.Timedelta('1825 days')).map(target_map)
    return df

def add_moving_averages(df):
    df = df.copy()
    
    # Ensure sorted by date
    df = df.sort_index()
    
    # Moving averages (using previous values only)
    df['ma7'] = df['y'].shift(1).rolling(window=7).mean()
    df['ma30'] = df['y'].shift(1).rolling(window=30).mean()
    df['ma60'] = df['y'].shift(1).rolling(window=60).mean()
    df['ma90'] = df['y'].shift(1).rolling(window=90).mean()
    df['ma120'] = df['y'].shift(1).rolling(window=120).mean()
    df['ma150'] = df['y'].shift(1).rolling(window=150).mean()
    df['ma180'] = df['y'].shift(1).rolling(window=180).mean()
    df['ma365'] = df['y'].shift(1).rolling(window=365).mean()
    
    return df

In the next two code block, we add weather data to the data set. This is not optimized i.e. we just obtain the weather data in Manhattan and hope that it is representative of the average weather over the whole city.

In [34]:
## Add weather data.

import requests
import pandas as pd

lat, lon = 40.7831, -73.9712
start = "2020-01-01"
end   = "2026-02-28"

url = (
    "https://archive-api.open-meteo.com/v1/archive"
    f"?latitude={lat}&longitude={lon}"
    f"&start_date={start}&end_date={end}"
    "&daily=temperature_2m_max,temperature_2m_min,temperature_2m_mean,"
    "apparent_temperature_max,apparent_temperature_min,apparent_temperature_mean,"
    "precipitation_sum,snowfall_sum"
    "&timezone=America/New_York"
)

response = requests.get(url)
data = response.json()

if 'error' in data:
    nd = pd.read_csv("weatherdata.csv")
    nd = nd.set_index('date')
    wd = nd

else:
    wd = pd.DataFrame(data["daily"])
    wd["date"] = pd.to_datetime(wd["time"])
    wd = wd.set_index("date")

In [35]:
def add_weather_data(df, wd):
    df = df.copy()
    wd = wd.copy()
    
    # Ensure datetime index
    df.index = pd.to_datetime(df.index)
    wd.index = pd.to_datetime(wd.index)
    
    # Drop unnecessary column
    if "time" in wd.columns:
        wd = wd.drop(columns=["time"])
    
    # Join on date index
    df = df.join(wd, how="left")
    
    return df

In [36]:
from pandas.tseries.holiday import USFederalHolidayCalendar

def add_federal_holidays(df, custom_holidays=None):
    df = df.copy()
    
    # Ensure datetime index
    df.index = pd.to_datetime(df.index)
    
    cal = USFederalHolidayCalendar()
    holidays = cal.holidays(start=df.index.min(), end=df.index.max())
    
    if custom_holidays:
        for d in custom_holidays:
            if len(d) == 5:  # MM-DD format → recurring annually
                years = df.index.year.unique()
                for y in years:
                    holidays = holidays.append(pd.to_datetime([f"{y}-{d}"]))
            else:  # YYYY-MM-DD → one specific date
                holidays = holidays.append(pd.to_datetime([d]))
    
    holidays = holidays.drop_duplicates().sort_values()
    
    df["is_federal_holiday"] = df.index.isin(holidays).astype(int)
    
    return df

In [37]:
def add_law_flag(df, law_name: str, start_date: str):
    # Adds a binary column to indicate when a new law is active.
    df = df.copy()
    
    # Ensure datetime index
    df.index = pd.to_datetime(df.index)
    
    # Convert start_date to datetime
    start_dt = pd.to_datetime(start_date)
    
    # Create binary column: 1 if date >= start_date, else 0
    df[law_name] = (df.index >= start_dt).astype(int)
    
    return df

In [38]:
# This must be run importing weather data

def add_more_weather_feature(df):
    target_map = df['apparent_temperature_min'].to_dict()
    df['apparent_temperature_min_lag1'] = (df.index - pd.Timedelta('1 days')).map(target_map)
    df['apparent_temperature_min_lag7'] = (df.index - pd.Timedelta('7 days')).map(target_map)
    df['apparent_temperature_min_lag14'] = (df.index - pd.Timedelta('14 days')).map(target_map)
    df['apparent_temperature_min_lag30'] = (df.index - pd.Timedelta('30 days')).map(target_map)
    df['apparent_temperature_min_lag60'] = (df.index - pd.Timedelta('60 days')).map(target_map)
    df['apparent_temperature_min_lag90'] = (df.index - pd.Timedelta('90 days')).map(target_map)
    df['apparent_temperature_min_lag120'] = (df.index - pd.Timedelta('120 days')).map(target_map)
    df['apparent_temperature_min_lag150'] = (df.index - pd.Timedelta('150 days')).map(target_map)
    df['apparent_temperature_min_lag180'] = (df.index - pd.Timedelta('180 days')).map(target_map)
    df['apparent_temperature_min_lag210'] = (df.index - pd.Timedelta('210 days')).map(target_map)
    df['apparent_temperature_min_lag240'] = (df.index - pd.Timedelta('240 days')).map(target_map)
    df['apparent_temperature_min_lag270'] = (df.index - pd.Timedelta('270 days')).map(target_map)
    df['apparent_temperature_min_lag300'] = (df.index - pd.Timedelta('300 days')).map(target_map)
    df['apparent_temperature_min_lag330'] = (df.index - pd.Timedelta('330 days')).map(target_map)
    df['apparent_temperature_min_lag360'] = (df.index - pd.Timedelta('360 days')).map(target_map)
    df['apparent_temperature_min_lag365'] = (df.index - pd.Timedelta('365 days')).map(target_map)
    df['apparent_temperature_min_lag730'] = (df.index - pd.Timedelta('730 days')).map(target_map)

    target_map = df['temperature_2m_max'].to_dict()
    df['temperature_2m_max_lag14'] = (df.index - pd.Timedelta('14 days')).map(target_map)
    df['temperature_2m_max_lag30'] = (df.index - pd.Timedelta('30 days')).map(target_map)
    df['temperature_2m_max_lag60'] = (df.index - pd.Timedelta('60 days')).map(target_map)

    return df

In [39]:
rs = rs.set_index('ds')
rs.index = pd.to_datetime(rs.index)
rs

             y
ds
2020-01-01   4
2020-01-02   7
2020-01-03  16
2020-01-04  10
2020-01-05   5
...         ..
2026-02-24   7
2026-02-25   8
2026-02-26   9
2026-02-27  17
2026-02-28   5

[2251 rows x 1 columns]

In [40]:
rs = create_features(rs)
rs = add_cyclic(rs)
rs = add_lags(rs)
rs = add_seasonal_lags(rs)
rs = add_moving_averages(rs)
rs = add_weather_data(rs,wd)
rs = add_more_weather_feature(rs)
rs = add_federal_holidays(rs, custom_holidays = ['12-31'])
rs = add_law_flag(rs, law_name='Trash_Law', start_date = '2024-03-01')
rs = add_law_flag(rs, law_name = 'New_Trash_Law', start_date = '2024-11-01')
rs = add_law_flag(rs, law_name='Rat_Mitigation_Zone', start_date = '2023-07-07')
rs = add_law_flag(rs, law_name='Rat_Czar_Appointed', start_date = '2023-04-12')

In [41]:
rs

,y,dayofweek,quarter,month,year,dayofyear,dayofmonth,weekofyear,dayofweek_sin,dayofweek_cos,...,apparent_temperature_min_lag365,apparent_temperature_min_lag730,temperature_2m_max_lag14,temperature_2m_max_lag30,temperature_2m_max_lag60,is_federal_holiday,Trash_Law,New_Trash_Law,Rat_Mitigation_Zone,Rat_Czar_Appointed
ds,,,,,,,,,,,,,,,,,,,,,
2020-01-01,4,2,1,1,2020,1,1,1,0.974928,-0.222521,...,NaN,NaN,NaN,NaN,NaN,1,0,0,0,0
2020-01-02,7,3,1,1,2020,2,2,1,0.433884,-0.900969,...,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0
2020-01-03,16,4,1,1,2020,3,3,1,-0.433884,-0.900969,...,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0
2020-01-04,10,5,1,1,2020,4,4,1,-0.974928,-0.222521,...,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0
2020-01-05,5,6,1,1,2020,5,5,1,-0.781831,0.623490,...,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2026-02-24,7,1,1,2,2026,55,24,9,0.781831,0.623490,...,-4.6,-11.1,-0.3,-5.2,-2.8,0,1,1,1,1
2026-02-25,8,2,1,2,2026,56,25,9,0.974928,-0.222521,...,0.1,-6.9,3.2,-3.1,-0.8,0,1,1,1,1
2026-02-26,9,3,1,2,2026,57,26,9,0.433884,-0.900969,...,-1.4,-4.1,0.8,-7.3,1.3,0,1,1,1,1
2026-02-27,17,4,1,2,2026,58,27,9,-0.433884,-0.900969,...,1.0,0.0,0.9,-6.7,7.2,0,1,1,1,1
2026-02-28,5,5,1,2,2026,59,28,9,-0.974928,-0.222521,...,-2.0,-9.0,3.6,-7.8,-0.2,0,1,1,1,1

### Features for XGBoost

In [42]:
FEATURES = ['apparent_temperature_min_lag30',
            'apparent_temperature_min_lag60',
            'apparent_temperature_min_lag120',
            'apparent_temperature_min_lag365',
            'apparent_temperature_min_lag730',
            'dayofyear', 
            'temperature_2m_max_lag30',
            'temperature_2m_max_lag60'
            ]

### Add default parameters for XGBoost

In [43]:
params = {'objective': 'reg:squarederror',
         'eval_metric': 'rmse',
         'booster': 'gbtree',
         'base_score': 0.5, 
         'n_estimators': 1000, 
        #  'min_child_weight': 6, 
        # 'learning_rate': 0.01,
        # 'max_depth': 8, 
        #  'subsample': 1,
        #  'colsample_bytree': 0.96,
        #  'colsample_bylevel': 0.6, 
        #  'colsample_bynode': 0.9, 
        #  'reg_alpha': 2.2, 
        #  'gamma': 100, 
        #  'reg_lambda': 0.18,
        #  'early_stopping_rounds': 100, 
        }

In [44]:
print(FEATURES)
print(params)
TARGET = 'y'

# Gotta make sure the features and parameters exist.

reg = xgb.XGBRegressor(**params)
results = []

for i, (train_index, test_index) in enumerate(tscv.split(rs)):
    train = rs.iloc[train_index]
    test = rs.iloc[test_index]
    
    reg.fit(train[FEATURES], train[TARGET])
    y_pred = reg.predict(test[FEATURES])
    y_true = test[TARGET].values
    
    # Our metrics
    rmse = np.sqrt(mean_squared_error(y_true, y_pred))
    mape = mean_absolute_percentage_error(y_true, y_pred)
    
    results.append({'fold': i, 'rmse': rmse, 'mape': mape})

xgb_results_df = pd.DataFrame(results)
mean_rmse = xgb_results_df['rmse'].mean()
mean_mape = xgb_results_df['mape'].mean()
xgb_results_df.loc['mean'] = ['mean', mean_rmse, mean_mape]

['apparent_temperature_min_lag30', 'apparent_temperature_min_lag60', 'apparent_temperature_min_lag120', 'apparent_temperature_min_lag365', 'apparent_temperature_min_lag730', 'dayofyear', 'temperature_2m_max_lag30', 'temperature_2m_max_lag60']
{'objective': 'reg:squarederror', 'eval_metric': 'rmse', 'booster': 'gbtree', 'base_score': 0.5, 'n_estimators': 1000}

In [45]:
xgb_results_df

      fold       rmse          mape
0        0   6.593968  5.454404e-01
1        1   5.511529  2.090745e-01
2        2   5.461204  3.708208e-01
3        3   7.352492  5.352463e-01
4        4   9.604590  5.430093e-01
5        5   6.913237  4.267199e-01
6        6   7.336617  3.604815e-01
7        7   8.106707  2.738692e-01
8        8   7.609508  4.417320e-01
9        9  11.005581  6.839630e-01
10      10   7.938400  5.134233e-01
11      11   8.173558  5.534216e-01
12      12   9.090894  3.599961e-01
13      13   6.827491  4.717081e-01
14      14   6.980573  4.372980e-01
15      15   7.779560  7.964015e-01
16      16   7.151851  6.393161e-01
17      17   8.631426  1.394979e+00
18      18   5.898776  6.858878e-01
19      19   6.871145  4.198562e+15
20      20   5.935147  9.863816e-01
21      21   7.217321  1.636952e+00
22      22   7.549772  7.843965e-01
23      23   9.184423  1.445553e+00
24      24   7.501596  1.220344e+00
25      25   8.953335  1.203623e+00
mean  mean   7.583873  1.614832e+14

## XGBoosted Prophet Model

In [46]:
# Recall the copy that was saved.
rs_saved

             ds   y
0    2020-01-01   4
1    2020-01-02   7
2    2020-01-03  16
3    2020-01-04  10
4    2020-01-05   5
...         ...  ..
2246 2026-02-24   7
2247 2026-02-25   8
2248 2026-02-26   9
2249 2026-02-27  17
2250 2026-02-28   5

[2251 rows x 2 columns]

In [47]:
rs = rs_saved

In [48]:
results = []

for i, (train_index, test_index) in enumerate(tscv.split(rs)):
    # Split the dataset into training and testing sets
    train = rs.iloc[train_index]
    test = rs.iloc[test_index]
    
    # Fit Prophet on the training data
    model = Prophet(holidays=holidays)
    model.add_country_holidays(country_name='US')
    model.fit(train)
    
    # Make predictions on the training set to calculate residuals
    train_future = model.make_future_dataframe(periods=0, freq='D')  # Use periods=0 to only use the training data
    train_forecast = model.predict(train_future)
    
    # Calculate residuals (actual - predicted) on the training data
    train_residuals = train['y'].values - train_forecast['yhat'][:len(train)].values
    
    # Build a new DataFrame of residuals
    residuals_df = pd.DataFrame({'ds': train['ds'], 'y': train_residuals })

    train = train.set_index('ds')
    train.index = pd.to_datetime(train.index)
    train = create_features(train)
    train = add_cyclic(train)
    train = add_lags(train)
    train = add_seasonal_lags(train)
    train = add_moving_averages(train)
    train = add_weather_data(train,wd)
    train = add_more_weather_feature(train)
    train = add_federal_holidays(train, custom_holidays = ['12-31'])
    train = add_law_flag(train, law_name='Trash_Law', start_date = '2024-03-01')
    train = add_law_flag(train, law_name = 'New_Trash_Law', start_date = '2024-11-01')
    train = add_law_flag(train, law_name='Rat_Mitigation_Zone', start_date = '2023-07-07')
    train = add_law_flag(train, law_name='Rat_Czar_Appointed', start_date = '2023-04-12')

    X_train_residuals = train[FEATURES]
    y_train_residuals = residuals_df['y']
    
    xgb_model = xgb.XGBRegressor(**params)
    xgb_model.fit(X_train_residuals, y_train_residuals)
    

    test = test.set_index('ds')
    test.index = pd.to_datetime(test.index)
    test = create_features(test)
    test = add_cyclic(test)
    test = add_lags(test)
    test = add_seasonal_lags(test)
    test = add_moving_averages(test)
    test = add_weather_data(test,wd)
    test = add_more_weather_feature(test)
    test = add_federal_holidays(test, custom_holidays = ['12-31'])
    test = add_law_flag(test, law_name='Trash_Law', start_date = '2024-03-01')
    test = add_law_flag(test, law_name = 'New_Trash_Law', start_date = '2024-11-01')
    test = add_law_flag(test, law_name='Rat_Mitigation_Zone', start_date = '2023-07-07')
    test = add_law_flag(test, law_name='Rat_Czar_Appointed', start_date = '2023-04-12')

    # Predict residuals using XGBoost for the test set
    X_test = test[FEATURES]  # Features for the test set
    xgb_residual_preds = xgb_model.predict(X_test)
    
    # Forecast using Prophet on the test set
    future = model.make_future_dataframe(periods=len(test), freq='D')
    prophet_forecast = model.predict(future)
    
    # Combine Prophet's forecast and XGBoost's residual prediction
    y_pred = prophet_forecast['yhat'][-len(test):].values + xgb_residual_preds
    
    # Actual values for the test set
    y_true = test['y'].values
    
    # Calculate RMSE
    rmse = np.sqrt(mean_squared_error(y_true, y_pred))
    
    # Calculate MAPE
    mape = mean_absolute_percentage_error(y_true, y_pred)
    
    # Store the results for this fold
    results.append({'fold': i, 'rmse': rmse, 'mape': mape})

    ## Uncomment code below if you want to have plots on feature importance.
    # fig, (ax1, ax2, ax3, ax4, ax5) = plt.subplots(5, 1, figsize=(10, 30))
    # plot_importance(xgb_model, ax=ax1, importance_type='gain')
    # ax1.set_title('Gain-based Importance', fontsize=12)

    # plot_importance(xgb_model, ax=ax2, importance_type='weight')
    # ax2.set_title('Split-based Importance', fontsize=12)

    # plot_importance(xgb_model, ax=ax3, importance_type='cover')
    # ax3.set_title('Cover Importance', fontsize=12)

    # plot_importance(xgb_model, ax=ax4, importance_type='total_gain')
    # ax4.set_title('Total Gain Importance', fontsize=12)

    # plot_importance(xgb_model, ax=ax5, importance_type='total_cover')
    # ax5.set_title('Total Cover Importance', fontsize=12)

    plt.show()

# Convert the results into a DataFrame
prophet_xgb_results_df = pd.DataFrame(results)

prophet_xgb_results_df = pd.DataFrame(results)
mean_rmse = prophet_xgb_results_df['rmse'].mean()
mean_mape = prophet_xgb_results_df['mape'].mean()
prophet_xgb_results_df.loc['mean'] = ['mean', mean_rmse, mean_mape]

01:29:53 - cmdstanpy - INFO - Chain [1] start processing
01:29:53 - cmdstanpy - INFO - Chain [1] done processing
01:29:58 - cmdstanpy - INFO - Chain [1] start processing
01:29:58 - cmdstanpy - INFO - Chain [1] done processing
01:30:04 - cmdstanpy - INFO - Chain [1] start processing
01:30:04 - cmdstanpy - INFO - Chain [1] done processing
01:30:09 - cmdstanpy - INFO - Chain [1] start processing
01:30:09 - cmdstanpy - INFO - Chain [1] done processing
01:30:15 - cmdstanpy - INFO - Chain [1] start processing
01:30:15 - cmdstanpy - INFO - Chain [1] done processing
01:30:20 - cmdstanpy - INFO - Chain [1] start processing
01:30:20 - cmdstanpy - INFO - Chain [1] done processing
01:30:26 - cmdstanpy - INFO - Chain [1] start processing
01:30:26 - cmdstanpy - INFO - Chain [1] done processing
01:30:31 - cmdstanpy - INFO - Chain [1] start processing
01:30:31 - cmdstanpy - INFO - Chain [1] done processing
01:30:36 - cmdstanpy - INFO - Chain [1] start processing
01:30:37 - cmdstanpy - INFO - Chain [1] done processing
01:30:42 - cmdstanpy - INFO - Chain [1] start processing
01:30:42 - cmdstanpy - INFO - Chain [1] done processing
01:30:47 - cmdstanpy - INFO - Chain [1] start processing
01:30:47 - cmdstanpy - INFO - Chain [1] done processing
01:30:52 - cmdstanpy - INFO - Chain [1] start processing
01:30:52 - cmdstanpy - INFO - Chain [1] done processing
01:30:57 - cmdstanpy - INFO - Chain [1] start processing
01:30:57 - cmdstanpy - INFO - Chain [1] done processing
01:31:03 - cmdstanpy - INFO - Chain [1] start processing
01:31:03 - cmdstanpy - INFO - Chain [1] done processing
01:31:08 - cmdstanpy - INFO - Chain [1] start processing
01:31:08 - cmdstanpy - INFO - Chain [1] done processing
01:31:13 - cmdstanpy - INFO - Chain [1] start processing
01:31:13 - cmdstanpy - INFO - Chain [1] done processing
01:31:19 - cmdstanpy - INFO - Chain [1] start processing
01:31:19 - cmdstanpy - INFO - Chain [1] done processing
01:31:24 - cmdstanpy - INFO - Chain [1] start processing
01:31:24 - cmdstanpy - INFO - Chain [1] done processing
01:31:30 - cmdstanpy - INFO - Chain [1] start processing
01:31:30 - cmdstanpy - INFO - Chain [1] done processing
01:31:35 - cmdstanpy - INFO - Chain [1] start processing
01:31:35 - cmdstanpy - INFO - Chain [1] done processing
01:31:41 - cmdstanpy - INFO - Chain [1] start processing
01:31:41 - cmdstanpy - INFO - Chain [1] done processing
01:31:45 - cmdstanpy - INFO - Chain [1] start processing
01:31:46 - cmdstanpy - INFO - Chain [1] done processing
01:31:51 - cmdstanpy - INFO - Chain [1] start processing
01:31:51 - cmdstanpy - INFO - Chain [1] done processing
01:31:57 - cmdstanpy - INFO - Chain [1] start processing
01:31:57 - cmdstanpy - INFO - Chain [1] done processing
01:32:02 - cmdstanpy - INFO - Chain [1] start processing
01:32:02 - cmdstanpy - INFO - Chain [1] done processing
01:32:07 - cmdstanpy - INFO - Chain [1] start processing
01:32:07 - cmdstanpy - INFO - Chain [1] done processing

In [49]:
prophet_xgb_results_df

      fold       rmse          mape
0        0   4.997927  3.934125e-01
1        1   5.449558  2.238328e-01
2        2   3.762977  2.678660e-01
3        3   3.932596  2.847101e-01
4        4   4.630647  2.409737e-01
5        5   5.886754  3.665368e-01
6        6   4.862755  2.408163e-01
7        7   7.741118  2.654960e-01
8        8   5.873941  3.170855e-01
9        9   5.869351  3.782779e-01
10      10   6.370718  4.151782e-01
11      11   7.456203  5.027089e-01
12      12   7.010637  3.127725e-01
13      13   5.477975  3.085632e-01
14      14   7.989720  5.503667e-01
15      15   9.723279  9.878439e-01
16      16   5.316384  4.590810e-01
17      17  10.207172  1.605202e+00
18      18  11.373901  1.375023e+00
19      19   7.279476  2.386218e+15
20      20   4.035675  6.341077e-01
21      21   6.876105  1.628564e+00
22      22   5.415986  4.450684e-01
23      23   6.264172  9.233234e-01
24      24   6.697280  1.069128e+00
25      25   4.951530  6.387503e-01
mean  mean   6.363609  9.177762e+13

# Conclusions on Model Comparisons

## Results Table

In [50]:
# We make a dictionary of models and their results to make it easier to iterate over.
models = {
    'baseline': baseline_results_df,
    'rolling4w': rolling4w_results_df,
    'prophet': prophet_results_df,
    'sarima': sarima_results_df,
    'hw': hw_results_df,
    'xgb': xgb_results_df,
    'prophet+xgb': prophet_xgb_results_df
}

all_results = []
for model_name, df in models.items():
    df['model'] = model_name
    all_results.append(df)

# Put all of the dataframes together into one dataframe for display
final_results_df = pd.concat(all_results, ignore_index=True)

# Make a pivot table so that we display rmse, mape and then each of the models and their results.
final_table = final_results_df.pivot(index='fold', columns='model', values=['rmse', 'mape'])
final_table.index = final_table.index.where(final_table.index != '-', 'mean')

final_table

            rmse                                                      \
model   baseline        hw   prophet prophet+xgb rolling4w    sarima
fold
0       6.110015  5.734597  4.648000    4.997927  5.355238  5.005975
1       4.792049  7.631673  7.456070    5.449558  8.373001  6.167581
2       4.519542  6.044236  3.755772    3.762977  3.894823  5.362712
3       5.820867  6.727356  3.921697    3.932596  5.993300  4.759396
4       5.803395  7.228770  4.491096    4.630647  6.008922  5.142934
5       7.330541  6.924762  6.057690    5.886754  7.652614  6.763359
6       5.947332  6.502953  5.067045    4.862755  8.599730  5.268748
7       6.018142  8.699943  6.354280    7.741118  8.957738  7.005431
8       6.515253  5.846188  5.992057    5.873941  6.800735  7.018665
9       7.840324  8.228982  5.324755    5.869351  5.257647  5.902277
10      9.310988  7.666488  5.579764    6.370718  5.630751  5.960499
11      8.895986  6.025826  5.457583    7.456203  5.490251  5.466420
12      8.002407  8.317778  6.856154    7.010637  8.568526  7.820472
13      6.797736  5.970340  5.010714    5.477975  6.602894  5.952080
14      7.611748  5.823659  6.310236    7.989720  5.500000  5.675855
15      8.421691  5.930965  4.629287    9.723279  6.366065  4.410161
16      7.654961  4.239823  4.280261    5.316384  4.689464  4.123681
17     10.062572  6.139685  5.843399   10.207172  7.188781  4.693388
18      7.677977  4.469317  4.408426   11.373901  3.668154  3.973114
19      6.678495  5.035023  2.938349    7.279476  5.628372  3.970715
20      6.710397  3.217969  3.631120    4.035675  2.950484  2.490315
21      6.719962  5.351250  3.330654    6.876105  4.156535  3.663106
22      5.608994  4.529289  3.519925    5.415986  5.229552  4.507117
23      7.456576  4.037067  3.451783    6.264172  3.935870  3.858648
24      8.015235  2.763491  3.772100    6.697280  2.041970  4.099142
25      6.383076  3.852078  4.581812    4.951530  5.143477  4.002693
mean    7.027164  5.882289  4.871924    6.363609  5.757111  5.117865

                          mape                                            \
model        xgb      baseline            hw       prophet   prophet+xgb
fold
0       6.593968  5.187832e-01  4.516267e-01  3.493749e-01  3.934125e-01
1       5.511529  1.711072e-01  3.116474e-01  3.300603e-01  2.238328e-01
2       5.461204  3.200928e-01  4.149782e-01  2.504353e-01  2.678660e-01
3       7.352492  4.201764e-01  4.865189e-01  2.842048e-01  2.847101e-01
4       9.604590  3.171943e-01  3.555821e-01  1.853417e-01  2.409737e-01
5       6.913237  5.227390e-01  4.295341e-01  3.874641e-01  3.665368e-01
6       7.336617  3.256959e-01  2.740456e-01  2.375071e-01  2.408163e-01
7       8.106707  2.473551e-01  3.076210e-01  1.923037e-01  2.654960e-01
8       7.609508  3.696147e-01  2.962146e-01  2.824904e-01  3.170855e-01
9      11.005581  5.171844e-01  5.333166e-01  3.432802e-01  3.782779e-01
10      7.938400  6.290299e-01  4.326266e-01  3.596880e-01  4.151782e-01
11      8.173558  6.089048e-01  3.671231e-01  3.605216e-01  5.027089e-01
12      9.090894  4.195949e-01  2.419009e-01  2.277337e-01  3.127725e-01
13      6.827491  4.752848e-01  3.783984e-01  2.967229e-01  3.085632e-01
14      6.980573  5.331502e-01  3.510820e-01  4.131089e-01  5.503667e-01
15      7.779560  8.997112e-01  6.164632e-01  4.523299e-01  9.878439e-01
16      7.151851  7.062848e-01  3.409041e-01  3.321512e-01  4.590810e-01
17      8.631426  1.681684e+00  9.310572e-01  8.980077e-01  1.605202e+00
18      5.898776  9.293678e-01  3.980163e-01  4.870380e-01  1.375023e+00
19      6.871145  3.824485e+15  3.052718e+15  2.441334e+14  2.386218e+15
20      5.935147  1.169345e+00  4.192029e-01  5.092911e-01  6.341077e-01
21      7.217321  1.850322e+00  1.053995e+00  6.930523e-01  1.628564e+00
22      7.549772  5.981685e-01  4.117205e-01  2.842049e-01  4.450684e-01
23      9.184423  1.286946e+00  5.935925e-01  5.167387e-01  9.233234e-01
24      7.501596  1.393778e+00  4.001561e-01  5.915224e-01  1.069128e+00
25      8.953335  8.871942e-01  3.583591e-01  5.565141e-01  6.387503e-01
mean    7.583873  1.470956e+14  1.174122e+14  9.389747e+12  9.177762e+13


model     rolling4w        sarima           xgb
fold
0      4.252300e-01  3.369476e-01  5.454404e-01
1      3.625078e-01  2.451594e-01  2.090745e-01
2      2.717289e-01  3.859427e-01  3.708208e-01
3      3.107589e-01  3.416060e-01  5.352463e-01
4      2.453872e-01  2.450909e-01  5.430093e-01
5      5.443236e-01  4.694163e-01  4.267199e-01
6      3.345505e-01  2.352967e-01  3.604815e-01
7      2.841237e-01  2.224091e-01  2.738692e-01
8      3.947767e-01  4.072846e-01  4.417320e-01
9      2.856080e-01  3.881165e-01  6.839630e-01
10     2.703794e-01  3.722656e-01  5.134233e-01
11     2.610070e-01  3.678337e-01  5.534216e-01
12     1.992474e-01  1.960797e-01  3.599961e-01
13     3.529541e-01  3.592433e-01  4.717081e-01
14     3.884974e-01  3.647973e-01  4.372980e-01
15     6.639706e-01  4.548879e-01  7.964015e-01
16     4.302836e-01  3.578910e-01  6.393161e-01
17     1.202054e+00  6.544846e-01  1.394979e+00
18     4.107391e-01  3.661534e-01  6.858878e-01
19     3.699385e+15  2.730803e+15  4.198562e+15
20     4.992334e-01  4.017614e-01  9.863816e-01
21     1.274620e+00  1.031922e+00  1.636952e+00
22     3.352837e-01  2.816386e-01  7.843965e-01
23     6.316356e-01  6.185217e-01  1.445553e+00
24     2.220805e-01  6.913284e-01  1.220344e+00
25     4.251677e-01  3.811827e-01  1.203623e+00
mean   1.422841e+14  1.050309e+14  1.614832e+14

## Summary

In the above table, we see that the Prophet model had the best average RMSE, but the margins are quite slim so far. Prophet beatsour Sarima by at best 0.2 on average.