In the previous notebook models_manhattan.ipynb, we found that the Prophet and NeuralProphet models performed well in terms of forecasting rat sightings by day citywide. In this notebook, we will do some more feature engineering and hyperparameter tuning to obtain a better optimal model.

Because we wish this to be reusable, we will write things for Prophet and NeuralProphet separately.

# Import Packages

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import datetime

from sklearn.model_selection import TimeSeriesSplit
from sklearn.metrics import mean_squared_error, mean_absolute_percentage_error
from sklearn.linear_model import LinearRegression

from prophet import Prophet
from pandas.tseries.holiday import USFederalHolidayCalendar
from prophet.diagnostics import cross_validation, performance_metrics
from prophet.plot import plot_cross_validation_metric
from prophet.plot import add_changepoints_to_plot
from prophet.plot import plot_plotly, plot_components_plotly
import itertools

import warnings
from statsmodels.tools.sm_exceptions import ConvergenceWarning
warnings.simplefilter('ignore', ConvergenceWarning)

import optuna
from neuralprophet import NeuralProphet
import logging

Importing plotly failed. Interactive plots will not work.
Importing plotly failed. Interactive plots will not work.

# Prophet

## Import the data

In [19]:
# set up the time series split
tscv = TimeSeriesSplit(gap=0, max_train_size=None, n_splits=26, test_size=14)

rs = pd.read_csv('../scr/data/cleaned_rat_sightings_data/all_daily_borough_rs.csv')
rs['created_date'] = pd.to_datetime(rs['created_date']) 

# Start by cutting off data before 2020-01-01 and after 2026-02-28.
rs = rs[rs['created_date']<'2026-03-01']
rs = rs[rs['created_date']>='2020-01-01']

## Restrict to MANHATTAN

rs = rs[rs['borough']=='MANHATTAN']

## Drop the column with borough

rs = rs.drop(columns=['borough'])

## rename columns for prophet

rs.rename(columns={'created_date': 'ds', 'count': 'y'}, inplace=True)

## Prepare Prophet

In [20]:
date_range = pd.date_range(start="2020-01-01", end="2026-02-28")

# Generate US federal holidays
calendar = USFederalHolidayCalendar()
holidays = calendar.holidays(start=date_range.min(), end=date_range.max())

federal_holidays = pd.DataFrame({
    'holiday': 'federal_us',
    'ds': pd.to_datetime(holidays),
    'lower_window': 0,
    'upper_window': 1})

holidays = federal_holidays

In [21]:
rs_saved = rs.copy()
df = rs.copy()

## Optuna for Hyperparameter Tuning for Prophet

In [22]:
import logging
logging.getLogger("cmdstanpy").setLevel(logging.WARNING)

In [23]:
## To tune for hyperparameters, add more possible parameters to the dictionary below and add more values to it.
## So far, the I've been able to get is {'changepoint_prior_scale': 0.1, 'seasonality_prior_scale': 5}

init_days = '2054 days'
cv_period = '14 days'
forecast_horizon = '14 days'

param_grid = {  
    'changepoint_prior_scale': [0.1, 1],
    'seasonality_prior_scale': [0.1, 1, 5, 10],
}

# Generate all combinations of parameters
all_params = [dict(zip(param_grid.keys(), v)) for v in itertools.product(*param_grid.values())]
rmses = []  # Store the RMSEs for each params here
performance = []

# Use cross validation to evaluate all parameters
for params in all_params:
    params['holidays'] = holidays
    m = Prophet(**params).fit(df)  # Fit model with given params
    df_cv = cross_validation(m, initial = init_days, period=cv_period, horizon = forecast_horizon)
    df_p = performance_metrics(df_cv, rolling_window=14)
    performance.append(df_p)
    rmses.append(df_p['rmse'].values[0])

# Find the best parameters
tuning_results = pd.DataFrame(all_params)
tuning_results['rmse'] = rmses

best_params = all_params[np.argmin(rmses)]

20:43:56 - cmdstanpy - INFO - Chain [1] start processing
20:43:56 - cmdstanpy - INFO - Chain [1] done processing

  0%|          | 0/14 [00:00<?, ?it/s]

20:43:56 - cmdstanpy - INFO - Chain [1] start processing
20:43:57 - cmdstanpy - INFO - Chain [1] done processing

KeyboardInterrupt:

In [ ]:
new_performance = pd.concat(performance, ignore_index=True)

# Round numeric columns for readability
numeric_cols = ["mse", "rmse", "mae", "mape", "mdape", "smape", "coverage"]
new_performance[numeric_cols] = new_performance[numeric_cols].round(4)


new_performance

  horizon       mse     rmse     mae    mape   mdape   smape  coverage
0 14 days  142.2601  11.9273  9.6061  0.3244  0.2428  0.3052    0.8827
1 14 days  141.3321  11.8883  9.5662  0.3234  0.2431  0.3053    0.8673
2 14 days  141.3546  11.8893  9.5800  0.3239  0.2432  0.3056    0.8827
3 14 days  141.1426  11.8803  9.5672  0.3234  0.2436  0.3045    0.8878
4 14 days  146.4931  12.1034  9.6572  0.3269  0.2385  0.3383    0.8520
5 14 days  145.7510  12.0727  9.6467  0.3264  0.2358  0.3389    0.8571
6 14 days  145.6748  12.0696  9.6284  0.3260  0.2361  0.3387    0.8571
7 14 days  146.1802  12.0905  9.6539  0.3266  0.2370  0.3392    0.8622

## Train the Model

In [ ]:
m = Prophet(**best_params)
m.add_country_holidays(country_name='US')
m.fit(df)
future = m.make_future_dataframe(periods=14)
forecast = m.predict(future)

17:27:57 - cmdstanpy - INFO - Chain [1] start processing
17:27:57 - cmdstanpy - INFO - Chain [1] done processing

## Plots and Evaluation of the Model

In [ ]:
fig1 = plot_plotly(m, forecast)
fig1.show()

fig2 = plot_components_plotly(m, forecast)
fig2.show()

# Neural Prophet

In [2]:
np.NaN = np.nan


# the following packages are meant to turn off a bunch of the warnings and ERRORs that pop up while running NeuralProphet.
# the errors that do show up are not all that important and a lot is due to outdated packages.
import warnings
import logging

warnings.filterwarnings("ignore")

logging.getLogger("neuralprophet").setLevel(logging.ERROR)
logging.getLogger("pytorch_lightning").setLevel(logging.ERROR)
logging.getLogger("NP").setLevel(logging.ERROR)

In [3]:
rs = pd.read_csv('../scr/data/cleaned_rat_sightings_data/all_daily_borough_rs.csv')
rs['created_date'] = pd.to_datetime(rs['created_date']) 

# Start by cutting off data before 2020-01-01 and after 2026-02-28.
rs = rs[rs['created_date']<'2026-03-01']
rs = rs[rs['created_date']>='2020-01-01']

## Restrict to MANHATTAN

rs = rs[rs['borough']=='MANHATTAN']

## Drop the column with borough

rs = rs.drop(columns=['borough'])

## rename columns for prophet

rs.rename(columns={'created_date': 'ds', 'count': 'y'}, inplace=True)

rs

              ds   y
2     2020-01-01   4
7     2020-01-02   7
12    2020-01-03  16
17    2020-01-04  10
21    2020-01-05   5
...          ...  ..
10611 2026-02-24   7
10616 2026-02-25   8
10620 2026-02-26   9
10625 2026-02-27  17
10629 2026-02-28   5

[2250 rows x 2 columns]

In [4]:
## Add weather data.
import requests

lat, lon = 40.7831, -73.9712
start = "2020-01-01"
end   = "2026-02-28"

url = (
    "https://archive-api.open-meteo.com/v1/archive"
    f"?latitude={lat}&longitude={lon}"
    f"&start_date={start}&end_date={end}"
    "&daily=temperature_2m_max,temperature_2m_min,temperature_2m_mean,"
    "apparent_temperature_max,apparent_temperature_min,apparent_temperature_mean,"
    "precipitation_sum,snowfall_sum"
    "&timezone=America/New_York"
)

response = requests.get(url)
data = response.json()

if 'error' in data:
    nd = pd.read_csv("weatherdata.csv")
    nd = nd.set_index('date')
    wd = nd
    
else:
    wd = pd.DataFrame(data["daily"])
    wd["date"] = pd.to_datetime(wd["time"])
    wd = wd.set_index("date")

In [ ]:
# Suppress cmdstanpy info logs
logging.getLogger("cmdstanpy").setLevel(logging.WARNING)


regressed_features = ['apparent_temperature_max', 'apparent_temperature_min', 'snowfall_sum']


wd = wd.reset_index(drop=True).rename(columns={"time": "ds"})
wd["ds"] = pd.to_datetime(wd["ds"])
rs["ds"] = pd.to_datetime(rs["ds"])

rs = rs.merge(
    wd[['ds'] + regressed_features],
    on="ds",
    how="left"
)

tscv = TimeSeriesSplit(gap=0, max_train_size=None, n_splits=2, test_size=14)


def objective(trial):
    regressor_lags = {
        'apparent_temperature_max': trial.suggest_int('lag_temp_max', 1, 60),
        'apparent_temperature_min': trial.suggest_int('lag_temp_min', 1, 60),
        'snowfall_sum': trial.suggest_int('lag_snowfall', 1, 7),
    }
    n_lags = trial.suggest_int('n_lags', 1, 60)
    epochs = trial.suggest_int('epochs', 50, 500)
    learning_rate = trial.suggest_float('learning_rate', 0.001, 1, log=True)
    batch_size = trial.suggest_int('batch_size', 20, 248)
    ar_reg = trial.suggest_float('ar_reg', 0.5, 3)
    fold_rmses = []
    for i, (train_idx, test_idx) in enumerate(tscv.split(rs)):

        train = rs.iloc[train_idx].copy()
        test = rs.iloc[test_idx].copy()
        
        existing_regressors = [col for col in regressed_features if col in train.columns]
        train = train.dropna(subset=["y"] + existing_regressors)
        test = test.dropna(subset=existing_regressors)
        
        # Skip fold if too few rows
        if len(train) < 20 or len(test) < 1:
            continue
        
        model = NeuralProphet(
            yearly_seasonality=True,
            weekly_seasonality=True,
            n_lags=n_lags,
            epochs=epochs,
            ar_reg = ar_reg,
            accelerator="auto",   # uses GPU if available
            learning_rate=learning_rate,
            batch_size=batch_size
        )
        model.add_country_holidays(country_name="US")
        for col in existing_regressors:
            model.add_lagged_regressor(col, n_lags=regressor_lags[col])
        
        model.fit(train, freq="D", progress="off")
        future = pd.concat([
            train[['ds','y'] + existing_regressors],
            test[['ds','y']].merge(wd[['ds'] + existing_regressors], on="ds", how="left")
        ])
        future = future.dropna(subset=existing_regressors)
        forecast = model.predict(future)
        
        y_pred = forecast["yhat1"].iloc[-len(test):].values
        y_true = test["y"].values
        
        rmse = np.sqrt(mean_squared_error(y_true, y_pred))
        fold_rmses.append(rmse)

        intermediate_score = np.mean(fold_rmses)
        trial.report(intermediate_score, i)
        if trial.should_prune():
            raise optuna.TrialPruned()
        
    return np.mean(fold_rmses) if fold_rmses else float("inf")

study = optuna.create_study(direction="minimize")
study.optimize(objective, n_trials=500)  # adjust n_trials as needed



best_params = study.best_params

[I 2026-03-07 20:44:54,440] A new study created in memory with name: no-name-001933b7-0a3e-4149-b2d4-3bf7e6840581

Training: 0it [00:00, ?it/s]

Predicting: 18it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 19it [00:00, ?it/s]

[I 2026-03-07 20:46:36,857] Trial 0 finished with value: 4.1678418617966235 and parameters: {'lag_temp_max': 40, 'lag_temp_min': 11, 'lag_snowfall': 1, 'n_lags': 26, 'epochs': 299, 'learning_rate': 0.00252233445608806, 'batch_size': 122, 'ar_reg': 0.8717002268747449}. Best is trial 0 with value: 4.1678418617966235.

Training: 0it [00:00, ?it/s]

Predicting: 19it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 20it [00:00, ?it/s]

[I 2026-03-07 20:48:07,879] Trial 1 finished with value: 3.4243586604045184 and parameters: {'lag_temp_max': 3, 'lag_temp_min': 31, 'lag_snowfall': 1, 'n_lags': 60, 'epochs': 237, 'learning_rate': 0.004046433639123029, 'batch_size': 114, 'ar_reg': 1.9031193024270294}. Best is trial 1 with value: 3.4243586604045184.

Training: 0it [00:00, ?it/s]

Predicting: 17it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 17it [00:00, ?it/s]

[I 2026-03-07 20:48:39,510] Trial 2 finished with value: 3.4380578159873334 and parameters: {'lag_temp_max': 18, 'lag_temp_min': 4, 'lag_snowfall': 2, 'n_lags': 51, 'epochs': 90, 'learning_rate': 0.07153805854922526, 'batch_size': 133, 'ar_reg': 2.917357976238904}. Best is trial 1 with value: 3.4243586604045184.

Training: 0it [00:00, ?it/s]

Predicting: 26it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 26it [00:00, ?it/s]

[I 2026-03-07 20:49:18,399] Trial 3 finished with value: 3.6079570559862657 and parameters: {'lag_temp_max': 27, 'lag_temp_min': 46, 'lag_snowfall': 1, 'n_lags': 36, 'epochs': 86, 'learning_rate': 0.005481433272851723, 'batch_size': 87, 'ar_reg': 2.9262625925827592}. Best is trial 1 with value: 3.4243586604045184.

Training: 0it [00:00, ?it/s]

Predicting: 10it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 10it [00:00, ?it/s]

[I 2026-03-07 20:49:38,617] Trial 4 finished with value: 3.787597595454818 and parameters: {'lag_temp_max': 47, 'lag_temp_min': 60, 'lag_snowfall': 5, 'n_lags': 46, 'epochs': 74, 'learning_rate': 0.01959399425390006, 'batch_size': 231, 'ar_reg': 1.2523629844325155}. Best is trial 1 with value: 3.4243586604045184.

Training: 0it [00:00, ?it/s]

Predicting: 11it [00:00, ?it/s]

[I 2026-03-07 20:50:41,946] Trial 5 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 13it [00:00, ?it/s]

[I 2026-03-07 20:51:12,328] Trial 6 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 16it [00:00, ?it/s]

[I 2026-03-07 20:52:20,304] Trial 7 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 28it [00:00, ?it/s]

[I 2026-03-07 20:52:48,541] Trial 8 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 12it [00:00, ?it/s]

[I 2026-03-07 20:53:30,046] Trial 9 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 96it [00:00, ?it/s]

[I 2026-03-07 20:55:02,492] Trial 10 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 19it [00:00, ?it/s]

[I 2026-03-07 20:55:33,978] Trial 11 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 14it [00:00, ?it/s]

[I 2026-03-07 20:56:31,550] Trial 12 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 32it [00:00, ?it/s]

[I 2026-03-07 20:57:12,597] Trial 13 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 51it [00:00, ?it/s]

[I 2026-03-07 20:58:49,959] Trial 14 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 21it [00:00, ?it/s]

[I 2026-03-07 21:00:03,538] Trial 15 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 15it [00:00, ?it/s]

[I 2026-03-07 21:00:16,844] Trial 16 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 13it [00:00, ?it/s]

[I 2026-03-07 21:00:25,231] Trial 17 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 22it [00:00, ?it/s]

[I 2026-03-07 21:01:09,247] Trial 18 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 37it [00:00, ?it/s]

[I 2026-03-07 21:02:28,637] Trial 19 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 11it [00:00, ?it/s]

[I 2026-03-07 21:02:47,945] Trial 20 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 24it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 24it [00:00, ?it/s]

[I 2026-03-07 21:03:23,894] Trial 21 finished with value: 3.6905074423697855 and parameters: {'lag_temp_max': 29, 'lag_temp_min': 51, 'lag_snowfall': 1, 'n_lags': 36, 'epochs': 91, 'learning_rate': 0.004825263087308648, 'batch_size': 93, 'ar_reg': 2.999616644433339}. Best is trial 1 with value: 3.4243586604045184.

Training: 0it [00:00, ?it/s]

Predicting: 17it [00:00, ?it/s]

[I 2026-03-07 21:03:43,127] Trial 22 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 27it [00:00, ?it/s]

[I 2026-03-07 21:03:55,074] Trial 23 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 43it [00:00, ?it/s]

[I 2026-03-07 21:04:40,631] Trial 24 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 15it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 15it [00:00, ?it/s]

[I 2026-03-07 21:05:42,357] Trial 25 finished with value: 3.462891853714306 and parameters: {'lag_temp_max': 48, 'lag_temp_min': 41, 'lag_snowfall': 2, 'n_lags': 32, 'epochs': 202, 'learning_rate': 0.0058415610730527924, 'batch_size': 152, 'ar_reg': 1.5857402245101684}. Best is trial 1 with value: 3.4243586604045184.

Training: 0it [00:00, ?it/s]

Predicting: 14it [00:00, ?it/s]

[I 2026-03-07 21:06:07,251] Trial 26 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 17it [00:00, ?it/s]

[I 2026-03-07 21:06:44,385] Trial 27 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 14it [00:00, ?it/s]

[I 2026-03-07 21:07:35,347] Trial 28 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 19it [00:00, ?it/s]

[I 2026-03-07 21:08:05,782] Trial 29 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 12it [00:00, ?it/s]

[I 2026-03-07 21:08:33,788] Trial 30 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 21it [00:00, ?it/s]

[I 2026-03-07 21:08:54,635] Trial 31 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 15it [00:00, ?it/s]

[I 2026-03-07 21:09:17,203] Trial 32 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 18it [00:00, ?it/s]

[I 2026-03-07 21:09:33,435] Trial 33 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 10it [00:00, ?it/s]

[I 2026-03-07 21:10:01,788] Trial 34 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 25it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 25it [00:00, ?it/s]

[I 2026-03-07 21:12:36,035] Trial 35 finished with value: 3.66401185820226 and parameters: {'lag_temp_max': 32, 'lag_temp_min': 51, 'lag_snowfall': 1, 'n_lags': 53, 'epochs': 312, 'learning_rate': 0.003081295743411651, 'batch_size': 90, 'ar_reg': 2.2262680324143695}. Best is trial 1 with value: 3.4243586604045184.

Training: 0it [00:00, ?it/s]

Predicting: 31it [00:00, ?it/s]

[I 2026-03-07 21:14:03,317] Trial 36 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 16it [00:00, ?it/s]

[I 2026-03-07 21:14:15,964] Trial 37 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 9it [00:00, ?it/s]

[I 2026-03-07 21:14:41,429] Trial 38 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 13it [00:00, ?it/s]

[I 2026-03-07 21:15:52,441] Trial 39 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 19it [00:00, ?it/s]

[I 2026-03-07 21:16:20,792] Trial 40 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 27it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 27it [00:00, ?it/s]

[I 2026-03-07 21:18:54,484] Trial 41 finished with value: 3.391358141255389 and parameters: {'lag_temp_max': 33, 'lag_temp_min': 48, 'lag_snowfall': 1, 'n_lags': 50, 'epochs': 308, 'learning_rate': 0.002870926965673125, 'batch_size': 82, 'ar_reg': 1.7981022731488931}. Best is trial 41 with value: 3.391358141255389.

Training: 0it [00:00, ?it/s]

Predicting: 28it [00:00, ?it/s]

[I 2026-03-07 21:20:14,674] Trial 42 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 75it [00:00, ?it/s]

[I 2026-03-07 21:22:17,647] Trial 43 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 21it [00:00, ?it/s]

[I 2026-03-07 21:23:29,521] Trial 44 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 16it [00:00, ?it/s]

[I 2026-03-07 21:24:06,111] Trial 45 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 32it [00:00, ?it/s]

[I 2026-03-07 21:25:46,524] Trial 46 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 24it [00:00, ?it/s]

[I 2026-03-07 21:27:26,637] Trial 47 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 15it [00:00, ?it/s]

[I 2026-03-07 21:28:17,046] Trial 48 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 18it [00:00, ?it/s]

[I 2026-03-07 21:29:04,907] Trial 49 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 46it [00:00, ?it/s]

[I 2026-03-07 21:29:36,226] Trial 50 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 25it [00:00, ?it/s]

[I 2026-03-07 21:30:56,022] Trial 51 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 22it [00:00, ?it/s]

[I 2026-03-07 21:32:00,840] Trial 52 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 28it [00:00, ?it/s]

[I 2026-03-07 21:33:25,134] Trial 53 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 21it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 21it [00:00, ?it/s]

[I 2026-03-07 21:35:52,412] Trial 54 finished with value: 3.675576051318361 and parameters: {'lag_temp_max': 42, 'lag_temp_min': 49, 'lag_snowfall': 2, 'n_lags': 58, 'epochs': 349, 'learning_rate': 0.001252814896838782, 'batch_size': 107, 'ar_reg': 2.8233278372721218}. Best is trial 41 with value: 3.391358141255389.

Training: 0it [00:00, ?it/s]

Predicting: 37it [00:00, ?it/s]

[I 2026-03-07 21:36:16,342] Trial 55 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 20it [00:00, ?it/s]

[I 2026-03-07 21:36:42,836] Trial 56 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 23it [00:00, ?it/s]

[I 2026-03-07 21:37:23,302] Trial 57 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 16it [00:00, ?it/s]

[I 2026-03-07 21:38:29,329] Trial 58 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 12it [00:00, ?it/s]

[I 2026-03-07 21:38:59,021] Trial 59 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 36it [00:00, ?it/s]

[I 2026-03-07 21:40:12,567] Trial 60 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 25it [00:00, ?it/s]

[I 2026-03-07 21:41:32,976] Trial 61 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 21it [00:00, ?it/s]

[I 2026-03-07 21:42:49,027] Trial 62 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 30it [00:00, ?it/s]

[I 2026-03-07 21:44:07,452] Trial 63 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 19it [00:00, ?it/s]

[I 2026-03-07 21:45:19,604] Trial 64 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 17it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 17it [00:00, ?it/s]

[I 2026-03-07 21:46:56,462] Trial 65 finished with value: 3.3887937297449877 and parameters: {'lag_temp_max': 30, 'lag_temp_min': 23, 'lag_snowfall': 2, 'n_lags': 55, 'epochs': 307, 'learning_rate': 0.0014709192770247534, 'batch_size': 131, 'ar_reg': 2.5331928213623582}. Best is trial 65 with value: 3.3887937297449877.

Training: 0it [00:00, ?it/s]

Predicting: 14it [00:00, ?it/s]

[I 2026-03-07 21:47:34,760] Trial 66 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 15it [00:00, ?it/s]

[I 2026-03-07 21:48:23,073] Trial 67 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 17it [00:00, ?it/s]

[I 2026-03-07 21:49:09,612] Trial 68 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 14it [00:00, ?it/s]

[I 2026-03-07 21:49:43,860] Trial 69 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 16it [00:00, ?it/s]

[I 2026-03-07 21:49:55,357] Trial 70 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 19it [00:00, ?it/s]

[I 2026-03-07 21:51:00,058] Trial 71 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 22it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 22it [00:00, ?it/s]

[I 2026-03-07 21:52:58,888] Trial 72 finished with value: 3.5988965833654283 and parameters: {'lag_temp_max': 38, 'lag_temp_min': 49, 'lag_snowfall': 5, 'n_lags': 28, 'epochs': 330, 'learning_rate': 0.0023211157320910283, 'batch_size': 100, 'ar_reg': 2.860662589391577}. Best is trial 65 with value: 3.3887937297449877.

Training: 0it [00:00, ?it/s]

Predicting: 23it [00:00, ?it/s]

[I 2026-03-07 21:53:55,117] Trial 73 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 27it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 27it [00:00, ?it/s]

[I 2026-03-07 21:56:02,080] Trial 74 finished with value: 3.3302061112365022 and parameters: {'lag_temp_max': 31, 'lag_temp_min': 4, 'lag_snowfall': 5, 'n_lags': 28, 'epochs': 291, 'learning_rate': 0.002650764121136624, 'batch_size': 83, 'ar_reg': 2.9826541696565183}. Best is trial 74 with value: 3.3302061112365022.

Training: 0it [00:00, ?it/s]

Predicting: 22it [00:00, ?it/s]

[I 2026-03-07 21:56:48,788] Trial 75 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 28it [00:00, ?it/s]

[I 2026-03-07 21:57:40,955] Trial 76 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 17it [00:00, ?it/s]

[I 2026-03-07 21:58:26,668] Trial 77 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 30it [00:00, ?it/s]

[I 2026-03-07 21:58:45,949] Trial 78 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 19it [00:00, ?it/s]

[I 2026-03-07 21:59:34,771] Trial 79 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 35it [00:00, ?it/s]

[I 2026-03-07 22:00:04,662] Trial 80 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 26it [00:00, ?it/s]

[I 2026-03-07 22:01:12,688] Trial 81 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 20it [00:00, ?it/s]

[I 2026-03-07 22:02:09,554] Trial 82 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 26it [00:00, ?it/s]

[I 2026-03-07 22:03:10,370] Trial 83 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 18it [00:00, ?it/s]

[I 2026-03-07 22:03:51,869] Trial 84 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 24it [00:00, ?it/s]

[I 2026-03-07 22:04:16,046] Trial 85 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 33it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 34it [00:00, ?it/s]

[I 2026-03-07 22:06:22,300] Trial 86 finished with value: 3.614225435965083 and parameters: {'lag_temp_max': 10, 'lag_temp_min': 53, 'lag_snowfall': 1, 'n_lags': 30, 'epochs': 292, 'learning_rate': 0.001530195575840674, 'batch_size': 66, 'ar_reg': 2.0186875537426636}. Best is trial 74 with value: 3.3302061112365022.

Training: 0it [00:00, ?it/s]

Predicting: 41it [00:00, ?it/s]

[I 2026-03-07 22:06:44,471] Trial 87 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 34it [00:00, ?it/s]

[I 2026-03-07 22:07:34,129] Trial 88 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 15it [00:00, ?it/s]

[I 2026-03-07 22:08:01,283] Trial 89 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 50it [00:00, ?it/s]

[I 2026-03-07 22:09:17,650] Trial 90 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 22it [00:00, ?it/s]

[I 2026-03-07 22:10:08,976] Trial 91 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 30it [00:00, ?it/s]

[I 2026-03-07 22:11:22,245] Trial 92 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 28it [00:00, ?it/s]

[I 2026-03-07 22:12:42,558] Trial 93 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 33it [00:00, ?it/s]

[I 2026-03-07 22:13:12,146] Trial 94 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 25it [00:00, ?it/s]

[I 2026-03-07 22:14:14,693] Trial 95 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 23it [00:00, ?it/s]

[I 2026-03-07 22:14:25,176] Trial 96 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 19it [00:00, ?it/s]

[I 2026-03-07 22:15:29,610] Trial 97 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 16it [00:00, ?it/s]

[I 2026-03-07 22:16:00,078] Trial 98 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 17it [00:00, ?it/s]

[I 2026-03-07 22:16:56,076] Trial 99 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 17it [00:00, ?it/s]

[I 2026-03-07 22:17:33,032] Trial 100 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 21it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 21it [00:00, ?it/s]

[I 2026-03-07 22:20:00,545] Trial 101 finished with value: 3.195942661359205 and parameters: {'lag_temp_max': 40, 'lag_temp_min': 49, 'lag_snowfall': 2, 'n_lags': 59, 'epochs': 351, 'learning_rate': 0.0010389811425102497, 'batch_size': 104, 'ar_reg': 2.9684833760688893}. Best is trial 101 with value: 3.195942661359205.

Training: 0it [00:00, ?it/s]

Predicting: 21it [00:00, ?it/s]

[I 2026-03-07 22:21:20,059] Trial 102 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 68it [00:00, ?it/s]

[I 2026-03-07 22:23:46,349] Trial 103 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 22it [00:00, ?it/s]

[I 2026-03-07 22:24:50,930] Trial 104 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 20it [00:00, ?it/s]

[I 2026-03-07 22:25:55,868] Trial 105 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 27it [00:00, ?it/s]

[I 2026-03-07 22:27:03,101] Trial 106 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 24it [00:00, ?it/s]

[I 2026-03-07 22:27:15,522] Trial 107 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 29it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 29it [00:00, ?it/s]

[I 2026-03-07 22:29:30,034] Trial 108 finished with value: 4.049558084450887 and parameters: {'lag_temp_max': 36, 'lag_temp_min': 49, 'lag_snowfall': 2, 'n_lags': 51, 'epochs': 268, 'learning_rate': 0.0013170880860625702, 'batch_size': 77, 'ar_reg': 0.511561425371067}. Best is trial 101 with value: 3.195942661359205.

Training: 0it [00:00, ?it/s]

Predicting: 19it [00:00, ?it/s]

[I 2026-03-07 22:29:45,628] Trial 109 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 31it [00:00, ?it/s]

[I 2026-03-07 22:31:23,233] Trial 110 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 21it [00:00, ?it/s]

[I 2026-03-07 22:32:42,896] Trial 111 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 22it [00:00, ?it/s]

[I 2026-03-07 22:34:06,175] Trial 112 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 20it [00:00, ?it/s]

[I 2026-03-07 22:35:11,575] Trial 113 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 25it [00:00, ?it/s]

[I 2026-03-07 22:36:36,235] Trial 114 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 14it [00:00, ?it/s]

[I 2026-03-07 22:37:33,936] Trial 115 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 18it [00:00, ?it/s]

[I 2026-03-07 22:38:39,343] Trial 116 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 23it [00:00, ?it/s]

[I 2026-03-07 22:39:51,983] Trial 117 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 26it [00:00, ?it/s]

[I 2026-03-07 22:41:02,682] Trial 118 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 39it [00:00, ?it/s]

[I 2026-03-07 22:42:28,491] Trial 119 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 17it [00:00, ?it/s]

[I 2026-03-07 22:43:03,626] Trial 120 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 24it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 24it [00:00, ?it/s]

[I 2026-03-07 22:43:40,561] Trial 121 finished with value: 3.8164494111277216 and parameters: {'lag_temp_max': 29, 'lag_temp_min': 49, 'lag_snowfall': 1, 'n_lags': 36, 'epochs': 100, 'learning_rate': 0.008903440771930553, 'batch_size': 92, 'ar_reg': 2.6343483512360755}. Best is trial 101 with value: 3.195942661359205.

Training: 0it [00:00, ?it/s]

Predicting: 26it [00:00, ?it/s]

[I 2026-03-07 22:43:55,015] Trial 122 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 15it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 15it [00:00, ?it/s]

[I 2026-03-07 22:44:29,813] Trial 123 finished with value: 3.512692555535251 and parameters: {'lag_temp_max': 32, 'lag_temp_min': 51, 'lag_snowfall': 1, 'n_lags': 40, 'epochs': 122, 'learning_rate': 0.005995061835624724, 'batch_size': 146, 'ar_reg': 2.849896959503679}. Best is trial 101 with value: 3.195942661359205.

Training: 0it [00:00, ?it/s]

Predicting: 14it [00:00, ?it/s]

[I 2026-03-07 22:44:45,183] Trial 124 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 15it [00:00, ?it/s]

[I 2026-03-07 22:44:56,417] Trial 125 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 13it [00:00, ?it/s]

[I 2026-03-07 22:45:24,233] Trial 126 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 16it [00:00, ?it/s]

[I 2026-03-07 22:45:43,816] Trial 127 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 15it [00:00, ?it/s]

[I 2026-03-07 22:46:24,284] Trial 128 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 20it [00:00, ?it/s]

[I 2026-03-07 22:46:58,287] Trial 129 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 28it [00:00, ?it/s]

[I 2026-03-07 22:48:32,503] Trial 130 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 22it [00:00, ?it/s]

[I 2026-03-07 22:49:00,229] Trial 131 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 15it [00:00, ?it/s]

[I 2026-03-07 22:49:24,042] Trial 132 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 23it [00:00, ?it/s]

[I 2026-03-07 22:49:42,975] Trial 133 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 19it [00:00, ?it/s]

[I 2026-03-07 22:51:13,759] Trial 134 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 25it [00:00, ?it/s]

[I 2026-03-07 22:52:35,914] Trial 135 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 18it [00:00, ?it/s]

[I 2026-03-07 22:53:50,437] Trial 136 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 14it [00:00, ?it/s]

[I 2026-03-07 22:54:15,987] Trial 137 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 21it [00:00, ?it/s]

[I 2026-03-07 22:55:27,205] Trial 138 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 16it [00:00, ?it/s]

[I 2026-03-07 22:56:01,217] Trial 139 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 33it [00:00, ?it/s]

[I 2026-03-07 22:57:11,869] Trial 140 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 11it [00:00, ?it/s]

[I 2026-03-07 22:57:25,267] Trial 141 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 11it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 11it [00:00, ?it/s]

[I 2026-03-07 22:57:56,706] Trial 142 finished with value: 3.912305611922318 and parameters: {'lag_temp_max': 43, 'lag_temp_min': 54, 'lag_snowfall': 5, 'n_lags': 48, 'epochs': 85, 'learning_rate': 0.013426941176131742, 'batch_size': 200, 'ar_reg': 1.2169348515693896}. Best is trial 101 with value: 3.195942661359205.

Training: 0it [00:00, ?it/s]

Predicting: 12it [00:00, ?it/s]

[I 2026-03-07 22:58:46,635] Trial 143 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 10it [00:00, ?it/s]

[I 2026-03-07 22:59:14,349] Trial 144 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 22it [00:00, ?it/s]

[I 2026-03-07 22:59:43,656] Trial 145 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 29it [00:00, ?it/s]

[I 2026-03-07 23:00:02,938] Trial 146 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 9it [00:00, ?it/s]

[I 2026-03-07 23:00:50,455] Trial 147 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 11it [00:00, ?it/s]

[I 2026-03-07 23:01:06,157] Trial 148 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 20it [00:00, ?it/s]

[I 2026-03-07 23:02:28,806] Trial 149 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 27it [00:00, ?it/s]

[I 2026-03-07 23:03:00,606] Trial 150 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 24it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 25it [00:00, ?it/s]

[I 2026-03-07 23:03:54,084] Trial 151 finished with value: 3.595761688138026 and parameters: {'lag_temp_max': 29, 'lag_temp_min': 50, 'lag_snowfall': 1, 'n_lags': 36, 'epochs': 102, 'learning_rate': 0.0055187104007863716, 'batch_size': 91, 'ar_reg': 2.639200496605214}. Best is trial 101 with value: 3.195942661359205.

Training: 0it [00:00, ?it/s]

Predicting: 26it [00:00, ?it/s]

[I 2026-03-07 23:04:16,700] Trial 152 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 23it [00:00, ?it/s]

[I 2026-03-07 23:04:41,911] Trial 153 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 24it [00:00, ?it/s]

[I 2026-03-07 23:06:02,554] Trial 154 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 22it [00:00, ?it/s]

[I 2026-03-07 23:06:32,239] Trial 155 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 31it [00:00, ?it/s]

[I 2026-03-07 23:06:56,835] Trial 156 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 13it [00:00, ?it/s]

[I 2026-03-07 23:07:59,263] Trial 157 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 18it [00:00, ?it/s]

[I 2026-03-07 23:08:25,731] Trial 158 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 26it [00:00, ?it/s]

[I 2026-03-07 23:09:55,531] Trial 159 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 22it [00:00, ?it/s]

[I 2026-03-07 23:11:07,857] Trial 160 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 24it [00:00, ?it/s]

[I 2026-03-07 23:11:33,317] Trial 161 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 24it [00:00, ?it/s]

[I 2026-03-07 23:11:51,299] Trial 162 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 27it [00:00, ?it/s]

[I 2026-03-07 23:12:20,694] Trial 163 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 21it [00:00, ?it/s]

[I 2026-03-07 23:12:42,120] Trial 164 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 23it [00:00, ?it/s]

[I 2026-03-07 23:13:53,315] Trial 165 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 17it [00:00, ?it/s]

[I 2026-03-07 23:14:56,566] Trial 166 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 25it [00:00, ?it/s]

[I 2026-03-07 23:17:06,133] Trial 167 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 21it [00:00, ?it/s]

[I 2026-03-07 23:17:24,355] Trial 168 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 29it [00:00, ?it/s]

[I 2026-03-07 23:19:04,556] Trial 169 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 27it [00:00, ?it/s]

[I 2026-03-07 23:19:18,830] Trial 170 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 11it [00:00, ?it/s]

[I 2026-03-07 23:19:34,011] Trial 171 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 11it [00:00, ?it/s]

[I 2026-03-07 23:19:50,324] Trial 172 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 24it [00:00, ?it/s]

[I 2026-03-07 23:20:20,972] Trial 173 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 9it [00:00, ?it/s]

[I 2026-03-07 23:20:37,767] Trial 174 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 10it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 10it [00:00, ?it/s]

[I 2026-03-07 23:21:10,188] Trial 175 finished with value: 3.9036913590212103 and parameters: {'lag_temp_max': 44, 'lag_temp_min': 52, 'lag_snowfall': 4, 'n_lags': 59, 'epochs': 90, 'learning_rate': 0.010410347500329823, 'batch_size': 227, 'ar_reg': 1.3053062753411315}. Best is trial 101 with value: 3.195942661359205.

Training: 0it [00:00, ?it/s]

Predicting: 10it [00:00, ?it/s]

[I 2026-03-07 23:21:42,913] Trial 176 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 10it [00:00, ?it/s]

[I 2026-03-07 23:22:03,526] Trial 177 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 10it [00:00, ?it/s]

[I 2026-03-07 23:23:03,596] Trial 178 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 22it [00:00, ?it/s]

[I 2026-03-07 23:23:29,300] Trial 179 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 20it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 20it [00:00, ?it/s]

[I 2026-03-07 23:26:04,695] Trial 180 finished with value: 3.4416434199296573 and parameters: {'lag_temp_max': 47, 'lag_temp_min': 50, 'lag_snowfall': 3, 'n_lags': 53, 'epochs': 320, 'learning_rate': 0.004791441458243874, 'batch_size': 111, 'ar_reg': 2.7819179752651295}. Best is trial 101 with value: 3.195942661359205.

Training: 0it [00:00, ?it/s]

Predicting: 20it [00:00, ?it/s]

[I 2026-03-07 23:27:10,001] Trial 181 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 19it [00:00, ?it/s]

[I 2026-03-07 23:28:12,020] Trial 182 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 19it [00:00, ?it/s]

[I 2026-03-07 23:29:13,246] Trial 183 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 25it [00:00, ?it/s]

[I 2026-03-07 23:30:28,128] Trial 184 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 21it [00:00, ?it/s]

[I 2026-03-07 23:31:38,705] Trial 185 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 16it [00:00, ?it/s]

[I 2026-03-07 23:32:02,626] Trial 186 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 23it [00:00, ?it/s]

[I 2026-03-07 23:33:04,780] Trial 187 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 10it [00:00, ?it/s]

[I 2026-03-07 23:33:15,108] Trial 188 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 22it [00:00, ?it/s]

[I 2026-03-07 23:34:22,540] Trial 189 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 18it [00:00, ?it/s]

[I 2026-03-07 23:34:33,154] Trial 190 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 12it [00:00, ?it/s]

[I 2026-03-07 23:34:48,171] Trial 191 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 10it [00:00, ?it/s]

[I 2026-03-07 23:34:59,899] Trial 192 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 10it [00:00, ?it/s]

[I 2026-03-07 23:35:11,038] Trial 193 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 15it [00:00, ?it/s]

[I 2026-03-07 23:35:22,734] Trial 194 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 25it [00:00, ?it/s]

[I 2026-03-07 23:36:37,004] Trial 195 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 16it [00:00, ?it/s]

[I 2026-03-07 23:37:33,489] Trial 196 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 28it [00:00, ?it/s]

[I 2026-03-07 23:37:55,550] Trial 197 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 15it [00:00, ?it/s]

[I 2026-03-07 23:38:45,982] Trial 198 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 19it [00:00, ?it/s]

[I 2026-03-07 23:39:05,515] Trial 199 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 10it [00:00, ?it/s]

[I 2026-03-07 23:39:50,520] Trial 200 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 30it [00:00, ?it/s]

[I 2026-03-07 23:40:58,059] Trial 201 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 32it [00:00, ?it/s]

[I 2026-03-07 23:42:10,194] Trial 202 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 26it [00:00, ?it/s]

[I 2026-03-07 23:43:07,036] Trial 203 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 29it [00:00, ?it/s]

[I 2026-03-07 23:44:22,054] Trial 204 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 25it [00:00, ?it/s]

[I 2026-03-07 23:44:39,772] Trial 205 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 23it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 23it [00:00, ?it/s]

[I 2026-03-07 23:46:23,377] Trial 206 finished with value: 3.1367622868005816 and parameters: {'lag_temp_max': 7, 'lag_temp_min': 35, 'lag_snowfall': 1, 'n_lags': 54, 'epochs': 233, 'learning_rate': 0.004311701268512139, 'batch_size': 98, 'ar_reg': 0.7997290182793909}. Best is trial 206 with value: 3.1367622868005816.

Training: 0it [00:00, ?it/s]

Predicting: 23it [00:00, ?it/s]

[I 2026-03-07 23:47:10,892] Trial 207 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 20it [00:00, ?it/s]

[I 2026-03-07 23:47:46,363] Trial 208 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 24it [00:00, ?it/s]

[I 2026-03-07 23:48:33,617] Trial 209 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 22it [00:00, ?it/s]

[I 2026-03-07 23:49:33,715] Trial 210 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 26it [00:00, ?it/s]

[I 2026-03-07 23:50:26,611] Trial 211 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 34it [00:00, ?it/s]

[I 2026-03-07 23:51:20,297] Trial 212 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 24it [00:00, ?it/s]

[I 2026-03-07 23:52:16,580] Trial 213 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 28it [00:00, ?it/s]

[I 2026-03-07 23:53:07,645] Trial 214 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 13it [00:00, ?it/s]

[I 2026-03-07 23:53:21,173] Trial 215 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 9it [00:00, ?it/s]

[I 2026-03-07 23:53:33,456] Trial 216 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 25it [00:00, ?it/s]

[I 2026-03-07 23:54:13,952] Trial 217 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 23it [00:00, ?it/s]

[I 2026-03-07 23:54:29,513] Trial 218 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 10it [00:00, ?it/s]

[I 2026-03-07 23:55:05,320] Trial 219 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 20it [00:00, ?it/s]

[I 2026-03-07 23:55:52,083] Trial 220 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 19it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 19it [00:00, ?it/s]

[I 2026-03-07 23:57:23,045] Trial 221 finished with value: 3.621793653648173 and parameters: {'lag_temp_max': 39, 'lag_temp_min': 2, 'lag_snowfall': 1, 'n_lags': 26, 'epochs': 299, 'learning_rate': 0.0032848611922266812, 'batch_size': 121, 'ar_reg': 1.0672452007926054}. Best is trial 206 with value: 3.1367622868005816.

Training: 0it [00:00, ?it/s]

Predicting: 18it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 18it [00:00, ?it/s]

[I 2026-03-07 23:58:40,704] Trial 222 finished with value: 3.2824401153090754 and parameters: {'lag_temp_max': 40, 'lag_temp_min': 2, 'lag_snowfall': 1, 'n_lags': 26, 'epochs': 281, 'learning_rate': 0.004516899889576882, 'batch_size': 127, 'ar_reg': 1.11130046607747}. Best is trial 206 with value: 3.1367622868005816.

Training: 0it [00:00, ?it/s]

Predicting: 17it [00:00, ?it/s]

[I 2026-03-07 23:59:05,140] Trial 223 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 19it [00:00, ?it/s]

[I 2026-03-07 23:59:47,752] Trial 224 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 17it [00:00, ?it/s]

[I 2026-03-08 00:00:29,334] Trial 225 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 18it [00:00, ?it/s]

[I 2026-03-08 00:01:10,017] Trial 226 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 19it [00:00, ?it/s]

[I 2026-03-08 00:01:49,281] Trial 227 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 16it [00:00, ?it/s]

[I 2026-03-08 00:02:30,542] Trial 228 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 20it [00:00, ?it/s]

[I 2026-03-08 00:03:13,005] Trial 229 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 17it [00:00, ?it/s]

[I 2026-03-08 00:03:30,924] Trial 230 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 17it [00:00, ?it/s]

[I 2026-03-08 00:04:10,135] Trial 231 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 21it [00:00, ?it/s]

[I 2026-03-08 00:05:04,892] Trial 232 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 18it [00:00, ?it/s]

[I 2026-03-08 00:05:52,250] Trial 233 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 24it [00:00, ?it/s]

[I 2026-03-08 00:06:09,693] Trial 234 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 20it [00:00, ?it/s]

[I 2026-03-08 00:06:24,171] Trial 235 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 22it [00:00, ?it/s]

[I 2026-03-08 00:07:25,420] Trial 236 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 26it [00:00, ?it/s]

[I 2026-03-08 00:08:23,380] Trial 237 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 23it [00:00, ?it/s]

[I 2026-03-08 00:09:14,655] Trial 238 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 10it [00:00, ?it/s]

[I 2026-03-08 00:09:26,186] Trial 239 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 17it [00:00, ?it/s]

[I 2026-03-08 00:10:10,148] Trial 240 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 19it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 19it [00:00, ?it/s]

[I 2026-03-08 00:11:42,548] Trial 241 finished with value: 3.836729392967909 and parameters: {'lag_temp_max': 41, 'lag_temp_min': 2, 'lag_snowfall': 1, 'n_lags': 26, 'epochs': 302, 'learning_rate': 0.002838445640123608, 'batch_size': 121, 'ar_reg': 1.1984559809540312}. Best is trial 206 with value: 3.1367622868005816.

Training: 0it [00:00, ?it/s]

Predicting: 18it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 18it [00:00, ?it/s]

[I 2026-03-08 00:13:11,306] Trial 242 finished with value: 3.2059463695769974 and parameters: {'lag_temp_max': 42, 'lag_temp_min': 3, 'lag_snowfall': 1, 'n_lags': 26, 'epochs': 305, 'learning_rate': 0.0028629773268995505, 'batch_size': 122, 'ar_reg': 1.1990045371604787}. Best is trial 206 with value: 3.1367622868005816.

Training: 0it [00:00, ?it/s]

Predicting: 19it [00:00, ?it/s]

[I 2026-03-08 00:13:56,220] Trial 243 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 19it [00:00, ?it/s]

[I 2026-03-08 00:14:47,198] Trial 244 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 19it [00:00, ?it/s]

[I 2026-03-08 00:15:35,066] Trial 245 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 18it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 18it [00:00, ?it/s]

[I 2026-03-08 00:17:00,522] Trial 246 finished with value: 3.6202078097588934 and parameters: {'lag_temp_max': 45, 'lag_temp_min': 5, 'lag_snowfall': 1, 'n_lags': 26, 'epochs': 285, 'learning_rate': 0.003772126888451484, 'batch_size': 126, 'ar_reg': 1.2242330189839088}. Best is trial 206 with value: 3.1367622868005816.

Training: 0it [00:00, ?it/s]

Predicting: 18it [00:00, ?it/s]

[I 2026-03-08 00:17:45,511] Trial 247 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 59it [00:00, ?it/s]

[I 2026-03-08 00:19:11,322] Trial 248 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 18it [00:00, ?it/s]

[I 2026-03-08 00:20:11,774] Trial 249 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 18it [00:00, ?it/s]

[I 2026-03-08 00:20:54,265] Trial 250 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 17it [00:00, ?it/s]

[I 2026-03-08 00:21:33,298] Trial 251 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 40it [00:00, ?it/s]

[I 2026-03-08 00:22:32,194] Trial 252 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 18it [00:00, ?it/s]

[I 2026-03-08 00:23:13,241] Trial 253 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 46it [00:00, ?it/s]

[I 2026-03-08 00:24:27,801] Trial 254 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 17it [00:00, ?it/s]

[I 2026-03-08 00:25:10,285] Trial 255 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 20it [00:00, ?it/s]

[I 2026-03-08 00:25:55,292] Trial 256 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 19it [00:00, ?it/s]

[I 2026-03-08 00:26:54,135] Trial 257 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 21it [00:00, ?it/s]

[I 2026-03-08 00:27:50,397] Trial 258 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 22it [00:00, ?it/s]

[I 2026-03-08 00:28:19,154] Trial 259 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 18it [00:00, ?it/s]

[I 2026-03-08 00:29:04,159] Trial 260 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 17it [00:00, ?it/s]

[I 2026-03-08 00:29:25,355] Trial 261 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 23it [00:00, ?it/s]

[I 2026-03-08 00:30:25,305] Trial 262 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 19it [00:00, ?it/s]

[I 2026-03-08 00:31:08,604] Trial 263 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 22it [00:00, ?it/s]

[I 2026-03-08 00:31:57,508] Trial 264 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 24it [00:00, ?it/s]

[I 2026-03-08 00:32:49,382] Trial 265 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 16it [00:00, ?it/s]

[I 2026-03-08 00:33:29,264] Trial 266 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 21it [00:00, ?it/s]

[I 2026-03-08 00:33:46,789] Trial 267 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 18it [00:00, ?it/s]

[I 2026-03-08 00:34:29,002] Trial 268 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 20it [00:00, ?it/s]

[I 2026-03-08 00:34:40,789] Trial 269 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 18it [00:00, ?it/s]

[I 2026-03-08 00:35:24,818] Trial 270 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 22it [00:00, ?it/s]

[I 2026-03-08 00:35:40,866] Trial 271 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 24it [00:00, ?it/s]

[I 2026-03-08 00:36:42,106] Trial 272 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 27it [00:00, ?it/s]

[I 2026-03-08 00:37:52,026] Trial 273 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 25it [00:00, ?it/s]

[I 2026-03-08 00:38:12,492] Trial 274 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 19it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 19it [00:00, ?it/s]

[I 2026-03-08 00:39:48,798] Trial 275 finished with value: 3.3331651256359596 and parameters: {'lag_temp_max': 28, 'lag_temp_min': 37, 'lag_snowfall': 1, 'n_lags': 52, 'epochs': 301, 'learning_rate': 0.004380777195654323, 'batch_size': 119, 'ar_reg': 1.744614763265504}. Best is trial 206 with value: 3.1367622868005816.

Training: 0it [00:00, ?it/s]

Predicting: 99it [00:00, ?it/s]

[I 2026-03-08 00:42:09,671] Trial 276 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 19it [00:00, ?it/s]

[I 2026-03-08 00:42:53,122] Trial 277 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 18it [00:00, ?it/s]

[I 2026-03-08 00:43:45,907] Trial 278 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 17it [00:00, ?it/s]

[I 2026-03-08 00:44:33,324] Trial 279 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 19it [00:00, ?it/s]

[I 2026-03-08 00:45:16,768] Trial 280 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 18it [00:00, ?it/s]

[I 2026-03-08 00:45:45,544] Trial 281 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 20it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 20it [00:00, ?it/s]

[I 2026-03-08 00:47:29,382] Trial 282 finished with value: 3.6721070327757177 and parameters: {'lag_temp_max': 28, 'lag_temp_min': 42, 'lag_snowfall': 1, 'n_lags': 35, 'epochs': 331, 'learning_rate': 0.002841888172642084, 'batch_size': 110, 'ar_reg': 2.7770013361900574}. Best is trial 206 with value: 3.1367622868005816.

Training: 0it [00:00, ?it/s]

Predicting: 20it [00:00, ?it/s]

[I 2026-03-08 00:48:23,452] Trial 283 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 21it [00:00, ?it/s]

[I 2026-03-08 00:49:17,319] Trial 284 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 15it [00:00, ?it/s]

[I 2026-03-08 00:50:06,363] Trial 285 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 23it [00:00, ?it/s]

[I 2026-03-08 00:51:02,363] Trial 286 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 21it [00:00, ?it/s]

[I 2026-03-08 00:51:59,093] Trial 287 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 24it [00:00, ?it/s]

[I 2026-03-08 00:53:04,447] Trial 288 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 22it [00:00, ?it/s]

[I 2026-03-08 00:54:01,548] Trial 289 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 20it [00:00, ?it/s]

[I 2026-03-08 00:54:40,562] Trial 290 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 21it [00:00, ?it/s]

[I 2026-03-08 00:55:30,971] Trial 291 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 16it [00:00, ?it/s]

[I 2026-03-08 00:56:11,091] Trial 292 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 23it [00:00, ?it/s]

[I 2026-03-08 00:57:02,059] Trial 293 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 25it [00:00, ?it/s]

[I 2026-03-08 00:58:11,161] Trial 294 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 36it [00:00, ?it/s]

[I 2026-03-08 00:59:06,264] Trial 295 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 17it [00:00, ?it/s]

[I 2026-03-08 00:59:47,863] Trial 296 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 24it [00:00, ?it/s]

[I 2026-03-08 01:00:40,466] Trial 297 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 27it [00:00, ?it/s]

[I 2026-03-08 01:01:29,914] Trial 298 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 21it [00:00, ?it/s]

[I 2026-03-08 01:02:32,917] Trial 299 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 20it [00:00, ?it/s]

[I 2026-03-08 01:03:28,069] Trial 300 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 29it [00:00, ?it/s]

[I 2026-03-08 01:04:48,237] Trial 301 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 19it [00:00, ?it/s]

[I 2026-03-08 01:05:39,706] Trial 302 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 25it [00:00, ?it/s]

[I 2026-03-08 01:06:01,366] Trial 303 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 20it [00:00, ?it/s]

[I 2026-03-08 01:06:11,800] Trial 304 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 22it [00:00, ?it/s]

[I 2026-03-08 01:06:25,388] Trial 305 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 18it [00:00, ?it/s]

[I 2026-03-08 01:07:07,205] Trial 306 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 26it [00:00, ?it/s]

[I 2026-03-08 01:07:26,701] Trial 307 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 31it [00:00, ?it/s]

[I 2026-03-08 01:08:03,382] Trial 308 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 23it [00:00, ?it/s]

[I 2026-03-08 01:08:52,322] Trial 309 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 17it [00:00, ?it/s]

[I 2026-03-08 01:09:35,655] Trial 310 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 22it [00:00, ?it/s]

[I 2026-03-08 01:10:36,806] Trial 311 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 19it [00:00, ?it/s]

[I 2026-03-08 01:11:22,840] Trial 312 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 14it [00:00, ?it/s]

[I 2026-03-08 01:12:07,271] Trial 313 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 17it [00:00, ?it/s]

[I 2026-03-08 01:12:55,268] Trial 314 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 16it [00:00, ?it/s]

[I 2026-03-08 01:13:08,377] Trial 315 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 24it [00:00, ?it/s]

[I 2026-03-08 01:13:24,198] Trial 316 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 19it [00:00, ?it/s]

[I 2026-03-08 01:14:11,191] Trial 317 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 20it [00:00, ?it/s]

[I 2026-03-08 01:15:09,847] Trial 318 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 12it [00:00, ?it/s]

[I 2026-03-08 01:15:55,485] Trial 319 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 27it [00:00, ?it/s]

[I 2026-03-08 01:16:20,168] Trial 320 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 18it [00:00, ?it/s]

[I 2026-03-08 01:16:55,686] Trial 321 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 26it [00:00, ?it/s]

[I 2026-03-08 01:17:50,685] Trial 322 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 22it [00:00, ?it/s]

[I 2026-03-08 01:18:47,359] Trial 323 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 24it [00:00, ?it/s]

[I 2026-03-08 01:19:41,527] Trial 324 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 17it [00:00, ?it/s]

[I 2026-03-08 01:19:54,609] Trial 325 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 18it [00:00, ?it/s]

[I 2026-03-08 01:20:45,293] Trial 326 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 13it [00:00, ?it/s]

[I 2026-03-08 01:21:34,934] Trial 327 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 21it [00:00, ?it/s]

[I 2026-03-08 01:22:08,774] Trial 328 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 23it [00:00, ?it/s]

[I 2026-03-08 01:23:00,763] Trial 329 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 19it [00:00, ?it/s]

[I 2026-03-08 01:23:38,133] Trial 330 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 20it [00:00, ?it/s]

[I 2026-03-08 01:23:58,223] Trial 331 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 29it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 29it [00:00, ?it/s]

[I 2026-03-08 01:26:20,052] Trial 332 finished with value: 3.084721197362562 and parameters: {'lag_temp_max': 48, 'lag_temp_min': 35, 'lag_snowfall': 1, 'n_lags': 47, 'epochs': 330, 'learning_rate': 0.0031632755499694104, 'batch_size': 77, 'ar_reg': 1.5085804840047352}. Best is trial 332 with value: 3.084721197362562.

Training: 0it [00:00, ?it/s]

Predicting: 29it [00:00, ?it/s]

[I 2026-03-08 01:27:35,740] Trial 333 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 28it [00:00, ?it/s]

[I 2026-03-08 01:28:48,403] Trial 334 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 15it [00:00, ?it/s]

[I 2026-03-08 01:29:36,978] Trial 335 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 34it [00:00, ?it/s]

[I 2026-03-08 01:30:56,230] Trial 336 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 32it [00:00, ?it/s]

[I 2026-03-08 01:32:08,316] Trial 337 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 29it [00:00, ?it/s]

[I 2026-03-08 01:32:36,659] Trial 338 pruned.

Training: 0it [00:00, ?it/s]

Predicting: 26it [00:00, ?it/s]

[I 2026-03-08 01:33:32,775] Trial 339 pruned.

Training: 0it [00:00, ?it/s]

In [ ]:
print("Best Parameters", best_params)
print("Best RMSE:", study.best_value)

Best Parameters {'lag_temp_max': 13, 'lag_temp_min': 15, 'lag_snowfall': 2, 'n_lags': 7, 'epochs': 245, 'learning_rate': 0.004202632132542488, 'batch_size': 93, 'ar_reg': 1.1855504612513517}
Best RMSE: 3.5706188689931917

In [ ]:
rs = pd.read_csv('../scr/data/cleaned_rat_sightings_data/all_daily_borough_rs.csv')
rs['created_date'] = pd.to_datetime(rs['created_date']) 

# Start by cutting off data before 2020-01-01 and after 2026-02-28.
rs = rs[rs['created_date']<'2026-03-01']
rs = rs[rs['created_date']>='2020-01-01']

## Restrict to MANHATTAN

rs = rs[rs['borough']=='MANHATTAN']

## Drop the column with borough

rs = rs.drop(columns=['borough'])

## rename columns for prophet

rs.rename(columns={'created_date': 'ds', 'count': 'y'}, inplace=True)


## Add weather data.
import requests

lat, lon = 40.7831, -73.9712
start = "2020-01-01"
end   = "2026-02-28"

url = (
    "https://archive-api.open-meteo.com/v1/archive"
    f"?latitude={lat}&longitude={lon}"
    f"&start_date={start}&end_date={end}"
    "&daily=temperature_2m_max,temperature_2m_min,temperature_2m_mean,"
    "apparent_temperature_max,apparent_temperature_min,apparent_temperature_mean,"
    "precipitation_sum,snowfall_sum"
    "&timezone=America/New_York"
)

response = requests.get(url)
data = response.json()

In [ ]:
tscv = TimeSeriesSplit(gap=0, max_train_size=None, n_splits=26, test_size=14)

regressed_features = ['apparent_temperature_max', 'apparent_temperature_min','snowfall_sum']


wd = wd.reset_index(drop=True).rename(columns={"time": "ds"})
wd["ds"] = pd.to_datetime(wd["ds"])
rs["ds"] = pd.to_datetime(rs["ds"])

rs = rs.merge(
    wd[['ds'] + regressed_features],
    on="ds",
    how="left"
)

lags_for_regressed_features = dict()
lags_for_regressed_features['apparent_temperature_max'] = best_params['lag_temp_max']
lags_for_regressed_features['apparent_temperature_min'] = best_params['lag_temp_min']
lags_for_regressed_features['snowfall_sum'] = best_params['lag_snowfall']


results = []

for i, (train_index, test_index) in enumerate(tscv.split(rs)):

    train = rs.iloc[train_index].copy()
    train = train.dropna(subset=["y"])

    test = rs.iloc[test_index].copy()


    model = NeuralProphet(yearly_seasonality=True, 
                          weekly_seasonality=True, 
                          learning_rate = best_params['learning_rate'],
                          epochs = best_params['epochs'],
                          n_lags= best_params['n_lags'],
                          ar_reg=best_params['ar_reg'],
                          accelerator="auto",   # uses GPU if available
                          batch_size= best_params['batch_size']
                          )
    model = model.add_country_holidays(country_name="US")
    for column in regressed_features:
        model.add_lagged_regressor(column, n_lags=lags_for_regressed_features[column])
        
    model.fit(train, freq="D", progress="off")

    # build dataframe containing future regressors
    future = pd.concat([train[['ds','y'] + regressed_features], test[['ds','y']].merge(wd[['ds'] + regressed_features], on="ds", how="left")])
    forecast = model.predict(future)

    y_pred = forecast["yhat1"].iloc[-len(test):].values
    y_true = test["y"].values

    rmse = np.sqrt(mean_squared_error(y_true, y_pred))
    mape = mean_absolute_percentage_error(y_true, y_pred)

    results.append({"fold": i, "rmse": rmse, "mape": mape})

neural_prophet_results_df = pd.DataFrame(results)
neural_prophet_results_df.loc["mean"] = ["mean", neural_prophet_results_df["rmse"].mean(), neural_prophet_results_df["mape"].mean()]
neural_prophet_results_df

Training: 0it [00:00, ?it/s]

Predicting: 21it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 21it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 21it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 21it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 21it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 21it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 22it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 22it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 22it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 22it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 22it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 22it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 22it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 23it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 23it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 23it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 23it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 23it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 23it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 23it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 24it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 24it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 24it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 24it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 24it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

Predicting: 24it [00:00, ?it/s]

      fold      rmse      mape
0        0  5.779064  0.417553
1        1  5.129356  0.219141
2        2  4.674332  0.302965
3        3  4.760209  0.353327
4        4  5.770191  0.325123
5        5  6.080056  0.410244
6        6  6.002675  0.286063
7        7  5.688211  0.170676
8        8  7.522395  0.405546
9        9  5.369426  0.302983
10      10  4.841759  0.245468
11      11  4.255097  0.260134
12      12  7.470388  0.258464
13      13  5.170675  0.256607
14      14  5.398861  0.302376
15      15  4.792103  0.380412
16      16  3.170399  0.247463
17      17  5.523212  0.671507
18      18  3.809869  0.416480
19      19  5.244645  0.735615
20      20  3.372456  0.463602
21      21  3.976569  0.927654
22      22  3.507778  0.275814
23      23  3.691350  0.483990
24      24  4.457778  0.669041
25      25  4.226073  0.447457
mean  mean  4.987882  0.393681

In [ ]:
model = NeuralProphet(yearly_seasonality=True, 
                          weekly_seasonality=True, 
                          # batch_size = best_params['batch_size'],
                          ar_reg=best_params['ar_reg'],
                          learning_rate = best_params['learning_rate'],
                          epochs = best_params['epochs'],
                          accelerator="auto",   # uses GPU if available
                          n_lags= best_params['n_lags']
                          )
model = model.add_country_holidays(country_name="US")
for column in regressed_features:
    model.add_lagged_regressor(column, n_lags=lags_for_regressed_features[column])
        
model.fit(rs, freq="D", progress="off")

new_rs = rs.copy()

new_rs = new_rs.drop(columns=['y'])

forecast = model.predict(rs)

Training: 0it [00:00, ?it/s]

Predicting: 35it [00:00, ?it/s]

In [ ]:
model.plot(forecast)

ERROR - (NP.plotly.plot) - plotly-resampler is not installed. Please install it to use the resampler.